/* Mental models, stories (Story DNA) and missions. */
window.MV = window.MV || {};

MV.MODELS = [
  { id: "second-order-thinking", name: "Second-order thinking", line: "Ask “and then what?” Think about the results of the results.", ask: "And then what? Who reacts, and what do they do next?", ex: "A limit on prices makes things cheaper today. Next year it causes shortages." },
  { id: "inversion", name: "Inversion", line: "Solve the problem backwards. Ask what would surely make you fail, then avoid it.", ask: "What would surely cause the opposite result?", ex: "Do not ask “how do I succeed?” Ask “what would surely make this fail?”" },
  { id: "opportunity-cost", name: "Opportunity cost", line: "The real cost of anything is the best other thing you gave up for it.", ask: "What am I giving up by choosing this?", ex: "An evening on social media costs you the book you did not read." },
  { id: "first-principles", name: "First principles", line: "Break a problem down to its basic truths and build up from there. Do not just copy what others do.", ask: "What do I know for sure, and what am I only assuming?", ex: "Rocket costs: raw materials are only ~2% of the price, so build the rocket yourself." },
  { id: "compounding", name: "Compounding", line: "Small, steady gains that build on each other become huge over time.", ask: "What small thing, done again and again, would change everything in 10 years?", ex: "Growing 1% a day for a year makes you ~37 times bigger." },
  { id: "margin-of-safety", name: "Margin of safety", line: "Keep a safety gap, so that mistakes and bad luck do not destroy you.", ask: "How wrong can I be and still be fine?", ex: "Bridges are built to carry much more than the expected load." },
  { id: "incentives", name: "Incentives", line: "People respond to rewards and punishments, often not in the way the rule-makers wanted.", ask: "What is each person really rewarded for?", ex: "Pay for rat tails and you get rat farms." },
  { id: "network-effects", name: "Network effects", line: "A product or network becomes more useful as more people use it.", ask: "Does each new user make this better for the others?", ex: "One telephone alone is useless. With a million users, everyone needs one." },
  { id: "feedback-loops", name: "Feedback loops", line: "A result comes back and becomes a cause. It can make a change grow (reinforcing) or slow it down (balancing).", ask: "What is feeding back into what?", ex: "A rush on a bank: fear makes people take out money, and that causes more fear." },
  { id: "bottlenecks", name: "Bottlenecks", line: "A system can only work as fast as its narrowest point allows.", ask: "What is the one thing that limits everything else?", ex: "A strait, a port, one engineer with too much work." },
  { id: "survivorship-bias", name: "Survivorship bias", line: "We see the winners and forget the failures we cannot see. This leads us to wrong conclusions.", ask: "What am I not seeing because it did not survive?", ex: "Studying only successful startups to learn what works." },
  { id: "confirmation-bias", name: "Confirmation bias", line: "We prefer proof that supports what we already believe.", ask: "What would change my mind, and have I looked for it?", ex: "Reading only the news that agrees with you." },
  { id: "bayesian-thinking", name: "Bayesian thinking", line: "Start with what you believe now. Change it a little or a lot, depending on how strong the new proof is.", ask: "How much should this proof change my mind, given what I believed before?", ex: "A positive test for a rare disease is still probably a false alarm." },
  { id: "game-theory", name: "Game theory", line: "Your result depends on what others do. So think about what they want and how they will react.", ask: "What will the other side do if I do this?", ex: "Nuclear standoffs, price wars, arms races." },
  { id: "goodharts-law", name: "Goodhart's law", line: "When a measure becomes a target, it stops being a good measure.", ask: "How could someone reach this number without reaching the real goal?", ex: "Teaching students only what will come in the exam." },
  { id: "lindy-effect", name: "Lindy effect", line: "For things that do not rot or wear out, the longer they have lasted, the longer they will probably last.", ask: "How long has this lasted, and why?", ex: "A 2,000-year-old book will probably still be read after this year's bestseller is forgotten." },
  { id: "map-vs-territory", name: "Map vs territory", line: "Models are simple pictures of reality. Do not mistake them for the real thing.", ask: "What does this model leave out?", ex: "Dashboards and forecasts are maps, not the world." }
];

MV.STORIES = [
  { id: "sarajevo", assetId: "sarajevo-1914", title: "The Wrong Turn",
    hook: "In 1914, one driver took a wrong turn, and a hundred years of European history changed.",
    setting: "Sarajevo, 28 June 1914. The Archduke of Austria-Hungary is visiting a tense Balkan city in an open car.",
    character: "Franz Ferdinand, the next in line to be emperor. And Gavrilo Princip, a young Bosnian Serb who had already given up on the plan to kill him.",
    conflict: "Earlier that day, a bomb had bounced off the Archduke's car. So the cars drove fast through the town. Then the route was changed, so that the Archduke could visit the wounded.",
    surprise: "Nobody told the driver about the change. He took the old route and was told to reverse. The car stopped right outside a cafe where Princip was standing.",
    turning: "Princip stepped forward and fired twice. He killed the Archduke and his wife Sophie.",
    payoff: "Within five weeks, Austria had attacked Serbia. Russia, Germany, France and Britain were at war.",
    meaning: "Weak systems turn small accidents into disasters. The real cause was the alliances and arms races, not only one bullet.",
    extra: ["That day, Princip's group had seven killers waiting along the route.", "Because of the alliances, each country's move to defend itself forced another country to act.", "Within four years, around 20 million people had died."],
    facts: [["1914"], ["wrong turn", "took a wrong", "wrong road", "wrong street"], ["princip"], ["stall", "stopped", "reverse", "backing"], ["alliance", "allies"], ["bomb", "grenade"]],
    vocab: ["fuse", "cascade", "alliance"] },
  { id: "arkhipov", assetId: "cuban-submarine", title: "The Man Who Said No",
    hook: "In 1962, a Soviet officer sat in a very hot submarine. He stopped a nuclear war by refusing to say yes.",
    setting: "October 1962, near Cuba. The Cuban Missile Crisis has the whole world afraid. Soviet submarine B-59 is hiding below US warships.",
    character: "Vasili Arkhipov, chief of staff of the submarine group. And Captain Valentin Savitsky, very tired and frightened.",
    conflict: "US ships drop practice depth charges to force the submarine to come up. The crew has no contact with Moscow. The heat is terrible and the air is bad. They believe war has started.",
    surprise: "The captain orders a nuclear torpedo to be made ready. Three officers must agree before a launch, and two say yes.",
    turning: "Arkhipov refuses. After an angry argument, he gets the captain to come up to the surface and wait for orders.",
    payoff: "B-59 comes up, no torpedo is fired, and the crisis ends a few days later.",
    meaning: "Systems depend on the judgement of single people under pressure. Sometimes safety comes from one person's power to say no, not from a plan.",
    extra: ["The torpedo carried a bomb about as powerful as the one dropped on Hiroshima.", "The Americans did not know the submarine carried nuclear weapons.", "The world learned the details only many decades later."],
    facts: [["1962"], ["b-59", "submarine", "sub "], ["arkhipov"], ["three", "all three", "consent"], ["torpedo"], ["refus", "said no", "veto"], ["depth charge"]],
    vocab: ["veto", "composure", "deterrence"] },
  { id: "hanoi", assetId: "hanoi-rats", title: "Rat Tails of Hanoi",
    hook: "Hanoi once paid people to kill rats, and ended up with more rats than ever.",
    setting: "Hanoi, 1902. The city is ruled by France. Its new drains are full of rats, and officials fear the plague.",
    character: "French officials who wanted results, and ordinary people who wanted to be paid.",
    conflict: "Hiring rat hunters costs too much. So the government offers a bounty: bring a rat tail and get a payment.",
    surprise: "Officials began to see tailless rats running around the city. People were cutting off the tails and letting the rats go.",
    turning: "Some people even started breeding rats to collect their tails. The bounty was a reward for tails, not for fewer rats.",
    payoff: "The scheme was cancelled. The city had almost as many rats as before.",
    meaning: "People chase whatever you measure. If you reward a stand-in measure and not the goal, you may get the opposite of what you wanted.",
    extra: ["Historian Michael Vann studied and recorded this event.", "People often call it a cobra effect, after a similar story from Delhi.", "Today's examples include sales and school targets that people cheat on."],
    facts: [["1902"], ["hanoi"], ["tail"], ["bounty", "reward", "paid"], ["breed", "farm"], ["release", "let go", "tailless"], ["proxy", "measure", "incentive"]],
    vocab: ["bounty", "proxy", "incentive"] },
  { id: "wald", assetId: "wald-bombers", title: "The Planes That Didn't Come Back",
    hook: "The military wanted to put armour on bombers where the bullet holes were. A statistician said that was exactly the wrong place.",
    setting: "World War II. Allied bombers are being shot down in huge numbers. The military wants to add armour, but not so much that the planes become too heavy.",
    character: "Abraham Wald, a mathematician in a secret research group that worked with statistics.",
    conflict: "Engineers studied the planes that returned. Most bullet holes were on the wings and the body. The answer seemed clear: armour those parts.",
    surprise: "Wald asked: what about the planes that never returned?",
    turning: "The planes that returned showed where a bomber could be hit and still survive. The parts with no holes, like the engines, were where a hit destroyed the plane.",
    payoff: "The armour went where the holes were not.",
    meaning: "The data you see has already been filtered. Always ask what is missing.",
    extra: ["This is called survivorship bias.", "It is also true for startup advice, investing and career stories.", "People often add details when they tell this story. But Wald's study of weak points, based on planes that survived, is real."],
    facts: [["wald"], ["bomber", "plane", "aircraft"], ["bullet hole", "holes"], ["return", "came back", "survive"], ["armo"], ["engine", "cockpit", "missing", "didn't come back"]],
    vocab: ["survivorship", "sample", "bias"] },
  { id: "semmelweis", assetId: "semmelweis", title: "The Doctor Who Told Doctors to Wash",
    hook: "In 1847, a doctor found out how to stop women dying after childbirth. It destroyed his career.",
    setting: "Vienna General Hospital, 1847. Two maternity clinics stand side by side. But in one of them, many more mothers die.",
    character: "Ignaz Semmelweis, a young Hungarian doctor who could not stop thinking about the deaths.",
    conflict: "One clinic was run by doctors, who also did autopsies (cutting open dead bodies to study them). Far more mothers died there than in the midwives' clinic. Nobody knew why.",
    surprise: "A fellow doctor was cut by a surgical knife during an autopsy and died. He had the same signs of illness as the mothers. Semmelweis understood that doctors were carrying something deadly on their hands.",
    turning: "He made everyone wash their hands with chlorinated lime, a chlorine solution. Deaths fell from around 10% to 1-2%.",
    payoff: "Other doctors rejected him. Accepting his idea meant admitting that they had been killing patients. He died in 1865, and most people had still not accepted that he was right.",
    meaning: "People can reject a truth because it is uncomfortable, even when the data is in front of them. This is the “Semmelweis reflex”.",
    extra: ["The discovery of germs came later and proved him right.", "At times, around 10% of mothers died in the doctors' clinic.", "Clean hands are still one of the biggest safety problems in hospitals."],
    facts: [["1847"], ["vienna"], ["handwash", "washing hands", "wash their hands", "wash hands"], ["autops", "cadaver", "corpse"], ["reject", "dismiss", "ignored"], ["chlorin", "lime"], ["died", "asylum"]],
    vocab: ["mortality", "reflex", "vindicated"] },
  { id: "container", assetId: "container-shipping", title: "The Box That Changed the World",
    hook: "A truck owner had a simple idea. It made a T-shirt from Vietnam cheaper than one made in your own town.",
    setting: "America in the 1950s. Huge teams of dock workers load ships by hand, one sack, crate or barrel at a time. It is slow and costly, and many goods are stolen.",
    character: "Malcolm McLean, who owned a trucking business in North Carolina. He was tired of watching his trucks wait at ports.",
    conflict: "Loading a ship took days. Ports, workers' unions and railways all fought against his idea of standard boxes.",
    surprise: "In 1956, the ship Ideal X sailed with 58 containers. The cost of loading fell from around $5.86 to $0.16 per ton.",
    turning: "He pushed for standard container sizes and even shared his patents. Ports and ships were rebuilt around the box.",
    payoff: "Shipping costs fell sharply, and supply chains became global.",
    meaning: "Agreeing on one standard can matter more than a new invention. It changes a whole system.",
    extra: ["Ports like Newark and Rotterdam grew, while older ports lost their business.", "Cheap shipping let companies make goods in other countries and receive parts just when needed.", "About 90% of non-bulk cargo now travels in containers."],
    facts: [["mclean"], ["1956"], ["container", "box"], ["ideal x"], ["cost", "cheap", "cheaper"], ["standard"], ["global", "supply chain", "trade"]],
    vocab: ["standardise", "logistics", "intermodal"] }
];

MV.MISSIONS = [
  { id: "m-confirm", model: "confirmation-bias", text: "Notice one example of confirmation bias today, in yourself or in someone else. Which belief was the person protecting?" },
  { id: "m-incentive", model: "incentives", text: "Find a system around you (a reward points scheme, a work target, a rule). Say what it really rewards. Is that the same as its stated goal?" },
  { id: "m-bottleneck", model: "bottlenecks", text: "Find a bottleneck in your day: one thing that limits everything else. What would happen if you made it wider?" },
  { id: "m-nojargon", model: null, text: "Explain one idea you have learned to someone, using no technical words. Note what they asked you." },
  { id: "m-where", model: null, text: "Ask someone where they grew up. See if you can connect their answer to something you have learned (history, geography, economics)." },
  { id: "m-opp", model: "opportunity-cost", text: "Make a small decision today. Say out loud what you are giving up by making it." },
  { id: "m-network", model: "network-effects", text: "Find something that becomes more useful as more people use it. Is it a real network effect, or is it only popular?" },
  { id: "m-survivor", model: "survivorship-bias", text: "When you hear a success story this week, ask: what do the failures look like, and where are they?" },
  { id: "m-second", model: "second-order-thinking", text: "Pick a news story and write down what happens after the first result. And then what?" },
  { id: "m-feedback", model: "feedback-loops", text: "Find a feedback loop in your habits, a team or a market. Does it make a change grow, or does it slow it down?" },
  { id: "m-inversion", model: "inversion", text: "Take one of your goals. Write down what would surely make you fail. Then avoid those things." },
  { id: "m-listen", model: null, text: "In one conversation, practise LISTEN, CONNECT, CONTRIBUTE, ASK. Share your idea only after the other person has said something that leads to it." }
];

MV.STATES = [
  { key: "ENCOUNTERED", label: "Encountered", short: "Seen", desc: "You have seen it once." },
  { key: "FAMILIAR", label: "Familiar", short: "Familiar", desc: "You know it when you see it." },
  { key: "REMEMBERED", label: "Remembered", short: "Recalled", desc: "You can remember it without help." },
  { key: "UNDERSTOOD", label: "Understood", short: "Understood", desc: "You can explain how and why it works." },
  { key: "CONNECTED", label: "Connected", short: "Connected", desc: "You can link it to another idea." },
  { key: "EXPRESSIBLE", label: "Expressible", short: "Expressible", desc: "You can explain it clearly, even to a 10-year-old." },
  { key: "CONVERSATION_READY", label: "Conversation ready", short: "Convo-ready", desc: "You can use it naturally when talking to people." },
  { key: "STORY_READY", label: "Story ready", short: "Story-ready", desc: "You can tell its story in an interesting way." },
  { key: "MASTERED", label: "Mastered", short: "Mastered", desc: "You can explain it, connect it, use it and teach it." }
];

/* Evidence needed to climb each rung (in order). */
MV.PROGRESSION = ["DISCOVER", "UNDERSTAND", "RECALL", "CONNECT", "EXPLAIN", "APPLY", "TEACH", "MASTER"];
