/* MindVault seed knowledge assets.
   mcq.o[0] is always the correct option (shuffled at runtime).
   chain = ordered causal steps [label, [lowercase keywords…]] used for recall grading,
   missing-link detection and explanation scoring. */
window.MV = window.MV || {};
MV.DOMAINS = {
  history: "History", geography: "Geography", economics: "Economics", business: "Business & Finance",
  psychology: "Psychology", science: "Science", philosophy: "Philosophy", strategy: "Strategy",
  design: "Architecture", anthropology: "Anthropology", language: "Language"
};
MV.DOMAIN_COLORS = {
  history: "#d9a441", geography: "#6fb7a8", economics: "#e07a5f", business: "#f2cc8f", psychology: "#b392d6",
  science: "#7ab8e8", philosophy: "#c9a0a0", strategy: "#9bc47a", design: "#e8a2c5", anthropology: "#c7b58a", language: "#8fa7b8"
};

MV.ASSETS = [
{ id: "roman-roads", type: "concept", domain: "history", title: "Roman roads", value: 4, cue: "roads, daily travel or late deliveries",
  fact: "Rome built about 80,000 km of stone roads (about 400,000 km if you count dirt tracks). These roads joined an empire that stretched from Britain to Syria.",
  why: "The roads turned many conquered lands into one economy. Soldiers, tax collectors, traders and news all travelled on the same network.",
  mech: "The roads were built the same way everywhere and could be used in any weather. So travel became faster and safer. A small army could then defend a very long border. Transport also became cheaper, so each region could make what it was best at and trade it. Every new road made all the old roads more useful.",
  models: ["network-effects", "compounding", "bottlenecks"],
  q: "Why were Roman roads more than a military project?",
  a: "They cut the time and cost of moving soldiers, goods and news. So the empire could defend itself cheaply, and regions could trade and focus on what they made best.",
  chain: [["Faster, cheaper travel", ["faster", "quick", "speed", "cheap", "cost", "time"]], ["A small army can cover more land", ["army", "legion", "troops", "military", "defend"]], ["More trade, and regions focus on what they do best", ["trade", "merchant", "commerce", "special", "goods"]], ["Each new road makes the network more useful", ["network", "connect", "each road", "more valuable", "every road"]]],
  mcq: { q: "What was the deeper effect of Rome's road network?", o: ["It made moving soldiers, goods and news cheaper, and joined the empire into one economy", "It was built mainly for chariot racing", "It marked the tax borders between provinces", "It worked as a wall to keep invaders out"] },
  bring: "When people talk about roads or metro lines: “Roads quietly decide who gets rich. Rome won mostly by building good roads.”",
  follow: "What do you think is today's Roman road: internet cables, ports, or something else?",
  deeper: "Romans built roads in layers: broken stone at the bottom, then gravel, then flat paving stones on top. Ditches on the sides carried rainwater away. “All roads lead to Rome” was really true. The network was planned with Rome at the centre.",
  story: null, jargon: ["infrastructure"], mis: [{ re: "(only|just|purely|mainly) (for|to) (the )?(war|military|army)", msg: "The roads were not only for the army. Traders and government officers used them just as much." }] },

{ id: "pantheon-dome", type: "fact", domain: "design", title: "The Pantheon's concrete dome", value: 3, cue: "buildings that last, concrete, or ancient technology",
  fact: "The Pantheon in Rome has a dome about 43 m wide. It was finished around 126 AD. It is still the largest concrete dome in the world built without steel bars inside (unreinforced).",
  why: "It has stood for nearly 1,900 years. Roman engineers solved a problem that modern builders still respect.",
  mech: "The Romans mixed lighter stones (aggregate) into the concrete near the top. They made the base thick and heavy. They also left a round opening, called the oculus, at the centre of the dome. All this reduced the stress on the dome. Their concrete, made with volcanic ash, was strong and lasted a long time.",
  models: ["lindy-effect", "first-principles"],
  q: "What is special about the Pantheon's dome?",
  a: "It is the largest concrete dome ever built without steel inside. It still stands after about 1,900 years. The concrete gets lighter towards the top, and a round opening in the centre lowers the stress.",
  chain: [["Largest concrete dome without steel", ["largest", "biggest", "unreinforced", "no steel", "concrete"]], ["Still standing after about 1,900 years", ["1,900", "1900", "nearly 2000", "still standing", "ancient", "survive", "years"]], ["Lighter material near the top", ["lighter", "lighten", "graded", "thinner", "aggregate"]], ["The round opening (oculus) lowers stress", ["oculus", "opening", "hole"]]],
  mcq: { q: "Why has the Pantheon dome lasted nearly 2,000 years?", o: ["The concrete gets lighter towards the top, and there is a round opening in the centre", "Steel rods are hidden inside the concrete", "It was fully rebuilt every hundred years", "It is cut from one single block of marble"] },
  bring: "When people talk about old buildings: “The Pantheon's dome is still the biggest concrete dome without steel in the world. It is nearly 2,000 years old.”",
  follow: "Why do you think so much modern concrete breaks down faster than that?",
  deeper: "Roman concrete used volcanic ash, called pozzolana. Recent research suggests that small lumps of lime in it can help cracks repair themselves.",
  story: null, jargon: ["unreinforced", "aggregate", "oculus"], mis: [] },

{ id: "sarajevo-1914", type: "historical story", domain: "history", title: "The wrong turn at Sarajevo (WWI)", value: 5, cue: "how big events start from small accidents",
  fact: "On 28 June 1914, a driver took a wrong turn. The car of Archduke Franz Ferdinand stopped right in front of Gavrilo Princip, who shot him. Within about five weeks, Europe's alliances had pulled the great powers into war.",
  why: "A small accident started a war. But the danger had been building for years through alliances and arms races. It is a classic example of how a weak system turns a small shock into a disaster.",
  mech: "Europe was split into groups of allies who had promised to fight for each other. Each country also had a fixed plan for getting its army ready (mobilisation). Austria-Hungary blamed Serbia. Russia supported Serbia. Germany supported Austria. Then France and Britain were pulled in. Each move made for defence forced the other side to answer.",
  models: ["feedback-loops", "game-theory", "second-order-thinking"],
  q: "Why did one killing in Sarajevo turn into a world war?",
  a: "The alliances and army plans were fixed and could not bend. Each country's move to defend itself forced the next country to act. So a local crisis grew into a war across Europe.",
  chain: [["Princip kills the Archduke in Sarajevo", ["princip", "assassinat", "franz ferdinand", "archduke", "sarajevo"]], ["Austria blames Serbia", ["austria", "serbia", "ultimatum"]], ["Alliances pull the big powers in", ["alliance", "allies", "russia", "germany", "france", "britain"]], ["Fixed army plans make each move bigger", ["mobili", "escalat", "domino", "chain", "trigger", "forced", "rigid"]]],
  mcq: { q: "What turned one killing into a war across Europe?", o: ["Linked alliances and fixed plans for getting armies ready", "A secret agreement to divide Serbia", "A blockade of Britain by sea", "The collapse of the German economy"] },
  bring: "When someone asks how wars start: “World War I almost did not happen. The Archduke's driver took a wrong turn and stopped right in front of the killer.”",
  follow: "Do you think the war would have happened anyway? Or did that one moment really matter?",
  deeper: "Historians still argue about whether the war was certain to happen. The causes had been building for decades. Countries were racing to build bigger navies. Rival alliances faced each other. People in the Balkans wanted their own nations. And the army timetables punished any country that waited.",
  story: "sarajevo", jargon: ["mobilisation"], mis: [{ re: "(started|caused) (only|just) by", msg: "The killing was only the spark. The alliances and arms races were what made it so dangerous." }] },

{ id: "wwii-origins", type: "event", domain: "history", title: "From Versailles to WWII", value: 5, cue: "history, politics or how peace agreements fail",
  fact: "The 1919 Treaty of Versailles blamed Germany for the war. It also made Germany pay very large sums for war damage (reparations). Then came hyperinflation and later the Great Depression. Together, these helped the Nazis rise to power.",
  why: "It shows how a peace agreement can lead to the next war. It is also why historians argue about whether peace terms should be harsh or gentle.",
  mech: "The reparations and the “war guilt” clause made Germans angry and bitter. Then came two economic crises: the inflation of 1923 and the depression of 1929. People stopped trusting the moderate parties. Extreme parties offered simple answers and people to blame.",
  models: ["second-order-thinking", "incentives", "feedback-loops"],
  q: "How did the years after WWI help cause WWII?",
  a: "The reparations and the war guilt clause of Versailles made Germans bitter. Then the economy collapsed. People lost trust in moderate leaders, and extreme leaders rose.",
  chain: [["Versailles: payments and blame", ["versailles", "reparation", "guilt", "treaty"]], ["Anger in Germany", ["resent", "humiliat", "anger", "bitter"]], ["Economic crisis", ["inflation", "depression", "econom", "unemploy", "collapse"]], ["Extreme leaders use the anger", ["nazi", "hitler", "extrem", "scapegoat", "rise"]]],
  mcq: { q: "Which of these best explains the rise of the Nazis?", o: ["A hated peace treaty, plus an economic collapse that made people lose trust in moderate parties", "An army takeover paid for by Britain", "Germany winning a big war in 1920", "A sudden return to religion"] },
  requires: ["sarajevo-1914"],
  bring: "When people talk about peace deals: “Versailles is the warning. A peace agreement can be so harsh that it leads to the next war.”",
  follow: "Is it better to make peace gentle or tough? What did the Marshall Plan do differently after WWII?",
  deeper: "At that time, economists like Keynes warned that Germany could never pay the reparations. After WWII, the Marshall Plan helped rebuild Europe instead of punishing it.",
  story: null, jargon: ["reparations"], mis: [{ re: "(solely|only|entirely) (because|due to|caused by) (the )?(treaty|versailles)", msg: "Versailles was only one cause. The Depression and the choices of politicians also mattered." }] },

{ id: "weimar-hyperinflation", type: "event", domain: "economics", title: "Weimar hyperinflation", value: 4, cue: "rising prices, savings or printing money",
  fact: "By November 1923, one US dollar bought about 4.2 trillion German marks. People burned banknotes to keep warm, because notes were cheaper than firewood. Prices rising this fast is called hyperinflation.",
  why: "It shows that money works only because people trust it. It also shows how inflation quietly destroys savings and trust between people.",
  mech: "The government printed money to pay its war debts and reparations. Prices went up. So people spent their cash at once, before it lost value. Money moved faster and prices rose even more. This is a feedback loop: the result feeds the cause.",
  models: ["feedback-loops", "compounding", "incentives"],
  q: "Why did German prices rise so fast in 1923?",
  a: "The government printed money to pay debts and reparations. People spent their cash at once, before it lost value. That pushed prices up even faster, in a feedback loop.",
  chain: [["Printing money to pay debts", ["print", "money supply", "debt", "reparation"]], ["Prices go up", ["price", "inflation"]], ["People spend their cash at once", ["spend", "dump", "immediately", "rush", "velocity"]], ["A feedback loop makes it faster", ["feedback", "spiral", "vicious", "faster", "accelerat", "loop"]]],
  mcq: { q: "What turned high inflation into hyperinflation in Weimar Germany?", o: ["A feedback loop: more money printed, less trust, and people spending cash at once", "Not enough paper to print banknotes", "A fixed exchange rate with gold", "Foreign banks refusing to give any loans"] },
  requires: ["sarajevo-1914"],
  bring: "When people talk about rising prices: “In 1923, Germans burned banknotes to keep warm. It was cheaper than wood.”",
  follow: "What do you think really makes people trust a currency?",
  deeper: "Workers were paid twice a day. They went shopping at once, because prices were higher again by evening. People with savings in cash or fixed deposits lost everything. People who owed money gained, because their debts became tiny.",
  story: null, jargon: ["hyperinflation", "money supply"], mis: [] },

{ id: "cold-war-mad", type: "concept", domain: "strategy", title: "Mutually Assured Destruction", value: 4, cue: "nuclear weapons, or two sides afraid to attack each other",
  fact: "Mutually Assured Destruction (MAD) means this: both superpowers can destroy each other, even after being hit first. So it makes no sense for either side to attack first.",
  why: "It explains why the Cold War never became a real war. It also shows that fear can keep things stable.",
  mech: "Each side kept weapons that could survive a surprise attack, such as missiles on submarines and in strong underground shelters. This is called second-strike ability. So a surprise attack could not stop the other side from hitting back. Attacking first meant your own country would surely be destroyed.",
  models: ["game-theory", "incentives"],
  q: "Why did MAD make nuclear war less likely?",
  a: "Both sides could hit back even after being attacked first. So attacking first meant destroying yourself. Neither side had any good reason to start.",
  chain: [["Both sides can destroy each other", ["both", "each other", "mutual", "superpower"]], ["The power to hit back survives", ["second strike", "second-strike", "retaliat", "submarine", "survive"]], ["Attacking first means destroying yourself", ["first strike", "attack first", "suicid", "self-destruct", "no winner", "destroy themselves"]], ["Fear keeps the peace (deterrence)", ["deter", "stable", "stabil", "peace", "prevent"]]],
  mcq: { q: "What made MAD stable?", o: ["Both sides could hit back after being attacked, so attacking first made no sense", "One side had a shield against missiles", "Both sides had agreed never to build new weapons", "Nuclear weapons could not hit their targets well enough to use"] },
  requires: ["wwii-origins"],
  bring: "If people talk about nuclear danger: “The strange thing is that it works because it is so frightening. Neither side can gain by attacking first.”",
  follow: "Does MAD still work when more than two countries, or armed groups, have the bomb?",
  deeper: "This is called a Nash equilibrium. It means no player can do better by changing only their own move. The danger comes from wrong messages or false alarms. That is why direct phone lines between leaders and arms-control treaties mattered.",
  story: null, jargon: ["deterrence", "second-strike", "Nash equilibrium"], mis: [] },

{ id: "nato-article5", type: "event", domain: "history", title: "NATO and Article 5", value: 3, cue: "alliances, Ukraine or the safety of Europe",
  fact: "NATO was started in 1949 with 12 member countries. Its Article 5 says that an attack on one member is an attack on all. It has been used only once: after the 9/11 attacks in 2001.",
  why: "It turns a promise into a clear warning line. An attacker knows that hitting one member means facing all of them.",
  mech: "All members promise in advance to act. So there is no doubt about how they will react. This makes an attack more costly and so less likely.",
  models: ["game-theory", "incentives"],
  q: "What does Article 5 of the NATO treaty do?",
  a: "It says an attack on one member is an attack on all. This promise, made in advance, stops others from attacking. It has been used once, after 9/11.",
  chain: [["An attack on one is an attack on all", ["attack on one", "all members", "collective", "attack on all", "all of them"]], ["A promise made in advance removes doubt", ["commit", "promise", "tripwire", "pledge", "ambigu"]], ["It stops others from attacking", ["deter", "prevent", "cost", "think twice"]], ["Used once, after 9/11", ["9/11", "september", "2001", "once"]]],
  mcq: { q: "When has NATO's Article 5 been used?", o: ["Once, after the 9/11 attacks in 2001", "Never", "During the Cuban Missile Crisis", "After the fall of the Berlin Wall"] },
  requires: ["wwii-origins"],
  bring: "When NATO is in the news: “Article 5 has been used only once. It was to help the US after 9/11.”",
  follow: "Do you think promises like that make wars less likely, or more likely to spread?",
  deeper: "Article 5 does not force members to fight. Each member must take the action it thinks is necessary. News headlines often miss this point.",
  story: null, jargon: ["tripwire", "collective defence"], mis: [{ re: "automatic(ally)? (declare|go to|send)", msg: "Article 5 does not mean automatic war. Each member promises to take the action it thinks is necessary." }] },

{ id: "cuban-submarine", type: "historical story", domain: "history", title: "The man who stopped a nuclear launch", value: 5, cue: "heroes, pressure, or the Cuban Missile Crisis",
  fact: "On 27 October 1962, the Soviet submarine B-59 had lost contact with Moscow. US ships were dropping depth charges (underwater bombs) on it. The captain wanted to fire a nuclear torpedo. Vasili Arkhipov, the commander of the submarine group, refused to agree. The torpedo was not fired.",
  why: "This may be the closest the world ever came to nuclear war. One officer who stayed calm under pressure stopped it.",
  mech: "Three officers had to agree before a launch. The crew was hot, tired and short of fresh air, and had no contact with Moscow. They believed war had already started. Arkhipov said no, and that stopped the launch.",
  models: ["game-theory", "second-order-thinking", "map-vs-territory"],
  q: "What happened on the Soviet submarine B-59 in October 1962?",
  a: "US ships dropped practice depth charges. The submarine lost contact with Moscow. The captain wanted to fire a nuclear torpedo. Vasili Arkhipov refused to agree.",
  chain: [["B-59 loses contact and is under depth charges", ["b-59", "submarine", "depth charge", "cut off", "no contact", "moscow"]], ["The captain thinks war has started", ["captain", "savitsky", "war had begun", "thought war", "believed"]], ["Three officers must agree", ["three", "consent", "agree", "all three"]], ["Arkhipov says no", ["arkhipov", "refus", "veto", "said no", "stopped"]]],
  mcq: { q: "Who stopped the launch of a nuclear torpedo from B-59?", o: ["Vasili Arkhipov, who refused to agree", "John F. Kennedy, by a radio order", "Captain Savitsky, who changed his mind on his own", "A fault in the torpedo"] },
  requires: ["cold-war-mad"],
  bring: "At dinner, if people talk about risk or luck: “One of the most important people in history was a Soviet officer on a submarine. In 1962 he said no to a nuclear launch.”",
  follow: "How much of history do you think depends on one person staying calm?",
  deeper: "The US ships used practice depth charges to force the submarine to come up. But the crew did not know they were only for practice. Many years later, Arkhipov was honoured with the Future of Life Award.",
  story: "arkhipov", jargon: [], mis: [] },

{ id: "east-india-company", type: "concept", domain: "business", title: "The East India Company", value: 4, cue: "company power, monopolies or colonial history",
  fact: "The East India Company got its royal licence (charter) in 1600. This company came to rule much of India. By the early 1800s it had its own army of around 260,000 soldiers, larger than Britain's own army.",
  why: "It was the first company that became too big and powerful to be allowed to fail. It was a business that behaved like a government.",
  mech: "The king's charter gave it a monopoly, which means only this company was allowed to do the trade. Its shareholders wanted profits. So the Company had strong reasons to control more land, collect taxes and use force. Its profits then paid for even more expansion.",
  models: ["incentives", "compounding", "feedback-loops"],
  q: "Why did a trading company end up ruling most of India?",
  a: "Its monopoly charter and its shareholders rewarded it for taking more land and collecting more tax. Profits paid for armies, and armies won more land.",
  chain: [["A royal charter gives it a monopoly", ["charter", "monopoly", "royal"]], ["Shareholders want profits", ["shareholder", "profit", "return", "dividend"]], ["Its own army, and collecting taxes", ["army", "tax", "force", "soldier", "revenue"]], ["Profits pay for more expansion", ["expan", "conquest", "fund", "reinvest", "loop", "compound"]]],
  mcq: { q: "What pushed the East India Company from trading to ruling?", o: ["Monopoly rights and the push for shareholder profit, which rewarded taking more control", "An order from the British parliament to make India a colony", "A plan to spread Christianity", "A deal with the Mughal emperor to end taxes"] },
  bring: "When people talk about big tech or company power: “The East India Company had its own army, bigger than Britain's. Company power is not a new problem.”",
  follow: "What stops a company today from becoming like a government?",
  deeper: "The word “loot” came into English from Hindi during this period. The Company was closed down after the 1857 rebellion. India then came under the direct rule of the British Crown.",
  story: null, jargon: ["monopoly", "charter"], mis: [] },

{ id: "thermopylae", type: "event", domain: "strategy", title: "Thermopylae", value: 4, cue: "small sides beating big ones, land shape, or leading under pressure",
  fact: "In 480 BC, about 7,000 Greeks, including 300 Spartans, defended a narrow pass by the sea. They held back a much larger Persian army for three days. Then the Persians found a way around them.",
  why: "The narrow pass made the Persians' large numbers useless. The shape of the land made a small force much stronger.",
  mech: "In a narrow place, only a few soldiers can fight at one time. So the bigger army cannot use its larger numbers. The Greeks lost only when a local man, Ephialtes, showed the Persians a path over the mountain.",
  models: ["bottlenecks", "game-theory"],
  q: "How could a small Greek force hold back a much bigger army at Thermopylae?",
  a: "The narrow pass limited how many Persians could fight at one time. So their numbers did not help. Then a traitor showed them a path around the pass.",
  chain: [["A narrow pass limits the fighting line", ["narrow", "pass", "chokepoint", "choke", "front"]], ["The big army cannot use its numbers", ["numbers", "outnumber", "larger", "cancel", "neutral", "fewer"]], ["The Greeks hold for days", ["three days", "days", "held"]], ["A traitor shows a mountain path", ["path", "betray", "ephialtes", "flank", "around", "mountain"]]],
  mcq: { q: "Why did the narrow pass help the Greeks?", o: ["Only a few Persians could fight at one time, so their large numbers did not help", "It hid the Greek navy", "It forced the Persians to fight uphill in snow", "It had forts all along it"] },
  bring: "When people talk about a small side beating a big one: “Thermopylae shows that the land can matter more than numbers. The pass took away the Persians' advantage.”",
  follow: "In business, what is like a narrow pass, where size does not matter?",
  deeper: "A small group of Greeks stayed behind so that the main force could retreat safely. Their fight gave the Greek navy and cities time to prepare. This helped the Greeks win later at Salamis and Plataea.",
  story: null, jargon: ["force multiplier"], mis: [{ re: "(only|just|exactly) 300", msg: "The 300 Spartans did not fight alone. Several thousand other Greeks fought with them." }] },

{ id: "sun-tzu", type: "concept", domain: "strategy", title: "Win without fighting (Sun Tzu)", value: 3, cue: "bargaining, competition or conflict",
  fact: "Sun Tzu's book The Art of War says the highest skill is to make the enemy give up without a fight. You win through a strong position, good preparation and good information.",
  why: "Battles cost a lot, even for the winner. So the best plan is one that makes the battle unnecessary.",
  mech: "You shape the situation first: a strong position, allies, tricks to mislead the enemy, and good supplies. Then fighting looks hopeless to your opponent. They give up or go back before anyone pays the cost of battle.",
  models: ["second-order-thinking", "inversion"],
  q: "What does Sun Tzu say is the best strategy of all?",
  a: "To win without fighting. Use position, preparation and information so that the opponent gives up before a costly battle.",
  chain: [["Winning without fighting is best", ["without fight", "no fight", "avoid battle", "without battle", "not fight"]], ["Battles cost a lot, even if you win", ["cost", "expens", "damage", "lose", "resources"]], ["Use position, information and tricks", ["position", "information", "decepti", "prepar", "intelligence", "terrain"]], ["The opponent gives up early", ["yield", "surrender", "retreat", "give up", "concede", "hopeless"]]],
  mcq: { q: "What is Sun Tzu's ideal victory?", o: ["Making the enemy give up without a battle", "Crushing the enemy in one big battle", "Starving the enemy by surrounding them for a long time", "Winning with a much larger army"] },
  bring: "In a story about bargaining: “Sun Tzu said the best win is the fight that never happens.”",
  follow: "When have you seen someone win a disagreement without really arguing?",
  deeper: "Sun Tzu also says you must know yourself and your enemy: “know the enemy and know yourself, in a hundred battles you will never be in peril.” Peril means danger.",
  story: null, jargon: [], mis: [] },

{ id: "ooda-loop", type: "mental model", domain: "strategy", title: "The OODA loop", value: 4, cue: "speed, competition or making decisions",
  fact: "Fighter pilot John Boyd described the OODA loop: Observe, Orient, Decide, Act. Orient means making sense of what you see. The side that goes through these four steps faster than its opponent wins.",
  why: "It shows that competition is a race to learn faster, not only a test of strength.",
  mech: "If you go through the steps faster, the situation changes before your opponent can react. Their actions answer a situation that is already gone. They become confused and make bad decisions.",
  models: ["feedback-loops", "first-principles"],
  q: "What does it mean to get “inside” an opponent's OODA loop?",
  a: "It means you observe, orient, decide and act faster than they can. So their answers are based on old information.",
  chain: [["Observe, Orient, Decide, Act", ["observe", "orient", "decide", "act"]], ["Go through the steps faster than the opponent", ["faster", "quicker", "speed", "tempo"]], ["The opponent reacts to an old situation", ["outdated", "late", "behind", "old information", "changed"]], ["Confusion and bad decisions", ["confus", "paraly", "mistake", "off balance"]]],
  mcq: { q: "Which of these describes winning with the OODA loop?", o: ["Going through observe, orient, decide and act faster than the opponent", "Having the most powerful weapons", "Planning every detail in advance", "Not deciding until you have all the data"] },
  bring: "When people talk about startups or sports: “Boyd's idea was that you do not need to be stronger. You need to learn and change faster.”",
  follow: "Where in your work would faster learning beat a better plan?",
  deeper: "Orient is the most important step. Here your beliefs, habits and culture shape how you understand what you see. Boyd called it the “schwerpunkt” of the loop, a German word for the main point.",
  story: null, jargon: ["OODA"], mis: [] },

{ id: "russia-ports", type: "concept", domain: "geography", title: "Russia's warm-water port problem", value: 4, cue: "Russia, Crimea or why geography matters",
  fact: "Russia has a very long coast. But much of it freezes in winter. Other parts reach the open ocean only through narrow sea passages that other countries control. So for centuries, Russia's plans have been shaped by its need for ports that stay open all year.",
  why: "Geography explains actions that look strange on a political map. Ports like Sevastopol matter a great deal to Russia.",
  mech: "An empire made mostly of land still needs the sea for trade and for its navy. Russia's northern ports freeze or are far from trade routes. Ships leaving the Baltic Sea and the Black Sea must pass through narrow straits held by other countries.",
  models: ["bottlenecks", "map-vs-territory"],
  q: "Why does Russia care so much about places like Crimea?",
  a: "Most of its coast freezes, or opens only through straits that others control. So ports without ice, like Sevastopol, are very important for its navy and its trade.",
  chain: [["Much of the coast freezes or is far from trade routes", ["freeze", "ice", "frozen", "arctic", "far"]], ["The ways out pass through straits others control", ["strait", "chokepoint", "bosphorus", "baltic", "denmark", "control"]], ["Russia needs warm-water ports", ["warm", "year-round", "ice-free", "port", "sevastopol", "naval base"]], ["This shapes its strategy", ["strategy", "strategic", "policy", "behav", "expan"]]],
  mcq: { q: "Why is Crimea so valuable to Russia?", o: ["It has a navy base on the Black Sea that is free of ice all year", "It has Russia's largest oil fields", "It is the only place where Russia grows wheat", "It shares a border with China"] },
  bring: "When people talk about Russia: “The map shows a huge coast. In reality, most of it is ice and narrow passages. That is half of the story.”",
  follow: "How much do you think geography decides what countries want?",
  deeper: "Even Russia's Black Sea ships must pass through the Turkish straits, the Bosphorus and the Dardanelles. Turkey controls these under an agreement called the Montreux Convention.",
  story: null, jargon: ["warm-water port", "chokepoint"], mis: [] },

{ id: "hormuz", type: "fact", domain: "geography", title: "The Strait of Hormuz", value: 4, cue: "oil prices, Iran or world trade",
  fact: "About one fifth of the oil the world uses passes through the Strait of Hormuz. At its narrowest point, this sea passage is only about 33 km wide.",
  why: "The whole world economy depends on one small piece of water. If it fails, everyone is hurt.",
  mech: "Oil producers like Saudi Arabia, Iraq, Kuwait and the UAE must send their ships through the strait. If it is blocked, less oil reaches the world and prices jump everywhere. There are very few other routes.",
  models: ["bottlenecks", "second-order-thinking"],
  q: "Why does the Strait of Hormuz matter to the world economy?",
  a: "About a fifth of the world's oil passes through a very narrow channel. There are few other routes. So if it is blocked, prices jump everywhere.",
  chain: [["About a fifth of the world's oil passes through", ["fifth", "20%", "20 percent", "oil"]], ["A very narrow channel", ["narrow", "33", "channel", "strait"]], ["Few other routes", ["alternative", "few", "no other", "pipeline"]], ["A block makes world prices jump", ["price", "spike", "disrupt", "shock", "block"]]],
  mcq: { q: "About how much of the oil the world uses passes through Hormuz?", o: ["About one fifth", "About one in a hundred", "About half", "Almost none, it mostly goes by pipeline"] },
  bring: "When people talk about petrol or oil prices: “Around 20% of the world's oil goes through a strait only about 30 km wide at its narrowest.”",
  follow: "What do you think would happen to prices if it closed for a month?",
  deeper: "The lanes for ships are only a few km wide in each direction. Some pipelines go around the strait, for example the Saudi East-West pipeline and the UAE's Fujairah route. But they can carry only a limited amount.",
  story: null, jargon: ["chokepoint"], mis: [] },

{ id: "container-shipping", type: "historical story", domain: "business", title: "The shipping container", value: 5, cue: "supply chains, world trade or why things are cheap",
  fact: "In 1956, a truck owner named Malcolm McLean sent the first container ship, the Ideal X, from Newark. The cost of loading fell from about $5.86 to about $0.16 per ton. That is over 95% cheaper.",
  why: "A metal box changed world trade. Shipping became so cheap that it made sense to make things anywhere in the world.",
  mech: "All the boxes were the same size. They could move between ship, train and truck without being unpacked. Ports needed far fewer workers. There was less theft, less waiting and much lower cost. This made possible today's worldwide supply chains, where parts arrive just when they are needed.",
  models: ["bottlenecks", "network-effects", "first-principles"],
  q: "Why did the shipping container change the world economy?",
  a: "Boxes of one standard size made loading and moving goods much cheaper and faster. Shipping costs fell sharply. So supply chains across the world started to make economic sense.",
  chain: [["Boxes of one standard size", ["standard", "box", "uniform", "same size"]], ["They move between ship, train and truck", ["truck", "train", "rail", "ship", "transfer", "intermodal"]], ["The cost of loading falls sharply", ["cost", "cheap", "labour", "labor", "dockworker", "time in port", "fell"]], ["Worldwide supply chains become possible", ["global", "supply chain", "trade", "factory", "anywhere", "offshore"]]],
  mcq: { q: "What was the really new idea in the container?", o: ["One standard size, so goods moved between ship, train and truck without unpacking", "Stronger steel for ships", "Faster ship engines", "Cooling to keep fruit fresh"] },
  bring: "When people talk about supply chains: “The big change in shipping was not a ship. It was a box. A truck owner thought of using boxes of one standard size.”",
  follow: "What other standard has quietly changed a whole industry?",
  deeper: "Agreeing on standard sizes (ISO sizes of 20 and 40 feet) was as important as the box itself. McLean even gave away his patents so that others would start using containers faster.",
  story: "container", jargon: ["intermodal", "supply chain"], mis: [] },

{ id: "amazon-flywheel", type: "mental model", domain: "business", title: "The Amazon flywheel", value: 4, cue: "startups, online platforms or why Amazon is hard to beat",
  fact: "In 2001, Jeff Bezos drew a loop called a flywheel. Lower prices bring more customers. More customers bring more sellers. More sellers bring lower costs. Lower costs allow lower prices again.",
  why: "It shows how a loop that feeds itself can turn low costs into a lasting defence against competitors.",
  mech: "Each turn of the loop makes the next turn cheaper. More sales spread the fixed costs, like warehouses and computers, over more orders. More choice brings more visitors. More visitors bring more sellers. Then the cycle repeats.",
  models: ["feedback-loops", "network-effects", "compounding"],
  q: "How does Amazon's flywheel work?",
  a: "Lower prices bring customers. More customers bring sellers. More sellers and more sales lower the costs. Lower costs pay for lower prices again.",
  chain: [["Lower prices", ["lower price", "low price", "cheaper", "price"]], ["More customers", ["customer", "traffic", "shopper"]], ["More sellers and more choice", ["seller", "selection", "marketplace", "third-party"]], ["Lower costs, and the loop repeats", ["cost", "scale", "loop", "reinforc", "flywheel", "again"]]],
  mcq: { q: "Why is it hard to compete with a flywheel?", o: ["Each turn lowers costs and makes the next turn stronger, so the loop feeds itself", "It depends on patents that never end", "Its prices never change", "It depends on one single supplier"] },
  bring: "When people talk about Amazon or online platforms: “Bezos drew his strategy on a napkin: lower prices, more customers, more sellers, lower costs, repeat.”",
  follow: "Where else do you see a flywheel, in business or in your own habits?",
  deeper: "Jim Collins made the flywheel idea well known in his book Good to Great. The main lesson: there is no single big push. Many steady pushes in the same direction add up over time.",
  story: null, jargon: ["moat", "flywheel"], mis: [] },

{ id: "comparative-advantage", type: "concept", domain: "economics", title: "Comparative advantage", value: 5, cue: "trade, jobs, or why countries focus on a few things",
  fact: "David Ricardo showed something surprising. Even if one country is better at making everything, both countries still gain from trade. Each should focus on what it does best compared with its other choices. This is called comparative advantage.",
  why: "It is the reason trade can make both sides richer. It works for people and teams too.",
  mech: "What matters is opportunity cost, not who is more skilled. Opportunity cost is what you give up to make something. The side that gives up less to make a thing should focus on that thing. The other side focuses on something else. Together they produce more.",
  models: ["opportunity-cost", "incentives"],
  q: "How can trade help a country that is worse at making everything?",
  a: "The gains come from differences in opportunity cost, not from who is best. Each side focuses on the thing for which it gives up the least. So both sides end up with more.",
  chain: [["Opportunity cost matters, not who is more skilled", ["opportunity cost", "give up", "sacrific", "relative"]], ["Each side focuses where it gives up the least", ["special", "focus", "best at", "relatively"]], ["Together they produce more", ["output", "total", "more", "produce more", "bigger pie"]], ["Trade lets both sides gain", ["trade", "both", "gain", "benefit", "win"]]],
  mcq: { q: "What creates comparative advantage?", o: ["Differences in opportunity cost, even if one side is better at everything", "Having the cheapest workers", "Having more natural resources", "Protecting local industries"] },
  bring: "When people talk about who should do which job: “A top lawyer should still hire a typist, even if she types faster herself. Her own time is worth more on legal work.”",
  follow: "Where in your life would you do better by letting someone else do a thing you are good at?",
  deeper: "Ricardo's famous example used English cloth and Portuguese wine. Critics point out two weak points. The idea assumes that everyone has a job. It also ignores the pain for workers who must change jobs.",
  story: null, jargon: ["opportunity cost", "specialise"], mis: [{ re: "(only|just) (the )?(better|best|cheapest) (country|one)", msg: "It is about what each side gives up, not about who is simply the best." }] },

{ id: "hanoi-rats", type: "historical story", domain: "economics", title: "The Hanoi rat bounty", value: 5, cue: "rewards, targets or results nobody planned",
  fact: "In 1902, the French rulers of Hanoi paid people a reward (a bounty) for every rat tail. People began to cut off the tails and let the rats go, so the rats could have more babies. Some people even farmed rats.",
  why: "It is the classic example of a reward that produces the opposite of what was wanted. It is one form of the “cobra effect”.",
  mech: "The officials wanted fewer rats. But they paid for tails. A tail was only a proxy, which means a stand-in measure for the real goal. People worked to get more tails, not to reduce the rats.",
  models: ["incentives", "goodharts-law", "second-order-thinking"],
  q: "What went wrong with Hanoi's rat bounty?",
  a: "It paid for rat tails, not for fewer rats. So people bred rats, or cut off the tails and let the rats go. They chased the measure and not the goal.",
  chain: [["A bounty is paid for rat tails", ["bounty", "tail", "paid", "reward"]], ["A stand-in measure (proxy), not the real goal", ["proxy", "measure", "metric", "target", "goal"]], ["People breed rats or let them go", ["bred", "breed", "farm", "released", "release", "cut off"]], ["The opposite result", ["opposite", "backfire", "more rats", "unintended", "worse"]]],
  mcq: { q: "Why did the Hanoi rat bounty fail?", o: ["It paid for tails, a stand-in measure, so people cheated instead of reducing rats", "The rats stopped dying from poison", "The reward was too small to interest hunters", "French officials banned rat hunting"] },
  bring: "When people talk about targets or KPIs: “It is the Hanoi rat problem. Pay for rat tails and you get rat farms.”",
  follow: "What measure around you are people quietly cheating on?",
  deeper: "Historian Michael Vann studied and recorded this event. The well-known “cobra effect” story, about a reward for cobras in Delhi, is told often but has little written proof. So the Hanoi story is the safer example to use.",
  story: "hanoi", jargon: ["proxy", "metric"], mis: [] },

{ id: "buffett-compounding", type: "fact", domain: "business", title: "Buffett and compounding", value: 4, cue: "investing, patience or long-term thinking",
  fact: "Warren Buffett earned about 99% of his wealth after his 50th birthday. He started investing as a child. Time did most of the work.",
  why: "It shows that the real power of compounding comes from time and from never stopping. It does not come from one brilliant year.",
  mech: "Compounding means your returns earn their own returns. A steady rate over many decades makes money grow faster and faster. So most of the gain comes in the last years.",
  models: ["compounding", "margin-of-safety"],
  q: "What does Buffett's wealth teach us about compounding?",
  a: "Most of the wealth comes late, because returns earn their own returns. So starting early and staying invested matters more than any one great year.",
  chain: [["Most of the wealth comes late (after 50)", ["after 50", "late", "99", "most of", "later"]], ["Returns earn their own returns", ["returns earn", "interest on interest", "exponential", "compound"]], ["Time matters most", ["time", "decades", "long", "patien", "early"]], ["Stay invested and never stop", ["stay", "survive", "keep investing", "not selling", "consisten"]]],
  mcq: { q: "What is the main lesson from when Buffett made most of his wealth?", o: ["Compounding rewards people who start early and stay invested for decades", "He always bought and sold at the perfect time", "He got most of his wealth from his family", "He took very risky bets at the end"] },
  bring: "When people talk about investing or SIPs: “Buffett made about 99% of his wealth after he turned 50. It is more about time than about being a genius.”",
  follow: "What could you start now that looks boring for years, and then suddenly does not?",
  deeper: "Suppose Buffett had started at 30 and retired at 60, with the same yearly returns. His wealth would be only a tiny part of what it is today.",
  story: null, jargon: ["compounding"], mis: [] },

{ id: "margin-of-safety", type: "mental model", domain: "business", title: "Margin of safety", value: 4, cue: "risk, planning, or investing",
  fact: "Benjamin Graham's margin of safety means this: buy only when the price is far below what you think the thing is worth. Then you are still safe even if your own judgement is wrong.",
  why: "It is a humble way to plan. You accept in advance that you may be wrong.",
  mech: "Your estimates are never certain. So you keep a gap between the price and the value you estimate. Engineers do the same when they keep a gap between the load and what a structure can carry. This gap protects you from mistakes and bad luck.",
  models: ["margin-of-safety", "inversion"],
  q: "Why does Graham insist on a margin of safety?",
  a: "Your estimates are never certain. If you buy far below the value you estimate, you have a safety gap. Then mistakes or bad luck do not destroy you.",
  chain: [["Estimates are never certain", ["uncertain", "wrong", "error", "mistake", "humil"]], ["Buy far below the value", ["below", "discount", "cheap", "gap between", "buffer"]], ["The gap takes care of mistakes", ["absorb", "buffer", "cushion", "protect", "survive"]], ["It protects you from losing everything", ["ruin", "lose", "downside", "safe", "avoid loss"]]],
  mcq: { q: "What does a margin of safety protect you from?", o: ["Your own mistakes and bad luck", "Taxes", "Competitors copying you", "Interest rates"] },
  bring: "When people talk about risk or planning: “Engineers build bridges to carry much more than the expected load. Graham used the same idea for investing.”",
  follow: "Where in your life do you have no safety gap at all?",
  deeper: "Bridges are usually designed to carry more than they need to, often around 2 times the expected load. Warren Buffett has called “margin of safety” the three most important words in investing.",
  story: null, jargon: ["intrinsic value"], mis: [] },

{ id: "wald-bombers", type: "historical story", domain: "science", title: "Wald and the missing bullet holes", value: 5, cue: "data, proof or hidden errors in thinking",
  fact: "During WWII, a statistician named Abraham Wald studied the bombers that came back. He told the military to add armour (protective metal) to the parts with few bullet holes. Planes hit in those parts never came back.",
  why: "The data you see has already been filtered. The data that is missing may be the most important.",
  mech: "The experts studied only the planes that survived. Holes in the wings or the body showed damage a plane could survive. Planes hit in the engines or the cockpit crashed. So those planes were missing from the data.",
  models: ["survivorship-bias", "inversion", "map-vs-territory"],
  q: "What did Wald understand about the bombers?",
  a: "The planes that came back showed damage a plane could survive. The parts without holes were where a hit destroyed the plane. So those parts needed the armour.",
  chain: [["They looked only at planes that came back", ["returning", "returned", "survivor", "came back", "made it back"]], ["Holes show damage a plane can survive", ["survivable", "survive", "could survive", "not fatal"]], ["No holes means a hit there destroys the plane", ["missing", "no holes", "fewest", "never came back", "didn't return", "fatal", "shot down"]], ["Add armour where there are no holes", ["armo", "engine", "cockpit", "reinforce"]]],
  mcq: { q: "Where did Wald say the armour should go?", o: ["Where returning planes had few holes, because hits there destroyed the plane", "Where returning planes had the most holes", "Equally all over the plane", "Only on the tail"] },
  bring: "When people talk about data or success stories: “Wald's great idea was to ask about the planes that did not come back.”",
  follow: "Which success story are we hearing only from the people who survived?",
  deeper: "People often add details when they tell this story. But Wald's reports are real. He worked out how easily each part of a plane could be destroyed, using the damage on planes that survived. His method estimated how many hits the lost planes had taken.",
  story: "wald", jargon: ["sample", "survivorship bias"], mis: [] },

{ id: "wason-246", type: "scientific principle", domain: "psychology", title: "The Wason 2-4-6 task", value: 4, cue: "arguments, beliefs, or how people test ideas",
  fact: "In 1960, Peter Wason showed people the numbers 2-4-6 and asked them to find the rule. People had a guess (a hypothesis) and tested examples that fitted it, like 8-10-12. They almost never tried examples that could prove their guess wrong. The real rule was simply any numbers going up.",
  why: "It shows that we naturally look for proof that we are right. This feels good but teaches us very little.",
  mech: "If you test only cases that fit your belief, you can never find out that it is false. You get real information only when you try to break your idea. For example, try 1-2-3 or 3-2-1.",
  models: ["confirmation-bias", "inversion", "bayesian-thinking"],
  q: "What did Wason's 2-4-6 experiment show?",
  a: "People test their ideas with examples that agree with them. They do not try to prove themselves wrong. So they stay sure but wrong. The rule was just any numbers going up.",
  chain: [["People test with examples that agree", ["confirm", "fit", "agree", "support", "same pattern"]], ["They almost never try to prove themselves wrong", ["disprove", "falsif", "wrong", "counter", "contradict"]], ["They stay sure but wrong", ["confident", "wrong", "certain", "mistaken"]], ["The rule was any numbers going up", ["ascending", "increasing", "any three", "any sequence", "any numbers"]]],
  mcq: { q: "What did most people do in the 2-4-6 task?", o: ["They tested examples that fitted their guess and did not try to prove it wrong", "They learned the full list of rules by heart", "They refused to guess", "They used random numbers"] },
  bring: "In a debate: “There is a famous experiment. People almost never test their own idea by trying to prove it wrong.”",
  follow: "Which belief of yours have you never really tried to prove wrong?",
  deeper: "The philosopher Karl Popper had a closely related idea, called falsification. A theory is scientific only if some test could show it to be false.",
  story: null, jargon: ["hypothesis", "falsify"], mis: [] },

{ id: "anchoring", type: "psychological concept", domain: "psychology", title: "Anchoring", value: 4, cue: "bargaining, prices or estimates",
  fact: "In a 1974 study, Tversky and Kahneman had people spin a wheel that was fixed to stop at 10 or 65. Then people guessed what share of UN members were African countries. The middle guesses were about 25% for the low number and 45% for the high number. This pull is called anchoring.",
  why: "Even numbers that are clearly random pull our guesses towards them.",
  mech: "We start from the number in front of us and then adjust. But we usually do not adjust enough. So the first number sets the range of our answer.",
  models: ["confirmation-bias", "map-vs-territory"],
  q: "What does the fixed-wheel experiment show about anchoring?",
  a: "A random first number pulled people's guesses towards it. We start from the anchor and do not adjust enough.",
  chain: [["A random number is shown first", ["random", "wheel", "first number", "initial"]], ["Guesses move towards it", ["toward", "influence", "pull", "bias", "closer"]], ["We do not adjust enough", ["adjust", "insufficient", "not enough", "start"]], ["Even numbers with no meaning work", ["irrelevant", "meaningless", "even", "arbitrary"]]],
  mcq: { q: "What happened to people's guesses after they saw a high random number?", o: ["The guesses were higher, pulled towards that number", "The guesses did not change", "The guesses were lower, to balance it", "The guesses became more correct"] },
  bring: "When people talk about bargaining: “The person who says the first number often wins. This is called anchoring. It works even when the number is random.”",
  follow: "Which number tends to anchor you when you buy something big?",
  deeper: "Even expert property agents are pulled by the asking price of a house. They still insist that they are not.",
  story: null, jargon: ["anchor", "heuristic"], mis: [] },

{ id: "loss-aversion", type: "psychological concept", domain: "psychology", title: "Loss aversion", value: 4, cue: "gambling, selling investments or keeping things as they are",
  fact: "Kahneman and Tversky found that a loss hurts about twice as much as a gain of the same size feels good. This is called loss aversion. So people avoid risk and hold on to things as they are.",
  why: "It explains why people keep losing investments too long, refuse good bets and resist change.",
  mech: "Our feelings react more strongly to losses than to gains. The pain of losing ₹100 is bigger than the joy of winning ₹100. So even a coin toss where you lose ₹100 or win ₹150 still feels like a bad deal.",
  models: ["opportunity-cost", "incentives"],
  q: "What is loss aversion?",
  a: "A loss feels about twice as bad as a gain of the same size feels good. This makes us avoid risk and keep things as they are.",
  chain: [["Losses feel heavier than gains", ["losses", "loss", "more painful", "hurt more", "weigh more"]], ["About twice as strong", ["twice", "2x", "double", "two times", "2.0", "2.5"]], ["We avoid risk and keep things as they are", ["avoid", "status quo", "risk", "stick", "cling"]], ["It bends our decisions", ["decision", "hold", "sell", "bet", "irrational"]]],
  mcq: { q: "About how much more does a loss hurt than a gain of the same size feels good?", o: ["About twice as much", "About the same", "About half as much", "About ten times as much"] },
  bring: "When someone will not sell a bad share: “That is loss aversion. Losing ₹100 hurts about twice as much as gaining ₹100 feels good.”",
  follow: "What are you holding on to mainly because letting go would feel like a loss?",
  deeper: "Many later studies in different settings have found the same effect. But the exact ratio changes with the situation and with how much money is involved.",
  story: null, jargon: ["status quo"], mis: [] },

{ id: "semmelweis", type: "historical story", domain: "science", title: "Semmelweis and handwashing", value: 5, cue: "experts refusing to change, medicine or proof",
  fact: "In 1847, Ignaz Semmelweis worked in a maternity ward in Vienna. He showed that washing hands with chlorinated lime (a chlorine solution) cut the deaths of mothers from around 10% to 1-2%. Other doctors rejected the idea.",
  why: "People can reject a truth because it makes them uncomfortable. This habit is now called the “Semmelweis reflex”.",
  mech: "One ward was run by doctors, who also cut open dead bodies to study them (autopsies). Far more mothers died there than in the ward run by midwives. Then a fellow doctor died after a cut from a surgical knife. Semmelweis linked the deaths to dirty hands. Doctors took his claim as an insult.",
  models: ["confirmation-bias", "bayesian-thinking", "feedback-loops"],
  q: "What did Semmelweis discover, and why was he rejected?",
  a: "Washing hands with chlorinated lime sharply cut the deaths of mothers. But doctors rejected it, because it meant they were killing their patients. Also, he could not explain why it worked, because germs were not yet understood.",
  chain: [["More mothers died in the doctors' ward", ["doctors", "students", "first clinic", "higher", "ward"]], ["A link to dead bodies and dirty hands", ["autops", "cadaver", "corpse", "contaminat", "hands", "kolletschka"]], ["Handwashing cut the deaths sharply", ["handwash", "washing", "chlorine", "lime", "dropped", "fell", "cut"]], ["The senior doctors rejected it", ["reject", "dismiss", "insult", "ignored", "resist", "no theory", "germ"]]],
  mcq: { q: "Why did doctors reject Semmelweis's handwashing results?", o: ["It meant they were causing the deaths, and germs were not yet understood", "His numbers were clearly false", "Handwashing made more patients die", "He refused to publish his results"] },
  bring: "When people talk about experts who refuse to change: “In 1847 Semmelweis proved that handwashing saved mothers' lives. Doctors rejected him, because it meant they were the problem.”",
  follow: "What do you think is today's handwashing, a truth that experts are ignoring?",
  deeper: "Years later, Louis Pasteur's germ theory showed that diseases come from tiny living things. It proved Semmelweis right. Semmelweis died in 1865 in a mental hospital, a very sad end.",
  story: "semmelweis", jargon: ["mortality", "germ theory"], mis: [] },

{ id: "red-queen", type: "scientific principle", domain: "science", title: "The Red Queen effect", value: 3, cue: "competition, evolution or arms races",
  fact: "Leigh Van Valen's Red Queen idea (1973) says that living species must keep changing all the time, only to keep up with their competitors and hunters. It is like Alice in the story, who runs fast but stays in the same place.",
  why: "It explains why progress often feels like standing still when everyone is competing. This is true in nature and in business.",
  mech: "When one species changes, life becomes harder for the others. So they change too. Everyone changes, but nobody gets ahead of the others.",
  models: ["feedback-loops", "game-theory"],
  q: "What does the Red Queen idea say?",
  a: "Species must keep changing only to hold their position, because their competitors and hunters change too. It is an arms race that never ends.",
  chain: [["Species must keep changing", ["keep evolving", "constantly", "continuous", "adapt"]], ["Only to stay in the same place", ["same place", "stay", "keep up", "maintain", "standing still"]], ["Competitors and hunters change too", ["compet", "predator", "prey", "parasite", "other species"]], ["An arms race", ["arms race", "coevol", "co-evol", "escalat"]]],
  mcq: { q: "What is the Red Queen idea?", o: ["Everyone must keep changing only to hold the same position against others", "The strongest species always wins", "Evolution slows down over time", "Species change only after others die out"] },
  bring: "When people talk about competition: “This is the Red Queen effect. You have to run as fast as you can only to stay where you are.”",
  follow: "In which parts of your work are you running only to stand still?",
  deeper: "The name comes from Lewis Carroll's book Through the Looking-Glass. A strong example in nature is a parasite and the animal it lives on. Each keeps changing in answer to the other.",
  story: null, jargon: ["coevolution"], mis: [] },

{ id: "dunbar", type: "scientific principle", domain: "anthropology", title: "Dunbar's number", value: 3, cue: "friendships, teams or social media",
  fact: "Robin Dunbar, who studies human societies, said that a person can keep about 150 steady relationships. He linked this to the size of the human brain. Estimates range from about 100 to 250.",
  why: "It helps explain the size of villages and army units. It also explains why large groups need structure.",
  mech: "Keeping a relationship alive takes time and mental effort. Above about 150 people, a group needs leaders, rules or ways of tracking who can be trusted. Without these, it does not hold together.",
  models: ["network-effects", "bottlenecks"],
  q: "What is Dunbar's number and why does it matter?",
  a: "It is about 150. This is roughly the most steady relationships a person can keep. So bigger groups need rules, leaders or ways of tracking trust in order to work.",
  chain: [["About 150 relationships", ["150", "hundred and fifty", "100 to 250"]], ["Limited by the brain and by time", ["brain", "cognitive", "neocortex", "capacity", "time", "limit"]], ["Bigger groups need structure", ["structure", "hierarch", "rules", "organis", "organiz", "reputation"]], ["It explains the sizes of groups", ["village", "army", "company", "team", "unit"]]],
  mcq: { q: "What is Dunbar's number?", o: ["About 150 steady relationships", "About 15 close friends", "About 1,500 people you know a little", "About 50 family members"] },
  bring: "When people talk about social media or company size: “Dunbar's number is about 150. That is roughly the size at which a village starts to need rules.”",
  follow: "How many people do you think you could truly call a real friend?",
  deeper: "Dunbar also describes layers: about 5 very close people, 15 good friends, 50 friends and 150 people who matter to you.",
  story: null, jargon: ["neocortex"], mis: [{ re: "exactly 150", msg: "It is a rough estimate, not an exact number. It may be anywhere from about 100 to 250." }] },

{ id: "stoic-control", type: "concept", domain: "philosophy", title: "The dichotomy of control", value: 4, cue: "stress, worry or things you cannot control",
  fact: "The Stoic teacher Epictetus divided things into two groups. This split is called the dichotomy of control. Some things are up to us: our judgements, choices and effort. Some are not: results, other people and what they think of us. Peace comes from giving attention to the first group.",
  why: "It turns worry into a sorting job. Act on what you control and accept the rest.",
  mech: "Worrying about things you cannot control wastes energy and clouds your thinking. When you move your effort to choices you can control, you act better and your mind becomes calm.",
  models: ["first-principles", "inversion"],
  q: "What is the Stoic dichotomy of control?",
  a: "Separate what is in your control (your judgements and actions) from what is not (results and other people). Put your effort only into the first.",
  chain: [["Some things are in our control", ["in our control", "in your control", "control", "up to us"]], ["Others are not (results, other people)", ["outcome", "other people", "not in", "outside", "reputation"]], ["Give attention to judgements and actions", ["focus", "judg", "choice", "effort", "action"]], ["This brings calm", ["calm", "peace", "tranquil", "anxiety", "serene", "less stress"]]],
  mcq: { q: "According to Epictetus, where should we put our attention?", o: ["On our own judgements and actions", "On results and what people think of us", "On wealth and status", "On the opinions of others"] },
  bring: "When someone is worried about an uncertain thing: “The Stoics had a method. Sort what is up to you from what is not.”",
  follow: "What are you worrying about now that you could not change even if you tried?",
  deeper: "Epictetus's short book, the Enchiridion, begins with this idea: “Some things are in our control and others not.” Marcus Aurelius and Seneca developed it further.",
  story: null, jargon: ["Stoic", "dichotomy"], mis: [] },

{ id: "map-territory", type: "mental model", domain: "philosophy", title: "The map is not the territory", value: 4, cue: "models, forecasts or arguments about facts",
  fact: "In 1931, Alfred Korzybski said “the map is not the territory”. Territory means the real land. The line warns us that our pictures of reality are simpler than reality. If we mix up the two, we make mistakes.",
  why: "It teaches us to be humble about forecasts, numbers and maps of every kind.",
  mech: "Every map leaves out some details. Trouble starts when those missing details matter. It also starts when we treat the model as the truth and not as a tool.",
  models: ["map-vs-territory", "goodharts-law"],
  q: "What does “the map is not the territory” mean?",
  a: "Models and descriptions are simpler than reality. If we take them for reality, we make mistakes when the missing details matter.",
  chain: [["Maps and models make things simpler", ["simplif", "leave out", "omit", "abstract", "incomplete"]], ["Reality has more in it", ["reality", "territory", "actual", "real thing"]], ["Mixing up the two causes mistakes", ["confus", "mistake", "error", "wrong", "mislead"]], ["Models are tools, not the truth", ["tool", "useful", "humil", "not truth", "approximat"]]],
  mcq: { q: "What mistake does this line warn us about?", o: ["Treating a simple model as if it were reality itself", "Never using maps", "Believing that reality can never be known", "Trusting your senses"] },
  bring: "When people talk about forecasts or dashboards: “The map is not the territory. The model is never the whole thing.”",
  follow: "Which model or number do you depend on that may be missing something big?",
  deeper: "Korzybski started a field called general semantics. He said that language itself is a map. The writer Borges wrote a famous story about a map as big as the land it showed. It shows how silly a perfect map would be.",
  story: null, jargon: [], mis: [] },

{ id: "veil-ignorance", type: "concept", domain: "philosophy", title: "Rawls's veil of ignorance", value: 3, cue: "fairness, government policy or making rules",
  fact: "In 1971, John Rawls suggested a test. Design the rules of society without knowing what your own place in it will be. This is called the veil of ignorance. It pushes you towards fair rules, because you could end up anywhere.",
  why: "It is a useful thought experiment for testing whether a rule is fair.",
  mech: "When your own position is hidden, you cannot choose rules that help only you. Sensible people then choose rules that protect the worst-off (the people at the bottom), because they might be those people.",
  models: ["incentives", "inversion"],
  q: "What is Rawls's veil of ignorance?",
  a: "It is a thought experiment. You design the rules without knowing your own position in society. This removes your self-interest. So you choose fair rules, especially for the worst-off.",
  chain: [["Design rules without knowing your position", ["without knowing", "don't know", "not know", "behind", "hidden", "ignoran"]], ["This removes self-interest", ["bias", "self-interest", "selfish", "impartial", "neutral"]], ["Protect the worst-off", ["worst-off", "worst off", "poor", "vulnerable", "lowest"]], ["This leads to fairness", ["fair", "justice", "equal"]]],
  mcq: { q: "What does the veil of ignorance take away?", o: ["Knowing your own place in society", "Knowing the law", "Knowing history", "Freedom to choose"] },
  bring: "When people talk about fairness: “Rawls asks you to design the rules before you know whether you will be rich or poor.”",
  follow: "Would you still choose the same rules for your workplace if you did not know your role there?",
  deeper: "Critics, including Robert Nozick, say it ignores what people have fairly earned. Rawls's ‘difference principle’ allows inequality only if it helps the worst-off.",
  story: null, jargon: ["impartial"], mis: [] },

{ id: "flying-buttress", type: "concept", domain: "design", title: "The flying buttress", value: 3, cue: "cathedrals, limits or engineering",
  fact: "Builders of Gothic cathedrals used flying buttresses. These are arched supports outside the building. They carry the sideways push (thrust) of the curved stone roofs (vaults). This allowed tall, thin walls full of coloured glass.",
  why: "A limit became the source of a whole style of beauty. The limit was that heavy stone roofs push the walls outward.",
  mech: "Earlier, thick walls had to resist the outward push. Now arches carry the force outside the building to heavy stone pillars. The wall is free to hold windows.",
  models: ["first-principles", "bottlenecks"],
  q: "What problem did the flying buttress solve?",
  a: "It carried the outward push of the stone roofs to pillars outside. So the walls could be thin, tall and full of windows.",
  chain: [["Curved stone roofs push the walls outward", ["thrust", "push", "outward", "sideways", "vault"]], ["Arches carry the force outside to pillars", ["arch", "pier", "external", "outside", "carry", "transfer"]], ["Walls can be thin and tall", ["thin", "tall", "height", "slender"]], ["Room for coloured glass windows", ["window", "glass", "light"]]],
  mcq: { q: "What did flying buttresses allow Gothic builders to do?", o: ["Build tall, thin walls with large windows", "Build rooms under the ground", "Make concrete domes", "Avoid using stone"] },
  bring: "In a cathedral: “Those arches outside are not decoration. They are the reason the walls can be made of glass.”",
  follow: "Which limit in your work could you turn into your special strength?",
  deeper: "Notre-Dame in Paris is a famous early example. Engineers still use the same idea today: move the weight out of the wall.",
  story: null, jargon: ["thrust", "vault"], mis: [] },

/* ---- Vocabulary ---- */
{ id: "v-perspicacious", type: "vocabulary item", domain: "language", title: "perspicacious", value: 2, cue: "someone who sees the truth behind things",
  fact: "perspicacious (adj.): very good at noticing and understanding things that other people miss.",
  why: "It is a more exact word than ‘smart’. It means sharp in judgement.",
  mech: "From the Latin word perspicere, “to see through”.",
  models: [], q: "What does “perspicacious” mean?", a: "Very good at understanding what is really going on.",
  chain: [["Sharp understanding", ["insight", "sharp", "keen", "perceptive", "see through", "shrewd", "notice"]]],
  mcq: { q: "A perspicacious investor is one who…", o: ["Notices what others miss", "Takes big risks", "Follows the crowd", "Gets scared easily"] },
  bring: "“She was perspicacious about the numbers, and found the mistake in minutes.”", follow: "Who is the most perspicacious person you know?", deeper: "It has the same root as ‘perspective’ and ‘spy’.",
  story: null, jargon: [], mis: [], word: "perspicacious" },
{ id: "v-sanguine", type: "vocabulary item", domain: "language", title: "sanguine", value: 2, cue: "staying hopeful in hard times",
  fact: "sanguine (adj.): hopeful and positive, especially in a difficult situation.",
  why: "It describes calm, sensible hope. It is not foolish cheerfulness.",
  mech: "From the Latin word sanguis (blood). In old medicine, a ‘sanguine’ person had a red face and a cheerful nature.",
  models: [], q: "What does “sanguine” mean?", a: "Hopeful and positive, even when things are difficult.",
  chain: [["Hopeful", ["optimis", "hopeful", "positive", "confident", "cheerful"]]],
  mcq: { q: "A sanguine reaction to bad news is…", o: ["Calm and hopeful", "Very angry", "Not caring", "Afraid"] },
  bring: "“He is sanguine about the merger, even after the job cuts.”", follow: "Are you sanguine or careful about the coming year?", deeper: "Do not mix it up with ‘sanguinary’, which means fond of bloodshed.",
  story: null, jargon: [], mis: [], word: "sanguine" },
{ id: "v-obsequious", type: "vocabulary item", domain: "language", title: "obsequious", value: 2, cue: "false praise or trying too hard to please",
  fact: "obsequious (adj.): trying too hard to please or obey someone, in a way that looks false.",
  why: "It names one exact fault: praising and serving powerful people too much.",
  mech: "From the Latin word obsequi, “to go along with”.",
  models: [], q: "What does “obsequious” mean?", a: "Trying too hard to please someone.",
  chain: [["Trying too hard to please", ["please", "fawn", "flatter", "servile", "eager", "obey"]]],
  mcq: { q: "An obsequious waiter…", o: ["Tries far too hard to please customers", "Ignores customers", "Argues with customers", "Works quickly"] },
  bring: "“The men at court were obsequious around the new king.”", follow: "Where does being polite end and being obsequious begin?", deeper: "Compare ‘sycophant’, a person who behaves like this all the time.",
  story: null, jargon: [], mis: [], word: "obsequious" },
{ id: "v-equanimity", type: "vocabulary item", domain: "language", title: "equanimity", value: 3, cue: "staying calm under pressure",
  fact: "equanimity (n.): a calm and steady mind, especially in difficult situations.",
  why: "It is what the Stoics aimed for. It is also the quality Arkhipov showed.",
  mech: "From the Latin words aequus (even) + animus (mind): an ‘even mind’.",
  models: [], q: "What does “equanimity” mean?", a: "A calm and steady mind under pressure.",
  chain: [["Calm and steady", ["calm", "composure", "composed", "even", "steady", "pressure"]]],
  mcq: { q: "Facing a crisis with equanimity means…", o: ["Staying calm and steady", "Acting without thinking", "Avoiding the problem", "Blaming others"] },
  bring: "“She took the bad news with real equanimity.”", follow: "What helps you keep your equanimity when things go wrong?", deeper: "It is central to both Stoic and Buddhist practice.",
  story: null, jargon: [], mis: [], word: "equanimity" },
{ id: "v-laconic", type: "vocabulary item", domain: "language", title: "laconic", value: 3, cue: "people who speak very little",
  fact: "laconic (adj.): using very few words. It comes from Laconia, the region of Sparta.",
  why: "The best story is this. Philip II of Macedon warned Sparta, “If I invade Laconia, I will raze Sparta.” To raze means to destroy completely. The Spartans replied with one word: “If.”",
  mech: "Spartans valued short speech. The Greek name for their region became an English adjective.",
  models: [], q: "What does “laconic” mean, and where does it come from?", a: "Using very few words. It comes from Laconia, the region of the Spartans.",
  chain: [["Few words", ["few words", "brief", "terse", "concise", "short", "curt"]], ["Sparta / Laconia", ["sparta", "laconia"]]],
  mcq: { q: "“Laconic” comes from the name of…", o: ["Laconia, the region of Sparta", "Lacon, a Roman poet", "The Latin word for milk", "A Greek island"] },
  bring: "“Talking of laconic: Sparta's reply to Philip of Macedon was just ‘If’.”", follow: "Who is the most laconic person you know?", deeper: "Compare ‘spartan’, which means very simple and without comfort.",
  story: null, jargon: [], mis: [], word: "laconic" },
{ id: "v-ephemeral", type: "vocabulary item", domain: "language", title: "ephemeral", value: 2, cue: "things that do not last",
  fact: "ephemeral (adj.): lasting for a very short time.",
  why: "It is the right word for fashions, trends and insects that live one day. The Greek root means ‘lasting a day’.",
  mech: "From the Greek word ephemeros, “lasting only a day”.",
  models: [], q: "What does “ephemeral” mean?", a: "Lasting a very short time.",
  chain: [["Lasting a short time", ["short", "brief", "fleeting", "temporary", "transient", "day"]]],
  mcq: { q: "An ephemeral trend is one that…", o: ["Disappears quickly", "Lasts for centuries", "Is hard to explain", "Is very expensive"] },
  bring: "“Fame on social media is ephemeral. Compare that with the Pantheon.”", follow: "What is ephemeral in your life that you wish would last?", deeper: "The mayfly, an insect that lives about one day as an adult, belongs to a group called Ephemeroptera. The name has the same root.",
  story: null, jargon: [], mis: [], word: "ephemeral" }
];

/* Bridges between assets: [a, b, note] */
MV.LINKS = [
  ["roman-roads", "container-shipping", "Both made it far cheaper to move goods. Whoever owns the network decides who can trade."],
  ["roman-roads", "comparative-advantage", "Cheap transport is what makes it worth focusing on what you do best. Roads made comparative advantage work in real life."],
  ["comparative-advantage", "container-shipping", "Containers made it cheap to make things anywhere and ship them everywhere. This is comparative advantage across the whole world."],
  ["container-shipping", "amazon-flywheel", "Amazon's main defence is its delivery network. The cost per parcel falls as the number of parcels rises. It is the container idea used for delivery to your door."],
  ["east-india-company", "hormuz", "Both are about controlling narrow points on trade routes. The Company did it with ships and forts. Today's powers do it with straits."],
  ["east-india-company", "hanoi-rats", "Both are stories about rewards. The Company's officers were paid to take wealth out, so they did. The results were ones nobody planned."],
  ["hormuz", "russia-ports", "Geography creates narrow points, and narrow points shape strategy."],
  ["russia-ports", "cold-war-mad", "The same geography shaped Soviet strategy. A huge land power wanted a way to the sea and friendly countries around it as a shield."],
  ["russia-ports", "nato-article5", "To Moscow, NATO's growth to the east looked like pressure on its way to the sea and on its shield of nearby countries. These were the very things it feared losing."],
  ["russia-ports", "map-territory", "A map of Russia shows a huge coast. In reality, the coast is ice and narrow passages."],
  ["thermopylae", "hormuz", "A narrow pass or a narrow strait: whoever blocks it has far more power than their size suggests."],
  ["thermopylae", "v-laconic", "The Spartans who fought at Thermopylae were famous for very short replies. They gave English the word “laconic”."],
  ["sun-tzu", "cold-war-mad", "Win without fighting: MAD is the strongest form of this idea in the nuclear age. The fear is so complete that the war never starts."],
  ["sun-tzu", "ooda-loop", "Boyd learned from Sun Tzu: win by moving faster than the opponent can react."],
  ["ooda-loop", "amazon-flywheel", "Both are fast loops of trying and learning. Amazon's speed in testing new ideas is an OODA loop in business."],
  ["ooda-loop", "red-queen", "OODA is the loop of one player. The Red Queen is the arms race that many such loops create."],
  ["sarajevo-1914", "wwii-origins", "The peace made at Versailles after WWI created the anger that led to WWII. The end of one story is the start of the next."],
  ["sarajevo-1914", "weimar-hyperinflation", "War debts and reparations from WWI led Germany to print too much money in 1923."],
  ["sarajevo-1914", "red-queen", "The arms races and alliances before 1914 worked like the Red Queen. Every step one side took to feel safe made the other side feel less safe."],
  ["sarajevo-1914", "cuban-submarine", "In both, a tiny chance event in a tightly linked system decided between disaster and survival. One was a wrong turn. The other was one officer saying no."],
  ["wwii-origins", "weimar-hyperinflation", "Inflation and then depression destroyed trust in moderate politics. This is the economic half of the Versailles story."],
  ["wwii-origins", "wald-bombers", "Wald's work was part of the WWII effort to use statistics to save lives."],
  ["wwii-origins", "cold-war-mad", "The Cold War grew out of the end of WWII. The allies of the war became rival superpowers."],
  ["wwii-origins", "nato-article5", "NATO was created in 1949 so that attacks like those of WWII would not happen again in Europe."],
  ["weimar-hyperinflation", "buffett-compounding", "Compounding works both ways. Inflation quietly compounds against people who save."],
  ["cold-war-mad", "cuban-submarine", "The crisis was MAD under pressure. The system nearly failed because messages did not get through."],
  ["cold-war-mad", "nato-article5", "Article 5 warns an attacker in advance that all members will answer. It is the logic of MAD used for an alliance."],
  ["cuban-submarine", "stoic-control", "Arkhipov stayed calm in the heat and pressure. That is the dichotomy of control in real life."],
  ["cuban-submarine", "v-equanimity", "Arkhipov is the perfect picture of equanimity under extreme pressure."],
  ["hanoi-rats", "map-territory", "The tails were the map. Fewer rats was the territory. Getting more tails did not change the real number of rats."],
  ["wason-246", "semmelweis", "The senior doctors kept testing only what they already believed. This is confirmation bias in a whole profession."],
  ["wason-246", "wald-bombers", "Both are about seeing only the proof that is easy to see: cases that agree with you, or planes that survived."],
  ["anchoring", "margin-of-safety", "An old price can anchor you and change what you think a thing is worth. Margin of safety is the habit of working out the value on your own."],
  ["loss-aversion", "buffett-compounding", "Loss aversion makes people run from ups and downs and sell their winners. This breaks the compounding that builds wealth."],
  ["loss-aversion", "margin-of-safety", "Margin of safety accepts that losses and gains are not equal. Avoiding a big loss matters more than chasing a big gain."],
  ["loss-aversion", "veil-ignorance", "Behind the veil, you would fear ending up at the bottom. Loss aversion explains why we then design protection for people who fall."],
  ["buffett-compounding", "margin-of-safety", "Compounding rewards those who never lose everything. Margin of safety is how you make sure you can keep going."],
  ["dunbar", "amazon-flywheel", "Online platforms go beyond Dunbar's limit. They replace personal trust with ratings and reviews."],
  ["map-territory", "wald-bombers", "The map (the bullet holes you can see) is not the territory (all planes were hit)."],
  ["pantheon-dome", "roman-roads", "Both come from the same Roman way of building: standard materials and methods used across a whole empire."],
  ["pantheon-dome", "flying-buttress", "Both solve the same problem: covering a wide space with heavy material while controlling the sideways push."],
  ["pantheon-dome", "v-ephemeral", "Short-lived things against things that last: the Pantheon has lasted longer than empires."],
  ["v-perspicacious", "wald-bombers", "Wald was perspicacious: he saw what the data was hiding."],
  ["v-sanguine", "buffett-compounding", "A sanguine long-term investor trusts compounding even when the market falls."],
  ["semmelweis", "red-queen", "Germs and the bodies they attack are in a Red Queen race. That is why we must keep learning hygiene again and again."]
];
