/* Local knowledge: Mumbai, Maharashtra and India. Same shape as data-assets.js, plus `region`.
   These are placed first in the library, and the feed and recommendations favour them. */
(function () {
  MV.REGIONS = { mumbai: "Mumbai", maharashtra: "Maharashtra", india: "India" };
  const L = (region, list) => list.map(a => Object.assign({ region, story: null, jargon: [], mis: [] }, a));

  const MUMBAI = L("mumbai", [
  { id: "mumbai-seven-islands", type: "concept", domain: "geography", title: "Mumbai was seven islands", value: 4, cue: "flooding, old Bombay, or how the city grew",
    fact: "Mumbai was once seven separate islands. Over about 150 years, people filled the sea between them with earth and rock to make one piece of land.",
    why: "Much of the city you walk on is man-made. This is one reason many low areas flood in the monsoon.",
    mech: "The islands were Colaba, Little Colaba, Bombay, Mazagaon, Parel, Worli and Mahim. At high tide the sea came in between them. Sea walls like the Hornby Vellard, finished around 1784, kept the sea out. Then the low ground was filled in. Much of this land is still low, so rain water drains away slowly.",
    models: ["second-order-thinking", "first-principles"],
    q: "How did seven islands become one city?",
    a: "Sea walls kept the tide out and the gaps between the islands were filled with earth and rock. The new land is low, so it floods easily.",
    chain: [["It was seven islands", ["seven", "7", "islands"]], ["Sea walls kept the sea out", ["wall", "vellard", "hornby", "block", "causeway"]], ["The gaps were filled with land", ["fill", "reclaim", "reclam", "land"]], ["Low land still floods", ["flood", "low", "monsoon", "drain"]]],
    mcq: { q: "How was most of Mumbai's land made?", o: ["By joining seven islands with filled-in land", "By cutting down a large hill", "It was always one big island", "By a river changing its path"] },
    bring: "When someone complains about flooding: “Much of Mumbai was sea 250 years ago. We are standing on filled-in land.”",
    follow: "Which part of the city do you think used to be under water?",
    deeper: "The old map lives on in names. Worli, Mahim, Parel and Colaba were separate islands. Breach Candy is said to be named after the gap, or breach, in the shore that the Hornby Vellard closed." },

  { id: "bombay-dowry", type: "fact", domain: "history", title: "Bombay was a wedding gift", value: 4, cue: "old Bombay, the British, or surprising deals",
    fact: "In 1661 Portugal gave Bombay to England as part of a wedding gift, when Princess Catherine of Braganza married King Charles II. In 1668 the king rented it to the East India Company for only 10 pounds a year.",
    why: "A place that is now home to over 20 million people was once given away as a small part of a marriage deal. Nobody knew what it would become.",
    mech: "The king found the islands costly and hard to run. The Company wanted a safe harbour on the west coast. Bombay has a deep natural harbour, so in 1687 the Company moved its main western base there from Surat. Trade followed, and the town grew.",
    models: ["opportunity-cost", "compounding"],
    q: "How did the English get Bombay, and what did they do with it?",
    a: "Portugal gave it as part of a royal wedding gift in 1661. The king rented it to the East India Company for 10 pounds a year, and the Company made it its western base because of the harbour.",
    chain: [["A wedding gift from Portugal", ["wedding", "dowry", "gift", "marri", "portug", "catherine"]], ["Rented to the East India Company", ["rent", "lease", "10 pounds", "ten pounds", "company"]], ["It had a deep natural harbour", ["harbour", "harbor", "port"]], ["The Company moved its base from Surat", ["surat", "base", "moved", "headquarter"]]],
    mcq: { q: "How did England first get Bombay?", o: ["As part of a royal wedding gift from Portugal", "By winning a war against the Marathas", "By buying it from the Mughal emperor", "By finding it empty"] },
    bring: "When property prices come up: “The King of England once rented out all of Bombay for 10 pounds a year.”",
    follow: "What do you think is the most under-priced thing around us today?",
    deeper: "The Portuguese had held the islands since 1534. The Portuguese governor in India did not want to hand them over, because he could see how good the harbour was." },

  { id: "dabbawalas", type: "business concept", domain: "business", title: "The dabbawalas", value: 5, cue: "delivery apps, logistics, or how things run on time",
    fact: "About 5,000 dabbawalas carry around 200,000 lunch boxes across Mumbai every working day. They use no computers. Each box has a simple code of colours, numbers and letters painted on it.",
    why: "It is one of the most reliable delivery systems in the world. Many of the men who run it did not finish school. Business schools come to study it.",
    mech: "Each box passes through several hands. The code shows the home area, the station it must reach, and the building. A small team owns each step and everyone earns about the same. The local trains give a fixed timetable for the whole city. Simple rules and a shared clock keep mistakes very rare.",
    models: ["first-principles", "incentives", "bottlenecks"],
    q: "How do the dabbawalas deliver so many lunch boxes with so few mistakes?",
    a: "A simple painted code tells each team where a box must go. Small teams own each step, pay is equal, and the local trains give everyone the same timetable.",
    chain: [["A simple code on every box", ["code", "colour", "color", "symbol", "mark", "paint"]], ["Small teams own each step", ["team", "group", "hand", "relay", "pass"]], ["Local trains set the timetable", ["train", "local", "timetable", "railway"]], ["Equal pay and shared ownership", ["equal", "same pay", "share", "owner", "trust"]]],
    mcq: { q: "What do the dabbawalas use to sort lunch boxes?", o: ["A painted code of colours, numbers and letters", "A mobile app with GPS", "Printed address labels", "A list kept by a central office"] },
    bring: "When delivery apps come up: “The dabbawalas have delivered lunch on time since 1890, with a painted code and the local train.”",
    follow: "Why do you think a system with no technology makes so few mistakes?",
    deeper: "You will often hear that they make only one mistake in several million deliveries. That number came from a magazine article and was never formally measured. But studies agree that mistakes are very rare." },

  { id: "mumbai-locals", type: "fact", domain: "history", title: "India's first train and the Mumbai locals", value: 4, cue: "trains, commuting or traffic",
    fact: "India's first passenger train ran on 16 April 1853 from Bori Bunder in Bombay to Thane, a trip of 34 km. Today Mumbai's local trains carry over 7 million people a day.",
    why: "The city grew along its railway lines. Without the locals, Mumbai could not work.",
    mech: "Mumbai is long and narrow, with many offices in the south and many homes in the north. Trains move huge numbers of people along this narrow strip faster and cheaper than roads can. So homes, shops and jobs grew up around the stations.",
    models: ["network-effects", "bottlenecks"],
    q: "Why are the local trains so important to Mumbai?",
    a: "The city is long and narrow. Trains move millions along it cheaply and fast, so the city grew around the stations. The first train ran from Bombay to Thane in 1853.",
    chain: [["First train ran Bombay to Thane in 1853", ["1853", "thane", "bori bunder", "first train"]], ["The city is long and narrow", ["narrow", "long", "north", "south", "strip"]], ["Trains move millions cheaply", ["million", "cheap", "fast", "crowd", "carry"]], ["The city grew around stations", ["station", "grew", "suburb", "around"]]],
    mcq: { q: "Where did India's first passenger train run in 1853?", o: ["From Bombay to Thane", "From Delhi to Agra", "From Calcutta to Howrah", "From Madras to Bangalore"] },
    bring: "On a crowded train: “This line is where Indian railways began. The first train went from here to Thane in 1853.”",
    follow: "What would Mumbai look like today if the trains had never been built?",
    deeper: "That first train had 14 coaches and about 400 guests, and was pulled by three steam engines. Bori Bunder later became Victoria Terminus, now Chhatrapati Shivaji Maharaj Terminus." },

  { id: "cotton-boom", type: "historical story", domain: "economics", title: "The Bombay cotton boom", value: 5, cue: "stock market bubbles, quick money, or South Mumbai's old buildings", story: "cotton",
    fact: "During the American Civil War, from 1861 to 1865, Britain could not get cotton from America. It bought from Bombay instead. Prices shot up and the city became very rich. When the war ended in 1865, the boom crashed.",
    why: "A war on the other side of the world built much of South Mumbai, and then ruined many of its traders.",
    mech: "British cloth mills needed cotton. With American cotton blocked, Indian cotton was the next best choice, so its price rose several times over. The easy money went into new banks and into schemes to fill the sea for land. When the war ended, American cotton came back, prices fell, and many of these companies failed.",
    models: ["second-order-thinking", "feedback-loops", "incentives"],
    q: "Why did Bombay boom and then crash in the 1860s?",
    a: "The American Civil War cut off American cotton, so Britain paid high prices for Bombay cotton. The easy money fed risky banks and land schemes. When the war ended, prices fell and they collapsed.",
    chain: [["The American Civil War blocked US cotton", ["civil war", "america", "blocked", "cut off"]], ["Britain bought Bombay cotton at high prices", ["britain", "mills", "price", "demand", "rose"]], ["Easy money fed risky schemes", ["bank", "scheme", "share", "specul", "reclam", "risky"]], ["The war ended and it crashed", ["ended", "crash", "fell", "collapse", "1865"]]],
    mcq: { q: "What caused Bombay's cotton boom in the 1860s?", o: ["The American Civil War cut off American cotton", "A new machine doubled cotton harvests", "The Suez Canal opened", "Britain stopped taxing Indian cotton"] },
    bring: "When a hot stock or property craze comes up: “Bombay had this in the 1860s. Cotton made everyone rich until the American war ended.”",
    follow: "What boom today depends on something that could suddenly end?",
    deeper: "The trader Premchand Roychand made a fortune in the boom. He paid for the Rajabai Clock Tower at the University of Mumbai and named it after his mother." },

  { id: "bse-banyan", type: "fact", domain: "business", title: "The stock exchange under a banyan tree", value: 3, cue: "the share market or Dalal Street",
    fact: "The Bombay Stock Exchange is the oldest stock exchange in Asia. It was formed in 1875. It began in the 1850s with a few brokers who met under a banyan tree near the Town Hall.",
    why: "One of the world's big markets started with no building at all. It needed only buyers, sellers and trust.",
    mech: "A market becomes more useful as more people join it, because it is easier to find someone to trade with. As the group of brokers grew, they kept moving to bigger spots. In 1875 they formed an association with rules, and later settled on Dalal Street.",
    models: ["network-effects", "lindy-effect"],
    q: "How did the Bombay Stock Exchange begin?",
    a: "Brokers met under a banyan tree in the 1850s. As more joined, the market became more useful, and in 1875 they formed an official association.",
    chain: [["Brokers met under a banyan tree", ["banyan", "tree", "brokers"]], ["More members made it more useful", ["more", "grew", "join", "useful", "network"]], ["Formed in 1875", ["1875", "association", "formed"]], ["Oldest in Asia", ["oldest", "asia", "first"]]],
    mcq: { q: "Where did the first Bombay share brokers meet?", o: ["Under a banyan tree", "In a British bank", "On a ship in the harbour", "In the Governor's house"] },
    bring: "When the share market comes up: “Dalal Street started as a few men under a banyan tree.”",
    follow: "What does a market really need in order to work?",
    deeper: "‘Dalal’ means broker in Marathi and Hindi. The 1865 cotton crash showed brokers that they needed clear rules, which pushed them to organise." },

  { id: "dharavi", type: "concept", domain: "economics", title: "Dharavi's hidden economy", value: 4, cue: "slums, small businesses or recycling",
    fact: "Dharavi covers only about 2 square kilometres, but several hundred thousand people live there. Its thousands of small workshops are often estimated to make goods worth around 1 billion US dollars a year.",
    why: "People call it a slum. It is also a busy factory town. The label hides what really happens there.",
    mech: "Homes and workplaces share the same small rooms, so costs are very low. Workshops recycle plastic and make leather goods, clothes, pottery and food. Because they are so close together, they can share suppliers, workers and buyers.",
    models: ["map-vs-territory", "network-effects"],
    q: "Why is it wrong to see Dharavi only as a slum?",
    a: "It is also a huge centre of small industry. Thousands of low-cost workshops, close together, recycle and make goods worth about a billion dollars a year.",
    chain: [["Very small area, very many people", ["small", "2 square", "crowded", "dense", "people"]], ["Thousands of workshops", ["workshop", "business", "factory", "industr", "unit"]], ["Recycling, leather, pottery, clothes", ["recycl", "leather", "pottery", "cloth", "plastic"]], ["Worth about a billion dollars a year", ["billion", "economy", "worth"]]],
    mcq: { q: "What is Dharavi known for, apart from crowded housing?", o: ["Thousands of small workshops and recycling units", "India's largest shopping mall", "A large IT park", "Rice farming"] },
    bring: "When someone calls Dharavi just a slum: “It also has thousands of workshops. People estimate it makes about a billion dollars of goods a year.”",
    follow: "What other places do we judge by a label without knowing what happens inside?",
    deeper: "Numbers for Dharavi are rough guesses, because most of its businesses are not officially counted. Population figures range from about 600,000 to 1 million." },

  { id: "mumbai-2005-flood", type: "event", domain: "science", title: "26 July 2005: the Mumbai flood", value: 4, cue: "monsoon, flooding or city planning",
    fact: "On 26 July 2005, Mumbai got 944 mm of rain in 24 hours. That is about 40% of a normal year's rain in one day. The city came to a stop, and over a thousand people died in the city and the state.",
    why: "It showed how a city with no spare room for water can fail all at once.",
    mech: "Very heavy rain came at the same time as a high tide, so the drains could not empty into the sea. The Mithi river had been made narrow by buildings and rubbish. Mangroves and open ground, which once soaked up water, had been built over. With no buffer left, the water had nowhere to go.",
    models: ["margin-of-safety", "bottlenecks", "second-order-thinking"],
    q: "Why was the 2005 flood in Mumbai so bad?",
    a: "Record rain met a high tide, so drains could not empty. The Mithi river was narrowed and the mangroves and open land that soak up water were built over.",
    chain: [["Record rain: 944 mm in a day", ["944", "record", "heavy rain", "one day", "24 hours"]], ["High tide blocked the drains", ["tide", "drain", "sea"]], ["The Mithi river was narrowed", ["mithi", "river", "narrow", "blocked"]], ["Mangroves and open land were gone", ["mangrove", "open", "built over", "buffer", "soak"]]],
    mcq: { q: "Which of these made the 2005 flood worse?", o: ["A high tide that stopped drains from emptying into the sea", "An earthquake under the sea", "A dam that broke in Thane", "Snow melting in the hills"] },
    bring: "When the monsoon floods come up: “On 26 July 2005 the city got 944 mm in a day. The real problem was that the water had nowhere to go.”",
    follow: "Where do you think Mumbai has the least room for water today?",
    deeper: "Much of the old drain system was built in British times for far lighter rain, and its outlets sit below high-tide level." },

  { id: "mumbai-art-deco", type: "fact", domain: "design", title: "Mumbai's Art Deco buildings", value: 3, cue: "Marine Drive, old cinemas or architecture",
    fact: "Mumbai has one of the largest collections of Art Deco buildings in the world, often said to be second only to Miami. In 2018 the Victorian Gothic and Art Deco buildings around the Oval Maidan became a UNESCO World Heritage Site.",
    why: "On one side of the Oval stand British Gothic buildings. On the other side stand Indian-built Art Deco flats. Two ages of the city face each other.",
    mech: "In the 1920s and 1930s new land was filled in at Marine Drive and near Churchgate. Art Deco was the modern style of that time. Rich Indian families and cinema owners chose it. So a whole area was built in one style within about twenty years.",
    models: ["lindy-effect"],
    q: "Why does Mumbai have so many Art Deco buildings?",
    a: "New land was made at Marine Drive and Churchgate in the 1920s and 30s, when Art Deco was the modern style. Indian owners built a whole area in that style.",
    chain: [["New land at Marine Drive and Churchgate", ["marine drive", "churchgate", "new land", "reclaim", "filled"]], ["Art Deco was the modern style then", ["modern", "style", "1930", "fashion"]], ["Built by Indian families and cinema owners", ["indian", "cinema", "famil", "owner"]], ["UNESCO site in 2018", ["unesco", "2018", "heritage"]]],
    mcq: { q: "Mumbai's Art Deco collection is often said to be second only to which city?", o: ["Miami", "Paris", "London", "Shanghai"] },
    bring: "On Marine Drive: “These curved buildings are Art Deco. Mumbai has one of the biggest collections in the world.”",
    follow: "Which old building in the city do you like most?",
    deeper: "Eros and Regal cinemas are well-known Art Deco buildings. Look for rounded corners, ship-like balconies and sunburst designs." },

  { id: "raja-harishchandra", type: "fact", domain: "history", title: "India's first feature film", value: 3, cue: "Bollywood or cinema",
    fact: "India's first full-length feature film, Raja Harishchandra, was made by Dadasaheb Phalke and shown in Bombay in 1913. It was silent, and men played the women's parts.",
    why: "The industry that now makes more films than any other country began with one man's risky experiment.",
    mech: "Phalke watched a film about the life of Christ and decided to put Indian gods and stories on screen. He went to London to learn how. He is said to have raised money against his insurance and his wife's jewellery, and his family worked as the crew. Acting was seen as shameful for women then, so no woman would take a part.",
    models: ["first-principles", "compounding"],
    q: "How did Indian cinema begin?",
    a: "Dadasaheb Phalke made Raja Harishchandra, a silent film shown in Bombay in 1913. He learned the craft in London and risked his family's money. Men played the women's roles.",
    chain: [["Dadasaheb Phalke made it", ["phalke", "dadasaheb"]], ["Shown in Bombay in 1913", ["1913", "bombay", "first"]], ["A silent film", ["silent", "no sound"]], ["Men played women's roles", ["men played", "women's", "female roles", "no woman"]]],
    mcq: { q: "Who made India's first full-length feature film?", o: ["Dadasaheb Phalke", "Satyajit Ray", "Raj Kapoor", "V. Shantaram"] },
    bring: "When films come up: “In India's first film, in 1913, the queen was played by a man. No woman would agree to act.”",
    follow: "What job that people look down on today might be respected in fifty years?",
    deeper: "Phalke was born in Trimbak, near Nashik. India's highest film award, the Dadasaheb Phalke Award, is named after him." },

  { id: "mumbai-name", type: "fact", domain: "anthropology", title: "Where the name Mumbai comes from", value: 3, cue: "Bombay versus Mumbai, or the Koli community",
    fact: "The name Mumbai comes from Mumbadevi, a goddess of the Koli fishing community, and ‘aai’, the Marathi word for mother. The Kolis lived on the islands long before any ruler came. The official name changed from Bombay to Mumbai in 1995.",
    why: "The city's oldest community is still here, in koliwadas, or fishing villages, between the towers.",
    mech: "The Portuguese called the place Bombaim, and the English turned that into Bombay. Marathi and Gujarati speakers had long called it Mumbai. In 1995 the state made that the official name.",
    models: ["map-vs-territory", "lindy-effect"],
    q: "Where does the name Mumbai come from?",
    a: "From Mumbadevi, the goddess of the Koli fishing people, plus ‘aai’, meaning mother. The Kolis were the first people of the islands. The name became official in 1995.",
    chain: [["From the goddess Mumbadevi", ["mumbadevi", "mumba", "goddess"]], ["‘Aai’ means mother", ["aai", "mother"]], ["Kolis were the first people here", ["koli", "fisher", "fishing", "first people", "original"]], ["Official since 1995", ["1995", "official", "renamed"]]],
    mcq: { q: "Mumbai is named after the goddess of which community?", o: ["The Koli fishing community", "The Parsi community", "The Maratha rulers", "Portuguese sailors"] },
    bring: "When Bombay versus Mumbai comes up: “Mumbai is the older name. It comes from Mumbadevi, the Kolis' goddess.”",
    follow: "Have you ever been inside one of the koliwadas?",
    deeper: "The Mumbadevi temple stands in Bhuleshwar. Worli, Versova, Mahim and Colaba still have koliwadas." },

  { id: "gateway-of-india", type: "fact", domain: "history", title: "The Gateway of India", value: 3, cue: "Colaba, the Taj hotel or the end of British rule",
    fact: "The Gateway of India was built to mark the visit of King George V in 1911, but it was finished only in 1924. In February 1948 the last British troops left India by marching out through it.",
    why: "A gate built to welcome the empire became the door the empire left by.",
    mech: "When the king arrived in 1911 only a cardboard model stood there. The real building took years of work on new land beside the harbour. Just 24 years after it opened, British rule had ended.",
    models: ["second-order-thinking"],
    q: "What is the story of the Gateway of India?",
    a: "It was built for King George V's 1911 visit and finished in 1924. In 1948 the last British soldiers left India through it.",
    chain: [["Built for King George V's visit in 1911", ["george", "1911", "king", "visit"]], ["Finished only in 1924", ["1924", "finished", "completed"]], ["Last British troops left through it in 1948", ["1948", "troops", "soldiers", "left", "last british"]]],
    mcq: { q: "Why was the Gateway of India built?", o: ["To mark the visit of King George V in 1911", "To celebrate India's independence", "As a lighthouse for ships", "As a gate to a fort"] },
    bring: "At the Gateway: “This was built to welcome a British king. In 1948 the last British soldiers walked out through it.”",
    follow: "Which other monument means something very different today from what its builders planned?",
    deeper: "The Taj Mahal Palace hotel next to it is older. Jamsetji Tata opened it in 1903, twenty-one years before the Gateway was finished." },

  { id: "vada-pav", type: "fact", domain: "anthropology", title: "The vada pav's world journey", value: 3, cue: "street food",
    fact: "The vada pav was created in 1966 by Ashok Vaidya at a stall outside Dadar station. But its main parts did not start in India. Potato and chilli came from the Americas, and ‘pav’ comes from ‘pão’, the Portuguese word for bread.",
    why: "Mumbai's most local snack is the result of 500 years of world trade.",
    mech: "Portuguese traders brought potatoes, chillies and oven-baked bread to India's west coast. Much later, mill workers and train commuters needed food that was cheap, filling and easy to eat while walking. A fried potato ball inside a bread roll did the job.",
    models: ["second-order-thinking", "first-principles"],
    q: "Why is the vada pav a global food as well as a local one?",
    a: "It was created at Dadar in 1966, but potato and chilli came from the Americas and pav comes from Portuguese bread. Trade brought the parts; Mumbai's workers needed a cheap, quick meal.",
    chain: [["Created at Dadar station in 1966", ["1966", "dadar", "vaidya"]], ["Potato and chilli came from the Americas", ["potato", "chilli", "chili", "america"]], ["Pav comes from Portuguese bread", ["portug", "pão", "pao", "bread"]], ["Cheap, quick food for workers", ["cheap", "worker", "commuter", "quick", "mill"]]],
    mcq: { q: "Where does the word ‘pav’ come from?", o: ["The Portuguese word for bread", "The Marathi word for foot", "A British bakery brand", "A Persian word for potato"] },
    bring: "Over a vada pav: “Nothing in this started in India. The potato and chilli are from the Americas, and the pav is Portuguese.”",
    follow: "Which other ‘Indian’ food do you think came from somewhere else?",
    deeper: "Tomatoes, cashews, guavas and papayas also reached India with the Portuguese." }
  ]);

  const MAHARASHTRA = L("maharashtra", [
  { id: "shivaji-forts", type: "concept", domain: "strategy", title: "Shivaji Maharaj and ganimi kava", value: 5, cue: "forts, treks in the Sahyadris, or beating a bigger rival",
    fact: "Chhatrapati Shivaji Maharaj (1630 to 1680) built the Maratha kingdom while fighting much bigger armies. He used hill forts and fast surprise attacks, a method known as ganimi kava.",
    why: "It shows how a small force can beat a large one by choosing where and how to fight.",
    mech: "The Sahyadri hills are steep, with narrow paths. Big armies with heavy guns and elephants move slowly there. Shivaji's light soldiers knew the land. They struck quickly and went back to forts that were very hard to capture. In those hills, the enemy's size became a weakness.",
    models: ["bottlenecks", "game-theory", "inversion"],
    q: "How did Shivaji Maharaj fight armies much larger than his own?",
    a: "He used the steep Sahyadri hills and strong forts, and made fast surprise attacks instead of open battles. Big, slow armies could not use their numbers there.",
    chain: [["Steep hills and narrow paths", ["hill", "sahyadri", "mountain", "narrow", "terrain"]], ["Strong hill forts", ["fort"]], ["Fast surprise attacks", ["surprise", "fast", "quick", "guerrilla", "ganimi", "raid"]], ["The big army's size became a weakness", ["big", "large", "slow", "size", "numbers", "heavy"]]],
    mcq: { q: "What was the main idea of ganimi kava?", o: ["Fast surprise attacks using hills and forts, not open battles", "Meeting the enemy on open ground with elephants", "Paying the enemy to go away", "Fighting only at sea"] },
    bring: "On a fort trek: “These forts were the whole plan. A big army is slow and weak in these hills.”",
    follow: "Where in work or sport does a small team win by choosing the ground?",
    deeper: "He was crowned Chhatrapati at Raigad in 1674. In 2025, twelve Maratha forts were added to the UNESCO World Heritage list as the ‘Maratha Military Landscapes of India’." },

  { id: "shivaji-agra", type: "historical story", domain: "history", title: "The escape from Agra", value: 5, cue: "clever escapes, or guards who stop paying attention", story: "agra",
    fact: "In 1666 Shivaji Maharaj was held under guard in Agra by the Mughal emperor Aurangzeb. He escaped with his young son Sambhaji. By tradition, they hid in large baskets used to send out sweets.",
    why: "A prisoner in the capital of the strongest empire in India got away without a fight. He used the guards' own habits against them.",
    mech: "Shivaji said he was ill and began sending out big baskets of sweets every day as gifts. At first the guards checked each basket. After many days they stopped checking. Then he and his son left inside the baskets.",
    models: ["inversion", "second-order-thinking"],
    q: "How did Shivaji Maharaj escape from Agra?",
    a: "He pretended to be ill and sent out baskets of sweets every day until the guards stopped checking them. Then he and his son Sambhaji hid in the baskets and were carried out.",
    chain: [["Held in Agra by Aurangzeb in 1666", ["agra", "aurangzeb", "1666", "mughal"]], ["Pretended to be ill", ["ill", "sick", "pretend"]], ["Daily baskets of sweets until guards stopped checking", ["basket", "sweet", "stopped checking", "habit", "routine"]], ["Escaped with his son Sambhaji", ["sambhaji", "son", "escape"]]],
    mcq: { q: "Why did the guards at Agra stop checking the baskets?", o: ["They saw the same baskets every day and grew careless", "Aurangzeb ordered them to stop", "They were paid to look away", "The baskets were too heavy to open"] },
    bring: "When security checks come up: “Shivaji Maharaj escaped Agra by making the guards bored. He sent out sweets every day until they stopped looking.”",
    follow: "What do we stop checking just because we see it every day?",
    deeper: "Historians agree that he escaped on 17 August 1666. The basket detail comes from later accounts, and some historians doubt it." },

  { id: "shivaji-navy", type: "fact", domain: "strategy", title: "Shivaji Maharaj's navy", value: 4, cue: "the Konkan coast, sea forts or the navy",
    fact: "Shivaji Maharaj built a navy and sea forts such as Sindhudurg, begun in 1664, to guard the Konkan coast. He is often called the father of the Indian Navy.",
    why: "Most Indian rulers of his time ignored the sea. He saw that whoever controlled the coast controlled the trade.",
    mech: "The Portuguese, the English and the Siddis of Janjira ruled the coastal waters and taxed ships. A land army could not stop them. Ships and sea forts gave the Marathas their own safe ports and a way to protect traders.",
    models: ["bottlenecks", "first-principles"],
    q: "Why did Shivaji Maharaj build a navy?",
    a: "Foreign powers and the Siddis controlled the coast and its trade, and an army on land could not stop them. Ships and sea forts like Sindhudurg gave the Marathas safe ports.",
    chain: [["Others controlled the sea and taxed ships", ["portug", "english", "siddi", "controlled", "tax"]], ["A land army could not stop them", ["land", "army", "could not"]], ["He built ships and sea forts", ["ship", "navy", "sea fort", "sindhudurg"]], ["Safe ports and protected trade", ["port", "trade", "protect", "coast"]]],
    mcq: { q: "Which sea fort did Shivaji Maharaj begin building in 1664?", o: ["Sindhudurg", "Daulatabad", "Golconda", "Red Fort"] },
    bring: "On a Konkan trip: “Sindhudurg was built in the sea because Shivaji Maharaj knew the coast decided who got rich.”",
    follow: "Why do you think most rulers of that time ignored the sea?",
    deeper: "Later, the Maratha admiral Kanhoji Angre held this coast against European ships for decades in the early 1700s." },

  { id: "panipat-1761", type: "event", domain: "history", title: "The Third Battle of Panipat", value: 4, cue: "supply chains, overreach, or Maratha history",
    fact: "On 14 January 1761 the Maratha army lost the Third Battle of Panipat to Ahmad Shah Abdali. It was one of the largest and deadliest battles of the 1700s.",
    why: "The Marathas were then the strongest power in India. The defeat stopped their rise in the north and left room for the British East India Company to grow.",
    mech: "The Maratha army was more than 1,000 km from home, and many families and pilgrims travelled with it. Abdali cut off its food supply. After weeks of hunger, the army had to come out and fight, and it was beaten.",
    models: ["bottlenecks", "margin-of-safety"],
    q: "Why did the Marathas lose at Panipat in 1761?",
    a: "They were far from home with many non-fighters to feed. Abdali cut their supplies, and a hungry army was forced to fight.",
    chain: [["Far from home", ["far", "1,000", "1000", "distance", "north"]], ["Many non-fighters to feed", ["famil", "pilgrim", "non-fight", "camp", "civilian"]], ["Abdali cut the supply lines", ["supply", "food", "cut", "abdali"]], ["A hungry army had to fight", ["hungry", "hunger", "starv", "forced"]]],
    mcq: { q: "What was the Marathas' biggest problem at Panipat?", o: ["Their food supply was cut off far from home", "They had no cavalry", "Heavy rain ruined their guns", "Their leader left before the battle"] },
    bring: "When a company grows too fast: “It is the Panipat problem. The Marathas were strong, but too far from their supplies.”",
    follow: "Where are you depending on a supply line that could be cut?",
    deeper: "In Marathi, ‘Panipat zhala’ is still used to mean a great disaster. The Marathas recovered much of their power in the north within about ten years." },

  { id: "ajanta", type: "fact", domain: "history", title: "The forgotten caves of Ajanta", value: 4, cue: "travel in Maharashtra, old art, or lost things",
    fact: "The Ajanta caves near Chhatrapati Sambhajinagar (Aurangabad) hold Buddhist paintings up to 2,000 years old. They lay forgotten in the forest until 1819, when a British officer named John Smith came upon them while hunting a tiger.",
    why: "Some of the finest ancient paintings in the world lasted because people forgot them.",
    mech: "Monks cut the caves into a curved cliff between about the 2nd century BCE and the 5th century CE. When Buddhism faded in the region, the caves were left empty and the forest covered them. Being hidden kept the paintings safe from people.",
    models: ["survivorship-bias", "lindy-effect"],
    q: "Why did the Ajanta paintings survive so long?",
    a: "After Buddhism faded in the area the caves were left and the forest hid them. They stayed untouched until a British officer found them in 1819 on a tiger hunt.",
    chain: [["Buddhist caves cut by monks", ["buddhis", "monk", "cave"]], ["Left empty and hidden by forest", ["forgot", "abandon", "forest", "hidden", "left"]], ["Being hidden protected the paintings", ["protect", "safe", "untouched", "survive", "preserv"]], ["Found in 1819 on a tiger hunt", ["1819", "tiger", "smith", "british officer"]]],
    mcq: { q: "How were the Ajanta caves found again in 1819?", o: ["A British officer saw them while hunting a tiger", "A farmer dug into them by accident", "A king ordered a search", "An earthquake opened the cliff"] },
    bring: "When travel plans come up: “Ajanta was lost for over a thousand years. A tiger hunt found it again.”",
    follow: "What do you think is still hidden in India that we have not found?",
    deeper: "John Smith scratched his name and the date on a painted pillar in Cave 10. You can still see it." },

  { id: "kailasa-temple", type: "concept", domain: "design", title: "The Kailasa temple at Ellora", value: 5, cue: "great buildings, or doing things in reverse",
    fact: "The Kailasa temple at Ellora was carved out of a single rock in the 8th century. The builders started at the top of the hill and cut downwards. It is the largest building in the world carved from one rock.",
    why: "Most buildings are made by adding pieces. This one was made only by taking rock away, so no mistake could be fixed.",
    mech: "Workers cut three deep trenches into the hillside to leave one huge block. Then they carved from the top down: the roof first, then halls, pillars and statues. Working downwards meant they needed no scaffolding, and the waste rock was simply carried away.",
    models: ["inversion", "first-principles"],
    q: "How was the Kailasa temple made?",
    a: "It was carved from one rock, from the top down. Trenches cut out a giant block, then workers carved the roof first and worked downwards, with no scaffolding.",
    chain: [["Carved from a single rock", ["single rock", "one rock", "monolith", "one stone"]], ["Cut from the top down", ["top", "down", "downward", "roof first"]], ["Trenches left one huge block", ["trench", "block", "cut around"]], ["No scaffolding, no way to fix mistakes", ["scaffold", "mistake", "fix", "taking away", "remov"]]],
    mcq: { q: "What is unusual about how the Kailasa temple was built?", o: ["It was carved from the top down out of one rock", "It was built without any tools", "It was moved from another place", "It was built in a single year"] },
    bring: "When a big project comes up: “The Kailasa temple was carved from the top down, out of one rock. They could not fix a single mistake.”",
    follow: "What would you plan differently if you could not undo any step?",
    deeper: "It was made under the Rashtrakuta king Krishna I. It is often estimated that about 200,000 tonnes of rock were removed." },

  { id: "lonar-crater", type: "fact", domain: "science", title: "Lonar crater lake", value: 4, cue: "space, meteorites or unusual places in Maharashtra",
    fact: "Lonar Lake in Buldhana district was made by a meteorite hitting the Earth. The crater is about 1.8 km wide. It is one of the very few known meteorite craters in basalt rock anywhere on Earth.",
    why: "The Moon and Mars are covered in craters in similar rock. So scientists study Lonar to understand them.",
    mech: "A rock from space hit the ground at very high speed and blasted out a bowl. Rain water collected in it. No river flows out, so over time the water became both salty and alkaline, which is rare.",
    models: ["bayesian-thinking", "map-vs-territory"],
    q: "What is special about Lonar Lake?",
    a: "A meteorite made it. It is one of very few craters in basalt rock on Earth, so it helps scientists understand craters on the Moon and Mars.",
    chain: [["Made by a meteorite", ["meteor", "space rock", "impact", "asteroid"]], ["In basalt rock, which is very rare", ["basalt", "rare", "few", "volcanic rock"]], ["Helps us understand the Moon and Mars", ["moon", "mars"]], ["Salty and alkaline water", ["salt", "alkaline", "no river"]]],
    mcq: { q: "How was Lonar Lake formed?", o: ["A meteorite hit the Earth", "A volcano collapsed", "A river was dammed", "A glacier melted"] },
    bring: "When weekend trips come up: “There is a meteorite crater you can walk into, in Buldhana. Lonar.”",
    follow: "If you could see one natural wonder in Maharashtra, which would it be?",
    deeper: "Its age is still argued over. Older studies said about 50,000 years. A newer dating method suggests about 570,000 years. In 2020 the lake turned pink for a while because of tiny salt-loving living things." },

  { id: "deccan-traps", type: "scientific principle", domain: "science", title: "The Deccan Traps", value: 5, cue: "the Sahyadris, black soil, or dinosaurs",
    fact: "About 66 million years ago, huge volcanic eruptions covered much of western and central India with lava. These rock layers, called the Deccan Traps, cover around 500,000 square km, including most of Maharashtra.",
    why: "The black rock of the Sahyadris, the flat-topped hills and the black cotton soil all come from this. It may also have helped kill the dinosaurs.",
    mech: "Lava poured out again and again over many thousands of years. Each flow cooled into a flat layer of basalt on top of the last. Later, rain cut the layers into steps. Gases from the eruptions changed the climate at about the same time that a giant asteroid hit Mexico.",
    models: ["second-order-thinking", "bayesian-thinking"],
    q: "What are the Deccan Traps and why do they matter?",
    a: "They are layers of lava from giant eruptions about 66 million years ago. They made Maharashtra's hills and black soil, and their gases may have helped end the dinosaurs.",
    chain: [["Giant eruptions about 66 million years ago", ["66 million", "volcan", "erupt", "lava"]], ["Lava cooled into flat layers of basalt", ["layer", "basalt", "flat", "step"]], ["Made the hills and black soil", ["sahyadri", "hill", "black soil", "ghats", "soil"]], ["May have helped kill the dinosaurs", ["dinosaur", "extinct", "climate", "gas"]]],
    mcq: { q: "What made the layered black rock of the Sahyadris?", o: ["Huge lava flows about 66 million years ago", "Sand left by an ancient sea", "A meteorite strike", "Ice sheets grinding the land"] },
    bring: "On a ghat road: “Look at the layers in the cliff. Each one is a lava flow from the time the dinosaurs died.”",
    follow: "Did you know the soil that grows cotton here started as lava?",
    deeper: "‘Trap’ comes from a Scandinavian word for stairs, because of the stepped hills. Scientists still argue about how much of the extinction was caused by the eruptions and how much by the asteroid." },

  { id: "western-ghats-rain", type: "concept", domain: "geography", title: "The Western Ghats and the rain shadow", value: 4, cue: "monsoon trips, drought news, or why Marathwada is dry",
    fact: "The Western Ghats block the monsoon winds from the sea. So Mahabaleshwar gets more than 5,000 mm of rain a year, while Solapur, east of the hills, gets only about 600 mm.",
    why: "One line of hills decides who gets floods and who gets drought. It explains Konkan rice, Deccan jowar, and Marathwada's water trouble.",
    mech: "Wet wind from the Arabian Sea hits the hills and is forced to rise. Rising air cools and drops its rain on the side facing the sea. By the time the wind crosses the top, it is dry. The dry side is called a rain shadow.",
    models: ["bottlenecks", "second-order-thinking"],
    q: "Why is the Konkan so wet while the land east of the Ghats is dry?",
    a: "Monsoon wind from the sea rises over the Ghats, cools, and drops its rain on the sea side. The air that crosses over is dry, leaving a rain shadow.",
    chain: [["Wet wind comes from the Arabian Sea", ["wind", "arabian", "sea", "monsoon"]], ["The hills force it to rise and cool", ["rise", "cool", "forced up", "lift"]], ["Rain falls on the sea-facing side", ["rain falls", "sea side", "windward", "konkan", "west side"]], ["The far side is dry: a rain shadow", ["rain shadow", "dry", "east", "drought"]]],
    mcq: { q: "Why does Solapur get so much less rain than Mahabaleshwar?", o: ["It lies in the rain shadow of the Western Ghats", "It is much closer to the sea", "It is at a higher height", "The monsoon never reaches Maharashtra"] },
    bring: "When drought news comes up: “The Ghats take most of the rain. That is why the Konkan floods while Marathwada waits.”",
    follow: "How should a state share water when one side gets ten times more rain?",
    deeper: "The Western Ghats are older than the Himalayas and are a UNESCO World Heritage Site for their wildlife. The Godavari, Krishna and Bhima all begin here and flow east." },

  { id: "savitribai-phule", type: "person", domain: "history", title: "Savitribai Phule", value: 5, cue: "girls' education, teachers or social change",
    fact: "In 1848 Savitribai Phule and her husband Jyotirao Phule opened a school for girls at Bhide Wada in Pune. She is seen as India's first woman teacher.",
    why: "At that time most people believed that girls and lower-caste children should not study. She taught them anyway.",
    mech: "People threw mud and dung at her on her way to school. It is said she carried a spare sari, changed when she arrived, and went on teaching. The Phules later opened more schools and a home for widows. Each girl who learned could teach others.",
    models: ["second-order-thinking", "compounding"],
    q: "What did Savitribai Phule do, and what did it cost her?",
    a: "With Jyotirao Phule she opened a girls' school in Pune in 1848 and taught there. People threw mud and dung at her, but she kept going and opened more schools.",
    chain: [["Opened a girls' school in Pune in 1848", ["1848", "pune", "school", "bhide"]], ["With her husband Jyotirao Phule", ["jyotirao", "jyotiba", "husband"]], ["People threw mud and dung at her", ["mud", "dung", "stones", "abuse", "spare sari"]], ["She kept teaching and opened more schools", ["kept", "continued", "more schools", "widow"]]],
    mcq: { q: "What is Savitribai Phule best known for?", o: ["Being India's first woman teacher", "Leading an army", "Writing the Constitution", "Founding a bank"] },
    bring: "When education comes up: “Savitribai Phule carried a spare sari to school, because people threw dung at her on the way.”",
    follow: "Who is doing something today that people mock, but that will look obviously right later?",
    deeper: "She died in 1897 after catching plague while caring for patients in Pune. Pune University is now named Savitribai Phule Pune University." },

  { id: "mahad-satyagraha", type: "event", domain: "history", title: "The Mahad Satyagraha", value: 4, cue: "equal rights, Dr Ambedkar, or laws that exist only on paper",
    fact: "On 20 March 1927, Dr B. R. Ambedkar led thousands of Dalits to drink water from the Chavdar tank in Mahad, in Raigad district. The law already allowed it, but upper castes had never let them.",
    why: "A very simple act, drinking water, showed the gap between rights on paper and rights in real life.",
    mech: "A right that nobody dares to use changes nothing. By using it in public and in large numbers, the marchers made the unfairness clear to everyone. Ambedkar later led the writing of India's Constitution, which banned untouchability.",
    models: ["map-vs-territory", "game-theory"],
    q: "What happened at Mahad in 1927 and why did it matter?",
    a: "Dr Ambedkar led thousands of Dalits to drink from a public tank that the law allowed them to use but society did not. It showed the gap between rights on paper and in real life.",
    chain: [["Dr Ambedkar led the march in 1927", ["ambedkar", "1927", "led"]], ["They drank from the Chavdar tank in Mahad", ["chavdar", "tank", "mahad", "water", "drank"]], ["The law allowed it, society did not", ["law", "allowed", "paper", "legal", "upper caste"]], ["Using the right in public made it real", ["public", "together", "visible", "real", "use"]]],
    mcq: { q: "What did the marchers at Mahad do?", o: ["Drank water from a public tank they had been kept away from", "Refused to pay the salt tax", "Burned foreign cloth", "Walked to Delhi"] },
    bring: "When rights come up: “At Mahad in 1927 the law was already on their side. They still had to walk to the tank together and drink.”",
    follow: "Which rights today exist on paper but are hard to use in real life?",
    deeper: "20 March is marked as Social Empowerment Day. Three years before Gandhi's Salt March, Mahad used the same kind of simple, peaceful act." }
  ]);

  const INDIA = L("india", [
  { id: "zero-brahmagupta", type: "concept", domain: "science", title: "Zero becomes a number", value: 5, cue: "maths, computers or Indian inventions",
    fact: "In 628 CE the Indian mathematician Brahmagupta wrote the first known rules for using zero as a number, such as ‘a number minus itself is zero’.",
    why: "Without zero as a number there is no easy arithmetic, no modern algebra, and no computers.",
    mech: "Earlier, people used a mark only to show an empty place. Brahmagupta treated zero as a real number that you can add, subtract and multiply. With zero and place value, ten symbols can write any number, and sums become easy. The idea travelled through the Arab world to Europe.",
    models: ["first-principles", "compounding"],
    q: "What did Brahmagupta do with zero, and why did it matter?",
    a: "In 628 CE he gave rules for zero as a real number. With zero and place value, ten symbols can write any number, which made arithmetic easy and later made algebra and computers possible.",
    chain: [["Brahmagupta, 628 CE", ["brahmagupta", "628"]], ["Zero as a real number with rules", ["number", "rules", "add", "subtract"]], ["Place value: ten symbols write any number", ["place value", "ten symbols", "digits", "decimal", "position"]], ["Spread through the Arab world to Europe", ["arab", "europe", "spread", "travel"]]],
    mcq: { q: "What was new about Brahmagupta's zero?", o: ["He gave rules for using zero as a number in sums", "He was the first to draw a circle", "He used zero only as a full stop", "He proved zero does not exist"] },
    bring: "When Indian inventions come up: “The big step was treating zero as a real number. Brahmagupta wrote the rules in 628.”",
    follow: "What other idea seems obvious now but had to be invented?",
    deeper: "Brahmagupta also wrote rules for negative numbers, calling them ‘debts’ and positive numbers ‘fortunes’. He got dividing by zero wrong, which is still undefined today.",
    mis: [{ re: "aryabhata (invented|discovered|found) zero", msg: "Aryabhata used place value, but the first known rules for zero as a number are Brahmagupta's." }] },

  { id: "indus-valley", type: "concept", domain: "history", title: "The planned cities of the Indus Valley", value: 4, cue: "city planning, drains or ancient India",
    fact: "About 4,500 years ago, Indus Valley cities such as Mohenjo-daro, Harappa and Dholavira had straight streets, covered drains, and bricks of one standard shape.",
    why: "They planned cities better than many places did thousands of years later. And we still cannot read their writing.",
    mech: "Bricks everywhere used the same ratio of 1:2:4, and traders used the same set of weights. Shared standards let cities far apart build and trade in the same way, even without one known king or palace.",
    models: ["network-effects", "first-principles"],
    q: "What was advanced about the Indus Valley cities?",
    a: "They had straight streets, covered drains and standard bricks and weights 4,500 years ago. Shared standards let distant cities build and trade alike. Their writing is still unread.",
    chain: [["About 4,500 years ago", ["4,500", "4500", "2500 bc", "2600", "ancient"]], ["Straight streets and covered drains", ["street", "grid", "drain", "sewer", "planned"]], ["Standard bricks and weights", ["brick", "weight", "standard", "1:2:4"]], ["Their writing is still unread", ["script", "writing", "unread", "decipher", "cannot read"]]],
    mcq: { q: "Which of these did Indus Valley cities have?", o: ["Covered drains and bricks of a standard shape", "Iron bridges", "Coins with kings' faces", "Paper books"] },
    bring: "When bad roads or drains come up: “Mohenjo-daro had covered drains 4,500 years ago.”",
    follow: "Why do you think we plan cities worse now, with far more tools?",
    deeper: "Dholavira in Kutch had large water tanks cut in rock and became a UNESCO World Heritage Site in 2021. Lothal in Gujarat had what many think was a dock for ships." },

  { id: "ashoka-kalinga", type: "historical story", domain: "history", title: "Ashoka after Kalinga", value: 5, cue: "leaders who admit mistakes, or the national emblem", story: "ashoka",
    fact: "Around 261 BCE Emperor Ashoka won the Kalinga war. His own stone writings say 100,000 people were killed and 150,000 taken away. Filled with regret, he gave up war and spent the rest of his rule spreading dhamma: kindness, tolerance and care for all.",
    why: "A ruler at the height of his power said in public that he was sorry. That is rare in any age.",
    mech: "He had his new rules cut into rocks and pillars across the empire, in local languages, so that ordinary people could know them. The four lions on top of his pillar at Sarnath are now India's national emblem.",
    models: ["second-order-thinking", "incentives"],
    q: "How did the Kalinga war change Ashoka?",
    a: "The huge loss of life filled him with regret. He gave up war, took up dhamma, and had his message cut into rocks and pillars for all to read.",
    chain: [["He won the Kalinga war", ["kalinga", "war", "won"]], ["About 100,000 were killed", ["100,000", "lakh", "hundred thousand", "killed", "deaths"]], ["He felt regret and gave up war", ["regret", "sorry", "remorse", "gave up", "stopped"]], ["He spread dhamma on rocks and pillars", ["dhamma", "dharma", "pillar", "rock", "edict"]]],
    mcq: { q: "What did Ashoka do after the Kalinga war?", o: ["Gave up war and spread a message of kindness", "Attacked the south of India", "Gave his throne to his brother", "Built a great wall"] },
    bring: "When leaders and mistakes come up: “Ashoka won his biggest war and then wrote on stone that he regretted it.”",
    follow: "Can you think of any leader today who has said sorry in public?",
    deeper: "His writings were forgotten for centuries. In 1837 James Prinsep worked out the Brahmi script and people could read them again. The wheel on India's flag is the Ashoka Chakra." },

  { id: "salt-march", type: "event", domain: "strategy", title: "The Salt March", value: 5, cue: "protests, Gandhi, or beating a stronger opponent",
    fact: "In March 1930 Gandhi walked about 385 km from Sabarmati Ashram to the sea at Dandi in 24 days. There he picked up a handful of salt and broke the British salt law.",
    why: "He chose a law that hurt every Indian, rich or poor. Breaking it was easy, peaceful, and impossible to ignore.",
    mech: "Only the British were allowed to make and sell salt, and they taxed it. If they ignored the march, the law was dead. If they arrested peaceful marchers, they looked cruel to the world. Both choices hurt them. About 60,000 people were jailed while the world's newspapers watched.",
    models: ["game-theory", "inversion"],
    q: "Why was the Salt March such a clever protest?",
    a: "Everyone needed salt, so everyone understood the issue. The British lost either way: ignore the march and the law dies, or arrest peaceful people and look cruel.",
    chain: [["Gandhi walked to Dandi in 1930", ["dandi", "1930", "walk", "march", "385"]], ["Salt was taxed and everyone needed it", ["salt", "tax", "everyone", "monopoly"]], ["The British lost either way", ["either", "both", "ignore", "arrest", "no good choice", "trap"]], ["Peaceful, and watched by the world", ["peace", "non-violen", "world", "press", "newspaper"]]],
    mcq: { q: "Why did Gandhi choose salt for his protest?", o: ["Everyone needed it, so the tax touched every Indian", "Salt was India's biggest export", "The British had banned eating salt", "Salt was only used by the rich"] },
    bring: "When protests come up: “Gandhi picked salt because nobody could say it was not their problem.”",
    follow: "What is the ‘salt’ of today, something small that touches everyone?",
    deeper: "He started with 78 followers and thousands joined on the way. Time magazine named him Man of the Year for 1930." },

  { id: "monsoon-economy", type: "concept", domain: "economics", title: "The monsoon and the economy", value: 4, cue: "rain forecasts, food prices or the economy",
    fact: "The south-west monsoon, from June to September, brings about three quarters of India's yearly rain. About half of India's farmland has no irrigation and depends on it.",
    why: "A good or bad monsoon changes food prices, farm incomes, and even sales of tractors and motorbikes.",
    mech: "Good rain means a good harvest. Farmers earn more and spend more, and food stays cheap. Poor rain means smaller harvests, higher food prices and less spending in villages. That then spreads to the rest of the economy.",
    models: ["second-order-thinking", "feedback-loops"],
    q: "Why does the monsoon matter so much to India's economy?",
    a: "It brings about three quarters of the year's rain, and half the farmland depends on it. Good rain raises harvests and village spending; poor rain raises food prices and cuts spending.",
    chain: [["About three quarters of the year's rain", ["three quarter", "75", "most of the rain", "june", "september"]], ["Half the farmland has no irrigation", ["half", "irrigation", "depends", "rain-fed"]], ["Rain decides the harvest and food prices", ["harvest", "crop", "food price", "price"]], ["Village spending spreads to the whole economy", ["spend", "income", "tractor", "economy", "demand"]]],
    mcq: { q: "About how much of India's yearly rain comes in the June to September monsoon?", o: ["About three quarters", "About one tenth", "About one quarter", "Almost none"] },
    bring: "When the rain forecast comes up: “A good monsoon is not just about farms. It decides food prices and even bike sales.”",
    follow: "Have you noticed vegetable prices change after a bad monsoon?",
    deeper: "A former finance minister once called the monsoon India's real finance minister. More irrigation has reduced the effect over the years, but it is still large." },

  { id: "reforms-1991", type: "event", domain: "economics", title: "The 1991 crisis and reforms", value: 5, cue: "the economy, liberalisation, or how India changed",
    fact: "In 1991 India had foreign money left for only about two to three weeks of imports. It sent 47 tonnes of gold to the Bank of England as security for emergency loans. Weeks later, the budget of 24 July 1991 opened up the economy.",
    why: "Much of modern India, from IT companies to the choice of cars and phones, goes back to this crisis.",
    mech: "The Gulf War pushed up oil prices, and India was spending more abroad than it earned. To get loans it had to change. The government cut the ‘licence raj’, the rule that firms needed permission to make almost anything. It lowered import taxes and let in foreign companies.",
    models: ["incentives", "second-order-thinking"],
    q: "What happened to India's economy in 1991?",
    a: "India nearly ran out of foreign money and sent gold abroad to get loans. In return it opened the economy: it cut the licence raj, lowered import taxes and allowed foreign companies.",
    chain: [["Almost out of foreign money", ["foreign", "reserves", "weeks", "imports", "ran out"]], ["Sent gold abroad for loans", ["gold", "47", "loan", "bank of england"]], ["Ended the licence raj", ["licence", "license", "permission", "permit"]], ["Opened to trade and foreign companies", ["open", "trade", "foreign compan", "import tax", "liberal"]]],
    mcq: { q: "What pushed India to open its economy in 1991?", o: ["It had almost run out of foreign money to pay for imports", "It won a trade war", "Oil was found near Mumbai", "A new constitution was written"] },
    bring: "When someone remembers waiting years for a phone or scooter: “That was before 1991. India had to send its gold abroad before things changed.”",
    follow: "What do you think India would look like if 1991 had not happened?",
    deeper: "P. V. Narasimha Rao was prime minister and Manmohan Singh was finance minister. Singh ended his budget speech with the line that no power on Earth can stop an idea whose time has come." },

  { id: "green-revolution", type: "concept", domain: "science", title: "The Green Revolution", value: 4, cue: "farming, food prices, or Punjab",
    fact: "In the mid-1960s India depended on food sent from abroad. New high-yield wheat and rice seeds, with more water and fertiliser, changed that. Wheat harvests roughly doubled within a few years.",
    why: "It ended the fear of famine in India. It also left problems: falling groundwater and tired soil in Punjab and Haryana.",
    mech: "The scientist Norman Borlaug bred short wheat plants that could carry heavy grain without falling over. M. S. Swaminathan and others adapted them for India. The government promised to buy the grain at a fixed price, so farmers took the risk of trying the new seeds.",
    models: ["second-order-thinking", "incentives"],
    q: "What was the Green Revolution, and what were its results?",
    a: "New high-yield seeds with more water and fertiliser, backed by a promised price, roughly doubled wheat harvests. India stopped depending on food from abroad, but groundwater and soil suffered.",
    chain: [["India depended on food from abroad", ["import", "abroad", "aid", "ship", "famine"]], ["New high-yield seeds", ["seed", "high-yield", "borlaug", "swaminathan", "variet"]], ["More water and fertiliser, and a promised price", ["fertili", "water", "irrigation", "price", "buy"]], ["Later costs: groundwater and soil", ["groundwater", "soil", "water table", "problem", "cost"]]],
    mcq: { q: "What was the main cause of the Green Revolution's bigger harvests?", o: ["New high-yield seeds with more water and fertiliser", "A large increase in farmland", "Unusually good monsoons for ten years", "Importing tractors from the USA"] },
    bring: "When farm news comes up: “In the 1960s India lived ‘ship to mouth’ on foreign wheat. New seeds changed that in a few years.”",
    follow: "Was the Green Revolution worth its cost to water and soil?",
    deeper: "It worked best where there was irrigation, so Punjab, Haryana and western Uttar Pradesh gained most, while rain-fed regions gained far less." },

  { id: "amul-white-revolution", type: "business concept", domain: "business", title: "Amul and the White Revolution", value: 4, cue: "milk, cooperatives or farmer incomes",
    fact: "Amul began in 1946 as a milk farmers' cooperative in Anand, Gujarat. From 1970 its model was copied across the country under ‘Operation Flood’, led by Verghese Kurien. India is now the world's largest milk producer.",
    why: "Millions of small farmers with one or two animals built a giant business that they own themselves.",
    mech: "Earlier, middlemen bought milk cheaply and kept the profit. In a cooperative the farmers own the dairy. Milk is collected in each village twice a day, tested, and paid for fairly, and the profit is shared. Fair pay made farmers produce more.",
    models: ["incentives", "network-effects"],
    q: "How did Amul change milk in India?",
    a: "Farmers formed a cooperative that they owned, so the profit went to them and not to middlemen. Fair pay made them produce more, and the model spread across India under Operation Flood.",
    chain: [["Started in Anand in 1946", ["anand", "1946", "gujarat"]], ["Farmers own the cooperative", ["cooperative", "co-op", "own", "farmers own"]], ["No middlemen, fair pay", ["middlem", "fair", "profit", "paid"]], ["Operation Flood spread it across India", ["operation flood", "kurien", "spread", "largest", "white revolution"]]],
    mcq: { q: "Who owns Amul?", o: ["Millions of milk farmers, through cooperatives", "The central government", "A single business family", "A foreign food company"] },
    bring: "When brands come up: “Amul is owned by its farmers. Millions of them, most with only a few animals.”",
    follow: "Which other businesses would work better if the suppliers owned them?",
    deeper: "The cooperative started because farmers in Kaira district were angry at the low prices paid by the one dairy allowed to buy their milk. Kurien, an engineer, had planned to stay only briefly in Anand." },

  { id: "upi", type: "business concept", domain: "business", title: "UPI", value: 5, cue: "paying by phone, QR codes or cash",
    fact: "UPI, launched in 2016, lets anyone send money from a phone in seconds at almost no cost. It now handles well over 10 billion payments a month, and India makes nearly half of the world's instant digital payments.",
    why: "A vegetable seller and a big shop use the same system. Very few countries have anything like it.",
    mech: "UPI is one shared system that all banks and payment apps connect to. So a person on one app can pay a person on any other. Each new user and each new shop makes it more useful for everyone else, and that brings in still more users.",
    models: ["network-effects", "feedback-loops"],
    q: "Why did UPI grow so fast?",
    a: "It is one shared system for all banks and apps, so anyone can pay anyone, in seconds and almost free. Each new user and shop makes it more useful, which brings more users.",
    chain: [["Launched in 2016", ["2016", "launch"]], ["One shared system for all banks and apps", ["shared", "all banks", "any app", "common", "open", "interoperab"]], ["Instant and almost free", ["instant", "seconds", "free", "no cost", "cheap"]], ["More users make it more useful", ["more users", "network", "useful", "everyone", "shops"]]],
    mcq: { q: "What makes UPI different from a single company's wallet?", o: ["Any bank or app can connect, so anyone can pay anyone", "It works only between friends", "It needs a credit card", "It only works in big shops"] },
    bring: "When paying a chaiwala by QR code: “India makes almost half the world's instant digital payments. Most countries cannot do this.”",
    follow: "When did you last pay for something small in cash?",
    deeper: "UPI is run by NPCI, which has its head office in Mumbai. It crossed 10 billion payments in a month for the first time in August 2023." },

  { id: "isro-frugal", type: "fact", domain: "science", title: "Chandrayaan-3 and low-cost space", value: 4, cue: "space, ISRO or doing more with less",
    fact: "On 23 August 2023 India's Chandrayaan-3 landed near the Moon's south pole. No spacecraft had ever landed there before. The mission cost about 615 crore rupees, less than many big films.",
    why: "It shows that careful, simple engineering can do what others do with far more money.",
    mech: "ISRO reuses designs it has already tested and builds most parts in India. It uses slower paths to the Moon that need smaller rockets. Chandrayaan-2 had crashed in 2019. Engineers studied each way the landing could fail and built this lander to survive them.",
    models: ["first-principles", "inversion"],
    q: "How did ISRO land on the Moon so cheaply?",
    a: "It reused tested designs, built parts in India, used a slower path with a smaller rocket, and designed the lander around every failure it had learned from in 2019.",
    chain: [["Landed near the Moon's south pole in 2023", ["south pole", "2023", "moon", "landed"]], ["Reused tested designs, built in India", ["reuse", "tested", "built in india", "own parts", "indigenous"]], ["Slower path, smaller rocket", ["slower", "smaller rocket", "longer route", "less fuel"]], ["Learned from the 2019 crash", ["2019", "chandrayaan-2", "crash", "failure", "learn"]]],
    mcq: { q: "What was special about where Chandrayaan-3 landed?", o: ["It was the first landing near the Moon's south pole", "It landed on the far side of Mars", "It landed in the largest crater on the Moon", "It landed where Apollo 11 did"] },
    bring: "When big budgets come up: “India landed on the Moon for less than the cost of many films.”",
    follow: "Where could ‘plan for failure first’ help in your own work?",
    deeper: "In 2014 the Mars Orbiter Mission, Mangalyaan, made India the first country to reach Mars orbit on its first try, for about 450 crore rupees." },

  { id: "india-plate", type: "scientific principle", domain: "science", title: "India's crash into Asia", value: 4, cue: "the Himalayas, earthquakes or maps",
    fact: "India was once joined to Africa and Antarctica. It broke away, moved north, and hit Asia about 50 million years ago. That slow crash pushed up the Himalayas, which are still rising.",
    why: "The Himalayas feed India's great rivers and shape the monsoon. The same push causes earthquakes in the north.",
    mech: "The Earth's surface is made of huge plates that move slowly. The Indian plate still pushes north by a few centimetres a year. The land has nowhere to go, so it folds upward into mountains.",
    models: ["second-order-thinking", "compounding"],
    q: "How were the Himalayas made?",
    a: "The Indian plate broke from Africa and Antarctica, moved north and hit Asia about 50 million years ago. It still pushes a few centimetres a year, folding the land up.",
    chain: [["India was joined to Africa and Antarctica", ["africa", "antarctica", "gondwana", "joined"]], ["It moved north and hit Asia", ["north", "asia", "collid", "hit", "crash"]], ["About 50 million years ago", ["50 million"]], ["Still pushing, so the Himalayas still rise", ["still", "rising", "centimet", "earthquake", "fold"]]],
    mcq: { q: "Why are the Himalayas still getting taller?", o: ["The Indian plate is still pushing into Asia", "Snow keeps piling up on top", "Volcanoes erupt under them", "The sea level is falling"] },
    bring: "When earthquakes or the Himalayas come up: “India is still moving north a few centimetres a year. The mountains are the crumple zone.”",
    follow: "Did you know sea shells are found high in the Himalayas?",
    deeper: "Small daily changes add up: a few centimetres a year over 50 million years moves a continent thousands of kilometres." },

  { id: "india-languages", type: "fact", domain: "anthropology", title: "India has no national language", value: 3, cue: "Hindi, Marathi or language arguments",
    fact: "India has no national language. The Constitution lists 22 ‘scheduled’ languages, and the 2011 census counted 121 languages each spoken by 10,000 or more people.",
    why: "Many people believe Hindi is the national language. In fact Hindi and English are the two official languages of the central government.",
    mech: "After independence, states were redrawn mainly by language. Maharashtra and Gujarat were formed on 1 May 1960 by splitting Bombay State. Each state can choose its own official language.",
    models: ["map-vs-territory"],
    q: "What is the true position of languages in India?",
    a: "There is no national language. Hindi and English are official languages of the central government, 22 languages are listed in the Constitution, and states were formed mostly by language.",
    chain: [["No national language", ["no national", "not national"]], ["Hindi and English are official languages of the centre", ["official", "hindi", "english", "central"]], ["22 scheduled languages", ["22", "scheduled"]], ["States were formed by language", ["states", "1960", "bombay state", "by language", "linguistic"]]],
    mcq: { q: "What is India's national language?", o: ["India has no national language", "Hindi", "English", "Sanskrit"] },
    bring: "When a language argument starts: “India has no national language at all. The Constitution lists 22.”",
    follow: "How many languages can the people in this room speak between them?",
    deeper: "1 May is Maharashtra Day because of the 1960 split. The movement for a Marathi-speaking state with Mumbai as its capital was called the Samyukta Maharashtra movement.",
    mis: [{ re: "hindi is (the|our|india's) national language", msg: "India has no national language. Hindi and English are official languages of the central government." }] },

  { id: "india-election", type: "fact", domain: "history", title: "The world's largest election", value: 3, cue: "voting, elections or democracy",
    fact: "India's 2024 general election had about 968 million registered voters, and about 642 million of them voted. It is the largest election in history.",
    why: "It works even in places with no roads. That is a huge feat of organisation.",
    mech: "The rule is that no voter should have to travel more than 2 km to vote. So officials carry voting machines on foot, by boat and on elephants to remote places. In Gujarat's Gir forest, a polling booth has been set up for a single voter.",
    models: ["first-principles"],
    q: "How big is an Indian general election, and how does it reach everyone?",
    a: "In 2024 about 968 million people could vote and about 642 million did. A booth must be within 2 km of every voter, so staff carry machines to the most remote places.",
    chain: [["About 968 million registered voters in 2024", ["968", "2024", "registered", "billion"]], ["About 642 million voted", ["642", "voted"]], ["A booth within 2 km of every voter", ["2 km", "two km", "booth", "near"]], ["Machines carried to remote places", ["remote", "carry", "elephant", "boat", "gir", "single voter"]]],
    mcq: { q: "What rule guides where polling booths are placed in India?", o: ["No voter should have to travel more than 2 km", "One booth for every city", "Only where there are roads", "Only in district towns"] },
    bring: "At election time: “In the Gir forest they set up a full polling booth for one single voter.”",
    follow: "Do you think voting should be made compulsory?",
    deeper: "India gave every adult the vote in its very first election in 1951 to 52, when most voters could not read. Party symbols were used so that everyone could choose." },

  { id: "bombay-time", type: "fact", domain: "geography", title: "One time zone, and Bombay Time", value: 3, cue: "time zones, sunrise or the north-east",
    fact: "India uses one time zone, though the sun rises almost two hours earlier in Arunachal Pradesh than in Gujarat. Bombay kept its own ‘Bombay Time’, 39 minutes behind Indian Standard Time, until 1955.",
    why: "Clock time is something people agree on. It is not the same as sun time.",
    mech: "Before railways, each city set its clocks by its own noon. Trains needed one timetable, so a standard time for India was set in 1906. Bombay did not want to change and kept its own time for decades.",
    models: ["map-vs-territory", "network-effects"],
    q: "Why does India have one time zone, and what was Bombay Time?",
    a: "Railways needed one timetable, so a single standard time was set in 1906, even though sunrise differs by almost two hours across India. Bombay kept its own time, 39 minutes behind, until 1955.",
    chain: [["One time zone for all of India", ["one time zone", "single", "ist"]], ["Sunrise differs by almost two hours", ["two hours", "sunrise", "arunachal", "east"]], ["Railways needed one timetable", ["railway", "train", "timetable", "1906"]], ["Bombay Time lasted until 1955", ["bombay time", "39", "1955"]]],
    mcq: { q: "Until when did Bombay keep its own local time?", o: ["1955", "1857", "1906", "1991"] },
    bring: "When someone is late: “Until 1955 you could have said you were on Bombay Time. It was 39 minutes behind the rest of India.”",
    follow: "Should the north-east have its own time zone?",
    deeper: "Tea gardens in Assam still use an informal ‘bagan time’, one hour ahead, to make better use of daylight." }
  ]);

  MV.ASSETS.unshift(...MUMBAI, ...MAHARASHTRA, ...INDIA);

  MV.STORIES.unshift(
  { id: "cotton", assetId: "cotton-boom", title: "The Day the Cotton Money Stopped",
    hook: "A war in America made Bombay rich, and then broke it almost overnight.",
    setting: "Bombay, 1861. The American Civil War has begun, and ships can no longer carry American cotton to Britain.",
    character: "Premchand Roychand, a clever young broker, and the thousands of traders who followed him.",
    conflict: "British mills needed cotton badly and paid any price for cotton from Bombay. Money poured into the city, and people put it into new banks and plans to fill the sea for land.",
    surprise: "In 1865 the war ended. American cotton came back and the price fell very fast.",
    turning: "Share prices crashed. Banks shut and many rich families lost everything.",
    payoff: "But the boom money had already paid for roads, buildings and new land that the city still uses today.",
    meaning: "Easy money from far away can leave as fast as it came. Always ask what happens when the cause of a boom ends.",
    extra: ["The Rajabai Clock Tower was paid for by Premchand Roychand and named after his mother.", "Shares in the Back Bay land company rose many times in value and then became almost worthless.", "The crash taught brokers that they needed rules, and ten years later they formed the stock exchange."],
    facts: [["1861", "1865", "civil war"], ["cotton"], ["america"], ["price"], ["crash", "fell", "collapse"], ["premchand", "bank"]],
    vocab: ["boom", "crash", "broker"] },
  { id: "agra", assetId: "shivaji-agra", title: "The Baskets of Sweets",
    hook: "The most powerful emperor in India had Shivaji Maharaj under guard. Shivaji left in a basket of sweets.",
    setting: "Agra, 1666. Shivaji Maharaj has come to the Mughal court with his nine-year-old son Sambhaji.",
    character: "Shivaji Maharaj, proud and quick-thinking, and Emperor Aurangzeb, who did not trust him.",
    conflict: "At court, Shivaji was made to stand behind less important nobles. He protested and walked out. Aurangzeb put him under house arrest with guards all around.",
    surprise: "Shivaji said he was ill. He began sending out huge baskets of sweets every day as gifts for holy men and the poor.",
    turning: "At first the guards checked every basket. After many days they grew bored and stopped. One evening, by tradition, Shivaji and Sambhaji hid in the baskets and were carried out.",
    payoff: "By the time the guards found the room empty, he was far away. He travelled home in disguise, and in 1674 he was crowned Chhatrapati.",
    meaning: "People stop checking what they see every day. Patience and a dull routine can beat strength.",
    extra: ["A loyal helper is said to have stayed in his bed so the guards would think he was still there.", "Historians agree on the escape, but some doubt the basket detail, which comes from later accounts.", "He took a long way home to avoid the roads the Mughals would search."],
    facts: [["1666"], ["agra"], ["aurangzeb"], ["basket"], ["sweet"], ["sambhaji", "son"], ["guard"]],
    vocab: ["routine", "disguise", "patience"] },
  { id: "ashoka", assetId: "ashoka-kalinga", title: "The Emperor Who Said Sorry",
    hook: "An emperor won his biggest war, and then said sorry for it in stone.",
    setting: "Eastern India, around 261 BCE. The Maurya empire covers most of the land, but Kalinga, today's Odisha, is still free.",
    character: "Ashoka, a hard and ambitious ruler.",
    conflict: "He attacked Kalinga with a huge army. Kalinga fought hard and lost.",
    surprise: "Ashoka's own writings say 100,000 people were killed and 150,000 carried away. When he saw this, he felt deep regret.",
    turning: "He gave up war as a way to grow his empire. He chose dhamma: kindness, respect for all faiths, and care for people and animals.",
    payoff: "He had these ideas cut into rocks and pillars across the land so that everyone could read them. The lions from his pillar at Sarnath are India's national emblem today.",
    meaning: "Real strength can mean admitting a wrong in public and changing your path.",
    extra: ["He built hospitals, planted trees along roads and dug wells for travellers.", "His writings were forgotten for centuries, until James Prinsep worked out the script in 1837.", "The wheel on India's flag is the Ashoka Chakra."],
    facts: [["kalinga"], ["ashoka"], ["100,000", "hundred thousand", "lakh"], ["regret", "sorry", "remorse"], ["dhamma", "dharma"], ["pillar", "rock", "stone"], ["lion", "emblem"]],
    vocab: ["regret", "conquest", "emblem"] });

  MV.LINKS.push(
    ["bombay-dowry", "east-india-company", "The Company rented Bombay from the king for 10 pounds a year and made it its western base."],
    ["bombay-dowry", "mumbai-seven-islands", "The islands the king received were small and marshy. Filling in the sea turned them into a city."],
    ["mumbai-seven-islands", "mumbai-2005-flood", "Land taken from the sea stays low. That is one reason water has nowhere to go in heavy rain."],
    ["mumbai-seven-islands", "mumbai-art-deco", "The Art Deco buildings of Marine Drive stand on land that was sea until the 1920s."],
    ["mumbai-locals", "dabbawalas", "The dabbawalas' whole system runs on the local train timetable."],
    ["mumbai-locals", "roman-roads", "Both are transport networks that decided where people lived and traded."],
    ["dabbawalas", "container-shipping", "Both move huge numbers of boxes cheaply, using a standard box and a simple code."],
    ["dabbawalas", "upi", "Both are simple shared systems that millions of people trust every day."],
    ["cotton-boom", "weimar-hyperinflation", "Both show how fast money can lose its value when the thing behind it changes."],
    ["cotton-boom", "bse-banyan", "The share craze of the cotton boom, and its crash, pushed brokers to form a proper exchange in 1875."],
    ["bse-banyan", "buffett-compounding", "A stock market lets ordinary savers own a share of growing companies for many years."],
    ["dharavi", "map-territory", "The word ‘slum’ is the map. The workshops and businesses are the real place."],
    ["mumbai-2005-flood", "margin-of-safety", "Mangroves and open land were the city's safety margin. Once they were built over, there was no buffer left."],
    ["mumbai-art-deco", "pantheon-dome", "Both are buildings that have outlived the people and powers that made them."],
    ["raja-harishchandra", "savitribai-phule", "In 1913 no woman would act in a film. The same beliefs had made girls' schooling a fight 65 years earlier."],
    ["mumbai-name", "india-languages", "Bombay State was split by language in 1960, and Mumbai became the capital of Marathi-speaking Maharashtra."],
    ["gateway-of-india", "east-india-company", "British rule began with a trading company and ended with soldiers marching out through the Gateway."],
    ["vada-pav", "bombay-dowry", "The Portuguese who once held Bombay also brought the bread, the potato and the chilli."],
    ["shivaji-forts", "thermopylae", "Both used narrow hill country to cancel the advantage of a much larger army."],
    ["shivaji-forts", "sun-tzu", "Shivaji Maharaj avoided big open battles and won by position, speed and surprise."],
    ["shivaji-forts", "deccan-traps", "The steep, flat-topped hills left by ancient lava were perfect places for forts."],
    ["shivaji-forts", "shivaji-agra", "The same way of thinking: avoid the enemy's strength and use their habits against them."],
    ["shivaji-navy", "shivaji-forts", "Hill forts guarded the land and sea forts guarded the coast. It was one idea in two places."],
    ["shivaji-navy", "russia-ports", "Both understood that a land power without safe ports is weak."],
    ["shivaji-navy", "hormuz", "Whoever controls the sea routes controls the trade."],
    ["panipat-1761", "roman-roads", "An army is only as strong as its supply line. Rome built roads for this. At Panipat the line was cut."],
    ["panipat-1761", "east-india-company", "The Maratha loss in the north left space for the Company to grow."],
    ["panipat-1761", "shivaji-forts", "Shivaji Maharaj fought close to home on ground he chose. At Panipat the Marathas fought far from home on open ground."],
    ["ajanta", "kailasa-temple", "Both were cut from the same hard volcanic rock, about 100 km apart."],
    ["ajanta", "wald-bombers", "We see only what survived. Ajanta's paintings lasted because the caves were forgotten."],
    ["kailasa-temple", "pantheon-dome", "Two different answers to one question: how do you make a huge stone building that lasts?"],
    ["kailasa-temple", "deccan-traps", "The temple could be carved from one rock because lava had left thick, even layers of basalt."],
    ["lonar-crater", "deccan-traps", "The meteorite hit the lava rock of the Deccan Traps. That is what makes Lonar so rare."],
    ["deccan-traps", "western-ghats-rain", "The Western Ghats are the high western edge of the Deccan lava layers."],
    ["deccan-traps", "india-plate", "The eruptions happened while India was still moving north towards Asia."],
    ["western-ghats-rain", "monsoon-economy", "The Ghats decide where the monsoon rain falls, and the rain decides the harvest."],
    ["western-ghats-rain", "mumbai-2005-flood", "The same hills that bring Mumbai its water also squeeze very heavy rain out over the coast."],
    ["savitribai-phule", "mahad-satyagraha", "Dr Ambedkar counted Jyotirao Phule among his teachers. The Phules' fight for schooling came before his fight for equal rights."],
    ["mahad-satyagraha", "salt-march", "Both broke an unfair rule with a simple, peaceful act: drinking water, and picking up salt."],
    ["mahad-satyagraha", "veil-ignorance", "Rawls asks what rules you would choose if you did not know your place in society. Ambedkar helped write such rules into the Constitution."],
    ["mahad-satyagraha", "india-election", "The Constitution that Dr Ambedkar helped write gave every adult one vote from the very first election."],
    ["zero-brahmagupta", "indus-valley", "Standard weights in the Indus cities, and later a standard way to write numbers: shared rules make trade and thinking easier."],
    ["indus-valley", "roman-roads", "Both show that shared standards, for bricks or for roads, hold a large region together."],
    ["indus-valley", "container-shipping", "Standard bricks 4,500 years ago and standard boxes in 1956 are the same idea."],
    ["ashoka-kalinga", "sun-tzu", "Sun Tzu said the best victory comes without fighting. Ashoka learned this after his most costly victory."],
    ["salt-march", "sun-tzu", "Gandhi beat an empire's law without a single weapon."],
    ["salt-march", "east-india-company", "The salt tax began under the Company. The march attacked one of its oldest ways of taking money."],
    ["monsoon-economy", "green-revolution", "Irrigation and new seeds made harvests depend a little less on the rain."],
    ["reforms-1991", "comparative-advantage", "Opening to trade let India do more of what it does best, such as software services."],
    ["reforms-1991", "bse-banyan", "After 1991 foreign investors could buy Indian shares, and the stock market grew many times over."],
    ["green-revolution", "amul-white-revolution", "First grain, then milk. Both used a fair, promised price to make farmers produce more."],
    ["amul-white-revolution", "hanoi-rats", "Both are about rewards. Amul paid farmers for good milk and got more milk. Hanoi paid for rat tails and got more rats."],
    ["upi", "amazon-flywheel", "More users bring more shops, and more shops bring more users."],
    ["upi", "container-shipping", "One shared standard that everyone can connect to."],
    ["upi", "india-election", "Both are systems built to work for a billion people, including the poorest."],
    ["isro-frugal", "ooda-loop", "ISRO learned from its 2019 crash and returned in four years. Learning fast can matter more than a big budget."],
    ["bombay-time", "mumbai-locals", "Railways are the reason a standard time was needed at all."],
    ["bombay-time", "map-territory", "The clock is the map. The sun is the real thing."]
  );
})();
