/* Wisdom from Warren Buffett and Charlie Munger, plus Munger's mental models.
   Same shape as data-assets.js. `pin` makes the feed and recommendations favour these. */
(function () {
  MV.DOMAINS.wisdom = "Buffett & Munger";
  MV.DOMAIN_COLORS.wisdom = "#58c08c";

  MV.MODELS.push(
    { id: "circle-of-competence", name: "Circle of competence", line: "Know what you truly understand, and stay inside that area. Knowing where the edge is matters more than how big the circle is.", ask: "Do I really understand this, or do I only think I do?", ex: "Buffett avoided internet stocks in 1999 because he could not judge them." },
    { id: "lollapalooza", name: "Lollapalooza effect", line: "When several forces push in the same direction at once, the result is far bigger than any one of them alone.", ask: "Are many pressures pushing the same way here?", ex: "At an auction, rivalry, a ticking clock and the crowd all push bids higher together." },
    { id: "man-with-a-hammer", name: "Man with a hammer", line: "If you know only one tool, you try to use it on every problem. Learn the big ideas of many subjects.", ask: "Am I using this idea because it fits, or because it is the only one I know?", ex: "A surgeon suggests surgery; a salesman suggests buying more." },
    { id: "social-proof", name: "Social proof", line: "We copy what other people do, most of all when we are unsure. The crowd can be wrong together.", ask: "Would I still do this if nobody else was doing it?", ex: "Everyone buys a rising share because everyone else is buying it." },
    { id: "commitment-consistency", name: "Commitment and consistency", line: "Once we say or choose something, we defend it and stop looking at new facts.", ask: "Am I holding this view only because I said it before?", ex: "Keeping a bad investment because you told friends it was a great buy." },
    { id: "availability-bias", name: "Availability bias", line: "We give too much weight to what comes to mind easily: recent, vivid or loud things.", ask: "What important fact here is quiet and easy to miss?", ex: "Fearing a plane crash more than the daily drive to work." },
    { id: "reciprocity", name: "Reciprocity", line: "When someone gives us something, we feel we must give back, often more than we got.", ask: "Is a small favour pushing me towards a big yes?", ex: "A free sample makes you buy the whole packet." },
    { id: "authority-bias", name: "Authority bias", line: "We follow people with titles and confidence, even when they are wrong.", ask: "Would I believe this if a stranger had said it?", ex: "A co-pilot stays silent while the captain makes a clear mistake." },
    { id: "mr-market", name: "Mr Market", line: "Think of the market as a moody partner who offers you a new price every day. You may ignore him or use him, but never let him guide you.", ask: "Is the price telling me something real, or is it just today's mood?", ex: "A good company's share falls 30% in a panic though its business is unchanged." },
    { id: "moat", name: "Economic moat", line: "A lasting advantage that protects a business from rivals, like the water around a castle.", ask: "What stops a rival from copying this and taking the customers?", ex: "A trusted brand, low costs, or a network that everyone already uses." }
  );

  const W = list => list.map(a => Object.assign({ domain: "wisdom", pin: true, story: null, jargon: [], mis: [] }, a));
  MV.ASSETS.push(...W([
  { id: "bm-partnership", type: "person", title: "Buffett and Munger", value: 4, cue: "great partnerships, or who these two men are",
    fact: "Warren Buffett, born in 1930 in Omaha, built Berkshire Hathaway into one of the largest companies in the world. His partner for over 60 years was Charlie Munger (1924 to 2023), a lawyer from the same town. They met in 1959.",
    why: "Buffett says Munger changed how he thought. Two people who disagree well can think better than one.",
    mech: "Buffett had learned to buy poor companies at very low prices. Munger pushed him to buy excellent companies and keep them for many years. Munger was also willing to say no to Buffett's ideas, so often that Buffett called him ‘the abominable no-man’.",
    models: ["compounding", "inversion"],
    q: "Who were Buffett and Munger, and what did Munger change?",
    a: "Buffett built Berkshire Hathaway. Munger, his partner for over 60 years after they met in 1959, pushed him from buying cheap poor companies to buying excellent companies and holding them.",
    chain: [["Buffett built Berkshire Hathaway", ["berkshire", "buffett", "omaha"]], ["Munger was his partner for over 60 years", ["munger", "partner", "60", "1959"]], ["Munger moved him from cheap to excellent companies", ["excellent", "quality", "wonderful", "cheap", "good compan"]], ["Munger often said no", ["no", "disagree", "challenge"]]],
    mcq: { q: "What was Munger's biggest effect on Buffett?", o: ["He pushed him to buy excellent companies, not just cheap ones", "He taught him to trade shares every day", "He gave him the money to start", "He told him to avoid the stock market"] },
    bring: "When partnerships come up: “Buffett says his best decisions came after Munger told him he was wrong.”",
    follow: "Who in your life is willing to tell you no?",
    deeper: "They said they never had a real fight in six decades. Munger's line for disagreements was that Buffett would see it his way in the end, because Buffett was smart and Munger was right." },

  { id: "bm-circle", type: "mental model", title: "Stay in your circle of competence", value: 5, cue: "investing tips, or being asked about things you don't know",
    fact: "Buffett says you do not need to be an expert on everything. You only need to judge well the things inside your ‘circle of competence’. The size of the circle is not very important. Knowing where its edge is, is vital.",
    why: "Most big mistakes happen when people act outside what they understand, while feeling sure of themselves.",
    mech: "Inside your circle you can tell a good chance from a bad one. Outside it you are guessing, and other people know more than you. So the skill is honesty: say ‘I don't know’ and pass. Buffett stayed out of internet shares in 1999, was laughed at, and was safe when they crashed.",
    models: ["circle-of-competence", "margin-of-safety"],
    q: "What is the circle of competence?",
    a: "The area you truly understand. Its size matters less than knowing its edge. Inside it you can judge well; outside it you are guessing, so you should pass.",
    chain: [["The area you truly understand", ["understand", "know well", "expert", "competence"]], ["Knowing the edge matters more than the size", ["edge", "boundar", "limit", "size"]], ["Outside it you are guessing", ["guess", "outside", "others know more"]], ["Say ‘I don't know’ and pass", ["don't know", "pass", "say no", "stay out", "avoid"]]],
    mcq: { q: "What matters most about your circle of competence?", o: ["Knowing where its edge is", "Making it as large as possible", "Hiding it from others", "Changing it every year"] },
    bring: "When someone asks for a hot tip: “I use Buffett's rule. If I don't understand it, I leave it.”",
    follow: "What is one thing you understand far better than most people?",
    deeper: "The idea is in Buffett's 1996 letter to shareholders. Munger added that you can slowly widen the circle by learning, but you must never fool yourself about where it ends." },

  { id: "bm-mr-market", type: "mental model", title: "Mr Market", value: 5, cue: "share prices jumping around, or market panic",
    fact: "Buffett's teacher Benjamin Graham told a story. Imagine a business partner called Mr Market. Every day he offers to buy your share or sell you his. Some days he is cheerful and names a high price. Some days he is afraid and names a low one.",
    why: "It turns scary price swings into something useful. The market is there to serve you, not to tell you what to think.",
    mech: "The business itself changes slowly. Mr Market's mood changes daily. If you know roughly what the business is worth, you can buy when he is afraid, sell when he is too cheerful, and ignore him the rest of the time.",
    models: ["mr-market", "margin-of-safety"],
    q: "Who is Mr Market and how should you treat him?",
    a: "He is a picture of the stock market: a moody partner who offers a new price every day. Use his prices when they suit you, and never let his mood decide what you think a business is worth.",
    chain: [["A moody partner who offers a price every day", ["moody", "mood", "every day", "partner", "daily"]], ["The business changes slowly, the price quickly", ["business", "slowly", "worth", "value"]], ["Buy when he is afraid, sell when he is too cheerful", ["afraid", "fear", "low price", "cheerful", "high price", "buy", "sell"]], ["He serves you; he does not guide you", ["serve", "ignore", "not guide", "not tell"]]],
    mcq: { q: "What is the lesson of the Mr Market story?", o: ["Use the market's prices, but do not let its mood guide you", "Always follow the market's mood", "Never buy shares at all", "Prices always show the true value"] },
    bring: "When the market falls and people panic: “That is just Mr Market in a bad mood. The companies are the same as last week.”",
    follow: "Have you ever sold something in fear and been sorry later?",
    deeper: "Graham told the story in The Intelligent Investor. Buffett retold it in his 1987 letter and has called that chapter the most important thing ever written about investing." },

  { id: "bm-moat", type: "business concept", title: "The castle and the moat", value: 5, cue: "why some companies stay strong, or brands you trust",
    fact: "Buffett looks for a business that is like a castle with a wide moat, the ditch of water that kept attackers out. The moat is a lasting advantage that rivals cannot easily copy.",
    why: "High profits attract rivals. Without a moat, they copy you and the profits vanish.",
    mech: "A moat can be a brand people trust, very low costs, a network everyone already uses, or the trouble of switching away. A business with a moat can raise prices a little each year and keep its customers. Buffett asks managers to widen the moat every year.",
    models: ["moat", "network-effects", "compounding"],
    q: "What does Buffett mean by a moat?",
    a: "A lasting advantage, such as a trusted brand, low costs or a network, that stops rivals from copying a business and taking its customers. It lets the business keep its profits for many years.",
    chain: [["A lasting advantage", ["lasting", "advantage", "durable", "long"]], ["Rivals cannot easily copy it", ["rival", "compet", "copy"]], ["Brand, low cost, network or switching trouble", ["brand", "low cost", "network", "switch"]], ["Profits are protected for years", ["profit", "protect", "raise price", "keep"]]],
    mcq: { q: "Which of these is a moat?", o: ["A brand that customers trust and will pay more for", "A high share price this year", "A large new office", "A big advertising budget alone"] },
    bring: "When a hot new company comes up: “The Buffett question is: what stops ten rivals from doing the same thing next year?”",
    follow: "Which Indian company do you think has the widest moat?",
    deeper: "Buffett's own test is pricing power: can the business raise its price without losing customers? If it must pray before raising prices by a little, it has no moat." },

  { id: "bm-rule-one", type: "insight", title: "Rule No. 1: never lose money", value: 4, cue: "risk, or chasing big returns",
    fact: "A rule that is widely credited to Buffett: “Rule No. 1: Never lose money. Rule No. 2: Never forget Rule No. 1.”",
    why: "He does not mean prices never fall. He means: do not take risks that can wipe you out. Losses hurt more than equal gains help.",
    mech: "The arithmetic is unfair. If you lose 50%, you then need a 100% gain just to get back to where you began. And compounding only works if you stay in the game. One big loss breaks the chain of many good years.",
    models: ["margin-of-safety", "compounding", "inversion"],
    q: "Why is ‘never lose money’ Buffett's first rule?",
    a: "A big loss is very hard to recover from: lose 50% and you need a 100% gain to get back. Compounding needs you to stay in the game, so avoiding big losses matters more than chasing big gains.",
    chain: [["Avoid losses that can wipe you out", ["wipe", "big loss", "ruin", "avoid loss"]], ["Lose 50%, need 100% to recover", ["50", "100", "double", "recover"]], ["Compounding needs you to stay in the game", ["compound", "stay in", "survive", "chain"]], ["Avoiding loss beats chasing gain", ["chasing", "more than", "first", "matters more"]]],
    mcq: { q: "If an investment falls 50%, how much must it rise to get back to the start?", o: ["100%", "50%", "25%", "75%"] },
    bring: "When someone is excited about a risky bet: “Lose half and you need to double just to get back. That is why Buffett's first rule is about not losing.”",
    follow: "What is one risk in your life that could wipe out years of work?",
    deeper: "Munger said the same thing in his own way: the first rule of compounding is never to interrupt it unnecessarily." },

  { id: "bm-fear-greed", type: "insight", title: "Be fearful when others are greedy", value: 5, cue: "market booms, crashes, or what everyone is buying",
    fact: "Buffett's advice on timing: be fearful when others are greedy, and greedy when others are fearful.",
    why: "The best prices come when everyone is afraid. The worst mistakes are made when everyone is sure prices can only go up.",
    mech: "When people are greedy, they pay too much and prices rise far above value. When they are afraid, they sell good things cheaply. A person who stays calm can do the opposite of the crowd. In October 2008, in the middle of the financial crisis, Buffett wrote that he was buying American shares.",
    models: ["social-proof", "mr-market", "second-order-thinking"],
    q: "What does ‘be fearful when others are greedy’ mean?",
    a: "When the crowd is greedy, prices are too high and you should be careful. When the crowd is afraid, good things are cheap and you should buy. Do the opposite of the crowd's mood.",
    chain: [["When the crowd is greedy, prices are too high", ["greedy", "too high", "expensive", "overpa"]], ["When the crowd is afraid, good things are cheap", ["afraid", "fear", "cheap", "panic"]], ["Do the opposite of the crowd", ["opposite", "against", "contrar"]], ["It needs calm", ["calm", "patien", "cash", "courage"]]],
    mcq: { q: "According to Buffett, when is the best time to buy?", o: ["When most people are afraid and selling", "When everyone is excited and buying", "When prices have risen for many years", "When friends give you a tip"] },
    bring: "When everyone is buying the same thing: “Buffett would get nervous now. He buys when people are scared, not when they are excited.”",
    follow: "What is everyone too excited about right now?",
    deeper: "He first wrote the line in his 1986 letter. It is simple to say and very hard to do, because acting against the crowd feels wrong in the moment." },

  { id: "bm-wonderful-company", type: "historical story", title: "A wonderful company at a fair price", value: 5, cue: "bargain hunting, or quality versus cheapness", story: "sees",
    fact: "In 1972 Buffett and Munger bought See's Candies, a chocolate maker, for 25 million dollars. It felt expensive to Buffett. It went on to earn about 2 billion dollars in profit. The lesson: it is far better to buy a wonderful company at a fair price than a fair company at a wonderful price.",
    why: "It changed Buffett from a hunter of cheap shares into a buyer of great businesses. Most of Berkshire's later success came from this change.",
    mech: "A cheap, poor business gives you one small gain and then trouble. A great business keeps growing for decades. See's had loyal customers, so it could raise its prices every year without needing much new money. Time is the friend of the wonderful business and the enemy of the poor one.",
    models: ["moat", "compounding", "opportunity-cost"],
    q: "What did See's Candies teach Buffett?",
    a: "That a wonderful company at a fair price beats a fair company at a cheap price. See's cost 25 million dollars in 1972 and earned about 2 billion, because loyal customers let it raise prices year after year.",
    chain: [["Bought See's Candies in 1972 for 25 million", ["see's", "sees", "1972", "25 million", "candy", "chocolate"]], ["It seemed expensive", ["expensive", "high price", "fair price", "not cheap"]], ["Loyal customers let it raise prices", ["loyal", "raise price", "brand", "customers"]], ["Great businesses keep growing for decades", ["decades", "grow", "time", "2 billion", "wonderful"]]],
    mcq: { q: "What is the lesson Buffett took from See's Candies?", o: ["Pay a fair price for a wonderful business", "Always buy the cheapest shares", "Never buy food companies", "Sell quickly after a small gain"] },
    bring: "When someone is hunting bargains: “Buffett's lesson from a chocolate company was: a great thing at a fair price beats a poor thing at a cheap price.”",
    follow: "Where in life have you bought cheap and been sorry?",
    deeper: "The sellers wanted 30 million dollars. Buffett would not go above 25 million and was ready to walk away. He later said he was lucky that they accepted." },

  { id: "bm-price-value", type: "insight", title: "Price is what you pay, value is what you get", value: 4, cue: "sales, discounts, or expensive things",
    fact: "Buffett often repeats a line he learned from Benjamin Graham: “Price is what you pay; value is what you get.”",
    why: "People mix up the two all the time. A high price does not prove something is good, and a low price does not prove it is a bargain.",
    mech: "Price is set each day by what buyers and sellers feel. Value comes from what the thing will give you over time: the cash a business earns, or the use you get from an object. You do well when you pay a price well below the value.",
    models: ["margin-of-safety", "map-vs-territory"],
    q: "What is the difference between price and value?",
    a: "Price is what you hand over today, set by the mood of buyers and sellers. Value is what you get over time. They are often different, and you do well when you pay much less than the value.",
    chain: [["Price is what you pay today", ["price", "pay", "today"]], ["Value is what you get over time", ["value", "get", "over time", "earn"]], ["They are often different", ["different", "not the same", "mix up"]], ["Pay well below value", ["below", "less than", "margin", "bargain"]]],
    mcq: { q: "A share's price doubles in a month. What has certainly changed?", o: ["Only the price; the value may be the same", "The value has doubled", "The company's profits have doubled", "The company has a new product"] },
    bring: "At a big sale: “Buffett's line fits here. Price is what you pay; value is what you get.”",
    follow: "What have you bought that was worth far more than its price?",
    deeper: "The line appears in Buffett's 2008 letter. He added that whether it is socks or shares, he likes buying quality goods when they are marked down." },

  { id: "bm-punch-card", type: "insight", title: "The 20-slot punch card", value: 4, cue: "too many choices, or acting too often",
    fact: "Buffett tells students to imagine a card with only 20 slots. Each investment decision you make in your whole life punches one slot. After 20, you are done.",
    why: "With so few chances, you would think very hard about each one, and you would do much better.",
    mech: "Most people make hundreds of small, hurried choices. A few big, careful choices usually give most of the results. A limit forces you to wait for the rare great chance, and then to act in a big way.",
    models: ["opportunity-cost", "circle-of-competence"],
    q: "What is the idea of the 20-slot punch card?",
    a: "Imagine you may make only 20 investment decisions in your life. You would think hard about each, wait for great chances, and act in a big way. A few careful choices beat many hurried ones.",
    chain: [["Only 20 decisions in a lifetime", ["20", "twenty", "slot", "lifetime"]], ["You would think hard about each", ["think hard", "careful", "think very"]], ["Wait for the rare great chance", ["wait", "rare", "great chance", "patien"]], ["A few careful choices beat many hurried ones", ["few", "many", "hurried", "big way"]]],
    mcq: { q: "What is the point of the punch-card idea?", o: ["Make few decisions, and make each one carefully", "Make at least 20 trades every year", "Never invest more than 20 rupees", "Change your mind 20 times"] },
    bring: "When someone trades shares every week: “Buffett says imagine you only get 20 decisions in your whole life.”",
    follow: "If you had only five big career decisions, how would you use them?",
    deeper: "Munger agreed: a few big, well-chosen bets made Berkshire. He said the wise bet heavily when the world offers them the chance, and the rest of the time they do nothing." },

  { id: "bm-inner-scorecard", type: "insight", title: "The inner scorecard", value: 5, cue: "what other people think, status or showing off",
    fact: "Buffett says the big question in life is whether you live by an inner scorecard or an outer one. He asks: would you rather be the best at something while the world thinks you are the worst, or be the worst while the world thinks you are the best?",
    why: "If you judge yourself by other people's praise, they control you. If you judge yourself by your own standards, you are free to do what is right.",
    mech: "An outer scorecard pushes you to copy the crowd and to look good. An inner scorecard lets you make unpopular choices that are correct. Buffett was called out of date for avoiding internet shares in 1999. He did not mind, because his own score said he was right.",
    models: ["social-proof", "circle-of-competence"],
    q: "What is the inner scorecard?",
    a: "Judging yourself by your own standards and not by what others think. It frees you to make correct choices that are unpopular, where an outer scorecard makes you copy the crowd.",
    chain: [["Judge yourself by your own standards", ["own standard", "yourself", "inner"]], ["Not by what others think", ["others think", "praise", "outer", "opinion"]], ["It lets you make unpopular but correct choices", ["unpopular", "correct", "right", "free"]], ["The outer scorecard makes you copy the crowd", ["crowd", "copy", "look good"]]],
    mcq: { q: "A person with an inner scorecard cares most about…", o: ["Meeting their own standards", "Being praised by others", "Having more than the neighbours", "Being famous"] },
    bring: "When status or showing off comes up: “Buffett asks: would you rather be good and thought bad, or bad and thought good?”",
    follow: "How would you answer Buffett's question honestly?",
    deeper: "Buffett says he learned it from his father, Howard, who did what he believed was right even when it made him unpopular. The idea is told in his biography, The Snowball." },

  { id: "bm-reputation", type: "insight", title: "Twenty years to build, five minutes to ruin", value: 4, cue: "trust, scandals or short cuts",
    fact: "Buffett says it takes 20 years to build a reputation and five minutes to ruin it. If you think about that, you will do things differently.",
    why: "Trust is worth more than any single profit, and it is the easiest thing to lose.",
    mech: "People deal with you on easy terms when they trust you: no long checks, a quick yes. One dishonest act ends that for years. In 1991, when the bank Salomon Brothers was caught cheating, Buffett took charge and told staff: lose money for the firm and I will be understanding; lose a shred of reputation and I will be ruthless.",
    models: ["second-order-thinking", "compounding"],
    q: "Why does Buffett guard reputation so strongly?",
    a: "Trust takes many years to build and can be lost in minutes. With trust, people deal with you quickly and easily. One dishonest act destroys that, so no single profit is worth the risk.",
    chain: [["Many years to build", ["20 years", "years to build", "slow"]], ["Minutes to ruin", ["five minutes", "minutes", "quick", "ruin", "lost"]], ["Trust makes dealing easy", ["trust", "easy", "quick yes"]], ["No profit is worth the risk", ["no profit", "not worth", "money"]]],
    mcq: { q: "What did Buffett tell Salomon staff he would be ruthless about?", o: ["Losing any of the firm's reputation", "Losing money on a trade", "Coming late to work", "Asking for a pay rise"] },
    bring: "When a short cut is tempting: “Buffett's test is simple. Would I be happy to see this on the front page of tomorrow's paper?”",
    follow: "Whose reputation do you trust without checking, and why?",
    deeper: "His newspaper test: do nothing you would not want reported on the front page of your local paper, written by a clever and unfriendly reporter, for your family to read." },

  { id: "bm-tide", type: "insight", title: "When the tide goes out", value: 4, cue: "booms, easy money or hidden risk",
    fact: "Buffett's line about hidden risk: “Only when the tide goes out do you discover who's been swimming naked.”",
    why: "In good times, careful and careless people look the same. You only see the difference when times turn bad.",
    mech: "When money is easy and prices rise, borrowed money and weak plans go unpunished. Everyone looks clever. When the good times stop, those who took hidden risks are suddenly exposed. So do not judge by results in a boom, and do not copy people only because they are winning now.",
    models: ["survivorship-bias", "margin-of-safety"],
    q: "What does ‘when the tide goes out’ mean?",
    a: "Good times hide risk, so careless and careful people look alike. When times turn bad, those who took hidden risks, such as heavy borrowing, are exposed. Do not judge by results in a boom.",
    chain: [["Good times hide risk", ["good times", "boom", "hide", "rising"]], ["Careless and careful look alike", ["alike", "same", "everyone looks"]], ["Bad times expose hidden risks", ["bad times", "expose", "tide goes out", "crash"]], ["Do not judge by results in a boom", ["judge", "results", "copy"]]],
    mcq: { q: "What is the ‘tide’ in Buffett's saying?", o: ["Good times and easy money", "The sea near Omaha", "A company's share price", "A new law"] },
    bring: "When someone boasts of easy profits in a boom: “As Buffett says, we will know who was swimming naked when the tide goes out.”",
    follow: "What risk around us is hidden only because times are good?",
    deeper: "He wrote it in his 2001 letter, about insurance companies that had taken on too much risk in the easy years." },

  { id: "bm-berkshire-mistake", type: "historical story", title: "Buffett's 200-billion-dollar mistake", value: 5, cue: "decisions made in anger, or famous mistakes", story: "berkshire",
    fact: "Berkshire Hathaway was a failing cloth mill. In 1964 its boss agreed to buy back Buffett's shares at 11.50 dollars, then sent an offer of 11.375. Angry at being cheated of an eighth of a dollar, Buffett bought control of the company in 1965, and the boss left. He later called buying Berkshire his biggest mistake.",
    why: "Even the best investor in the world made a huge decision out of anger. And a bad start did not stop a great result.",
    mech: "For 20 years good money went into a dying cloth business. Buffett has estimated that if he had put that money straight into insurance companies, the result would have been about 200 billion dollars higher. He closed the mills in 1985.",
    models: ["opportunity-cost", "commitment-consistency", "inversion"],
    q: "Why does Buffett call buying Berkshire Hathaway a mistake?",
    a: "He bought control of a dying cloth mill in 1965 out of anger over an eighth of a dollar. Money stayed stuck in a poor business for 20 years. He estimates this cost about 200 billion dollars compared with investing it better.",
    chain: [["A failing cloth mill", ["cloth", "textile", "mill", "failing", "dying"]], ["He bought control in anger over an eighth of a dollar", ["anger", "angry", "eighth", "11", "cheated"]], ["Money stayed stuck in a poor business", ["stuck", "poor business", "20 years", "good money"]], ["It cost about 200 billion dollars", ["200 billion", "cost", "better"]]],
    mcq: { q: "Why did Buffett take control of Berkshire Hathaway in 1965?", o: ["He was angry that its boss lowered an agreed price slightly", "He loved the cloth business", "The government asked him to", "Munger told him to buy it"] },
    bring: "When someone decides in anger: “Buffett bought Berkshire Hathaway out of spite over a few cents. He says it cost him 200 billion dollars.”",
    follow: "What decision have you made mainly to prove a point?",
    deeper: "The lesson he drew: when a business is poor, a good manager cannot save it. In his words, when you find yourself in a boat that keeps leaking, changing boats is better than patching leaks." },

  { id: "bm-latticework", type: "mental model", title: "Munger's latticework of mental models", value: 5, cue: "how to think better, or what to study",
    fact: "Charlie Munger said you cannot be wise by remembering separate facts. You need the big ideas from many subjects, and they must hang together on a ‘latticework’, a frame, in your head. He said about 80 or 90 models do most of the work.",
    why: "Real problems do not stay inside one subject. A person with many models sees what a specialist misses.",
    mech: "Take the main ideas from maths, physics, biology, psychology, economics and history. For example: compounding, breaking points, evolution, incentives, opportunity cost. Use them together, as a checklist. If two or three models point the same way, you can be much more sure.",
    models: ["man-with-a-hammer", "first-principles", "lollapalooza"],
    q: "What is Munger's latticework of mental models?",
    a: "A frame in your head holding the big ideas from many subjects, used together like a checklist. About 80 or 90 models do most of the work, and they help you see what a one-subject expert misses.",
    chain: [["Big ideas from many subjects", ["many subjects", "discipline", "big ideas", "different fields"]], ["Held together on a frame", ["frame", "lattice", "together", "connect"]], ["About 80 or 90 models do most of the work", ["80", "90"]], ["Used together like a checklist", ["checklist", "use them together", "several models"]]],
    mcq: { q: "Why did Munger want models from many subjects?", o: ["Real problems cross subjects, so one tool is not enough", "To pass more examinations", "Because each subject has only one idea", "To sound clever at parties"] },
    bring: "When study or careers come up: “Munger's advice was to learn the few big ideas from every subject, not everything from one.”",
    follow: "Which idea from one subject has helped you most in another?",
    deeper: "He set this out in a 1994 talk at the University of Southern California called ‘A Lesson on Elementary Worldly Wisdom’. This app's Mental models page is built on the same idea." },

  { id: "bm-invert", type: "mental model", title: "Invert, always invert", value: 5, cue: "hard problems, goals or avoiding failure",
    fact: "Munger loved a rule from the mathematician Carl Jacobi: “Invert, always invert.” Turn the problem upside down. He joked: all I want to know is where I am going to die, so that I will never go there.",
    why: "It is often easier to see what will cause failure than what will cause success. Avoiding the big mistakes gets you most of the way.",
    mech: "Do not only ask ‘how do I succeed?’ Ask ‘what would make this fail for sure?’ and then avoid those things. To have a good life, list what ruins lives: debt, envy, laziness, being unreliable. Then stay away from them.",
    models: ["inversion", "margin-of-safety"],
    q: "What does ‘invert, always invert’ mean?",
    a: "Turn the problem upside down. Ask what would surely cause failure, then avoid those things. It is often easier to see and avoid big mistakes than to find the perfect path.",
    chain: [["Turn the problem upside down", ["upside down", "backward", "reverse", "invert"]], ["Ask what would cause failure", ["fail", "ruin", "go wrong"]], ["Then avoid those things", ["avoid", "stay away", "never go"]], ["Easier than finding the perfect path", ["easier", "perfect", "mistake"]]],
    mcq: { q: "How would Munger approach ‘how do I have a happy marriage?’", o: ["Ask what ruins marriages, and avoid those things", "Copy a famous couple", "Read only success stories", "Wait and see what happens"] },
    bring: "When planning something big: “Munger would ask it backwards. What would make this fail for sure? Then we avoid that.”",
    follow: "What would guarantee failure in your current project?",
    deeper: "In a 1986 school speech Munger did exactly this. He gave the students a list of sure ways to have a miserable life, such as being unreliable and refusing to learn from other people's mistakes." },

  { id: "bm-incentives", type: "mental model", title: "Show me the incentive", value: 5, cue: "why people behave as they do at work",
    fact: "Munger said: “Show me the incentive and I'll show you the outcome.” He added that he had been in the top few per cent of his age group in understanding the power of incentives all his life, and all his life he had underestimated it.",
    why: "If you want to know what people will do, do not listen to what they say. Look at what they are rewarded for.",
    mech: "His favourite example is the courier company FedEx. Its night workers were paid by the hour and the packages were always late. The company changed to paying per shift, and let workers go home when the work was done. The delay vanished.",
    models: ["incentives", "goodharts-law"],
    q: "What is Munger's lesson about incentives?",
    a: "People do what they are rewarded for, so look at the reward, not the words. FedEx fixed late night shifts by paying per shift, not per hour, so workers gained by finishing fast.",
    chain: [["People do what they are rewarded for", ["reward", "paid", "incentive"]], ["Look at rewards, not words", ["not what they say", "not the words", "look at"]], ["FedEx paid per shift, not per hour", ["fedex", "per shift", "hour"]], ["The delay vanished", ["delay", "late", "faster", "finish"]]],
    mcq: { q: "How did FedEx fix its slow night shift?", o: ["It paid per shift and let workers leave when done", "It hired twice as many workers", "It fined the slowest workers", "It bought faster planes"] },
    bring: "When a team is behaving strangely: “Munger's first question would be: what are they being paid to do?”",
    follow: "What are you rewarded for at work that is different from what your company says it wants?",
    deeper: "Munger also warned about ‘incentive-caused bias’: a person paid to believe something will come to believe it honestly. So be careful with advice from anyone who gains if you take it." },

  { id: "bm-lollapalooza", type: "mental model", title: "The lollapalooza effect", value: 4, cue: "crazes, auctions, cults or sudden success",
    fact: "Munger's word for an extreme result is ‘lollapalooza’. It happens when several forces of human psychology push in the same direction at the same time.",
    why: "Single causes rarely explain very big events. Looking for causes that combine helps you understand booms, crazes and big failures.",
    mech: "One push has a small effect. Three or four together do not just add up; they multiply. At an open auction you feel rivalry, see others bidding, have little time, and have already said a number aloud. Together these make people pay far too much.",
    models: ["lollapalooza", "social-proof", "commitment-consistency"],
    q: "What is the lollapalooza effect?",
    a: "An extreme result that comes when several psychological forces push the same way at once. They multiply, not just add. An auction combines rivalry, the crowd, time pressure and your own earlier bids.",
    chain: [["Several forces at once", ["several", "many forces", "at once", "same time", "combine"]], ["All pushing the same way", ["same way", "same direction"]], ["They multiply, not just add", ["multiply", "not just add", "far bigger"]], ["Example: an auction", ["auction", "rivalry", "crowd", "time pressure"]]],
    mcq: { q: "A lollapalooza effect needs…", o: ["Several forces pushing the same way together", "One very strong cause", "A large amount of money", "A long period of time"] },
    bring: "When a craze comes up: “Munger called this a lollapalooza: the crowd, the fear of missing out and easy money all pushing one way.”",
    follow: "What forces were pushing together in the last craze you saw?",
    deeper: "It works for good things too. Munger explained Coca-Cola's success as many forces together: taste, habit, being for sale everywhere, and seeing everyone else drink it." },

  { id: "bm-hammer", type: "mental model", title: "The man with a hammer", value: 4, cue: "experts, or one answer to every problem",
    fact: "Munger often quoted the old saying: to a man with only a hammer, every problem looks like a nail.",
    why: "Experts tend to see every problem through their own subject. It makes clever people give bad advice with full confidence.",
    mech: "If you have only one tool, your mind bends each problem to fit it. A person with many tools can pick the right one. Munger's cure was to learn the big ideas of many subjects and run through them like a pilot's checklist.",
    models: ["man-with-a-hammer", "confirmation-bias"],
    q: "What is the ‘man with a hammer’ problem?",
    a: "A person who knows only one tool or subject tries to use it on every problem, so experts can give confident bad advice. The cure is to learn the big ideas of many subjects and check them one by one.",
    chain: [["Only one tool", ["one tool", "only a hammer", "one subject", "single"]], ["Every problem looks like a nail", ["nail", "every problem", "bends", "fit"]], ["Experts give confident bad advice", ["expert", "confiden", "bad advice"]], ["Cure: many models, used as a checklist", ["many", "checklist", "big ideas"]]],
    mcq: { q: "What is Munger's cure for the man-with-a-hammer problem?", o: ["Learn the main ideas of many subjects", "Buy a better hammer", "Trust only one expert", "Avoid making decisions"] },
    bring: "When an expert has the same answer for everything: “To a man with a hammer, everything looks like a nail.”",
    follow: "What is your own hammer, the idea you use too often?",
    deeper: "The saying is often linked to the psychologist Abraham Maslow. Munger made it famous among investors." },

  { id: "bm-misjudgment", type: "psychological concept", title: "The psychology of human misjudgment", value: 5, cue: "why smart people do foolish things",
    fact: "In a famous talk, Munger listed 25 standard ways the human mind goes wrong. They include copying the crowd (social proof), sticking to what we said before (consistency), trusting authority, returning favours, and hating to lose what we have.",
    why: "These are not rare faults. They work in everyone, every day. Knowing the list helps you catch them in yourself and see when others are using them on you.",
    mech: "The mind uses short cuts to decide fast. Mostly they work. But sellers, bosses and crowds can trigger them, and several together are very strong. Munger used the list as a checklist before any big decision.",
    models: ["social-proof", "commitment-consistency", "authority-bias", "reciprocity", "availability-bias"],
    q: "What is Munger's ‘psychology of human misjudgment’?",
    a: "A list of 25 common ways the mind goes wrong, such as copying the crowd, sticking to earlier views, trusting authority and returning favours. He used it as a checklist before big decisions.",
    chain: [["A list of 25 ways the mind goes wrong", ["25", "list", "ways the mind", "tendenc"]], ["Copying the crowd", ["crowd", "social proof", "copy"]], ["Sticking to earlier views; trusting authority", ["earlier", "consisten", "authority", "favour", "said before"]], ["Used as a checklist before big decisions", ["checklist", "before", "decision"]]],
    mcq: { q: "Which of these is on Munger's list of mind errors?", o: ["Copying what the crowd does", "Reading too many books", "Saving too much money", "Sleeping too little"] },
    bring: "When a clever person does something foolish: “Munger had a list of 25 ways the mind fools itself. This looks like one of them.”",
    follow: "Which of these traps do you fall into most often?",
    deeper: "He first gave the talk at Harvard in 1995 and rewrote it in 2005 for the book Poor Charlie's Almanack. Much of it builds on Robert Cialdini's book Influence." },

  { id: "bm-not-stupid", type: "insight", title: "Try to be not stupid", value: 5, cue: "being clever, or avoiding mistakes",
    fact: "Munger said it is remarkable how much long-term advantage he and Buffett got by trying to be consistently not stupid, instead of trying to be very intelligent.",
    why: "You do not need to be a genius. You need to avoid the big, common errors that genius people also make.",
    mech: "In many games, most points are lost through mistakes, not won through brilliant moves. So the steady player who avoids errors beats the clever player who takes wild chances. Staying out of debt trouble, staying inside what you understand, and not acting in a hurry cover most of it.",
    models: ["inversion", "circle-of-competence", "margin-of-safety"],
    q: "What does Munger mean by ‘consistently not stupid’?",
    a: "Long-term success comes more from steadily avoiding big, common mistakes than from brilliant moves. Stay out of debt trouble, stay inside what you understand, and do not act in a hurry.",
    chain: [["Avoid big, common mistakes", ["avoid", "mistake", "error"]], ["More than brilliant moves", ["brilliant", "clever", "intelligent", "genius"]], ["Steadily, over a long time", ["steadily", "consistent", "long-term", "long time"]], ["Debt, understanding, hurry", ["debt", "understand", "hurry"]]],
    mcq: { q: "According to Munger, what gave him and Buffett a long-term advantage?", o: ["Steadily avoiding stupid mistakes", "Being cleverer than everyone", "Trading faster than others", "Secret information"] },
    bring: "When people praise genius: “Munger said they won mostly by trying to be not stupid, rather than trying to be very clever.”",
    follow: "What is one stupid mistake you could simply stop making?",
    deeper: "This is inversion used on a whole career. Amateur tennis works the same way: most points are lost by errors, so the player who just keeps the ball in play usually wins." },

  { id: "bm-patience", type: "insight", title: "The big money is in the waiting", value: 5, cue: "patience, or the urge to do something",
    fact: "Munger said the big money is not in the buying or the selling, but in the waiting. Buffett put it this way: our favourite holding period is forever.",
    why: "Most people feel they must act. Doing nothing, when nothing needs doing, is a rare and valuable skill.",
    mech: "Compounding needs time, and every time you sell you stop it and pay costs and tax. A great business does the work for you if you leave it alone. Berkshire has held its Coca-Cola shares since 1988.",
    models: ["compounding", "opportunity-cost"],
    q: "Why do Buffett and Munger praise waiting?",
    a: "Compounding needs time, and each sale stops it and adds costs and tax. A great business grows by itself if you leave it alone, so the hard and valuable skill is to do nothing.",
    chain: [["Compounding needs time", ["compound", "time", "years"]], ["Selling stops it and adds costs and tax", ["sell", "cost", "tax", "stop"]], ["A great business grows if left alone", ["great business", "left alone", "leave it", "grows"]], ["Doing nothing is a skill", ["nothing", "wait", "patien"]]],
    mcq: { q: "Where did Munger say the big money is made?", o: ["In the waiting", "In the buying", "In the selling", "In the borrowing"] },
    bring: "When someone wants to sell after a small gain: “Munger said the big money is in the waiting.”",
    follow: "What in your life would grow best if you just left it alone?",
    deeper: "Buffett compared it to baseball with no called strikes. You can stand at the plate all day and swing only at the one ball you really like." },

  { id: "bm-deserve", type: "insight", title: "Deserve what you want", value: 4, cue: "ambition, careers or fairness",
    fact: "Munger's advice to young people: the safest way to try to get what you want is to try to deserve what you want.",
    why: "It moves your attention from tricks and luck to the one thing you control: being worth choosing.",
    mech: "He called it the golden rule turned around. Deliver to the world what you would buy if you were on the other side. People who are reliable and give real value are trusted with more and more over the years, and that trust compounds.",
    models: ["compounding", "incentives"],
    q: "What does Munger mean by ‘deserve what you want’?",
    a: "The safest way to get something is to be worth it: give others what you would want if you were in their place. Being reliable and useful builds trust, and trust compounds over the years.",
    chain: [["Be worth what you want", ["worth", "deserve", "earn"]], ["Give what you would want in their place", ["their place", "other side", "would want", "would buy"]], ["Be reliable and useful", ["reliable", "useful", "value"]], ["Trust compounds over the years", ["trust", "compound", "years"]]],
    mcq: { q: "What did Munger call the safest way to get what you want?", o: ["Try to deserve it", "Ask for it loudly", "Wait for good luck", "Take it before others do"] },
    bring: "When a young person asks for career advice: “Munger's rule was: to get what you want, deserve what you want.”",
    follow: "What would you have to become to deserve the thing you want most?",
    deeper: "He said this in his 2007 speech to law graduates at the University of Southern California. He also told them to keep learning every day: go to bed a little wiser than you woke up." },

  { id: "bm-other-side", type: "insight", title: "Know the other side's argument", value: 5, cue: "arguments, politics or strong opinions",
    fact: "Munger said he never let himself hold an opinion on anything unless he knew the other side's argument better than they did.",
    why: "It is easy to feel sure when you have heard only your own side. This rule makes you earn your opinions.",
    mech: "We naturally look for facts that agree with us. To fight that, state the opposite view so well that its own supporters would nod. If you cannot, you do not yet understand the question. If you can and still disagree, your view is far stronger.",
    models: ["confirmation-bias", "inversion"],
    q: "What is Munger's rule for holding an opinion?",
    a: "Hold an opinion only if you can state the other side's argument better than they can. It fights our habit of seeking facts that agree with us, and it makes the views you keep much stronger.",
    chain: [["State the other side better than they can", ["other side", "better than", "opposite view", "their argument"]], ["We seek facts that agree with us", ["agree with us", "confirm", "only your own side"]], ["If you cannot, you do not understand it yet", ["cannot", "do not understand", "don't understand"]], ["Views that pass are stronger", ["stronger", "earn"]]],
    mcq: { q: "Before holding an opinion, Munger required himself to…", o: ["Know the opposing argument better than its supporters", "Check that his friends agreed", "Read one book on the subject", "Wait for one year"] },
    bring: "In a heated argument: “Munger's rule: I should not have an opinion until I can argue your side better than you can. Let me try.”",
    follow: "On what topic could you not explain the other side fairly?",
    deeper: "He praised Charles Darwin for the same habit. Darwin wrote down every fact that went against his ideas at once, because he knew the mind forgets unwelcome facts quickly." },

  { id: "bm-envy", type: "insight", title: "Envy, not greed", value: 4, cue: "comparing yourself with others, salaries or neighbours",
    fact: "Munger said the world is not driven by greed. It is driven by envy. He called envy the one sin you can never have any fun with.",
    why: "People who have plenty still feel poor when a neighbour has more. Envy makes people take foolish risks to keep up.",
    mech: "We judge our lives by comparing, not by what we really need. So a rise in someone else's pay can make you unhappy with your own. In investing, watching a neighbour get rich faster pushes people into risks they do not understand.",
    models: ["social-proof", "opportunity-cost"],
    q: "Why did Munger say envy drives the world?",
    a: "People judge themselves by comparing with others, not by what they need. So even people with plenty feel poor and take foolish risks to keep up. Envy also gives no pleasure at all.",
    chain: [["We compare ourselves with others", ["compar", "neighbour", "neighbor", "others have"]], ["Not by what we need", ["need", "plenty", "enough"]], ["It leads to foolish risks", ["risk", "keep up", "foolish"]], ["Envy gives no pleasure", ["no fun", "no pleasure", "unhappy"]]],
    mcq: { q: "According to Munger, what drives people more than greed?", o: ["Envy", "Fear", "Laziness", "Curiosity"] },
    bring: "When people compare salaries or flats: “Munger said envy is the only sin that is no fun at all.”",
    follow: "Who do you compare yourself with, and does it help you?",
    deeper: "His cure was simple: stop comparing. Someone will always be getting richer faster than you, and he said that is not a tragedy." },

  { id: "bm-read", type: "insight", title: "Wise people read all the time", value: 4, cue: "reading habits or how to get smarter",
    fact: "Munger said that in his whole life he had known no wise people who did not read all the time. None, zero. Buffett spends most of his working day reading.",
    why: "Reading is the cheapest way to borrow the experience of the best minds, living and dead.",
    mech: "Knowledge builds up like compound interest. Each thing you learn makes the next thing easier to understand and to connect. A little every day, kept up for decades, makes a very large difference.",
    models: ["compounding", "man-with-a-hammer"],
    q: "Why do Buffett and Munger read so much?",
    a: "Reading lets you learn from the best minds cheaply. Knowledge builds like compound interest: each thing learned makes the next easier, so a little every day adds up hugely over decades.",
    chain: [["They read for hours every day", ["read", "every day", "hours", "all the time"]], ["Learn from the best minds", ["best minds", "experience", "borrow", "learn from"]], ["Knowledge builds like compound interest", ["compound", "builds", "adds up"]], ["Each thing learned makes the next easier", ["next", "easier", "connect"]]],
    mcq: { q: "What did Munger say about wise people?", o: ["All the ones he knew read all the time", "They avoid books and trust experience", "They are born wise", "They only read newspapers"] },
    bring: "When reading comes up: “Munger said he never met a wise person who did not read all the time.”",
    follow: "What is the best book you have read in the last year?",
    deeper: "Munger's children called him ‘a book with legs sticking out’. His goal each day was to go to bed a little wiser than he woke up." }
  ]));

  MV.STORIES.push(
  { id: "sees", assetId: "bm-wonderful-company", title: "The Chocolate Lesson",
    hook: "A box of chocolates taught Warren Buffett the most valuable lesson of his career.",
    setting: "California, 1972. See's Candies, a much-loved chocolate maker, is for sale.",
    character: "Warren Buffett, who had always hunted for cheap shares, and Charlie Munger, who believed in paying for quality.",
    conflict: "The owners wanted 30 million dollars. To Buffett this looked expensive. He would not pay more than 25 million and was ready to walk away.",
    surprise: "The sellers accepted 25 million. Then See's did something cheap companies never did: it raised its prices a little every year, and customers kept buying.",
    turning: "Buffett saw that a loved brand needs very little new money and keeps growing. A wonderful company at a fair price beats a fair company at a wonderful price.",
    payoff: "See's went on to earn about 2 billion dollars, and the idea led him to buy companies like Coca-Cola.",
    meaning: "Quality is worth paying for. Time helps a great business and hurts a poor one.",
    extra: ["Munger and his friends had pushed Buffett to raise his offer.", "Buffett later said that if the sellers had asked for a little more, he would have missed it.", "The money See's earned was used to buy other good businesses."],
    facts: [["1972"], ["see's", "sees", "chocolate", "candy"], ["25 million"], ["munger"], ["raise", "prices"], ["wonderful", "quality", "fair price"]],
    vocab: ["quality", "brand", "bargain"] },
  { id: "berkshire", assetId: "bm-berkshire-mistake", title: "The Most Expensive Eighth of a Dollar",
    hook: "Warren Buffett says his biggest mistake was buying Berkshire Hathaway, and he did it because he was angry.",
    setting: "New England, 1964. Berkshire Hathaway is a cloth mill that is slowly dying. Buffett owns some of its shares because they are cheap.",
    character: "Warren Buffett, a young investor, and Seabury Stanton, the mill's boss.",
    conflict: "Stanton agreed to buy Buffett's shares back at 11.50 dollars each. Then the written offer came at 11.375, an eighth of a dollar less.",
    surprise: "Buffett felt cheated. He did not sell. He bought more and more shares until he controlled the company in 1965. Stanton left.",
    turning: "Now he owned a failing cloth business. For 20 years he kept putting money and effort into it before he closed the mills in 1985.",
    payoff: "He estimates that the mistake cost about 200 billion dollars, compared with putting the money into good businesses from the start.",
    meaning: "Decisions made in anger are expensive. And when a business is poor, it is better to change boats than to keep patching leaks.",
    extra: ["Berkshire's name stayed, though nothing of the cloth business is left.", "Buffett used the company as the base for buying insurance firms and much more.", "He tells the story openly so that others can learn from it."],
    facts: [["1964", "1965"], ["cloth", "textile", "mill"], ["eighth", "11"], ["angry", "anger", "cheated"], ["stanton", "boss"], ["200 billion"], ["mistake"]],
    vocab: ["spite", "control", "mistake"] });

  MV.LINKS.push(
    ["bm-partnership", "buffett-compounding", "Buffett's wealth came from decades of compounding. Munger helped him pick businesses worth holding that long."],
    ["bm-partnership", "bm-wonderful-company", "See's Candies was the deal where Munger's thinking changed Buffett's."],
    ["bm-circle", "shivaji-forts", "Shivaji Maharaj fought only on ground he knew. That is a circle of competence in war."],
    ["bm-circle", "bm-not-stupid", "Staying inside what you understand is the simplest way to avoid stupid mistakes."],
    ["bm-circle", "panipat-1761", "At Panipat the Marathas fought far outside the ground they knew, and paid for it."],
    ["bm-mr-market", "bse-banyan", "The stock exchange is where Mr Market shouts his prices every day."],
    ["bm-mr-market", "margin-of-safety", "Both come from Benjamin Graham: know the value, then buy only when Mr Market offers a price well below it."],
    ["bm-mr-market", "bm-fear-greed", "Mr Market's moods are the fear and greed that Buffett tells us to act against."],
    ["bm-moat", "amazon-flywheel", "Amazon's flywheel keeps making its moat wider: lower costs, more sellers, more customers."],
    ["bm-moat", "upi", "A network that everyone already uses is one of the strongest moats."],
    ["bm-moat", "shivaji-navy", "Sea forts like Sindhudurg were real moats. Buffett borrowed the picture for business."],
    ["bm-moat", "amul-white-revolution", "Amul's trusted brand and its huge network of farmers are a moat that rivals cannot copy quickly."],
    ["bm-rule-one", "loss-aversion", "We hate losses by nature. Buffett's rule gives that feeling a sound reason: big losses are very hard to recover from."],
    ["bm-rule-one", "margin-of-safety", "A margin of safety is how you obey Rule No. 1."],
    ["bm-fear-greed", "cotton-boom", "In the Bombay cotton boom everyone was greedy together. The careful ones were the few who were fearful."],
    ["bm-tide", "cotton-boom", "When the American war ended, the tide went out in Bombay and showed which banks had nothing behind them."],
    ["bm-tide", "wald-bombers", "In a boom we see only the winners. The risks that sank others stay hidden until the tide goes out."],
    ["bm-wonderful-company", "bm-moat", "See's Candies had a moat: customers who loved the brand and accepted higher prices."],
    ["bm-price-value", "anchoring", "A price tag anchors our idea of what a thing is worth. Value has to be worked out separately."],
    ["bm-price-value", "map-territory", "Price is the map. Value is the real thing."],
    ["bm-punch-card", "bm-patience", "Few decisions and long waiting are two sides of the same habit."],
    ["bm-inner-scorecard", "stoic-control", "The Stoics said: mind what you control, not other people's opinions. That is the inner scorecard."],
    ["bm-inner-scorecard", "bm-envy", "Envy comes from keeping score against other people. The inner scorecard ends it."],
    ["bm-reputation", "dabbawalas", "The dabbawalas' whole business rests on a reputation for never failing, built over more than a century."],
    ["bm-berkshire-mistake", "comparative-advantage", "The real cost was the opportunity cost: what the same money could have earned somewhere better."],
    ["bm-berkshire-mistake", "bm-invert", "Buffett studies his own mistakes so that he knows where not to go again."],
    ["bm-latticework", "bm-hammer", "The latticework is the cure for the man with a hammer: many tools, not one."],
    ["bm-latticework", "zero-brahmagupta", "A big idea from one field, like zero in maths, changes what is possible in every other field."],
    ["bm-invert", "wald-bombers", "Wald inverted the question. He did not ask where the planes were hit, but where the missing planes must have been hit."],
    ["bm-invert", "isro-frugal", "ISRO designed Chandrayaan-3 by first listing every way the landing could fail."],
    ["bm-invert", "sun-tzu", "Sun Tzu also began from what to avoid: the costly battle."],
    ["bm-incentives", "hanoi-rats", "Hanoi paid for rat tails and got rat farms. Munger would have predicted it."],
    ["bm-incentives", "amul-white-revolution", "Amul changed who got the profit, and farmers produced more milk."],
    ["bm-incentives", "east-india-company", "Company officers were rewarded for taking wealth out of India, so that is what they did."],
    ["bm-lollapalooza", "cotton-boom", "Easy money, rising prices and the crowd all pushed the same way in 1860s Bombay."],
    ["bm-lollapalooza", "sarajevo-1914", "Alliances, arms races and pride all pushed the same way in 1914, and a small event became a world war."],
    ["bm-misjudgment", "wason-246", "Wason's test shows one item on Munger's list at work: we look for facts that agree with us."],
    ["bm-misjudgment", "anchoring", "Anchoring is another of the mind's short cuts that can be used against us."],
    ["bm-misjudgment", "semmelweis", "Doctors rejected handwashing because it went against what they had always said and done."],
    ["bm-not-stupid", "bm-invert", "Being ‘not stupid’ is inversion used every day: find the errors and avoid them."],
    ["bm-patience", "buffett-compounding", "Waiting is what lets compounding do its work."],
    ["bm-deserve", "savitribai-phule", "Savitribai Phule earned her place in history by years of real service, in the face of insults."],
    ["bm-other-side", "wason-246", "People rarely test their own ideas against the opposite case. Munger made it a rule."],
    ["bm-envy", "loss-aversion", "Both show that we measure by comparison: with what we had, or with what others have."],
    ["bm-read", "buffett-compounding", "Knowledge compounds in the same way money does."]
  );
})();
