/* Everyday money. Same shape as data-india.js. Education only: how money works, not what to buy.
   Indian rules and rates quoted here were checked in October 2026 and are marked "as of 2026". They change often. */
(function () {
  MV.DOMAINS.money = "Everyday money";
  MV.DOMAIN_COLORS.money = "#e9c46a";
  const P = list => list.map(a => Object.assign({ domain: "money", pin: true, story: null, jargon: [], mis: [] }, a));

  MV.ASSETS.push(...P([

  /* ---------- Compounding ---------- */
  { id: "money-rule-72", type: "mental model", title: "The Rule of 72", value: 5, cue: "interest rates, doubling your money, or how fast prices rise",
    emoji: "✖️", wiki: "Rule of 72",
    fact: "Divide 72 by the yearly rate of growth. The answer is roughly the number of years money takes to double. At 8% a year, money doubles in about 9 years. At 12%, it doubles in about 6 years.",
    why: "You can check any offer in your head in five seconds. You can also see how fast a loan or rising prices will hurt you.",
    mech: "Growth adds to itself. Each year you earn on the first amount and also on all the earlier gains. So the amount doubles after a fixed number of years, again and again. The number 72 is a short cut for this sum, and it works well for rates between about 4% and 15%. The same rule works against you with loans and with inflation.",
    models: ["compounding", "first-principles"],
    q: "What is the Rule of 72, and why does it work for loans and inflation too?",
    a: "Divide 72 by the yearly rate to get the years needed to double. It works because growth earns on earlier growth. The same doubling happens to a loan you do not repay, and inflation halves the value of money in the same time.",
    chain: [["Divide 72 by the yearly rate", ["72", "divide"]], ["The answer is the years to double", ["double", "doubling", "twice"]], ["Growth earns on earlier growth", ["earlier", "adds to itself", "compound", "on the gains"]], ["It also works for loans and inflation", ["loan", "inflation", "debt", "against you"]]],
    mcq: { q: "At 9% a year, about how long does money take to double?", o: ["About 8 years", "About 4 years", "About 11 years", "About 18 years"] },
    bring: "When someone says a scheme doubles money in 3 years: “By the Rule of 72 that is 24% a year. Who can safely pay that much?”",
    follow: "At the rate your savings account pays, how many years would your money take to double?",
    deeper: "A credit card charging 36% a year doubles an unpaid debt in about 2 years. Prices rising at 6% a year double in about 12 years. The rule is only a close estimate, not an exact sum." },

  { id: "money-start-early", type: "insight", title: "Time matters more than amount", value: 5, cue: "when to start investing, or a young person's first salary",
    emoji: "⏳", wiki: "Compound interest",
    fact: "Take a growth rate of 10% a year, only as an example. Asha puts in ₹5,000 a month from age 25 to 60. Ravi puts in ₹10,000 a month from age 35 to 60. Asha ends with about ₹1.9 crore. Ravi ends with about ₹1.3 crore.",
    why: "Ravi put in ₹30 lakh and Asha only ₹21 lakh, yet Asha has more. Ten early years were worth more than double the monthly amount.",
    mech: "Money that goes in early has more years to grow. Asha's first rupees double about five times in 35 years. Ravi's first rupees have only 25 years, so they double about three and a half times. The last doublings are the biggest ones, because they act on a large amount. Starting late removes exactly those last doublings.",
    models: ["compounding", "opportunity-cost"],
    q: "Why can a person who invests less money end up with more than a person who invests double?",
    a: "If she starts ten years early, her money has more years to grow. Early money doubles more times, and the last doublings are the largest. So time can beat a bigger monthly amount.",
    chain: [["One person starts ten years early", ["early", "earlier", "ten years", "10 years", "age 25"]], ["Early money has more years to grow", ["more years", "more time", "longer", "time"]], ["It doubles more times", ["double", "doubling", "compound"]], ["The last doublings are the largest", ["last", "largest", "biggest", "large amount"]]],
    mcq: { q: "In this example, why does Asha end with more than Ravi?", o: ["Her money had ten more years to grow", "She invested more rupees in total", "She earned a higher rate than Ravi", "She paid less tax than Ravi"] },
    bring: "When a young colleague says he will start saving later: “In one worked example, ₹5,000 a month from age 25 beats ₹10,000 a month from age 35.”",
    follow: "If you could send one money message to yourself at 22, what would it be?",
    deeper: "The 10% rate is only for the sum. Real returns go up and down every year and nobody can promise them. The lesson holds at any positive rate: the earlier money goes in, the more doublings it gets." },

  { id: "money-sip", type: "concept", title: "How a SIP works", value: 4, cue: "mutual funds, SIPs, or what to do when the market falls",
    emoji: "📅", wiki: "Systematic investment plan",
    fact: "A SIP, or systematic investment plan, puts a fixed amount into a mutual fund every month. The same ₹5,000 buys more units when the price is low and fewer units when the price is high.",
    why: "You do not need to guess the right day to invest. The habit matters more than the timing.",
    mech: "A fund's price per unit is called its NAV. Suppose the NAV is ₹50, then ₹40, then ₹50. Your ₹5,000 buys 100 units, then 125 units, then 100 units. You hold 325 units for ₹15,000, so your average cost is about ₹46. That is lower than the average price, because you bought more units when they were cheap. This effect is called rupee cost averaging.",
    models: ["mr-market", "commitment-consistency"],
    q: "What is a SIP, and what is rupee cost averaging?",
    a: "A SIP invests a fixed amount in a fund every month. The fixed amount buys more units when the NAV is low and fewer when it is high. So your average cost per unit comes out lower than the average price.",
    chain: [["A fixed amount goes in every month", ["fixed", "every month", "monthly", "regular"]], ["It buys more units when the price is low", ["more units", "low", "cheap", "falls"]], ["It buys fewer units when the price is high", ["fewer", "high", "costly"]], ["So the average cost per unit is lower", ["average", "averaging"]]],
    mcq: { q: "In a SIP, what happens in a month when the fund's price falls?", o: ["The same amount buys more units", "The SIP stops by itself", "The same amount buys fewer units", "The fund returns your money"] },
    bring: "When the market falls and a friend wants to stop his SIP: “This is the month your ₹5,000 buys the most units.”",
    follow: "What is harder for you: starting a monthly habit, or continuing it when prices fall?",
    deeper: "A SIP does not remove risk. If the fund falls for many years, a SIP also loses money. NAV means net asset value. It is the value of everything the fund owns, divided by the number of units." },

  { id: "money-one-percent-fee", type: "insight", title: "What a 1% fee really costs", value: 5, cue: "mutual fund charges, expense ratios, or agents and commissions",
    emoji: "✂️", wiki: "Mutual fund fees and expenses",
    fact: "Put ₹10,000 a month away for 30 years. At 11% a year it grows to about ₹2.8 crore. At 10% it grows to about ₹2.3 crore. A fee of just 1% a year costs about ₹55 lakh.",
    why: "A 1% fee sounds tiny. Over a working life it can take about one fifth of your final money.",
    mech: "A fund's fee is called the expense ratio. It is charged every year on your whole balance, not only on the new money or the profit. The rupees taken as fees can no longer grow for you. So you lose the fee and also all the growth that the fee would have earned. Over 30 years this lost growth becomes far bigger than the fees themselves.",
    models: ["compounding", "incentives", "second-order-thinking"],
    q: "Why does a 1% yearly fee cost so much over 30 years?",
    a: "The fee, called the expense ratio, is charged every year on the whole balance. Money taken as fees cannot grow, so you also lose its future growth. Over 30 years a 1% fee can cost about a fifth of the final amount.",
    chain: [["The fee is charged every year", ["every year", "yearly", "each year", "expense ratio"]], ["It is charged on the whole balance", ["whole", "balance", "total", "entire"]], ["Fee money can no longer grow", ["grow", "growth", "compound"]], ["Over 30 years it takes about a fifth", ["fifth", "55 lakh", "30 years", "20%"]]],
    mcq: { q: "On what amount is a mutual fund's yearly fee charged?", o: ["On your whole balance, every year", "Only on the profit you make", "Only on the money you add that year", "Only once, when you first invest"] },
    bring: "When someone says 1% is nothing: “On a 30-year SIP, 1% a year can eat about a fifth of the final amount.”",
    follow: "Do you know the yearly fee on any fund or policy you hold?",
    deeper: "The 10% and 11% rates are only for the sum. Returns are never certain, but a fee is certain. Many funds in India come in two forms: a ‘regular’ plan that pays a seller's commission, and a ‘direct’ plan with a lower expense ratio." },

  /* ---------- Inflation ---------- */
  { id: "money-inflation", type: "concept", title: "Inflation: the silent cut", value: 5, cue: "rising prices, cash kept at home, or what things cost in our parents' time",
    emoji: "🎈", wiki: "Inflation",
    fact: "Inflation means that prices rise over time. If prices rise 6% a year, ₹1 lakh kept as cash for 20 years will buy only what about ₹31,000 buys today.",
    why: "The note in your hand looks the same. Its power to buy things falls every year, so doing nothing is not safe.",
    mech: "Each year the same goods cost a little more. The rise compounds, like interest working in reverse. At 6% a year, prices double in about 12 years and become over three times higher in 20 years. So money that earns nothing loses about two thirds of its buying power in 20 years.",
    models: ["compounding", "second-order-thinking"],
    q: "What does 6% inflation do to ₹1 lakh kept as cash for 20 years, and why?",
    a: "Prices rise a little each year and the rise compounds. At 6% they become more than three times higher in 20 years. So ₹1 lakh in cash buys only what about ₹31,000 buys today.",
    chain: [["Prices rise every year", ["prices rise", "rise", "cost a little more", "costlier"]], ["The rise compounds", ["compound", "double"]], ["Prices become over three times higher in 20 years", ["three times", "20 years", "triple"]], ["Idle cash loses buying power", ["buying power", "buys only", "31,000", "power to buy"]]],
    mcq: { q: "At 6% inflation, what will ₹1 lakh in cash buy after 20 years?", o: ["What about ₹31,000 buys today", "What ₹1 lakh buys today", "What about ₹80,000 buys today", "Almost nothing at all"] },
    bring: "When someone keeps a lot of cash at home: “At 6% inflation, that cash loses half its buying power in about 12 years.”",
    follow: "What did a vada pav or a cinema ticket cost when you were in school?",
    deeper: "Since 2016 India's central bank, the RBI, has had an official target of 4% inflation, with a band of 2% to 6%. The real figure has moved above and below this in different years. Your own inflation can be higher, because school fees and hospital bills often rise faster than the average." },

  { id: "money-real-return", type: "concept", title: "Real return: what is left after tax and inflation", value: 5, cue: "fixed deposits, ‘safe’ savings, or interest rates",
    emoji: "🧮", wiki: "Real interest rate",
    fact: "The rate a bank prints is the nominal return. The real return is what is left after tax and inflation. A fixed deposit at 7% can give a person in the 30% tax slab a real return below zero.",
    why: "A deposit can grow in rupees and still shrink in what it can buy. Many careful savers never notice this.",
    mech: "Take a 7% fixed deposit. Interest is taxed at your slab rate. In the 30% slab, tax takes 2.1%, so you keep 4.9%. If prices rise 6% that year, your money buys about 1% less than before. Your balance went up, but your buying power went down. Only the return above inflation makes you richer.",
    models: ["second-order-thinking", "map-vs-territory"],
    q: "How can a fixed deposit that pays 7% make you poorer?",
    a: "The 7% is the nominal return. Tax at the 30% slab leaves 4.9%. If inflation is 6%, the real return is about minus 1%, so the money buys less than before.",
    chain: [["The printed rate is the nominal return", ["nominal", "printed", "7%"]], ["Tax takes a part of the interest", ["tax", "slab", "4.9"]], ["Inflation takes another part", ["inflation", "prices rise", "6%"]], ["The real return can be below zero", ["real", "below zero", "minus", "buys less", "buying power"]]],
    mcq: { q: "What is the ‘real return’ on a deposit?", o: ["The return left after tax and inflation", "The rate printed on the bank's poster", "The interest before any tax is cut", "The return promised by the bank manager"] },
    bring: "When someone says an FD is fully safe: “The rupees are safe. But after tax and inflation, the buying power can still fall.”",
    follow: "Which of your savings do you think beat inflation after tax?",
    deeper: "This does not make fixed deposits useless. They keep money steady and easy to reach, which is right for emergency money and near goals. The point is that ‘no fall in rupees’ and ‘no loss of value’ are two different things." },

  /* ---------- Risk and safety ---------- */
  { id: "money-emergency-fund", type: "concept", title: "The emergency fund", value: 5, cue: "job loss, sudden bills, or where to keep spare cash",
    emoji: "🛟", wiki: null,
    fact: "An emergency fund is money kept aside only for shocks, such as a job loss or a sudden repair. A common rough guide is three to six months of expenses. If you spend ₹40,000 a month, that is ₹1.2 lakh to ₹2.4 lakh.",
    why: "Without it, one bad month pushes you into costly loans. With it, a shock stays a small problem.",
    mech: "Shocks come without warning, and often when markets are also down. With no cash ready, you must borrow on a credit card at about 40% a year. Or you must sell investments at a bad price. Both choices turn a short problem into a long one. So this money is kept where it is safe and quick to reach, even if it earns little.",
    models: ["margin-of-safety", "inversion"],
    q: "What is an emergency fund for, and why is it kept in a low-return place?",
    a: "It is three to six months of expenses kept for shocks like a job loss. Without it you must borrow at high interest or sell investments at a bad price. So it is kept safe and quick to reach, not for high return.",
    chain: [["Three to six months of expenses", ["three", "six", "months", "expenses"]], ["Shocks come without warning", ["shock", "job loss", "warning", "sudden", "emergency"]], ["Without it you borrow costly or sell low", ["borrow", "credit card", "sell", "loan"]], ["So it is kept safe and quick to reach", ["safe", "quick", "reach", "liquid"]]],
    mcq: { q: "What is the main job of an emergency fund?", o: ["To stop a shock from forcing costly loans or bad sales", "To earn the highest return possible", "To save income tax every year", "To pay for a yearly holiday"] },
    bring: "When a friend puts every spare rupee in shares: “What happens if you lose your job in the same month the market falls?”",
    follow: "If your income stopped tomorrow, for how many months could you manage?",
    deeper: "The right size depends on the person. A single earner with children and a home loan needs more than a young person with two earning parents. The fund's ‘return’ is the 40% loan you never had to take." },

  { id: "money-risk-return", type: "concept", title: "Higher return always comes with higher risk", value: 5, cue: "an offer that looks too good, or ‘safe’ high returns",
    emoji: "⚖️", wiki: "Risk–return spectrum",
    fact: "No investment gives high return with no risk. If a safe deposit pays about 7% and someone offers a ‘safe’ 15%, the extra 8% is payment for a risk you cannot yet see.",
    why: "This one rule protects you from most bad products and almost every fraud.",
    mech: "Suppose a truly safe 15% did exist. Big investors would rush in with crores to lend at that rate. The borrower would then not need to pay so much, and the rate would fall. So a high rate that stays on offer means lenders see danger. Also, risk is not the same as volatility. Volatility means the price moves up and down. Risk is the chance of losing money for good.",
    models: ["incentives", "inversion", "second-order-thinking"],
    q: "Why can a high return never be fully safe?",
    a: "If a safe high return existed, big investors would rush in and the rate would fall. A high rate that stays means there is hidden risk. Risk means losing money for good, which is different from volatility, the daily up and down of prices.",
    chain: [["Safe money earns a low rate", ["safe", "low rate", "7%"]], ["Big money would rush into a safe high return", ["rush", "big investors", "crores"]], ["So the rate would fall", ["fall", "drop", "lower"]], ["A high rate that stays means hidden risk", ["risk", "danger", "hidden", "volatility"]]],
    mcq: { q: "A company offers a ‘safe’ 15% when bank deposits pay 7%. What does the extra 8% most likely show?", o: ["Extra risk that the lender is being paid to carry", "The company is kinder than banks", "Banks are hiding the true rate", "A special reward for early customers"] },
    bring: "When someone shares a ‘risk-free 18%’ message: “If it were risk-free, the big banks would have taken it all before it reached WhatsApp.”",
    follow: "What is the best ‘too good to be true’ offer you have seen?",
    deeper: "Shares are volatile, but a wide basket of them has rewarded patient holders over long periods. A fixed deposit in a weak company looks calm until the day it does not pay. A calm price is not proof of safety." },

  { id: "money-diversification", type: "concept", title: "Diversification and asset allocation", value: 5, cue: "‘all eggs in one basket’, one hot share, or how to spread money",
    emoji: "🧺", wiki: "Diversification (finance)",
    fact: "Diversification means spreading money across many things that do not all fall together. If ₹1 lakh sits in one share that halves, you lose ₹50,000. Spread equally over 20 shares, one halving costs only ₹2,500.",
    why: "It is the only way to lower risk without knowing the future. Even experts cannot say which single company will fail.",
    mech: "Every company can have its own bad luck: a fraud, a fire, a failed product. These events are mostly separate, so they rarely strike all companies at once. In a wide basket, one loss is a small part and other gains cover it. Asset allocation takes this one step further. It splits money between types such as shares, bonds and gold, which often move differently.",
    models: ["margin-of-safety", "inversion"],
    q: "Why does spreading money across many investments lower risk?",
    a: "Each company's bad luck is mostly separate from the others. In a wide basket one failure is a small part, and other gains cover it. Asset allocation also spreads money across types like shares, bonds and gold that move differently.",
    chain: [["Each company has its own bad luck", ["bad luck", "fraud", "fail", "own"]], ["These events are mostly separate", ["separate", "not all", "rarely", "independent"]], ["In a wide basket one loss is small", ["small part", "basket", "spread", "2,500"]], ["Asset allocation spreads across types", ["allocation", "types", "bonds", "gold", "differently"]]],
    mcq: { q: "Why does diversification work?", o: ["Different investments rarely all fail at the same time", "It raises the return of every share", "It removes all risk from the market", "The government repays spread-out losses"] },
    bring: "When a colleague puts his whole bonus into one share: “If you are right, good. If you are wrong, how much of your money goes?”",
    follow: "How much of your family's wealth sits in one single thing, such as one flat or one company?",
    deeper: "Diversification cannot remove the risk of the whole market falling together, as in 2008 or March 2020. Many salaried people also forget one hidden concentration: their job and their employer's shares depend on the same company." },

  { id: "money-deposit-insurance", type: "fact", title: "Deposit insurance: the ₹5 lakh cover", value: 4, cue: "bank safety, co-operative banks, or large fixed deposits",
    emoji: "🏦", wiki: "Deposit Insurance and Credit Guarantee Corporation",
    fact: "If a bank in India fails, the DICGC, an arm of the RBI, pays each depositor up to ₹5 lakh per bank. As of 2026 this limit covers savings, fixed, current and recurring deposits together, with interest.",
    why: "Bank deposits feel fully safe. The legal promise has a limit, and it helps to know where the limit is.",
    mech: "Banks pay a small premium to the DICGC on their deposits. If a bank fails, the DICGC pays its depositors up to the limit. The limit is per person, per bank, across all branches. So ₹8 lakh in one bank has ₹5 lakh covered. The same ₹8 lakh split between two banks is fully covered.",
    models: ["margin-of-safety", "second-order-thinking"],
    q: "How does deposit insurance work in India, and what is the limit?",
    a: "Banks pay a premium to the DICGC. If a bank fails, each depositor gets up to ₹5 lakh per bank, counting all accounts and interest. Money split across two banks gets separate cover in each.",
    chain: [["Banks pay a premium to the DICGC", ["premium", "dicgc"]], ["If a bank fails, depositors are paid", ["fails", "fail", "paid", "pays"]], ["The limit is ₹5 lakh per person per bank", ["5 lakh", "limit", "per bank"]], ["Two banks give separate cover", ["two banks", "split", "separate", "each"]]],
    mcq: { q: "As of 2026, how much of a person's deposits in one failed bank does the DICGC cover?", o: ["Up to ₹5 lakh in total, with interest", "The full amount, whatever it is", "Up to ₹5 lakh for every branch", "Only the savings account, not fixed deposits"] },
    bring: "When someone moves all savings to a small bank for higher interest: “Remember the insurance covers ₹5 lakh per bank, not the whole amount.”",
    follow: "Did you know there was a limit on how much of a bank deposit is insured?",
    deeper: "The limit was ₹1 lakh until February 2020. It was raised to ₹5 lakh after the trouble at the Mumbai-based PMC Bank in 2019. There has been public talk of raising it again, so check the current figure. Large banks very rarely fail, but small ones sometimes do." },

  { id: "money-ponzi", type: "historical story", story: "ponzi", title: "The Ponzi scheme", value: 5, cue: "chit fund frauds, ‘double your money’ schemes, or guaranteed returns",
    emoji: "🎩", wiki: "Charles Ponzi",
    fact: "In 1920 Charles Ponzi of Boston promised 50% profit in 45 days. He paid old investors with new investors' money. The scheme collapsed in August 1920, and people lost about 20 million dollars.",
    why: "The same trick returns in every country and every decade. Only the story around it changes.",
    mech: "There is no real business that earns the promised profit. Early investors are paid on time, using money from later investors. They tell friends, and trust spreads fast. But the scheme needs more and more new money to pay everyone. When new money slows, the payments stop and the last people in lose almost everything.",
    models: ["social-proof", "incentives", "feedback-loops"],
    q: "How does a Ponzi scheme work, and why must it always collapse?",
    a: "It promises a high, sure profit but has no real business. Old investors are paid with new investors' money, so they bring friends. It needs ever more new money, and when that slows the payments stop and it collapses.",
    chain: [["It promises a high, sure profit", ["promis", "50%", "guarantee", "high", "sure"]], ["Old investors are paid with new investors' money", ["new investors", "new money", "later investors", "old investors"]], ["Happy early investors bring friends", ["friends", "trust", "spread"]], ["When new money slows, it collapses", ["collapse", "slows", "stop", "lose"]]],
    mcq: { q: "Where does the ‘profit’ in a Ponzi scheme come from?", o: ["From the money put in by newer investors", "From a secret but real business", "From government bonds", "From the organiser's own savings"] },
    bring: "When a relative says a scheme has paid him on time for six months: “Ponzi also paid on time. That is how the trick wins trust.”",
    follow: "What would you check before putting money in a scheme your friend is happy with?",
    deeper: "Ponzi did not invent the trick, but his case gave it its name. India has seen similar collapses. The Saradha Group in West Bengal failed in 2013 after collecting money from well over a million small depositors, by most reports." },

  /* ---------- Borrowing ---------- */
  { id: "money-emi", type: "concept", title: "How an EMI works", value: 5, cue: "home loans, car loans, or paying off a loan early",
    emoji: "🏠", wiki: "Equated monthly installment",
    fact: "An EMI is one fixed monthly payment that covers interest and repays some of the loan. On a ₹50 lakh home loan for 20 years at 9%, the EMI is about ₹45,000. In the first month, ₹37,500 of it is interest.",
    why: "After five years of paying, most people are shocked by how little of the loan has gone.",
    mech: "Each month the bank charges interest on the amount you still owe. At the start you owe the most, so interest takes most of the EMI. Only the small remainder reduces the loan. As the loan shrinks, the interest part falls and the repayment part grows. In this example you pay about ₹27 lakh in five years, but the loan falls by less than ₹6 lakh.",
    models: ["compounding", "second-order-thinking"],
    q: "Why does most of an early EMI go to interest?",
    a: "Interest is charged each month on the amount you still owe. At the start you owe the most, so interest takes most of the EMI and little is left to reduce the loan. As the loan shrinks, more of each EMI repays it.",
    chain: [["An EMI is one fixed monthly payment", ["fixed", "monthly", "emi"]], ["Interest is charged on what you still owe", ["still owe", "outstanding", "balance", "amount you"]], ["At the start interest takes most of it", ["start", "first", "early", "most"]], ["As the loan shrinks, more goes to repayment", ["shrinks", "falls", "reduce", "repay"]]],
    mcq: { q: "In the first years of a 20-year home loan, where does most of each EMI go?", o: ["To interest", "To repaying the loan amount", "Half to interest and half to the loan", "To insurance and bank fees"] },
    bring: "When a friend takes a home loan: “On a 20-year loan, the first years' EMIs are mostly interest. Ask the bank for the full schedule.”",
    follow: "Have you ever looked at the month-by-month schedule of a loan you took?",
    deeper: "In this example the total interest over 20 years is about ₹58 lakh, more than the loan itself. Because early EMIs are mostly interest, an extra repayment made early cuts far more interest than the same amount paid late." },

  { id: "money-credit-card-trap", type: "concept", title: "The minimum-due trap", value: 5, cue: "credit card bills, ‘minimum amount due’, or card debt",
    emoji: "💳", wiki: "Credit card debt",
    fact: "Credit cards in India often charge about 3% to 3.5% a month on unpaid bills, as of 2026. That is around 40% a year. Paying only the ‘minimum amount due’, often about 5% of the bill, keeps you in debt for years.",
    why: "The minimum due looks like a kind offer. It is the most costly common loan an ordinary person takes.",
    mech: "Take a ₹1 lakh bill at 3.5% a month. The first month's interest is ₹3,500. The minimum payment is about ₹5,000, so the debt falls by only ₹1,500. Paying only the minimum each month, it takes about three and a half years to halve the debt. By then you have paid over ₹1 lakh in interest. Also, while a balance is unpaid, new purchases are usually charged interest from day one.",
    models: ["compounding", "incentives"],
    q: "Why is paying only the minimum due on a credit card a trap?",
    a: "The card charges about 3.5% a month, roughly 40% a year. The minimum payment is about 5%, so most of it goes to interest and the debt falls very slowly. You stay in debt for years and pay more interest than you borrowed.",
    chain: [["Cards charge about 40% a year", ["3.5%", "40%", "a month"]], ["The minimum due is about 5% of the bill", ["minimum", "5%"]], ["Most of that payment is interest", ["interest"]], ["So the debt falls very slowly", ["slowly", "years", "falls by only", "halve"]]],
    mcq: { q: "What happens if you pay only the minimum due every month?", o: ["Most of it goes to interest and the debt lasts for years", "The bank cancels the remaining interest", "The debt ends in about a year", "Your credit limit doubles as a reward"] },
    bring: "When someone says he always pays the minimum due: “At about 40% a year, that is the costliest loan most of us ever take.”",
    follow: "Do you know the monthly interest rate printed on your own card statement?",
    deeper: "A card costs nothing in interest if the full bill is paid by the due date every month. The trouble starts only when a balance is carried forward. Rates differ by bank and card, so the exact figure is on your statement." },

  { id: "money-no-cost-emi", type: "insight", title: "The true cost of ‘no-cost EMI’", value: 4, cue: "buying a phone on EMI, online sales, or ‘zero interest’ offers",
    emoji: "📱", wiki: null,
    fact: "A ‘no-cost EMI’ is still a loan with interest. The seller gives a discount equal to the interest, so the two cancel. But you still pay 18% GST on the interest, and often a processing fee.",
    why: "It feels free, so people buy costlier things than they planned. That is why sellers happily pay for it.",
    mech: "Take a ₹60,000 phone on six EMIs of ₹10,000. The bank records a loan of about ₹57,500 at 15% interest. The seller's discount of about ₹2,500 covers the interest. You then pay GST of about ₹450 on that interest, plus a processing fee of perhaps ₹200. A buyer paying in full may also get the discount as a lower price, which the EMI buyer gives up.",
    models: ["incentives", "opportunity-cost"],
    q: "Why is a ‘no-cost EMI’ not really free?",
    a: "It is a loan with interest, and the seller's discount only cancels the interest. You still pay GST on the interest and often a processing fee. You may also give up a discount for paying in full, and the easy EMI makes you spend more.",
    chain: [["It is still a loan with interest", ["loan", "interest"]], ["The seller's discount cancels the interest", ["discount", "cancel", "covers"]], ["You pay GST and a processing fee", ["gst", "processing fee", "fee"]], ["Easy EMIs make people spend more", ["spend more", "costlier", "give up", "feels free"]]],
    mcq: { q: "In a ‘no-cost EMI’, who usually pays the interest?", o: ["The seller, through a discount built into the deal", "Nobody, because the bank lends free", "The government, as a subsidy", "The phone company's insurance"] },
    bring: "During a festival sale: “No-cost EMI is a loan plus a discount. Check the GST and the fee, and ask the price for full payment.”",
    follow: "Would you still buy that model if you had to pay the full price today?",
    deeper: "In 2013 the RBI told banks to stop ‘zero percent’ EMI schemes on credit cards. It said zero percent interest does not really exist, and that hidden charges stop customers from seeing the true price. Each EMI is also a loan on your credit record." },

  /* ---------- Insurance ---------- */
  { id: "money-insurance-purpose", type: "concept", title: "What insurance is really for", value: 5, cue: "insurance agents, ‘what do I get back?’, or health cover",
    emoji: "☂️", wiki: "Insurance",
    fact: "Insurance is for losses that are rare but too large to bear alone. You pay a small, sure cost every year, called the premium. In return the insurer carries the large, unsure loss. One ₹8 lakh hospital bill can undo six years of saving ₹10,000 a month.",
    why: "People often ask what they will ‘get back’ from a policy. A good year for insurance is a year when you get nothing back.",
    mech: "Many people pay small premiums into one pool. In any year only a few of them suffer the big loss, and the pool pays those few. Each person swaps a small sure cost for protection from a ruinous one. This works only for rare, large losses. For small, frequent costs the premium must be higher than the costs, so saving is cheaper.",
    models: ["margin-of-safety", "inversion"],
    q: "What kind of loss is insurance meant for, and how does it work?",
    a: "It is for rare losses too large to bear, like a big hospital bill. Many people pay a small premium into a pool, and the pool pays the few who suffer the loss. You swap a small sure cost for protection from ruin.",
    chain: [["It is for rare but very large losses", ["rare", "large", "big"]], ["Many people pay small premiums into a pool", ["premium", "pool", "many people"]], ["The pool pays the few who suffer", ["few", "pays", "claim"]], ["A small sure cost replaces a ruinous one", ["sure cost", "ruin", "protection", "swap"]]],
    mcq: { q: "Which loss is insurance best suited for?", o: ["A rare loss that is too large to bear alone", "A small cost that comes every month", "A loss that is certain to happen", "Any expense, to get money back"] },
    bring: "When someone says insurance is a waste because he never claimed: “You paid for protection, and you were lucky. That is the best result.”",
    follow: "Which single event could wipe out your family's savings?",
    deeper: "Many salaried people depend only on their employer's group health cover. That cover normally ends when the job ends, which may be exactly when it is needed. Hospital costs in India have also risen faster than general prices in recent years." },

  { id: "money-term-insurance", type: "concept", title: "Term insurance and mixed products", value: 5, cue: "LIC-type policies, endowment plans, ULIPs, or life cover",
    emoji: "🛡️", wiki: "Term life insurance",
    fact: "Term insurance is pure life cover. If the insured person dies during the term, the family gets a large sum. If the person lives, nothing is paid. Mixed products join insurance and saving in one policy, and usually do both jobs poorly.",
    why: "The mix feels better because money ‘comes back’. This feeling often leaves families with too little cover.",
    mech: "Pure cover is cheap because most people outlive the term, so few claims are paid. A mixed policy must split each premium three ways: cover, costs and commission, and savings. So the same premium buys much smaller cover. The savings part has often earned close to what a bank deposit pays. The parts are also hard to see, so the buyer cannot compare prices.",
    models: ["incentives", "opportunity-cost", "first-principles"],
    q: "Why does mixing insurance and investment in one policy usually cost more?",
    a: "Term insurance is pure cover and is cheap because few claims are paid. A mixed policy splits the premium between cover, costs and commission, and savings. So it gives a much smaller cover and a modest return, and the buyer cannot compare the parts.",
    chain: [["Term insurance is pure cover", ["pure", "term", "cover"]], ["It is cheap because few claims are paid", ["cheap", "few claims", "outlive"]], ["A mixed policy splits the premium", ["split", "commission", "costs", "three ways"]], ["So cover is small and the return is modest", ["smaller cover", "small", "modest", "bank deposit", "poorly"]]],
    mcq: { q: "Why is pure term insurance cheap for a large cover?", o: ["Most buyers outlive the term, so few claims are paid", "The government pays half the premium", "It covers only accidents", "The insurer invests the money in shares"] },
    bring: "When an agent says “you get all your money back”: “Then how much of my premium buys cover, and how much is your commission?”",
    follow: "If you were not there, how many years of expenses would your family's cover pay for?",
    deeper: "Life cover exists to replace income for people who depend on you. A person with no dependants may need little of it. Sellers have often earned a much higher commission on mixed policies than on term cover, which explains what gets recommended." },

  /* ---------- Investing basics ---------- */
  { id: "money-index-fund", type: "historical story", story: "bogle", title: "The index fund", value: 5, cue: "mutual funds, star fund managers, or ‘which fund is best?’",
    emoji: "📈", wiki: "John C. Bogle",
    fact: "An index fund simply buys every share in a market index, such as the Nifty 50, at a very low fee. John Bogle opened the first one for the public in 1976. Since then, most actively managed funds have failed to beat their index over long periods.",
    why: "It sounds wrong that doing nothing clever beats most paid experts. The reason is simple arithmetic.",
    mech: "All investors together own the whole market. So before costs, the average investor must earn the market's return. Active funds pay for managers, research and frequent trading, and charge higher fees. After these costs, the average active fund must fall behind the index. An index fund has very low costs, so it stays close to the market's return.",
    models: ["incentives", "survivorship-bias", "compounding"],
    q: "Why do most active funds fail to beat a simple index fund over time?",
    a: "An index fund buys the whole index at a very low fee. All investors together are the market, so the average investor earns the market return before costs. Active funds have higher costs, so after costs most of them fall behind the index.",
    chain: [["An index fund buys the whole index", ["whole", "every share", "index"]], ["Investors together earn the market return", ["average", "together", "market return", "market's return"]], ["Active funds have higher costs", ["cost", "fee", "manager"]], ["After costs most fall behind", ["behind", "fail", "beat"]]],
    mcq: { q: "Why do most active funds trail the index over long periods?", o: ["Their higher costs pull returns below the market average", "Their managers are poorly educated", "Index funds get secret information", "The law limits what active funds may earn"] },
    bring: "When someone praises a star fund manager: “S&P's India report shows about three in four large-cap funds trailed the index over ten years.”",
    follow: "If most experts cannot beat the average, why do people still pay them to try?",
    deeper: "The S&P SPIVA India report for the end of 2025 found that about three quarters of large-cap funds trailed their index over ten years. Some funds do win. The hard part is knowing in advance which ones. An index fund still carries the full risk of the market." },

  { id: "money-gold", type: "concept", title: "Gold: what it does and does not do", value: 4, cue: "gold prices, wedding jewellery, or Akshaya Tritiya",
    emoji: "🪙", wiki: "Gold as an investment",
    fact: "Indian households are often estimated to hold about 25,000 tonnes of gold, more than any other country's households. Gold holds its value over long periods and through crises. But it pays no interest, rent or profit.",
    why: "Gold is loved in India for good reasons. It helps to know which job it does well and which it cannot do.",
    mech: "Gold cannot be printed, and it is trusted everywhere. So people run to it when they fear inflation, war or weak banks, and its price rises. For generations it was the one asset a family could hide, carry, pledge or sell in any town. But gold produces nothing. Its price rises only when the next buyer pays more. Jewellery also loses making charges when sold.",
    models: ["lindy-effect", "social-proof", "first-principles"],
    q: "Why is gold valued, and what can it not do?",
    a: "Gold cannot be printed and is trusted everywhere, so people run to it in a crisis and it holds value. It was easy for families to carry, pledge or sell. But it produces nothing, so it pays no income and gains only if the price rises.",
    chain: [["Gold cannot be printed and is trusted", ["printed", "trusted", "scarce"]], ["People run to it in a crisis", ["crisis", "fear", "war", "inflation"]], ["Families could carry, pledge or sell it", ["carry", "pledge", "sell", "hide"]], ["It produces nothing and pays no income", ["produces nothing", "no interest", "no income", "pays no"]]],
    mcq: { q: "What income does a gold bar pay its owner each year?", o: ["None; it only gains if the price rises", "About 2% interest", "A share of mining profit", "Rent from the jeweller"] },
    bring: "When gold prices are in the news: “Gold is protection, not a business. It pays nothing while you hold it.”",
    follow: "How much of your family's gold is jewellery, and how much could really be sold?",
    deeper: "India mines very little gold, so nearly all of it is imported. This is why heavy gold buying affects the rupee. A jewellery buyer pays making charges and GST at purchase, and gets back mostly the metal's value on sale." },

  { id: "money-ppf-epf", type: "concept", title: "PPF and EPF: forced long-term saving", value: 4, cue: "provident fund, PF deductions on a salary slip, or retirement",
    emoji: "🔒", wiki: "Public Provident Fund",
    fact: "EPF takes a part of a salaried person's pay every month for retirement, and the employer adds to it. PPF is a 15-year government savings account that anyone can open. As of 2026, PPF pays 7.1% and EPF paid 8.25% for 2025-26.",
    why: "Many Indians reach retirement with real money only because the PF was cut before the salary reached them.",
    mech: "Both work by locking money away. EPF is deducted before you see your salary, so you never decide to spend it. PPF cannot be fully withdrawn for 15 years. The lock removes temptation, and the interest compounds for decades without a break. The government sets the rates and can change them. PPF interest is tax-free under current rules.",
    models: ["commitment-consistency", "compounding"],
    q: "How do EPF and PPF help people build long-term savings?",
    a: "EPF is deducted from salary every month and the employer adds to it. PPF locks money for 15 years. Because the money is locked, it is not spent, and the interest compounds for decades.",
    chain: [["EPF is deducted from salary each month", ["deduct", "salary", "epf", "cut"]], ["The employer also adds to it", ["employer"]], ["PPF locks money for 15 years", ["15", "lock", "ppf"]], ["Locked money compounds for decades", ["compound", "decades", "not spent", "temptation"]]],
    mcq: { q: "What is the main reason PF builds wealth for ordinary earners?", o: ["The money is locked away and compounds for decades", "It pays a higher return than any share", "The government doubles the balance at 60", "It can be withdrawn at any time"] },
    bring: "When a colleague wants to withdraw his PF on changing jobs: “That money is doing well only because nobody touches it.”",
    follow: "Do you know how much is in your PF account today?",
    deeper: "As of 2026, PPF accepts ₹500 to ₹1.5 lakh a year. The EPF rate is 12% of wages from the employee, with a matching share from the employer. These rules change, so check the current ones." },

  /* ---------- Behaviour ---------- */
  { id: "money-pay-yourself-first", type: "psychological concept", title: "Pay yourself first", value: 5, cue: "‘I cannot save’, salary hikes, or where the raise went",
    emoji: "🥇", wiki: null,
    fact: "‘Pay yourself first’ means moving savings out on salary day, before any spending. Most people do the opposite and save what is left at the end of the month. Usually nothing is left.",
    why: "It explains why people who earn ₹50,000 and people who earn ₹2 lakh can both feel they have no money.",
    mech: "Spending grows to fill the money that is in the account. When income rises, wants rise with it: a bigger phone, a better car, costlier dinners. This is called lifestyle inflation. An automatic transfer on salary day removes the money before wants can reach it. You then adjust your spending to what remains, and you hardly notice the difference.",
    models: ["commitment-consistency", "inversion"],
    q: "What does ‘pay yourself first’ mean, and why does it work better than saving what is left?",
    a: "It means moving savings out automatically on salary day, before spending. Spending grows to fill whatever is in the account, and wants rise with income, which is lifestyle inflation. So money saved first is safe, and you adjust to what remains.",
    chain: [["Move savings out on salary day", ["salary day", "first", "before spending", "before any spending"]], ["Spending grows to fill what is available", ["fill", "grows", "what is left", "available"]], ["Wants rise with income", ["lifestyle", "wants", "rise"]], ["An automatic transfer beats willpower", ["automatic", "adjust", "transfer"]]],
    mcq: { q: "What is ‘lifestyle inflation’?", o: ["Spending rising whenever income rises", "Prices of luxury goods rising", "The government raising taxes on the rich", "Rent rising faster than salary"] },
    bring: "When a friend says he will save more after the next raise: “The raise will vanish too, unless the saving leaves on salary day.”",
    follow: "After your last raise, how much of it did you actually keep?",
    deeper: "A rough guide called 50-30-20 splits take-home pay into 50% needs, 30% wants and 20% savings. In Mumbai, rent alone can break the 50%, so treat it only as a starting point. Keeping half of every raise is another simple version of the same idea." },

  { id: "money-mental-accounting", type: "psychological concept", title: "Mental accounting and sunk costs", value: 4, cue: "bonuses, refunds, or ‘I have already spent so much on it’",
    emoji: "🗂️", wiki: "Mental accounting",
    fact: "Mental accounting means we treat money differently depending on where it came from. A ₹50,000 bonus feels like ‘extra’ and is spent freely. The same ₹50,000 from salary is guarded. But every rupee buys exactly the same.",
    why: "It explains why people keep savings at 7% while carrying card debt at 40%, and why they hold on to bad purchases.",
    mech: "The mind puts money into separate boxes: salary, bonus, refund, winnings. Each box gets its own rules. This helps with budgeting, but it hides the full picture. A related error is the sunk cost fallacy. Money already spent cannot come back. Yet we keep paying for a bad plan to avoid admitting the loss. Only future costs and future gains should decide.",
    models: ["opportunity-cost", "commitment-consistency"],
    q: "What are mental accounting and the sunk cost fallacy?",
    a: "Mental accounting is putting money in separate boxes, so a bonus is spent more freely than salary though every rupee is the same. The sunk cost fallacy is continuing a bad plan because of money already spent. That money cannot come back, so only future costs and gains should decide.",
    chain: [["We put money into separate boxes", ["box", "separate", "label"]], ["A bonus is spent more freely than salary", ["bonus", "freely", "extra"]], ["But every rupee is the same", ["same", "every rupee"]], ["Money already spent should not decide", ["sunk", "already spent", "future", "cannot come back"]]],
    mcq: { q: "You paid ₹6,000 for a gym year and hate going. What is the sunk cost error?", o: ["Forcing yourself to go only because you already paid", "Asking the gym for a refund", "Stopping because you do not enjoy it", "Choosing a cheaper plan next year"] },
    bring: "When someone holds a bad share ‘until it returns to my buying price’: “The share does not know what you paid. Would you buy it today?”",
    follow: "Is there something you keep paying for only because you have already paid so much?",
    deeper: "Richard Thaler, who won the Nobel Prize in economics in 2017, gave mental accounting its name. Waiting for a share to return to your purchase price mixes three errors: sunk cost, anchoring on that price, and loss aversion." },

  { id: "money-herd-and-checking", type: "psychological concept", title: "The herd, hot tips and daily checking", value: 4, cue: "IPO fever, WhatsApp stock tips, or checking the portfolio app",
    emoji: "🐑", wiki: "Herd behavior",
    fact: "People buy what everyone else is buying, most of all in IPOs and hot tips. And people who check their investments every day tend to trade more and earn less. Both habits come from feelings, not from facts.",
    why: "In investing, the usual enemy is not lack of information. It is our own reaction to noise and to the crowd.",
    mech: "When unsure, we copy others, because a crowd feels safe. By the time a tip reaches you, early buyers have already pushed the price up. Daily checking adds a second problem. On any single day, shares fall almost as often as they rise. A loss hurts about twice as much as an equal gain pleases. So the daily checker feels more pain, and sells at bad times.",
    models: ["social-proof", "mr-market", "availability-bias"],
    q: "Why do following the crowd and checking prices daily lead to worse results?",
    a: "We copy the crowd when unsure, but by the time a tip reaches us the price has already gone up. Checking daily shows many small falls, and a loss hurts about twice as much as a gain pleases. So the daily checker feels pain and sells at bad times.",
    chain: [["When unsure we copy the crowd", ["copy", "crowd", "everyone", "herd"]], ["The price is already up when the tip arrives", ["already", "tip", "early buyers"]], ["Daily checking shows many small falls", ["daily", "every day", "single day", "falls"]], ["Losses hurt more, so people sell at bad times", ["hurt", "pain", "sell", "twice"]]],
    mcq: { q: "Why does checking a portfolio every day often lead to worse decisions?", o: ["Frequent small losses hurt and push people to sell", "The app charges a fee for each look", "Prices fall whenever many people look", "Daily data is always wrong"] },
    bring: "When a friend shares a ‘sure’ stock tip: “If it has reached our WhatsApp group, who do you think bought before us?”",
    follow: "How often do you open your investment app, and how do you feel afterwards?",
    deeper: "Over a single day, shares fall nearly half the time. Over ten or more years, a wide index has rarely shown a loss. The investment is the same. Only the frequency of looking changes what the investor feels." },

  /* ---------- Tax and earning ---------- */
  { id: "money-tax-slabs", type: "concept", title: "Tax slabs: marginal and average rate", value: 5, cue: "income tax, salary hikes, or ‘I will move into a higher slab’",
    emoji: "🪜", wiki: "Income tax in India",
    fact: "Income tax is charged in slabs, like steps. Each rate applies only to the part of income inside that step. Under the new regime as of 2026-27, a taxable income of ₹15 lakh pays ₹1.05 lakh before cess. That is 7% on average, not 15%.",
    why: "Many people believe a raise can push all their income into a higher rate and leave them poorer. Slabs do not work that way.",
    mech: "The first ₹4 lakh is taxed at nil. The next ₹4 lakh is taxed at 5%, which is ₹20,000. The next ₹4 lakh is taxed at 10%, which is ₹40,000. The last ₹3 lakh is taxed at 15%, which is ₹45,000. The marginal rate is the rate on your last rupee, here 15%. The average rate is total tax divided by income, here 7%.",
    models: ["first-principles", "map-vs-territory"],
    q: "What is the difference between the marginal and the average tax rate?",
    a: "Tax is charged in slabs, and each rate applies only to the part of income inside that slab. The marginal rate is the rate on the last rupee earned. The average rate is total tax divided by income, and it is always lower.",
    chain: [["Tax is charged in slabs", ["slab", "step"]], ["Each rate applies only to its own part", ["only to the part", "part of income", "inside"]], ["The marginal rate is on the last rupee", ["marginal", "last rupee"]], ["The average rate is total tax divided by income", ["average", "divided", "lower"]]],
    mcq: { q: "Your raise moves you into the next slab. What happens to your tax?", o: ["Only the income inside the new slab is taxed at the higher rate", "All your income is now taxed at the higher rate", "Your take-home pay must fall", "The raise itself is tax-free"] },
    bring: "When a colleague fears a raise will ‘put him in a higher slab’: “Only the extra rupees get the higher rate. A raise still leaves you with more.”",
    follow: "Do you know your own average tax rate, not only your slab?",
    deeper: "As of 2026-27 the new regime slabs are nil to ₹4 lakh, then 5%, 10%, 15%, 20% and 25% for each further ₹4 lakh, and 30% above ₹24 lakh. A rebate makes tax zero up to ₹12 lakh of taxable income. A 4% cess is added to the tax. Slabs change in Budgets." },

  { id: "money-human-capital", type: "insight", title: "Your earning power is your biggest asset", value: 5, cue: "cutting small expenses, career moves, or learning new skills",
    emoji: "🎓", wiki: "Human capital",
    fact: "Human capital is the value of your skills and your future earnings. Skipping a ₹100 coffee every day saves ₹36,500 a year. A 10% raise on a ₹8 lakh salary adds ₹80,000 a year, and every later raise builds on it.",
    why: "Advice on money usually stops at cutting costs. For most working people, growing income matters far more.",
    mech: "Spending can be cut only down to zero, so saving has a limit. Income has no fixed limit. A raise is also not a one-time gain. Next year's raise is a percentage of the new, higher salary, so the gain compounds over a career. For a person of 30, the salary still to come over 30 years is worth far more than present savings.",
    models: ["compounding", "opportunity-cost", "circle-of-competence"],
    q: "Why can building skills matter more than cutting small expenses?",
    a: "Cutting costs has a limit, because spending cannot go below zero. Income has no fixed limit, and each raise compounds because later raises build on it. For most working people, future earnings from skills are their largest asset.",
    chain: [["Cutting costs has a limit", ["limit", "zero", "cut"]], ["Income has no fixed limit", ["income", "no fixed limit", "raise"]], ["A raise compounds over a career", ["compound", "build on", "builds on", "higher salary"]], ["Future earnings are the largest asset", ["future earnings", "largest asset", "skills", "biggest asset"]]],
    mcq: { q: "Why does a salary raise matter more than it first seems?", o: ["Every later raise is calculated on the higher salary", "Raises are not taxed", "A raise makes expenses fall", "Employers must repeat the raise each year"] },
    bring: "When a friend worries over small savings: “Good habit. But one new skill that lifts your pay by 10% beats years of skipped coffee.”",
    follow: "Which one skill, if you learned it this year, would raise your income the most?",
    deeper: "The two ideas work together. A raise helps only if part of it is kept, and savings grow faster when income rises. Human capital also needs protection, which is the real job of health cover and term cover." }

  ]));

  /* ---------- Stories ---------- */
  MV.STORIES.push(
  { id: "ponzi", assetId: "money-ponzi", title: "Fifty Percent in Forty-Five Days",
    hook: "In 1920 one man in Boston made thousands of people rich on paper, and then poor in a single month.",
    setting: "Boston, USA, in early 1920. The First World War is over, and ordinary people are hungry for a way to get ahead.",
    character: "Charles Ponzi, a charming Italian immigrant who had arrived in America years earlier with almost no money.",
    conflict: "Ponzi promised 50% profit in 45 days. He said he traded international postal reply coupons, which cost less in some countries than in others.",
    surprise: "He hardly bought any coupons. There were not nearly enough coupons in the world for the money he took in. He paid old investors with new investors' money.",
    turning: "In the summer of 1920 the Boston Post newspaper began asking how the business could work. Investors rushed to take their money out.",
    payoff: "The scheme collapsed in August 1920. Investors lost about 20 million dollars, several banks failed, and Ponzi went to prison.",
    meaning: "A high return that is ‘guaranteed’ is the warning, not the attraction. Always ask where the profit really comes from.",
    extra: ["At the peak, people queued in the street outside his office and some mortgaged their homes to invest.", "Ponzi was later sent back to Italy. He died poor in a charity hospital in Rio de Janeiro in 1949.", "The Boston Post won a Pulitzer Prize in 1921 for exposing him."],
    facts: [["1920"], ["boston"], ["50%", "45 days"], ["coupon"], ["new investors", "old investors"], ["collapse", "prison", "lost"], ["guaranteed", "where the profit"]],
    vocab: ["scheme", "collapse", "guaranteed"] },

  { id: "bogle", assetId: "money-index-fund", title: "Bogle's Folly",
    hook: "The fund that the experts laughed at in 1976 became one of the largest in the world.",
    setting: "The United States in the mid-1970s. Mutual funds are run by well-paid managers who promise to beat the market.",
    character: "John Bogle, known as Jack, who had founded a new fund company called Vanguard in 1975.",
    conflict: "Bogle saw that most managers did not beat the market after their fees. So he planned a fund that would simply buy all 500 companies in the S&P 500 index, at very low cost.",
    surprise: "He hoped to raise 150 million dollars. When the fund opened on 31 August 1976, it had raised only about 11 million.",
    turning: "Rivals called it ‘Bogle's folly’ and said that settling for the average was no way to invest. Bogle refused to close the fund.",
    payoff: "Year after year, low costs kept the fund ahead of most managed funds. Today index funds hold trillions of dollars around the world.",
    meaning: "In investing you keep what you do not pay away. A plain idea with low costs can beat clever ideas with high costs.",
    extra: ["The fund was first called the First Index Investment Trust. It is now the Vanguard 500 Index Fund.", "At the start it did not have enough money to buy all 500 shares, so it bought only some of them.", "Warren Buffett has said Bogle did more for ordinary American investors than any other person."],
    facts: [["1976"], ["bogle"], ["vanguard"], ["index"], ["150 million", "11 million"], ["folly", "laughed"], ["low cost", "fees", "costs"]],
    vocab: ["index", "folly", "average"] }
  );

  /* ---------- Links ---------- */
  MV.LINKS.push(
    ["money-rule-72", "buffett-compounding", "The Rule of 72 is the quick sum behind Buffett's wealth: money that keeps doubling becomes huge with enough time."],
    ["money-rule-72", "money-inflation", "The same rule shows inflation at work: at 6% a year, prices double in about 12 years."],
    ["money-rule-72", "money-credit-card-trap", "At about 36% to 40% a year, the Rule of 72 says an unpaid card debt doubles in about two years."],
    ["money-start-early", "buffett-compounding", "Buffett began investing as a child, and most of his wealth came after age 60. Both show that time is the main input."],
    ["money-start-early", "bm-patience", "Starting early only helps if you then wait. Munger said the big money is in the waiting."],
    ["money-start-early", "money-rule-72", "Ten extra years at 10% means about one and a half extra doublings."],
    ["money-sip", "bm-mr-market", "A SIP buys more units when Mr Market is gloomy and prices are low, without needing any courage."],
    ["money-sip", "money-pay-yourself-first", "Both take the decision away from your mood by making the transfer automatic."],
    ["money-sip", "bm-fear-greed", "A SIP keeps buying when others are fearful, which is the hard half of Buffett's rule."],
    ["money-one-percent-fee", "money-index-fund", "An index fund's main advantage is its low fee, and the 1% sum shows how much a fee is worth over 30 years."],
    ["money-one-percent-fee", "bm-incentives", "A seller paid by commission earns more from a high-fee product, so ask how the adviser is paid."],
    ["money-one-percent-fee", "buffett-compounding", "Compounding works on costs too: a fee taken every year also removes all the growth that money would have earned."],
    ["money-inflation", "weimar-hyperinflation", "Weimar Germany shows the extreme case of what 6% inflation does slowly: money losing its power to buy."],
    ["money-inflation", "money-real-return", "Inflation is the reason a return must be judged by what it buys, not by the number of rupees."],
    ["money-inflation", "money-gold", "Fear of inflation is one main reason people buy gold, because gold cannot be printed."],
    ["money-real-return", "bm-price-value", "Both separate the number you see from what you truly get: the printed rate is not the real return."],
    ["money-emergency-fund", "margin-of-safety", "An emergency fund is a margin of safety for a household: spare room so that one shock does not break the plan."],
    ["money-emergency-fund", "bm-rule-one", "Without spare cash a shock forces you to sell at a loss or borrow at 40%, which breaks Rule No. 1."],
    ["money-emergency-fund", "money-credit-card-trap", "The emergency fund exists so that a bad month does not end up on a credit card."],
    ["money-emergency-fund", "bm-tide", "A job loss in a falling market is the tide going out, and the emergency fund decides who is exposed."],
    ["money-risk-return", "money-ponzi", "A Ponzi scheme sells the one thing that cannot exist: a high return with no risk."],
    ["money-risk-return", "bm-rule-one", "Buffett's rule is about avoiding loss for good, which is the true meaning of risk, not daily price movement."],
    ["money-risk-return", "bm-mr-market", "Mr Market's mood swings are volatility. They become real risk only if you are forced to sell to him."],
    ["money-diversification", "money-index-fund", "An index fund is diversification in one purchase, because it holds every company in the index."],
    ["money-diversification", "margin-of-safety", "Both accept that you may be wrong and arrange things so that one mistake is not fatal."],
    ["money-diversification", "cotton-boom", "In the 1860s Bombay put its money into one boom built on cotton, and one event broke it all together."],
    ["money-deposit-insurance", "money-diversification", "Splitting large deposits between banks is diversification applied to the ₹5 lakh insurance limit."],
    ["money-deposit-insurance", "money-insurance-purpose", "Deposit insurance is the same pooling idea: all banks pay a small premium to cover the rare failure of one."],
    ["money-ponzi", "bm-incentives", "Early investors are paid well, so they honestly recommend the scheme. Their reward is what spreads the fraud."],
    ["money-ponzi", "cotton-boom", "In both, early winners pulled in crowds, and the last people to enter carried the losses."],
    ["money-ponzi", "hanoi-rats", "Both show a reward system producing the opposite of what people believed they were paying for."],
    ["money-ponzi", "money-herd-and-checking", "A Ponzi scheme grows through the herd: people join because friends have already been paid."],
    ["money-emi", "buffett-compounding", "An EMI is compounding seen from the borrower's side: early on, the interest is large because the balance is large."],
    ["money-credit-card-trap", "bm-incentives", "A card company earns most from customers who carry a balance, so the minimum due is shown clearly on every bill."],
    ["money-credit-card-trap", "money-no-cost-emi", "Both make borrowing feel painless in the shop, and the cost appears only later."],
    ["money-no-cost-emi", "anchoring", "A small monthly figure becomes the anchor, and the full price of the phone drops out of sight."],
    ["money-no-cost-emi", "bm-price-value", "The EMI hides the price. The useful question is whether the thing is worth its full price to you."],
    ["money-no-cost-emi", "upi", "UPI made paying easy and instant, and easy credit at checkout goes one step further by making borrowing just as easy."],
    ["money-insurance-purpose", "bm-rule-one", "Insurance protects against the one loss large enough to wipe out years of saving."],
    ["money-insurance-purpose", "money-emergency-fund", "The emergency fund handles small, likely shocks. Insurance handles rare, ruinous ones."],
    ["money-term-insurance", "bm-incentives", "Mixed policies have paid sellers more commission than term cover, which explains which one is pushed harder."],
    ["money-term-insurance", "money-one-percent-fee", "Both show how costs hidden inside a product quietly reduce what the buyer finally gets."],
    ["money-term-insurance", "money-human-capital", "Term cover insures your human capital: the future income your family depends on."],
    ["money-index-fund", "bm-circle", "Buying the whole index is an honest answer for someone who knows that picking winners is outside his circle."],
    ["money-index-fund", "bm-patience", "An index fund rewards the investor who buys, holds and waits, which is Munger's point about patience."],
    ["money-index-fund", "bse-banyan", "The Sensex, the index of the exchange that began under the banyan tree, is one of the indexes such funds copy."],
    ["money-gold", "reforms-1991", "In the 1991 crisis India pledged its gold reserves abroad to borrow, showing gold's role as the asset of last resort."],
    ["money-ppf-epf", "money-pay-yourself-first", "EPF is ‘pay yourself first’ made compulsory: the saving is cut before the salary arrives."],
    ["money-ppf-epf", "bm-patience", "A 15-year lock forces the waiting that Munger says most investors cannot manage by themselves."],
    ["money-pay-yourself-first", "bm-envy", "Lifestyle inflation is often driven by envy: we raise our spending to match the people around us."],
    ["money-pay-yourself-first", "money-human-capital", "A raise builds wealth only if part of it is saved before the lifestyle grows to absorb it."],
    ["money-mental-accounting", "loss-aversion", "We hold on to sunk costs because admitting them means accepting a loss, and losses hurt more than gains please."],
    ["money-mental-accounting", "anchoring", "Waiting for a share to return to your buying price is anchoring on a number the market does not care about."],
    ["money-mental-accounting", "money-credit-card-trap", "Keeping savings at 7% while owing card debt at 40% is mental accounting: the two boxes are never compared."],
    ["money-herd-and-checking", "loss-aversion", "Daily checking hurts because of loss aversion: the many small falls weigh more than the equal small rises."],
    ["money-herd-and-checking", "bm-fear-greed", "The herd buys in greed and sells in fear. Buffett's advice is to do the opposite."],
    ["money-herd-and-checking", "cotton-boom", "The share mania of 1860s Bombay was herd behaviour: people bought because everyone around them was getting rich."],
    ["money-herd-and-checking", "bm-mr-market", "Checking prices daily means listening to every one of Mr Market's moods, most of which are noise."],
    ["money-tax-slabs", "money-real-return", "Your marginal slab rate is the rate that cuts your interest income, so it sets your real return on a deposit."],
    ["money-tax-slabs", "reforms-1991", "In the 1970s India's top income tax rate was above 90%. Much lower and simpler rates came in the reform years of the 1990s."],
    ["money-human-capital", "bm-deserve", "Munger's advice to deserve what you want is the same idea: raise your value and the income follows."],
    ["money-human-capital", "bm-read", "Reading and learning every day is how Buffett and Munger kept adding to their own human capital."],
    ["money-human-capital", "comparative-advantage", "Income grows fastest when you put your time into the skill where your advantage over others is largest."]
  );
})();
