/* Lives that teach: leaders, makers and ordinary heroes. Same shape as data-india.js. */
(function () {
  const P = list => list.map(a => Object.assign({ story: null, jargon: [], mis: [] }, a));

  MV.ASSETS.push(...P([
  /* ---------- India ---------- */
  { id: "lv-sudha-murty-postcard", type: "person", domain: "business", region: "india", title: "Sudha Murty's postcard to J. R. D. Tata", value: 4, cue: "women at work, unfair rules, or speaking up to the boss",
    emoji: "📮", wiki: "Sudha Murty",
    fact: "In 1974 Sudha Murty was a student at the Indian Institute of Science in Bengaluru. She saw a job notice from Telco, now Tata Motors. It said that lady candidates need not apply. She wrote a postcard of complaint straight to J. R. D. Tata, the head of the Tata group.",
    why: "A postcard cost a few paise. It got her an interview, a job, and a rule changed at one of India's biggest companies.",
    mech: "She did not complain to friends. She wrote to the one person who could change the rule. About ten days later a telegram called her for an interview in Pune, with all travel costs paid. She was hired and became the first woman engineer on Telco's shop floor. Years later she met J. R. D. Tata often, and he treated the postcard as a fair point, not an insult.",
    models: ["bottlenecks", "incentives"],
    q: "What did Sudha Murty do about the Telco notice, and what happened?",
    a: "She wrote a postcard straight to J. R. D. Tata saying the notice banning women was unfair. Telco called her for an interview and she became its first woman engineer.",
    chain: [["A job notice said women need not apply", ["notice", "advert", "women", "lady", "need not apply"]], ["She wrote a postcard straight to the top", ["postcard", "wrote", "letter", "j. r. d", "jrd", "top"]], ["She was called for an interview and hired", ["interview", "telegram", "hired", "job", "pune"]], ["First woman engineer at Telco", ["first woman", "first female", "engineer", "shop floor"]]],
    mcq: { q: "How did Sudha Murty respond to a job notice that excluded women?", o: ["She wrote a postcard of complaint to J. R. D. Tata and was then called for an interview", "She filed a court case against Telco", "She started her own engineering firm instead", "She wrote a newspaper article under a false name"] },
    bring: "When someone says one person cannot change a big company: “Sudha Murty changed Telco's hiring rule with a postcard in 1974.”",
    follow: "Who is the one person who could actually fix the problem you are complaining about?",
    deeper: "She worked at Telco in Pune and later lent her husband Narayana Murthy 10,000 rupees to start Infosys in 1981. She has told the postcard story herself many times, so it is well attested." },

  { id: "lv-sreedharan-metro", type: "person", domain: "business", region: "india", title: "Sreedharan and the Delhi Metro's clocks", value: 4, cue: "late projects, government work, or deadlines",
    emoji: "🚇", wiki: "Delhi Metro",
    fact: "Phase 1 of the Delhi Metro, about 65 km, was finished in 2005. It came in two years and nine months ahead of schedule and within budget. The man in charge was the engineer E. Sreedharan, then already past retirement age.",
    why: "Indian public projects were famous for running late and over cost. One man showed that the same system could deliver early.",
    mech: "Sreedharan treated time as the main cost. Big countdown clocks at offices showed the days left to each deadline, so nobody could forget it. He insisted on freedom from political interference in hiring and contracts. Decisions were taken fast and at the site, not sent up a long chain. Each completed section was opened to the public, which kept support strong and money flowing.",
    models: ["bottlenecks", "incentives", "goodharts-law"],
    q: "How did the Delhi Metro's first phase finish early when so many projects run late?",
    a: "Sreedharan made time the main measure, with countdown clocks showing days left. He kept politics out of hiring and contracts, let decisions be taken fast at the site, and opened sections as they were finished.",
    chain: [["Time was treated as the main cost", ["time", "countdown", "clock", "deadline", "days left"]], ["No political interference in hiring or contracts", ["politic", "interfer", "hiring", "contract", "freedom"]], ["Fast decisions taken at the site", ["fast", "quick", "site", "decision", "chain"]], ["Finished nearly three years early", ["early", "ahead", "2005", "schedule", "budget"]]],
    mcq: { q: "By how much did Delhi Metro Phase 1 beat its schedule?", o: ["About two years and nine months", "About two weeks", "It finished exactly on time", "It finished four years late"] },
    bring: "When a flyover is years late: “The Delhi Metro's first phase finished almost three years early. Sreedharan put countdown clocks on the walls.”",
    follow: "What would change at your workplace if a clock showed the days left on every project?",
    deeper: "Sreedharan had earlier led the Konkan Railway and, in 1964, rebuilt the storm-wrecked Pamban bridge to Rameswaram in 46 days against a six-month target. He was born in 1932 and the press named him the ‘Metro Man’." },

  { id: "lv-ela-bhatt-sewa", type: "person", domain: "business", region: "india", title: "Ela Bhatt: a union for women with no employer", value: 4, cue: "informal work, street vendors, or women's savings groups",
    emoji: "🧺", wiki: "Ela Bhatt",
    fact: "In 1972 the lawyer Ela Bhatt founded SEWA, the Self-Employed Women's Association, in Ahmedabad. It was registered as a trade union, though its members had no employer. They were vegetable sellers, home workers and head-loaders. In 1974 they started their own cooperative bank.",
    why: "Most working Indians have no boss and no contract. SEWA showed that they could still organise and get credit.",
    mech: "Labour law assumed a worker and an employer. Bhatt argued that self-employed women also faced low pay, police harassment and money-lenders. A union gave them a shared voice with the city and the police. The bank gave small loans and a safe place to save, so members could stop paying huge interest to lenders. By 2022 SEWA had about 2 million members.",
    models: ["network-effects", "first-principles", "incentives"],
    q: "Why was SEWA an unusual trade union, and how did it help its members?",
    a: "Its members were self-employed women with no employer. The union gave them a shared voice against harassment, and the 1974 cooperative bank gave small loans and savings so they could escape money-lenders.",
    chain: [["Self-employed women had no employer and no union", ["self-employed", "no employer", "informal", "vendor", "home worker"]], ["Registered as a trade union in 1972", ["union", "1972", "registered", "voice"]], ["A cooperative bank for small loans and savings", ["bank", "loan", "saving", "1974", "credit"]], ["Members escaped money-lenders", ["money-lender", "moneylender", "lender", "interest"]]],
    mcq: { q: "What made SEWA different from other trade unions in 1972?", o: ["Its members were self-employed women with no employer", "It was only for factory workers", "It was run by the government", "It only accepted men"] },
    bring: "When street vendors come up: “Ela Bhatt built a union for women with no boss in 1972. It now has about 2 million members.”",
    follow: "Who around us works hard every day but has no employer to argue with?",
    deeper: "Bhatt had earlier worked for the Textile Labour Association founded under Gandhi's guidance. She received the Ramon Magsaysay Award in 1977 and the Padma Bhushan in 1986, and died in 2022." },

  { id: "lv-satyarthi-child-labour", type: "person", domain: "history", region: "india", title: "Kailash Satyarthi and the march that made a law", value: 4, cue: "child labour, Nobel prizes, or a protest that changed a rule",
    emoji: "🧒", wiki: "Kailash Satyarthi",
    fact: "Kailash Satyarthi, an engineer from Madhya Pradesh, founded Bachpan Bachao Andolan in 1980 to rescue children from bonded labour. In 1998 he led a Global March Against Child Labour across many countries. In 1999 the International Labour Organization adopted Convention 182 against the worst forms of child labour. He shared the 2014 Nobel Peace Prize with Malala Yousafzai.",
    why: "Rescuing children one raid at a time is slow. A rule that every country signs changes the game for all of them.",
    mech: "His group raided factories and quarries and freed children, but new children replaced them. So he aimed at the rule, not only the rescue. The 1998 march ended in Geneva where the ILO was meeting. Public pressure from many countries made it easy for governments to vote yes. Convention 182 became the fastest ratified ILO convention ever.",
    models: ["second-order-thinking", "bottlenecks", "incentives"],
    q: "Why did Satyarthi organise a world march in 1998, and what came of it?",
    a: "Rescuing children one by one did not stop the supply, so he aimed at the rules. The march ended at the ILO in Geneva, and in 1999 Convention 182 against the worst forms of child labour was adopted.",
    chain: [["Rescues alone did not stop child labour", ["rescue", "raid", "freed", "one by one", "replaced"]], ["A global march in 1998 aimed at the rules", ["march", "1998", "global", "rule", "pressure"]], ["ILO Convention 182 adopted in 1999", ["182", "convention", "ilo", "1999", "geneva"]], ["Nobel Peace Prize 2014, shared with Malala", ["nobel", "2014", "malala"]]],
    mcq: { q: "What did the 1998 Global March Against Child Labour lead to?", o: ["ILO Convention 182 against the worst forms of child labour", "A ban on all factories in India", "The founding of UNICEF", "A new Indian school holiday"] },
    bring: "When child labour comes up: “Satyarthi's group freed children for years, then he marched to Geneva to change the rule itself.”",
    follow: "When you fix a problem again and again, what rule would stop it from coming back?",
    deeper: "Bachpan Bachao Andolan says it has freed over 80,000 children. The Nobel committee praised the pairing of a Hindu Indian and a Muslim Pakistani in a shared struggle for children." },

  { id: "lv-arunima-everest", type: "person", domain: "psychology", region: "india", title: "Arunima Sinha: Everest on one leg", value: 4, cue: "setbacks, disability, or starting again after a disaster",
    emoji: "🏔️", wiki: "Arunima Sinha",
    fact: "In April 2011 Arunima Sinha, a national-level volleyball player from Uttar Pradesh, was pushed from a moving train by robbers. Her left leg was crushed and cut off below the knee. On 21 May 2013, about two years later, she stood on top of Mount Everest. She was the first woman amputee to do so.",
    why: "Most people would spend years grieving a lost sporting career. She chose a harder goal than the one she lost.",
    mech: "In hospital she decided on a goal so big it left no room for self-pity. She went to Bachendri Pal, the first Indian woman to climb Everest in 1984, and trained under her. A prosthetic leg does not feel the ground, so every step on ice had to be checked by eye. The climb to the summit took 52 days. Her story later funded a sports academy for disabled children.",
    models: ["inversion", "commitment-consistency"],
    q: "How did Arunima Sinha go from a hospital bed to the top of Everest?",
    a: "After losing her leg in 2011, she set a goal far bigger than what she had lost. She trained under Bachendri Pal, learned to climb on a prosthetic leg, and reached the summit in May 2013.",
    chain: [["Lost her leg after being pushed from a train in 2011", ["train", "2011", "leg", "amput", "pushed"]], ["Chose a bigger goal instead of self-pity", ["goal", "bigger", "decided", "self-pity", "chose"]], ["Trained under Bachendri Pal on a prosthetic leg", ["bachendri", "trained", "prosthetic", "artificial"]], ["Summit on 21 May 2013", ["2013", "summit", "top", "everest"]]],
    mcq: { q: "Who trained Arunima Sinha for Everest?", o: ["Bachendri Pal, the first Indian woman to climb Everest", "Edmund Hillary's son", "The Indian Army's ski school", "Her volleyball coach"] },
    bring: "When someone feels a setback has ended everything: “Arunima Sinha lost a leg in 2011 and climbed Everest in 2013.”",
    follow: "After a bad loss, is it easier to aim lower or to aim at something completely new?",
    deeper: "The Jaipur Foot and other low-cost prosthetics have made such climbs possible for many Indians. She went on to climb the highest peaks on several continents and received the Padma Shri in 2015." },

  { id: "lv-milkha-rome", type: "person", domain: "psychology", region: "india", title: "Milkha Singh looked back in Rome", value: 4, cue: "near misses, Partition, or losing focus at the last moment",
    emoji: "🏃", wiki: "Milkha Singh",
    fact: "At the 1960 Rome Olympics, Milkha Singh ran the 400 metres final in about 45.7 seconds. He finished fourth, missing the bronze by about a tenth of a second. He said that at around 250 metres he slowed and glanced at the other runners, and lost the medal there.",
    why: "He had survived the murder of his parents in the Partition of 1947. The hardest lesson of his life came from one glance.",
    mech: "He was leading at the halfway point and feared he could not keep the pace. So he eased off and looked around. The glance broke his rhythm for a fraction of a second. In a race decided by hundredths, that was the medal. His time stood as the Indian record for almost 40 years, so the speed was there. The focus was not.",
    models: ["second-order-thinking", "commitment-consistency"],
    q: "Why did Milkha Singh miss a medal in Rome, by his own account?",
    a: "He was leading but feared he could not keep the pace, so around 250 metres he slowed and looked back. The broken rhythm cost him the bronze by about a tenth of a second.",
    chain: [["Leading the 400 m final in Rome, 1960", ["rome", "1960", "leading", "400"]], ["Feared he could not hold the pace", ["fear", "pace", "could not", "sustain", "eased"]], ["Slowed and looked back at 250 metres", ["look", "glanc", "slow", "250", "rhythm"]], ["Fourth by about a tenth of a second", ["fourth", "4th", "tenth", "bronze", "miss"]]],
    mcq: { q: "What did Milkha Singh blame for losing the 1960 Olympic bronze?", o: ["Slowing down and looking back at the other runners mid-race", "A false start by another runner", "A torn shoe", "Illness on the day of the race"] },
    bring: "When someone checks the competition too often: “Milkha Singh lost an Olympic medal by looking back once.”",
    follow: "When you are ahead, is it harder to keep pushing or to stop checking others?",
    deeper: "As a boy he saw his parents killed during Partition and reached Delhi as a refugee. He was rejected by the army three times before being accepted. The name ‘Flying Sikh’ is said to have been given to him in Pakistan after a 1960 race in Lahore." },

  { id: "lv-usha-hundredth", type: "person", domain: "psychology", region: "india", title: "P. T. Usha and one hundredth of a second", value: 3, cue: "close finishes, athletics, or small margins deciding big results",
    emoji: "⏱️", wiki: "P. T. Usha",
    fact: "At the 1984 Los Angeles Olympics, P. T. Usha ran the 400 metres hurdles final in 55.42 seconds. The bronze went to Cristieana Cojocaru of Romania in 55.41. Usha was fourth by one hundredth of a second, the closest an Indian woman has come to an Olympic athletics medal.",
    why: "A hundredth of a second is less than a blink. It decided whether a girl from a Kerala village became an Olympic medallist.",
    mech: "She came from Payyoli in Kerala and was spotted at a school meet. She trained under coach O. M. Nambiar for years before the Games. In the final she was level with the bronze medallist at the line. The photo finish put her a few centimetres behind. She went on to win 4 golds at the 1986 Asian Games, so the loss did not end her.",
    models: ["margin-of-safety", "compounding"],
    q: "How close did P. T. Usha come to an Olympic medal in 1984?",
    a: "She finished fourth in the 400 m hurdles in 55.42 seconds, one hundredth of a second behind the bronze medallist. The photo finish put her a few centimetres behind, and she went on to win 4 Asian Games golds in 1986.",
    chain: [["Los Angeles 1984, 400 m hurdles final", ["1984", "los angeles", "hurdles", "400"]], ["Fourth by one hundredth of a second", ["hundredth", "0.01", "55.42", "fourth", "4th"]], ["Decided by a photo finish", ["photo", "centimetre", "line", "level"]], ["Went on to win 4 Asian Games golds in 1986", ["asian games", "1986", "gold", "went on"]]],
    mcq: { q: "By how much did P. T. Usha miss the 1984 Olympic bronze?", o: ["One hundredth of a second", "One full second", "Half a lap", "She was disqualified"] },
    bring: "When someone says small margins do not matter: “P. T. Usha missed an Olympic medal by one hundredth of a second.”",
    follow: "Where in your own work could a tiny margin decide everything?",
    deeper: "Her 55.42 was an Asian record at the time. She later ran a sports school in Kerala and became president of the Indian Olympic Association in 2022." },

  { id: "lv-manjhi-mountain", type: "historical story", domain: "psychology", region: "india", title: "Dashrath Manjhi carved a road through a hill", value: 5, cue: "patience, one person against a system, or grief turned into work", story: "manjhi",
    emoji: "🔨", wiki: "Dashrath Manjhi",
    fact: "Dashrath Manjhi was a poor labourer in Gehlaur village, Gaya district, Bihar. A rocky hill cut his village off from the nearest town. From 1960 to 1982, working alone with a hammer and chisel, he cut a path 110 metres long and about 9 metres wide through the hill. The journey to town fell from about 55 km to about 15 km.",
    why: "Nobody gave him money, a machine or permission. Twenty-two years of small blows did what the government had not done.",
    mech: "In 1959 his wife Falguni Devi was hurt crossing the hill and died because help was too far away. He decided the hill itself was the problem. He sold his goats to buy tools and worked on the rock each day, often at night after farm labour. Villagers mocked him at first, then some brought food. Each day moved only a little rock, but the days added up.",
    models: ["compounding", "first-principles", "commitment-consistency"],
    q: "Why did Dashrath Manjhi cut a road through a hill, and how?",
    a: "His wife died in 1959 because the hill made the hospital too far. He worked alone with a hammer and chisel from 1960 to 1982 and cut a 110-metre path, so the trip to town fell from 55 km to 15 km.",
    chain: [["His wife died because help was too far away", ["wife", "falguni", "died", "hospital", "far"]], ["He decided the hill itself was the problem", ["hill", "mountain", "problem", "decided", "rock"]], ["22 years alone with hammer and chisel", ["hammer", "chisel", "22", "1960", "1982", "alone"]], ["A 110 m path cut the journey from 55 km to 15 km", ["110", "55", "15 km", "path", "road"]]],
    mcq: { q: "What tools did Dashrath Manjhi use to cut through the hill?", o: ["A hammer and chisel", "Dynamite borrowed from a quarry", "A bulldozer lent by the state", "A team of hired labourers"] },
    bring: "When a task feels too big: “Dashrath Manjhi cut a road through a hill with a hammer. It took 22 years.”",
    follow: "What small daily effort of yours would look big if you kept it up for 20 years?",
    deeper: "The Bihar government later named the road after him and gave him a state funeral when he died in 2007. The 2015 Hindi film Manjhi: The Mountain Man told his story." },

  { id: "lv-neerja-pan-am", type: "historical story", domain: "history", region: "india", title: "Neerja Bhanot and Pan Am Flight 73", value: 5, cue: "courage at work, hijackings, or Mumbai's quiet heroes", story: "neerja",
    emoji: "✈️", wiki: "Neerja Bhanot",
    fact: "On 5 September 1986, Pan Am Flight 73 from Mumbai was hijacked on the ground at Karachi. Neerja Bhanot, the 22-year-old senior flight purser, warned the cockpit so the pilots could escape, hid the American passports the hijackers wanted, and opened an emergency exit when the shooting began. She was killed shielding three children.",
    why: "She had been a model and a flight attendant for only a year. Training and a few quick decisions saved most of the 360 people on board.",
    mech: "The moment the hijackers boarded, she passed the hijack code to the cockpit, so the pilots left through a hatch and the plane could not fly. The hijackers then wanted American passengers, so she and her crew hid their passports. After about 17 hours the lights failed and the men opened fire. She opened an exit door and helped passengers down the slide instead of leaving first.",
    models: ["margin-of-safety", "bottlenecks"],
    q: "How did Neerja Bhanot save lives on Pan Am 73?",
    a: "She alerted the cockpit so the pilots escaped and the plane stayed grounded, hid the American passports the hijackers wanted, and when shooting began opened an emergency exit to let passengers out. She died shielding three children.",
    chain: [["Alerted the cockpit so the pilots escaped", ["cockpit", "pilot", "code", "hatch", "grounded"]], ["Hid the American passports", ["passport", "american", "hid"]], ["Opened an emergency exit when shooting began", ["exit", "door", "slide", "shoot", "fire"]], ["Killed shielding three children", ["three children", "shield", "killed", "died"]]],
    mcq: { q: "Why did Neerja Bhanot hide passengers' passports during the hijacking?", o: ["The hijackers wanted to find and target American passengers", "To stop passengers from leaving the plane", "The passports contained the plane's flight plan", "To sell them later for ransom"] },
    bring: "When someone says a job is just a job: “Neerja Bhanot was 22 and a flight attendant for a year. She saved a planeload of people in Karachi.”",
    follow: "Which part of your work would you be glad you had practised, if an emergency came?",
    deeper: "She was awarded the Ashoka Chakra, India's highest peacetime bravery award, and was its youngest recipient. The 2016 film Neerja told her story. A square in Mumbai's Ghatkopar is named after her." },

  { id: "lv-homai-vyarawalla", type: "person", domain: "history", region: "india", title: "Homai Vyarawalla shot the news under another name", value: 4, cue: "photography, women in media, or doing the work before you get the credit",
    emoji: "📷", wiki: "Homai Vyarawalla",
    fact: "Homai Vyarawalla, a Parsi woman from Gujarat raised in Mumbai, became India's first woman photojournalist. Her first pictures appeared in the Bombay Chronicle in 1938. Many were printed under her husband's name, because editors and readers did not believe a woman had taken them. She photographed the last years of British rule and the first years of free India, and was awarded the Padma Vibhushan in 2011.",
    why: "She let others take the credit so that the work could be published at all. The photographs outlived the names on them.",
    mech: "In the 1930s a woman with a camera at a public event was so unusual that people did not take her seriously. That had an upside: she could move around unnoticed and get close. Her husband Maneckshaw, also a photographer, let his name go on her work. In the 1940s she moved to Delhi and worked for the British Information Services, signing her pictures Dalda 13, after her car number plate. She photographed Gandhi, Nehru, Lord Mountbatten and the first Independence Day. In 1970 she put the camera down for good.",
    models: ["second-order-thinking", "inversion"],
    q: "Why were Homai Vyarawalla's early photographs published under her husband's name, and how did she build a career anyway?",
    a: "Editors and readers would not believe a woman had taken them, so her husband's name went on her work. Being ignored let her move freely and get close. From the 1940s in Delhi she signed her pictures Dalda 13 and photographed the leaders of a new India.",
    chain: [["First woman photojournalist; pictures in the Bombay Chronicle from 1938", ["1938", "bombay chronicle", "first woman", "photojournalist"]], ["Published under her husband's name because people did not believe a woman took them", ["husband", "maneckshaw", "name", "believe", "credit"]], ["Being ignored let her get close to the action", ["unnoticed", "ignored", "close", "move", "freely", "seriously"]], ["Signed Dalda 13 in Delhi; photographed Gandhi, Nehru and the first Independence Day", ["dalda", "delhi", "nehru", "gandhi", "mountbatten", "independence"]]],
    mcq: { q: "What was Homai Vyarawalla's professional signature, Dalda 13, taken from?", o: ["Her car's number plate", "Her birth year", "The number of her camera", "A brand that sponsored her"] },
    bring: "When someone wants credit before the work is done: “India's first woman photojournalist published under her husband's name for years. The pictures are what lasted.”",
    follow: "Would you let someone else's name go on your work if that was the only way to get it out?",
    deeper: "She stopped taking pictures in 1970, a year after her husband died, saying the manners of the new press pack were not for her. She was born in 1913 and died in Vadodara in 2012, aged 98." },

  { id: "lv-somnath-sharma-badgam", type: "person", domain: "history", region: "india", title: "Major Somnath Sharma at Badgam, 1947", value: 4, cue: "the army, Kashmir in 1947, or holding a position when it matters most",
    emoji: "🎖️", wiki: "Somnath Sharma",
    fact: "On 3 November 1947 Major Somnath Sharma led about 100 men of the Kumaon Regiment at Badgam, near Srinagar airfield, with one arm in plaster. Several hundred raiders from Pakistan attacked. His last radio message said he would not withdraw an inch but fight to the last man and the last round. He was killed, but the airfield held. He was the first Param Vir Chakra.",
    why: "Srinagar airfield was the only way Indian troops could reach Kashmir in October 1947. Had it fallen that day, the history of Kashmir might be different.",
    mech: "Indian troops had been flown into Srinagar from 27 October after the Maharaja signed the Instrument of Accession. The raiders were only a few kilometres from the airfield. Sharma's company was sent to Badgam to find them and was attacked by a far larger force. He kept his men firing, filled magazines himself with his good arm, and asked for reinforcements by radio. His stand delayed the raiders for about six hours, long enough for more troops to arrive and secure the airfield.",
    models: ["bottlenecks", "margin-of-safety"],
    q: "Why did Major Somnath Sharma's stand at Badgam matter so much?",
    a: "Srinagar airfield was the only way to bring Indian troops into Kashmir. His company of about 100 held off several hundred raiders for about six hours on 3 November 1947. He was killed, but the delay let reinforcements secure the airfield, and he became the first Param Vir Chakra.",
    chain: [["Srinagar airfield was the only way in for Indian troops", ["airfield", "srinagar", "only way", "flown"]], ["About 100 men attacked by several hundred raiders at Badgam, 3 November 1947", ["badgam", "1947", "raider", "hundred", "outnumber"]], ["He would not withdraw an inch; killed fighting", ["not withdraw", "last man", "last round", "killed", "inch"]], ["The delay saved the airfield; first Param Vir Chakra", ["delay", "six hours", "reinforce", "param vir", "pvc", "first"]]],
    mcq: { q: "What was Major Somnath Sharma's company protecting at Badgam in November 1947?", o: ["Srinagar airfield, the only way to bring Indian troops into Kashmir", "The Maharaja's palace", "A bridge over the Jhelum", "The Srinagar radio station"] },
    bring: "When Kashmir in 1947 comes up: “The airfield at Srinagar nearly fell on 3 November. Somnath Sharma's company held the raiders for six hours and he died doing it.”",
    follow: "What is the one position in your work that everything else depends on?",
    deeper: "His arm was in plaster, and he had insisted on going with his company. He was 24. His younger brother, V. N. Sharma, later became Chief of the Army Staff. The Param Vir Chakra was created in 1950 and given to him with effect from 1947." },

  { id: "lv-anandibai-doctor", type: "person", domain: "history", region: "india", title: "Anandibai Joshi, India's first woman doctor", value: 4, cue: "women in medicine, early marriage, or studying against the odds",
    emoji: "🩺", wiki: "Anandi Gopal Joshi",
    fact: "Anandibai Joshi, born in Kalyan near Mumbai in 1865, was married at nine. At fourteen she had a son who died within ten days because no medical help was available. She decided to become a doctor. In March 1886 she received a medical degree from the Woman's Medical College of Pennsylvania in the United States, the first Indian woman to do so.",
    why: "She turned a private grief into a plan at an age when most girls were not taught to read. She did it against her own community's anger.",
    mech: "Her husband Gopalrao, a postal clerk, taught her to read and pushed her to study. Neighbours threw stones and insults at a Hindu woman going abroad. In 1883 she gave a public speech in Serampore explaining why India needed women doctors, since many women would not see a male doctor. An American woman, Theodicia Carpenter, offered her a home. She sailed alone in 1883 and finished the degree in three years.",
    models: ["first-principles", "inversion"],
    q: "Why did Anandibai Joshi become a doctor, and what did it cost her?",
    a: "Her baby died at ten days old because there was no medical help, so she decided to become a doctor. Her husband taught her to read, she faced insults for going abroad, and she sailed alone to America in 1883 and graduated in 1886.",
    chain: [["Her baby died because there was no medical help", ["baby", "son", "died", "ten days", "no medical"]], ["Her husband taught her and pushed her to study", ["husband", "gopalrao", "taught", "read", "study"]], ["She faced insults for going abroad", ["insult", "stone", "anger", "abroad", "community"]], ["Medical degree in Pennsylvania, 1886", ["1886", "pennsylvania", "degree", "america", "graduat"]]],
    mcq: { q: "What pushed Anandibai Joshi to become a doctor?", o: ["Her newborn son died because no medical help was available", "Her father was a doctor", "A British officer offered her a scholarship", "She wanted to move to America permanently"] },
    bring: "When women in medicine come up: “The first Indian woman doctor graduated in 1886. She was married at nine and lost a baby at fourteen.”",
    follow: "What grief or anger in your life could be turned into a plan?",
    deeper: "She caught tuberculosis in the cold American winters and died in Pune in February 1887, a month before her 22nd birthday, before she could practise. A crater on Venus is named after her." },

  { id: "lv-ratan-tata-two-bets", type: "person", domain: "business", region: "india", title: "Ratan Tata's two big bets of 2008", value: 4, cue: "bold business decisions, cheap cars, or Indian companies buying foreign brands",
    emoji: "🚗", wiki: "Tata Nano",
    fact: "In 2008 Ratan Tata made two big bets. In January he launched the Tata Nano, a car priced at about 1 lakh rupees. In June Tata Motors bought Jaguar Land Rover from Ford for about 2.3 billion US dollars. The Nano lost money and production stopped in 2018. Jaguar Land Rover became the group's main source of car profits for many years.",
    why: "The same leader, the same year, one bet failed and one worked. Boldness alone does not decide the result.",
    mech: "The Nano was built to a price, so quality and safety were cut to the bone. Buyers did not want to be seen in the ‘cheapest car’, and moving the factory from Singur in West Bengal to Sanand in Gujarat cost time. Jaguar Land Rover already had strong brands and engineers. Tata gave them money and freedom just as demand for luxury cars rose in China. The cheap bet fought the customer's pride. The expensive bet rode an existing strength.",
    models: ["second-order-thinking", "incentives", "survivorship-bias"],
    q: "Why did the Nano fail while the Jaguar Land Rover purchase worked?",
    a: "The Nano was built to a 1 lakh price, so quality was cut and buyers did not want the cheapest car; the factory move from Singur also cost time. Jaguar Land Rover had strong brands and engineers, and demand for luxury cars rose, especially in China.",
    chain: [["Nano launched at about 1 lakh rupees in 2008", ["nano", "1 lakh", "one lakh", "2008", "cheapest"]], ["Cost cutting and buyers' pride hurt the Nano", ["quality", "safety", "pride", "cheapest car", "seen in"]], ["Factory moved from Singur to Sanand", ["singur", "sanand", "factory", "moved"]], ["Jaguar Land Rover had strong brands and rising demand", ["jaguar", "land rover", "brand", "china", "luxury", "demand"]]],
    mcq: { q: "What was the launch price of the Tata Nano in 2008?", o: ["About 1 lakh rupees", "About 5 lakh rupees", "About 50,000 rupees", "About 10 lakh rupees"] },
    bring: "When a cheap product flops: “The Nano taught Tata that nobody wants to buy the ‘cheapest car’. Jaguar Land Rover, bought the same year, made the money.”",
    follow: "Would you rather sell the cheapest thing in a market or the one people are proud to own?",
    deeper: "Ford had bought Jaguar in 1989 and Land Rover in 2000 for far more than it sold them for. Ratan Tata stepped down as chairman in 2012 and died in October 2024." },

  { id: "lv-jamsetji-after-death", type: "person", domain: "business", region: "india", title: "Jamsetji Tata's dreams were built after he died", value: 4, cue: "legacy, long-term plans, or starting what you will not finish",
    emoji: "🏗️", wiki: "Jamsetji Tata",
    fact: "Jamsetji Tata died in 1904. Of his four great plans, only the Taj Mahal Hotel in Mumbai, opened in 1903, was finished in his lifetime. His steel works, his science institute and his hydro-electric power scheme were all built by others. Tata Steel started in 1907, the Indian Institute of Science opened in Bengaluru in 1909, and the first Tata hydro power reached Mumbai in 1915.",
    why: "He spent years and money on things he knew he might never see. The institutions outlived him by more than a century.",
    mech: "He planned each project in detail and wrote down the purpose. He put aside land and his own money, including a large gift of property for the science institute. He trained his sons Dorabji and Ratanji and trusted partners to carry on. Because the plans were clear and the money was committed, the next generation could not easily drop them. The projects became a family duty, not one man's hobby.",
    models: ["compounding", "second-order-thinking", "lindy-effect"],
    q: "How did Jamsetji Tata's biggest projects get built when he died before they started?",
    a: "He planned them in detail, set aside land and money, and trained his sons and partners to carry them out. So Tata Steel in 1907, the science institute in 1909 and hydro power in 1915 were all built after his death in 1904.",
    chain: [["Only the Taj Hotel was finished in his lifetime", ["taj", "hotel", "1903", "lifetime", "only"]], ["He died in 1904 with plans written and money set aside", ["1904", "died", "plan", "money", "land", "set aside"]], ["His sons and partners carried the plans out", ["son", "dorabji", "partner", "carried", "trained", "next generation"]], ["Steel 1907, IISc 1909, hydro power 1915", ["1907", "1909", "1915", "steel", "institute", "hydro", "power"]]],
    mcq: { q: "Which of Jamsetji Tata's four great projects was finished while he was alive?", o: ["The Taj Mahal Hotel in Mumbai", "Tata Steel at Jamshedpur", "The Indian Institute of Science", "The hydro-electric power plant"] },
    bring: "When someone says a plan will take too long: “Jamsetji Tata planned steel, a science institute and hydro power, and died before any of them opened.”",
    follow: "What would you start today if you knew someone else would have to finish it?",
    deeper: "The science institute idea began in the 1890s and faced years of delay with the British government over land and money. Swami Vivekananda, whom Jamsetji met on a ship in 1893, was among those he wrote to about it." },

  /* ---------- World ---------- */
  { id: "lv-lincoln-unsent-letter", type: "person", domain: "psychology", title: "Lincoln's letters that were never sent", value: 5, cue: "anger, angry emails, or how to handle a colleague who let you down",
    emoji: "✉️", wiki: "George Meade",
    fact: "After the Battle of Gettysburg in July 1863, General George Meade let the beaten Confederate army escape across the Potomac river. Lincoln was furious and wrote Meade a sharp letter on 14 July. Then he put it in an envelope and wrote on it: never sent, or signed. It was found among his papers after his death.",
    why: "Writing the letter let the anger out. Not sending it kept a good general working for him.",
    mech: "Lincoln believed Lee's escape had cost a chance to end the war. He wrote exactly how he felt, which cooled him down. Then he thought about the result of sending it. Meade had just won the biggest battle of the war and might resign if insulted. The anger was real but the letter would do harm. So he kept it. He did this with other letters too.",
    models: ["second-order-thinking", "inversion"],
    q: "What did Lincoln do with his angry letter to General Meade, and why?",
    a: "He wrote out his anger at Lee's escape in full, then did not send it, marking the envelope never sent or signed. Sending it would have hurt a general who had just won Gettysburg and might resign.",
    chain: [["Meade let Lee's army escape after Gettysburg, July 1863", ["meade", "lee", "escape", "gettysburg", "1863", "potomac"]], ["Lincoln wrote a sharp letter in full", ["wrote", "letter", "sharp", "anger", "furious"]], ["He thought about the result of sending it", ["result", "harm", "resign", "thought", "insult"]], ["Never sent, or signed", ["never sent", "not send", "kept", "envelope", "did not send"]]],
    mcq: { q: "What did Lincoln write on the envelope of his letter to Meade?", o: ["Never sent, or signed", "Deliver at once", "Read to the whole army", "Burn after reading"] },
    bring: "When someone is about to fire off an angry message: “Lincoln wrote his angriest letters in full and then never sent them.”",
    follow: "Have you ever been glad you did not send something you wrote?",
    deeper: "Lincoln is also reported to have advised others to write a hot letter, put it aside, and read it again the next day. Modern email makes the gap between writing and sending almost zero, which is exactly the danger." },

  { id: "lv-keller-water-pump", type: "person", domain: "psychology", title: "Helen Keller and the word for water", value: 4, cue: "teaching, breakthroughs, or how learning really begins",
    emoji: "🚰", wiki: "Helen Keller",
    fact: "Helen Keller lost her sight and hearing to an illness before she was two, and had almost no way to communicate. On 3 March 1887 a young teacher, Anne Sullivan, came to her home in Alabama. On 5 April Sullivan held one of Helen's hands under a water pump and spelled w-a-t-e-r into the other. Helen understood that things have names. She learned about 30 words that day.",
    why: "One month of patient, apparently failed effort ended in a moment that opened a whole life. In 1904 she became the first deaf-blind person to earn a university degree.",
    mech: "Sullivan, who had been nearly blind herself, spelled words into Helen's palm for weeks. Helen copied the finger shapes like a game, without knowing they meant anything. At the pump, the cold water on one hand and the spelling on the other came together. The link between a thing and its sign clicked. Once she had the idea of a name, every word after that was easier. Sullivan stayed with her for 49 years.",
    models: ["first-principles", "compounding", "feedback-loops"],
    q: "What happened at the water pump in April 1887, and why did it matter?",
    a: "After weeks of spelling into Helen's palm with no result, Sullivan spelled w-a-t-e-r while water ran over her other hand. Helen understood that things have names and learned about 30 words that day. In 1904 she became the first deaf-blind university graduate.",
    chain: [["Deaf and blind from infancy, with no way to communicate", ["deaf", "blind", "communicat", "illness", "two"]], ["Sullivan spelled words into her palm for weeks with no result", ["palm", "spell", "finger", "weeks", "game", "copied"]], ["At the pump the water and the word came together", ["pump", "water", "w-a-t-e-r", "click", "together", "names"]], ["About 30 words that day; a degree in 1904", ["30 words", "thirty", "1904", "degree", "graduat", "easier"]]],
    mcq: { q: "What did Helen Keller understand at the water pump on 5 April 1887?", o: ["That things have names, and the finger shapes were words", "How to read printed books", "That her teacher was leaving", "How to speak out loud"] },
    bring: "When a student seems to make no progress: “Anne Sullivan spelled into Helen Keller's hand for a month with nothing to show. Then one word at a pump changed everything.”",
    follow: "Have you ever had a moment when a subject suddenly made sense after weeks of confusion?",
    deeper: "Keller wrote books, toured the world and campaigned for disabled people and for women's votes. She visited India in 1955 and met Nehru. The play and film The Miracle Worker tell the story of the pump." },

  { id: "lv-mandela-afrikaans", type: "person", domain: "strategy", title: "Mandela learned his jailers' language", value: 5, cue: "understanding opponents, negotiation, or learning a language",
    emoji: "📖", wiki: "Robben Island",
    fact: "On Robben Island, Nelson Mandela studied Afrikaans, the language of the white Afrikaner government that had jailed him. He also read Afrikaner history and poetry. Many fellow prisoners thought this was the language of the enemy and refused to learn it.",
    why: "He spent years preparing to talk to the other side before anyone offered to talk. When the talks came, he could speak to them in their own words.",
    mech: "Mandela believed that any solution for South Africa would have to include the Afrikaners, who saw themselves as Africans too. To negotiate well he needed to know how they thought and what they feared. He practised Afrikaans on the warders, which also softened the way many of them treated him. In the talks of the early 1990s and as president, he used the language and his knowledge of their history to win trust. In 1995 he wore the Springbok rugby jersey, a symbol Afrikaners loved.",
    models: ["game-theory", "second-order-thinking", "reciprocity"],
    q: "Why did Mandela learn Afrikaans in prison, and what did it achieve?",
    a: "He believed any solution had to include the Afrikaners, so he had to understand how they thought. He practised on the warders, which softened their treatment, and later used the language and their history to win trust in negotiations.",
    chain: [["He studied the language and history of the people who jailed him", ["afrikaans", "language", "history", "jailer", "studied", "learn"]], ["He believed any solution had to include the Afrikaners", ["include", "solution", "part of", "afrikaner", "africans too"]], ["Practising on the warders softened their treatment", ["warder", "guard", "soften", "practis"]], ["He used it to win trust in negotiations", ["trust", "negotiat", "talk", "jersey", "springbok"]]],
    mcq: { q: "Why did Mandela learn Afrikaans on Robben Island?", o: ["To understand how his opponents thought, ready for future negotiations", "Because the prison forced all prisoners to learn it", "To pass a law exam", "To write letters to his family"] },
    bring: "When someone refuses to listen to the other side: “Mandela spent years in prison learning his jailers' language and history so he could negotiate with them one day.”",
    follow: "Whose way of thinking do you most need to understand, and how would you start?",
    deeper: "A quote about speaking to a man ‘in his language’ going ‘to his heart’ is often credited to Mandela, but its source is unclear. His 1995 appearance in the Springbok jersey at the Rugby World Cup final was the subject of the film Invictus." },

  { id: "lv-king-birmingham-letter", type: "person", domain: "history", title: "King's letter from a Birmingham jail", value: 4, cue: "protest, patience versus urgency, or writing under pressure",
    emoji: "🕊️", wiki: "Letter from Birmingham Jail",
    fact: "On 16 April 1963, Martin Luther King Jr. was in jail in Birmingham, Alabama, for leading protests against racial segregation. Eight white clergymen had published a statement calling the protests unwise and untimely. King replied with a long letter, begun in the margins of a newspaper and continued on scraps of paper smuggled out by his lawyers.",
    why: "He answered his polite critics, not his loud enemies. The letter became one of the most read arguments for non-violent protest.",
    mech: "The clergymen said he should wait and use the courts. King answered that ‘wait’ had almost always meant ‘never’ for Black Americans. He wrote that injustice anywhere is a threat to justice everywhere. He explained the steps of a non-violent campaign: collect facts, negotiate, prepare yourself, then act. He argued that an unjust law is no law, citing Gandhi's example and Christian teaching. Having no paper or desk, he wrote wherever he could.",
    models: ["first-principles", "commitment-consistency"],
    q: "Who was King's Birmingham letter addressed to, and what did it argue?",
    a: "It answered eight white clergymen who called the protests untimely. King argued that ‘wait’ had meant ‘never’, that injustice anywhere threatens justice everywhere, and set out the steps of a non-violent campaign.",
    chain: [["Jailed in Birmingham in April 1963 for protests", ["birmingham", "1963", "jail", "arrest", "protest"]], ["Eight clergymen called the protests untimely", ["clergy", "eight", "untimely", "unwise", "critic"]], ["Written in newspaper margins and on scraps of paper", ["margin", "newspaper", "scrap", "smuggl", "paper"]], ["‘Wait’ has meant ‘never’; injustice anywhere threatens justice everywhere", ["wait", "never", "injustice anywhere", "justice everywhere", "non-violent"]]],
    mcq: { q: "Who was the Letter from Birmingham Jail written to?", o: ["Eight white clergymen who had criticised the protests as untimely", "The President of the United States", "King's wife", "The Governor of Alabama"] },
    bring: "When told to wait for a better time: “King wrote from jail that ‘wait’ has almost always meant ‘never’.”",
    follow: "Is it better to answer your harshest critics or your most reasonable ones?",
    deeper: "King named Gandhi as a model for non-violent action and had visited India in 1959. The letter was published in magazines later in 1963 and is now taught in schools around the world." },

  { id: "lv-curie-two-nobels", type: "person", domain: "science", title: "Marie Curie: two Nobels and no patent", value: 4, cue: "scientists, women in science, or sharing knowledge versus owning it",
    emoji: "⚗️", wiki: "Marie Curie",
    fact: "Marie Curie won the Nobel Prize in Physics in 1903, shared with Pierre Curie and Henri Becquerel, and the Nobel Prize in Chemistry in 1911 on her own. She is the only person to win Nobels in two different sciences. She and Pierre chose not to patent their method for isolating radium, so anyone could use it.",
    why: "She could have become very rich from radium. She chose to let the whole world use her method instead.",
    mech: "To find radium she boiled down tonnes of pitchblende ore in a leaky shed, with Pierre, over about four years. The Curies believed the method belonged to science, so they published it freely. Radium became hugely valuable and other people profited. She later had to raise money to buy a single gram of radium for her own lab. The radioactive dust she carried home with her settled in her notebooks, which are still kept in lead-lined boxes today.",
    models: ["opportunity-cost", "network-effects"],
    q: "What did Marie Curie decide about patenting radium, and what did it cost her?",
    a: "She and Pierre published their method for isolating radium freely instead of patenting it, so anyone could use it. Others grew rich and she later had to raise money to buy a single gram of radium for her lab.",
    chain: [["Nobel in Physics 1903 and Chemistry 1911", ["1903", "1911", "two nobel", "physics", "chemistry"]], ["Isolated radium from tonnes of ore in a shed", ["pitchblende", "ore", "shed", "tonnes", "isolat"]], ["Chose not to patent the method", ["patent", "freely", "published", "belong", "anyone"]], ["Others profited; she had to raise money for radium", ["profit", "rich", "raise money", "gram", "buy"]]],
    mcq: { q: "Why did the Curies not patent their radium method?", o: ["They believed the method belonged to science and should be free for all", "French law banned all patents on chemicals", "They tried but another scientist had already patented it", "They did not know what a patent was"] },
    bring: "When people argue about patents: “Marie Curie gave away the method for making radium and later could not afford a gram of it.”",
    follow: "If you discovered something valuable, would you own it or share it?",
    deeper: "French law at the time would in any case have made it hard for a married woman to hold a patent in her own name. Her daughter Irène also won a Nobel Prize, in Chemistry in 1935." },

  { id: "lv-nightingale-diagram", type: "person", domain: "science", title: "Nightingale's chart that changed army hospitals", value: 5, cue: "data, charts, or how to convince people who do not read tables",
    emoji: "📊", wiki: "Florence Nightingale",
    fact: "Florence Nightingale is remembered as a nurse in the Crimean War of 1854 to 1856. She was also a statistician. In 1858 she published a rose-shaped chart showing that far more British soldiers died of disease than of wounds. In 1858 she became the first woman member of what is now the Royal Statistical Society.",
    why: "She knew generals would not read tables of numbers. A picture made the deaths impossible to ignore.",
    mech: "In the hospital at Scutari she counted deaths by cause each month. Most were from cholera, typhus and dysentery, spread by filth and crowding, not from battle. Her chart drew each month as a wedge, and the size of the wedge showed the deaths. Blue wedges for disease dwarfed red wedges for wounds. She sent it to the Queen and ministers. Army hospitals were cleaned up and death rates fell.",
    models: ["map-vs-territory", "bottlenecks", "first-principles"],
    q: "What did Nightingale's famous chart show, and why did she draw it?",
    a: "She counted deaths by cause and found most soldiers died of disease, not wounds. She drew it as a rose chart with wedges because generals would not read tables, and sent it to the Queen and ministers, leading to cleaner army hospitals.",
    chain: [["She counted deaths by cause in the Crimean hospital", ["count", "death", "cause", "scutari", "crimea", "statistic"]], ["Most died of disease, not wounds", ["disease", "cholera", "typhus", "not wound", "not of wounds", "filth"]], ["A rose chart with wedges, because generals would not read tables", ["rose", "wedge", "chart", "diagram", "table", "picture"]], ["Sent to the Queen; hospitals were cleaned up", ["queen", "minister", "clean", "fell", "reform"]]],
    mcq: { q: "What did Nightingale's 1858 rose diagram show?", o: ["That far more soldiers died of disease than of battle wounds", "That the army needed more cannons", "That nurses were paid too little", "That winter battles were the most deadly"] },
    bring: "When a report is full of tables: “Nightingale changed the British army with one chart. She knew nobody would read her tables.”",
    follow: "What number in your work would people act on if they could see it as a picture?",
    deeper: "In the worst months of early 1855, disease deaths were many times the deaths from wounds. She later used statistics to push for sanitation reform in India, a country she never visited." },

  { id: "lv-shackleton-endurance", type: "historical story", domain: "strategy", title: "Shackleton brought all 28 men home", value: 5, cue: "leadership in a crisis, failure that becomes a success, or keeping a team together", story: "shackleton",
    emoji: "🧊", wiki: "Imperial Trans-Antarctic Expedition",
    fact: "In 1915 Ernest Shackleton's ship Endurance was trapped and then crushed by Antarctic ice. It sank on 21 November 1915. For almost two years, 28 men lived on the ice and on a bare island. Shackleton sailed 800 miles in an open boat to fetch help. On 30 August 1916 every one of the 28 was rescued alive.",
    why: "He failed completely at his goal of crossing Antarctica. He is remembered as a great leader because of how he handled the failure.",
    mech: "When the ship was lost, he changed the goal from crossing the continent to getting everyone home. He kept the men busy, fed and in good spirits, and mixed troublemakers into his own tent. After months on drifting ice they rowed to Elephant Island. He then took five men in the small boat James Caird across the stormiest sea on Earth to South Georgia, then crossed its mountains on foot to a whaling station. He went back for the others four times until a ship got through.",
    models: ["margin-of-safety", "inversion", "feedback-loops"],
    q: "How did Shackleton save his crew after losing the Endurance?",
    a: "He changed the goal from crossing Antarctica to getting everyone home, and kept the men busy and hopeful on the ice. After reaching Elephant Island he sailed 800 miles in the James Caird to South Georgia, crossed its mountains, and returned with a ship to rescue all 28.",
    chain: [["Endurance crushed by ice and sank in November 1915", ["crush", "sank", "ice", "1915", "endurance"]], ["He changed the goal to getting everyone home", ["goal", "home", "everyone", "changed", "survival"]], ["Kept the men busy, fed and hopeful", ["busy", "spirit", "hope", "fed", "morale", "tent"]], ["800 miles in the James Caird, then rescue of all 28", ["800", "james caird", "south georgia", "28", "rescue", "all"]]],
    mcq: { q: "How many of Shackleton's 28 men survived the Endurance expedition?", o: ["All 28", "About half", "Only Shackleton and five others", "None"] },
    bring: "When a project fails: “Shackleton never crossed Antarctica. He is famous because he brought all 28 men home.”",
    follow: "When a plan collapses, how fast can you change what ‘success’ means?",
    deeper: "The wreck of Endurance was found in March 2022, 3,000 metres down in the Weddell Sea, in remarkably good condition. The ship's name came from Shackleton's family motto: by endurance we conquer." },

  { id: "lv-edison-invention-factory", type: "person", domain: "business", title: "Edison's invention factory", value: 4, cue: "innovation, R&D, or failing many times before success",
    emoji: "💡", wiki: "Thomas Edison",
    fact: "In 1876 Thomas Edison opened a laboratory at Menlo Park, New Jersey, and set it a target: a small invention every ten days and a big one every six months or so. It was the first industrial research lab. Edison ended his life with 1,093 US patents, more than anyone of his time.",
    why: "He treated invention as a process you can organise, not a flash of genius. That idea built every modern research lab.",
    mech: "He hired machinists, chemists and glass-blowers and put them in one building with every tool and material. Ideas were tested at once, in many versions at a time. Failures were recorded, so the same mistake was not made twice. The phonograph in 1877 and a practical electric light bulb in 1879 came out of this system. The lab, not the lone man, was the invention.",
    models: ["compounding", "first-principles", "feedback-loops"],
    q: "What was new about Edison's Menlo Park laboratory?",
    a: "He ran invention as an organised process: a team of skilled men in one building with every tool, testing many versions at once and recording failures, with a target of a small invention every ten days.",
    chain: [["A lab with a target: a small invention every ten days", ["ten days", "target", "menlo park", "1876", "every six months"]], ["Skilled team and every tool in one building", ["team", "machinist", "chemist", "tool", "one building", "hired"]], ["Many versions tested at once; failures recorded", ["version", "test", "failure", "record", "mistake"]], ["Phonograph 1877, light bulb 1879, 1,093 patents", ["phonograph", "bulb", "1879", "1,093", "1093", "patent"]]],
    mcq: { q: "What target did Edison set for his Menlo Park laboratory?", o: ["A small invention every ten days and a big one every six months or so", "One invention a year", "A patent every day", "To beat Tesla to every idea"] },
    bring: "When someone waits for inspiration: “Edison did not wait. He built a factory for ideas with a quota of one every ten days.”",
    follow: "Could your team set a quota for small experiments the way Edison did?",
    deeper: "The famous line about finding 10,000 ways that do not work comes from a story told by an associate years later, and the number changes with each telling. Treat the exact words as uncertain, though the attitude was his." },

  { id: "lv-wright-wind-tunnel", type: "person", domain: "science", title: "The Wright brothers stopped trusting the tables", value: 5, cue: "testing things yourself, expert data, or the first flight",
    emoji: "🛩️", wiki: "Wright Flyer",
    fact: "Wilbur and Orville Wright ran a bicycle shop in Dayton, Ohio. Their 1901 glider produced only about a third of the lift that published tables predicted. So in late 1901 they built a small wind tunnel and measured about 200 wing shapes themselves. On 17 December 1903 their Flyer made the first powered, controlled flight: 12 seconds and 120 feet.",
    why: "Two men with no degrees beat well-funded experts because they checked the data instead of trusting it.",
    mech: "The lift tables everyone used included a number measured a century earlier that was wrong by about a third. The brothers noticed the gap between prediction and result and refused to explain it away. Their wind tunnel, a wooden box with a fan driven by the shop engine, gave them correct numbers in weeks. They also solved control by warping the wings, an idea from watching birds and twisting a bicycle inner-tube box. Correct data plus control gave them flight.",
    models: ["first-principles", "map-vs-territory", "confirmation-bias"],
    q: "Why did the Wright brothers build a wind tunnel, and what came of it?",
    a: "Their 1901 glider gave only a third of the lift the published tables predicted, so they measured about 200 wing shapes in their own wind tunnel. With correct data and wing-warping for control, they flew on 17 December 1903.",
    chain: [["The 1901 glider gave a third of the predicted lift", ["third", "1901", "glider", "lift", "predict"]], ["They refused to explain the gap away and tested themselves", ["wind tunnel", "measure", "test", "themselves", "200"]], ["The old tables had a wrong number", ["wrong", "table", "number", "century", "error"]], ["First powered flight, 17 December 1903", ["1903", "12 seconds", "120 feet", "first", "flyer"]]],
    mcq: { q: "What did the Wright brothers do when their glider underperformed the published tables?", o: ["Built their own wind tunnel and measured wing shapes themselves", "Gave up flying and returned to bicycles", "Hired a university professor to redo the maths", "Copied a French glider design"] },
    bring: "When everyone trusts the same spreadsheet: “The Wright brothers flew because they stopped trusting the lift tables and measured for themselves.”",
    follow: "Which number in your work does everyone use but nobody has checked?",
    deeper: "Samuel Langley, head of the Smithsonian, had government money and crashed his own machine into the Potomac nine days before the Wrights flew. Orville flew first; the longest flight that day, by Wilbur, lasted 59 seconds." },

  { id: "lv-rosa-parks-prepared", type: "person", domain: "history", title: "Rosa Parks was not just tired", value: 4, cue: "protest, quiet courage, or the myth of the accidental hero",
    emoji: "🚌", wiki: "Rosa Parks",
    fact: "On 1 December 1955 Rosa Parks refused to give up her bus seat to a white man in Montgomery, Alabama, and was arrested. She is often described as a tired seamstress. In fact she had been secretary of the local NAACP civil rights group since 1943 and had attended a training school for activists that summer.",
    why: "The famous story makes her act look like chance. The real one shows years of preparation waiting for the right moment.",
    mech: "Local activists had been looking for a test case against bus segregation. Parks knew the law and the risks and had thought about what she would do. When the driver ordered her to move, she stayed seated and let herself be arrested calmly. Because her record was spotless, the city could not smear her. Her arrest set off a bus boycott by Montgomery's Black residents that lasted 381 days, until the courts struck down bus segregation.",
    models: ["second-order-thinking", "incentives", "social-proof"],
    q: "Why is the ‘tired seamstress’ version of Rosa Parks misleading?",
    a: "She was a trained activist, NAACP secretary since 1943, who knew the law and the risks. Her calm, spotless arrest gave activists the test case they wanted, and the 381-day bus boycott followed.",
    chain: [["She refused to give up her seat on 1 December 1955", ["seat", "1955", "refused", "montgomery", "bus"]], ["She was a trained activist, not a chance protester", ["naacp", "secretary", "activist", "trained", "1943", "school"]], ["A spotless record made her the right test case", ["record", "spotless", "test case", "smear", "calm"]], ["A 381-day boycott ended bus segregation", ["381", "boycott", "segregation", "court", "struck"]]],
    mcq: { q: "What was Rosa Parks's role before her famous arrest?", o: ["Secretary of the local NAACP civil rights group", "A schoolteacher with no political links", "A newspaper reporter", "A bus company employee"] },
    bring: "When someone calls a protest spontaneous: “Rosa Parks had been an NAACP officer for 12 years. She said the only tired she was, was tired of giving in.”",
    follow: "What are you preparing for now that others might one day call luck?",
    deeper: "In her 1992 autobiography she wrote that she was not physically tired that day, only tired of giving in. Nine months earlier a 15-year-old, Claudette Colvin, had done the same thing, but activists judged her case less likely to win public support." },

  { id: "lv-malala-blog", type: "person", domain: "history", title: "Malala wrote before she was famous", value: 4, cue: "girls' education, courage of the young, or speaking out under threat",
    emoji: "📚", wiki: "Malala Yousafzai",
    fact: "In early 2009, at the age of 11, Malala Yousafzai began writing an anonymous blog for BBC Urdu about life in Pakistan's Swat valley, where the Taliban had banned girls from school. On 9 October 2012 a gunman boarded her school bus and shot her in the head. She survived. In 2014, at 17, she became the youngest Nobel Peace Prize winner.",
    why: "She spoke up as a child when adults around her were silent. The attack meant to silence her gave her a voice heard around the world.",
    mech: "Her father ran a school and refused to close it, so she grew up seeing resistance as normal. The blog, under the pen name Gul Makai, told the world what the ban felt like to one girl. Her identity became known and the threats grew. After the shooting she was flown to Britain for treatment and kept speaking. The Taliban had made her a symbol by trying to kill her.",
    models: ["second-order-thinking", "commitment-consistency"],
    q: "How did Malala become known, and what happened after the attack?",
    a: "At 11 she wrote an anonymous BBC Urdu blog about the Taliban's ban on girls' schools in Swat. She was shot in 2012, survived, kept speaking from Britain, and won the Nobel Peace Prize at 17 in 2014.",
    chain: [["Taliban banned girls' schools in Swat", ["swat", "taliban", "ban", "girls", "school"]], ["At 11 she wrote an anonymous BBC Urdu blog", ["blog", "bbc", "11", "eleven", "gul makai", "anonymous"]], ["Shot on her school bus in October 2012 and survived", ["shot", "2012", "bus", "survived", "head"]], ["Youngest Nobel Peace Prize winner, 2014", ["nobel", "2014", "youngest", "17"]]],
    mcq: { q: "How did Malala first become known outside Swat?", o: ["By writing an anonymous blog for BBC Urdu at age 11", "By winning a national debate competition", "By appearing in a Pakistani film", "By leading a march to Islamabad"] },
    bring: "When girls' schooling comes up: “Malala was 11 when she began writing about the school ban. The Taliban shot her to silence her and made her famous instead.”",
    follow: "Why do attempts to silence someone so often make them louder?",
    deeper: "She shared the 2014 prize with Kailash Satyarthi of India. Her birthday, 12 July, is marked by the United Nations as Malala Day." },

  { id: "lv-kariko-mrna", type: "person", domain: "science", title: "Karikó: thirty years of rejection before mRNA", value: 5, cue: "persistence, research funding, or how the COVID vaccines were possible",
    emoji: "🧬", wiki: "Katalin Karikó",
    fact: "Katalin Karikó, a Hungarian scientist in the United States, spent the 1990s trying to make mRNA, a molecule that carries instructions to cells, into a medicine. Her grant applications kept failing. In 1995 the University of Pennsylvania demoted her. In 2005 she and Drew Weissman published the fix that made mRNA vaccines possible. They won the Nobel Prize in Medicine in 2023.",
    why: "The COVID vaccines of 2020 were built on work that funders had judged a dead end for decades.",
    mech: "When mRNA was injected, the body's immune system attacked it as a foreign invader, so it caused inflammation and was quickly destroyed. Karikó and Weissman found that swapping one building block of the RNA, a change the body itself uses, made the immune system ignore it. Reviewers were not interested. Two small companies, BioNTech and Moderna, built on the paper. When COVID came in 2020, the method produced vaccines within a year.",
    models: ["survivorship-bias", "second-order-thinking", "circle-of-competence"],
    q: "What problem did Karikó solve, and why did it take so long to be recognised?",
    a: "Injected mRNA triggered the immune system and was destroyed. She and Weissman found in 2005 that changing one building block made the body ignore it. Funders had rejected her for years and she was demoted in 1995, but BioNTech and Moderna built on the work and it gave COVID vaccines in 2020.",
    chain: [["Grants rejected; demoted in 1995", ["demot", "1995", "rejected", "grant", "funding"]], ["Injected mRNA set off the immune system", ["immune", "inflammation", "attack", "destroyed", "foreign"]], ["Swapping one building block made the body ignore it, 2005", ["building block", "nucleoside", "swap", "chang", "2005", "ignore"]], ["COVID vaccines in 2020; Nobel 2023", ["covid", "2020", "vaccine", "nobel", "2023", "biontech", "moderna"]]],
    mcq: { q: "What was the key discovery by Karikó and Weissman in 2005?", o: ["Changing one building block of mRNA stopped the immune system from attacking it", "A way to freeze vaccines at room temperature", "The structure of the coronavirus spike", "A cheaper way to make syringes"] },
    bring: "When research funding comes up: “The COVID vaccine's key idea came from a scientist who was demoted in 1995 because nobody would fund her.”",
    follow: "How do you tell a dead end from an idea that is simply early?",
    deeper: "Karikó moved to BioNTech in 2013. The Pfizer-BioNTech and Moderna vaccines both use the modified building block from the 2005 paper." },

  { id: "lv-bannister-mile", type: "person", domain: "psychology", title: "Bannister's four-minute mile and who followed", value: 4, cue: "mental barriers, records, or how one person's success changes what others believe",
    emoji: "🏅", wiki: "Roger Bannister",
    fact: "On 6 May 1954 Roger Bannister, a 25-year-old medical student, ran a mile in 3 minutes 59.4 seconds at Oxford. He was the first person to run a mile in under four minutes. Only 46 days later, John Landy of Australia ran faster still. Within about three years, around ten more runners had done it.",
    why: "People had called four minutes a limit of the human body. Once one man crossed it, others found that they could too.",
    mech: "Bannister trained for about half an hour a day during his hospital lunch breaks, and planned the race with two friends who set the pace for him. The barrier was partly physical and partly belief: nobody knew how it would feel to run that fast. His run gave others proof that it was possible, and a time to aim at. Landy, who had run 4:02 several times, broke the record almost at once.",
    models: ["social-proof", "map-vs-territory", "availability-bias"],
    q: "What happened after Bannister broke the four-minute mile?",
    a: "Bannister ran 3:59.4 on 6 May 1954 with friends pacing him, after training in lunch breaks. Landy beat his time 46 days later, and within about three years around ten more runners had gone under four minutes, because the barrier was partly belief.",
    chain: [["First mile under four minutes, 6 May 1954", ["1954", "3:59", "four minutes", "first", "oxford"]], ["Trained in lunch breaks; friends paced the race", ["lunch", "half an hour", "pace", "friend", "medical student"]], ["Landy broke it 46 days later", ["landy", "46", "days later", "australia"]], ["The barrier was partly belief", ["belief", "mental", "possible", "proof", "limit"]]],
    mcq: { q: "How soon after Bannister did the next runner break four minutes?", o: ["About 46 days", "About ten years", "The same afternoon", "Not until the 1970s"] },
    bring: "When someone says something cannot be done: “People said that about the four-minute mile. After Bannister did it in 1954, another man did it within seven weeks.”",
    follow: "What limit do you accept only because nobody you know has crossed it?",
    deeper: "You will hear that dozens broke four minutes within a year. That is not true; the record books show one more in 1954 and a slow trickle after. Bannister went on to a long career as a neurologist and said he was prouder of his medical work." },

  { id: "lv-braille-fifteen", type: "person", domain: "science", title: "Louis Braille invented Braille at fifteen", value: 4, cue: "disability, inventions by young people, or simplifying a complex system",
    emoji: "⠃", wiki: "Louis Braille",
    fact: "Louis Braille lost his sight at about age three after an accident in his father's workshop in France. At a school for blind children in Paris he met a 12-dot code made by an army officer for messages in the dark. By 1824, at age 15, he had cut it to a 6-dot cell a fingertip could read at once. It is still used worldwide.",
    why: "The adult inventor had built a system for soldiers. A blind teenager saw what was wrong with it and fixed it.",
    mech: "Charles Barbier's night writing used 12 dots per symbol and stood for sounds, not letters. A finger had to move to read one symbol, and it could not spell properly. Braille shrank the cell to 6 dots, two columns of three, the size of a fingertip. That gave 63 patterns, enough for the alphabet, numbers and punctuation. Reading became fast because each cell was felt in one touch. His school did not officially adopt it until 1854, two years after he died.",
    models: ["first-principles", "bottlenecks", "lindy-effect"],
    q: "What was wrong with the 12-dot code, and how did Braille fix it?",
    a: "Barbier's 12-dot night writing was too big for one fingertip and stood for sounds, not letters. Braille cut it to a 6-dot cell, read in one touch, giving 63 patterns for letters, numbers and punctuation. It was adopted officially in 1854, after his death.",
    chain: [["Barbier's 12-dot night writing for soldiers", ["barbier", "12", "twelve", "night writing", "soldier", "army"]], ["Too big for one fingertip and based on sounds", ["fingertip", "too big", "sound", "move", "spell"]], ["A 6-dot cell read in one touch, 63 patterns", ["6", "six", "63", "cell", "one touch", "fingertip"]], ["Adopted officially in 1854, after his death in 1852", ["1854", "1852", "adopt", "after he died", "death"]]],
    mcq: { q: "How many dots does a Braille cell have?", o: ["Six", "Twelve", "Three", "Twenty-six"] },
    bring: "When a system feels too complicated: “Braille was a 15-year-old who cut a 12-dot army code down to 6 dots. We still use his version.”",
    follow: "Which system you use every day could be cut in half without losing anything?",
    deeper: "Braille also worked out codes for music and mathematics. World Braille Day is 4 January, his birthday. In India, Braille is used for all major scripts through a shared system called Bharati Braille." },

  { id: "lv-petrov-1983", type: "person", domain: "strategy", title: "Petrov: the other man who said no", value: 5, cue: "false alarms, trusting machines, or quiet decisions that mattered",
    emoji: "🛰️", wiki: "Stanislav Petrov",
    fact: "Just after midnight on 26 September 1983, Soviet officer Stanislav Petrov was on duty at a secret early-warning centre. The computer reported that the United States had launched five nuclear missiles at the Soviet Union. His job was to report an attack up the chain. He judged it a false alarm and reported a system fault instead.",
    why: "Cold War tensions were very high that autumn. A report of attack might have led to a Soviet counter-strike. He had minutes to decide.",
    mech: "Petrov reasoned that a real American attack would use hundreds of missiles, not five. Ground radar saw nothing. He knew the new satellite system had problems. So he trusted his judgment of what made sense over what the screen said. The alarm was later traced to sunlight reflecting off high clouds, which the satellites read as rocket flames. He was neither punished nor rewarded at the time.",
    models: ["bayesian-thinking", "map-vs-territory", "second-order-thinking"],
    q: "Why did Petrov decide the 1983 missile alarm was false?",
    a: "The screen showed only five missiles, but a real attack would use hundreds. Ground radar saw nothing and he knew the new satellites had faults. He reported a system error, and the cause turned out to be sunlight on high clouds.",
    chain: [["The computer reported five US missiles, 26 September 1983", ["five", "5", "1983", "computer", "screen", "missile"]], ["A real attack would use hundreds, and radar saw nothing", ["hundred", "radar", "nothing", "make sense", "real attack"]], ["He reported a system fault instead of an attack", ["fault", "false alarm", "error", "reported", "did not report"]], ["Cause: sunlight reflecting off high clouds", ["sunlight", "cloud", "reflect", "sun"]]],
    mcq: { q: "What caused the 1983 Soviet missile false alarm?", o: ["Sunlight reflecting off high clouds, read by satellites as rocket flames", "An American test launch", "A hacker in the Soviet system", "A power cut at the centre"] },
    bring: "When someone trusts a dashboard over common sense: “In 1983 a Soviet computer said five missiles were coming. Petrov asked why only five, and said no.”",
    follow: "When a system you rely on gives a strange reading, what question would you ask first?",
    deeper: "His story became public only in the 1990s. He received international awards late in life and died in 2017. In 1962, submarine officer Vasily Arkhipov had made a similar refusal during the Cuban missile crisis." },

  { id: "lv-salk-patent-sun", type: "person", domain: "science", title: "Salk: could you patent the sun?", value: 4, cue: "vaccines, polio, or whether lifesaving things should be owned",
    emoji: "💉", wiki: "Jonas Salk",
    fact: "On 12 April 1955 the United States announced that Jonas Salk's polio vaccine worked. The same evening, on television, the journalist Edward Murrow asked him who owned the patent. Salk replied: ‘Well, the people, I would say. There is no patent. Could you patent the sun?’",
    why: "Polio paralysed tens of thousands of children a year. A vaccine that anyone could make spread far faster than one company could sell it.",
    mech: "The vaccine was funded by millions of small public donations through the March of Dimes charity, so Salk felt it already belonged to the public. With no patent, many manufacturers could make it at once. Cases in the US fell sharply within a few years. India later used both Salk's injected vaccine and Sabin's oral drops in its own campaign and was declared polio-free in 2014.",
    models: ["network-effects", "opportunity-cost", "incentives"],
    q: "What did Salk say about patenting the polio vaccine, and why did it matter?",
    a: "Asked who owned the patent, he said ‘the people’ and ‘could you patent the sun?’. The vaccine had been paid for by public donations, and with no patent many makers could produce it, so cases fell fast.",
    chain: [["Polio vaccine announced to work on 12 April 1955", ["1955", "announced", "polio", "worked"]], ["Asked about the patent, he said ‘the people’", ["people", "patent", "murrow", "who owned"]], ["‘Could you patent the sun?’", ["sun", "patent the sun"]], ["No patent, so many makers and fast spread", ["many", "manufactur", "makers", "fell", "donation", "public"]]],
    mcq: { q: "What was Salk's reply when asked who owned the polio vaccine patent?", o: ["‘The people. There is no patent. Could you patent the sun?’", "‘The University of Pittsburgh owns it’", "‘I will sell it to the highest bidder’", "‘The United States Army’"] },
    bring: "When a medicine's price comes up: “Jonas Salk was asked who owned the polio vaccine patent. He said: could you patent the sun?”",
    follow: "Should some discoveries be impossible to own?",
    deeper: "Lawyers for the charity had in fact looked into a patent and concluded the vaccine could not be patented because of earlier work. So the famous line was partly a choice and partly a legal fact. Salk never grew rich from the vaccine." }
  ]));

  MV.STORIES.push(
  { id: "manjhi", assetId: "lv-manjhi-mountain", title: "The Man Who Moved a Mountain",
    hook: "A poor labourer in Bihar lost his wife to a hill. So he spent 22 years cutting the hill in half with a hammer.",
    setting: "Gehlaur village, Gaya district, Bihar, around 1959. A ridge of rock separates the village from the nearest town with a doctor, a market and a school. Going around it means a trip of about 55 km.",
    character: "Dashrath Manjhi, a landless labourer from a poor community, and his wife Falguni Devi, who brought him food and water while he worked.",
    conflict: "In 1959 Falguni Devi fell while crossing the hill. She was badly hurt, and she died because the doctor was too far away. Dashrath decided that the hill itself had killed her.",
    surprise: "Instead of grieving quietly, he sold his goats, bought a hammer and a chisel, and began to cut a path through the solid rock. Alone. Villagers called him mad.",
    turning: "He worked year after year, often at night after a day of farm labour. Slowly a gap appeared. Some villagers began to bring him food. The gap grew wide enough for a person, then for a cart.",
    payoff: "In 1982, after 22 years, the path was done: 110 metres long and about 9 metres wide. The journey to town fell from about 55 km to about 15 km. Children could reach school and the sick could reach a doctor.",
    meaning: "A huge problem can be beaten by a small effort repeated every day for a very long time. The important choice is to start, and to treat the problem as yours to solve.",
    extra: ["He is said to have walked to Delhi along the railway line to ask the government to build a proper road, and was turned away.", "Bihar gave him a state funeral when he died in 2007, and the road is named after him.", "The 2015 film Manjhi: The Mountain Man told his story to all of India."],
    facts: [["1959", "wife", "falguni"], ["hammer", "chisel"], ["22 years", "1982"], ["110"], ["55", "15 km"], ["gehlaur", "bihar", "gaya"]],
    vocab: ["persistence", "ridge", "landless"] },

  { id: "neerja", assetId: "lv-neerja-pan-am", title: "Seventeen Hours in Karachi",
    hook: "Four armed men stormed a plane from Mumbai. The most senior crew member left on board was a 22-year-old woman.",
    setting: "Karachi airport, 5 September 1986. Pan Am Flight 73 from Mumbai to New York is on the ground, with about 360 passengers and crew on board.",
    character: "Neerja Bhanot, senior flight purser, born in Chandigarh and raised in Mumbai, a former model who had joined Pan Am about a year earlier.",
    conflict: "Four hijackers dressed as airport guards forced their way on board with guns and grenades. They wanted the plane flown to another country, and they wanted to find the American passengers.",
    surprise: "In the first moments Neerja passed the hijack code to the cockpit. The three pilots escaped through a hatch above them. With no pilots, the plane could not take off, and the hijackers were stuck on the ground.",
    turning: "The hijackers ordered the crew to collect passports so they could pick out Americans. Neerja and her crew hid the American passports under seats and in rubbish chutes. For about 17 hours she kept passengers calm while the men threatened and shot.",
    payoff: "When the plane's power failed and the lights went out, the hijackers opened fire. Neerja opened an emergency exit so passengers could escape down the slide. She was killed shielding three children. About 20 people died; most of the 360 survived.",
    meaning: "Courage is often a set of small, trained decisions made one after another. She did her job, each step of it, when the cost of doing it was her life.",
    extra: ["She was awarded the Ashoka Chakra, India's highest peacetime bravery award, and remains its youngest recipient.", "She had sent the hijack alert so fast that the pilots were gone before the hijackers reached the cockpit.", "A square in Mumbai's Ghatkopar is named after her, and the 2016 film Neerja told her story."],
    facts: [["1986", "5 september"], ["karachi"], ["pan am", "73"], ["cockpit", "pilot"], ["passport"], ["exit", "slide"], ["three children"]],
    vocab: ["purser", "hijack", "shield"] },

  { id: "shackleton", assetId: "lv-shackleton-endurance", title: "By Endurance We Conquer",
    hook: "He set out to cross Antarctica and lost his ship before he even reached it. Then he spent two years bringing every man home.",
    setting: "The Weddell Sea, Antarctica, 1915. The wooden ship Endurance, with 28 men aboard, is frozen fast in the pack ice, hundreds of miles from land, with no radio that can reach anyone.",
    character: "Ernest Shackleton, an Irish-born explorer who had failed twice to reach the South Pole, and his crew of sailors, scientists and a stowaway.",
    conflict: "The ice drifted for ten months, squeezing the ship. On 21 November 1915 Endurance was crushed and sank. The men were left on moving ice with three small boats and whatever they could drag.",
    surprise: "Shackleton quietly dropped the expedition's goal. The new goal was simple: everyone goes home alive. He kept the men busy, fed and in good humour, and put the grumblers in his own tent where he could watch them.",
    turning: "When the ice broke up in April 1916 they rowed to Elephant Island, a bare rock nobody visited. Shackleton then took five men in the 7-metre boat James Caird across 800 miles of the stormiest ocean on Earth to South Georgia. They landed on the wrong side and crossed its unmapped mountains on foot in 36 hours.",
    payoff: "He reached a whaling station and went back for his men. Ice stopped him three times. On 30 August 1916 the Chilean tug Yelcho got through to Elephant Island. All 28 men were alive.",
    meaning: "When the original plan is dead, a leader's first job is to name the new goal clearly and keep everyone believing in it. Shackleton failed at exploring and succeeded at leading.",
    extra: ["The men on Elephant Island lived for four months under two upturned boats, eating penguins and seals.", "The navigator Frank Worsley steered the James Caird using only a few glimpses of the sun through cloud.", "The wreck of Endurance was found in March 2022, 3,000 metres down, with its name still clear on the stern."],
    facts: [["endurance"], ["1915", "21 november"], ["crush", "sank"], ["elephant island"], ["james caird", "800"], ["south georgia"], ["28", "every man", "all"]],
    vocab: ["expedition", "stowaway", "morale"] }
  );

  MV.LINKS.push(
    /* links to existing ideas */
    ["lv-sudha-murty-postcard", "in-infosys-y2k", "The woman who wrote the postcard in 1974 lent the 10,000 rupees that started Infosys in 1981."],
    ["lv-sudha-murty-postcard", "savitribai-phule", "Both fought a rule that kept women out: one from schools in the 1840s, one from a factory floor in 1974."],
    ["lv-sreedharan-metro", "mh-konkan-railway", "The same engineer: Konkan Railway first, then the Delhi Metro, both delivered against the usual delays."],
    ["lv-sreedharan-metro", "dabbawalas", "Both run on a shared clock that everyone can see, so no one can quietly fall behind."],
    ["lv-ela-bhatt-sewa", "in-lijjat", "Both let poor women earn and save together, through a union in one case and a cooperative in the other."],
    ["lv-ela-bhatt-sewa", "mw-hawkers", "SEWA's first members were street vendors like Mumbai's hawkers: working hard with no employer and no legal protection."],
    ["lv-satyarthi-child-labour", "th-ambedkar-educate", "Both saw that freeing people one at a time is not enough; the rules and organisations must change."],
    ["lv-arunima-everest", "is-jaipur-foot", "Low-cost artificial legs are what let Indian amputees walk, run and even climb."],
    ["lv-arunima-everest", "th-buddha-second-arrow", "The train took her leg, the first arrow. She refused to shoot the second arrow of despair at herself."],
    ["lv-milkha-rome", "loss-aversion", "Fear of losing a lead made him ease off and look back, and the fear caused the loss."],
    ["lv-milkha-rome", "im-15-august-date", "His parents were killed in the violence of Partition that followed independence in 1947."],
    ["lv-usha-hundredth", "mhc-gavaskar-10000", "Both are Indian sporting landmarks of the 1980s, one a record reached and one a medal missed by a hundredth."],
    ["lv-manjhi-mountain", "mhc-ralegan-siddhi", "One man's hill road and one village's water system: both were built by local hands when nobody else would."],
    ["lv-manjhi-mountain", "money-start-early", "Both show the power of small amounts added every day for decades."],
    ["lv-neerja-pan-am", "mw-26-11", "Hotel staff in 2008 and a flight purser in 1986: ordinary workers who put guests and passengers before themselves."],
    ["lv-anandibai-doctor", "savitribai-phule", "Phule opened a girls' school in Pune in 1848; thirty-eight years later a woman from near Mumbai earned a medical degree."],
    ["lv-anandibai-doctor", "is-sushruta-nose", "Indian medicine had an ancient tradition; what was new in 1886 was a woman trained in modern medicine."],
    ["lv-ratan-tata-two-bets", "in-tata-steel", "Jamsetji's steel and Ratan Tata's cars: the same group betting on heavy industry a century apart."],
    ["lv-ratan-tata-two-bets", "ec-creative-destruction", "Ford sold Jaguar Land Rover at a loss; a new owner with new money turned it around."],
    ["lv-jamsetji-after-death", "in-tata-steel", "The steel dream is one of the three plans finished after his death in 1904."],
    ["lv-jamsetji-after-death", "mh-mumbai-water", "Tata's hydro-electric scheme used the same Western Ghats rain that fills Mumbai's lakes."],
    ["lv-lincoln-unsent-letter", "stoic-control", "He could not control Meade's choices, only his own reply to them."],
    ["lv-lincoln-unsent-letter", "th-seneca-premeditatio", "Both are habits for handling strong feeling: imagine the harm before it happens, or write the anger down and wait."],
    ["lv-mandela-afrikaans", "wm-mandela", "The prison study of Afrikaans is part of how the negotiations of the early 1990s succeeded."],
    ["lv-mandela-afrikaans", "sun-tzu", "Know your enemy: Mandela did it with a grammar book and the warders as teachers."],
    ["lv-king-birmingham-letter", "salt-march", "King named Gandhi as his model; the Salt March was the template for breaking an unjust law in public."],
    ["lv-king-birmingham-letter", "mahad-satyagraha", "Both were public acts against a rule of exclusion, answered by careful written argument."],
    ["lv-curie-two-nobels", "is-patents-generics", "Curie gave away the radium method; India's 1970 patent law also put access ahead of ownership."],
    ["lv-curie-two-nobels", "sp-radiocarbon", "Both depend on radioactive decay, which Curie's work on radium first made understood."],
    ["lv-nightingale-diagram", "semmelweis", "Both found that dirt killed patients; Nightingale's chart convinced people where Semmelweis's tables failed."],
    ["lv-nightingale-diagram", "wm-minard-1812", "Two famous charts of the 1850s and 1860s that made deaths visible at a glance."],
    ["lv-nightingale-diagram", "wald-bombers", "Both used careful counting to overturn what the generals believed."],
    ["lv-shackleton-endurance", "ig-kanchenjunga", "Both are about expedition leadership in extreme cold, and about knowing when the summit no longer matters."],
    ["lv-shackleton-endurance", "margin-of-safety", "Three boats, extra food and a leader who planned for failure gave the men enough buffer to survive."],
    ["lv-edison-invention-factory", "sp-war-of-currents", "The same Edison who built the lab backed the losing side in the fight over AC and DC."],
    ["lv-edison-invention-factory", "th-smith-pin-factory", "Edison applied the division of labour to inventing, with specialists for each step."],
    ["lv-wright-wind-tunnel", "th-feynman-fool-yourself", "The Wrights refused to fool themselves when the glider did not match the tables."],
    ["lv-wright-wind-tunnel", "mp-juhu-first-flight", "Only eight years after Kitty Hawk, the first airmail flight in India took off near Mumbai."],
    ["lv-rosa-parks-prepared", "wald-bombers", "We remember the one arrest that worked and forget the earlier ones that activists judged unlikely to succeed."],
    ["lv-rosa-parks-prepared", "lv-king-birmingham-letter", "Her 1955 arrest launched the boycott that made King a national leader; his 1963 letter defended the method."],
    ["lv-malala-blog", "lv-satyarthi-child-labour", "They shared the 2014 Nobel Peace Prize for children's rights, one Pakistani and one Indian."],
    ["lv-malala-blog", "th-tagore-without-fear", "Both are about speaking the truth in a place where fear was meant to silence it."],
    ["lv-kariko-mrna", "wm-covid-vaccine", "The 2005 modified-RNA paper is the science that made the one-year vaccine possible."],
    ["lv-kariko-mrna", "bm-patience", "Thirty years of rejected grants before the payoff: the big money really was in the waiting."],
    ["lv-bannister-mile", "anchoring", "Four minutes was an anchor in runners' minds until one man moved it."],
    ["lv-bannister-mile", "lv-usha-hundredth", "Both are about tiny margins of time on the track, and what a record or a near miss does to belief."],
    ["lv-braille-fifteen", "wh-phoenician-alphabet", "Both cut a complex writing system down to a small set of simple signs that anyone could learn."],
    ["lv-braille-fifteen", "is-jaipur-foot", "Both are simple, cheap designs for disabled people that spread across the world."],
    ["lv-petrov-1983", "cuban-submarine", "Arkhipov in 1962 and Petrov in 1983: two Soviet officers who refused to start a nuclear war."],
    ["lv-petrov-1983", "cold-war-mad", "Mutually assured destruction only works if nobody fires by mistake; Petrov is why it held in 1983."],
    ["lv-petrov-1983", "map-territory", "The screen said five missiles; the territory had none."],
    ["lv-salk-patent-sun", "is-polio-free", "India's 2014 polio-free status rests on vaccines whose inventors did not lock them behind patents."],
    ["lv-salk-patent-sun", "lv-curie-two-nobels", "Curie and Salk both chose not to own what they had made, and said so plainly."],
    ["lv-salk-patent-sun", "is-serum-institute", "A vaccine with no patent is exactly what a low-cost mass producer can make."],
    ["lv-homai-vyarawalla", "im-15-august-date", "She photographed the first Independence Day celebrations in Delhi in August 1947."],
    ["lv-homai-vyarawalla", "bm-inner-scorecard", "She judged her work by the pictures, not by whose name was printed under them."],
    ["lv-somnath-sharma-badgam", "im-kashmir-accession", "The troops he was protecting had been flown in only days after the Instrument of Accession was signed."],
    ["lv-somnath-sharma-badgam", "thermopylae", "A small force holding a vital point against many, long enough for others to act."],
    ["lv-somnath-sharma-badgam", "im-kargil", "Captain Vikram Batra in 1999 and Major Somnath Sharma in 1947 both earned the Param Vir Chakra in Kashmir."],
    ["lv-keller-water-pump", "savitribai-phule", "Both are about a teacher opening a door that others had decided should stay shut."],
    ["lv-keller-water-pump", "th-aristotle-habit", "Weeks of practice with no visible result were building the habit that made the breakthrough possible."],
    /* links within the pack */
    ["lv-keller-water-pump", "lv-braille-fifteen", "Braille's six dots and Sullivan's finger spelling: two ways of putting words into a hand."],
    ["lv-homai-vyarawalla", "lv-anandibai-doctor", "Two women connected to Mumbai who were the first Indians of their sex in their profession."],
    ["lv-somnath-sharma-badgam", "lv-neerja-pan-am", "Both were young Indians who stayed at their post when leaving would have saved them."],
    ["lv-mandela-afrikaans", "lv-king-birmingham-letter", "Both chose to argue with their opponents in words those opponents respected, rather than only to defy them."],
    ["lv-sreedharan-metro", "lv-jamsetji-after-death", "Both built public works that outlast their builders, by planning in detail and keeping politics out."],
    ["lv-milkha-rome", "lv-usha-hundredth", "Two Indian fourth places, 1960 and 1984, each a fraction of a second from a medal."],
    ["lv-arunima-everest", "lv-manjhi-mountain", "A lost leg and a lost wife: both answered a tragedy with a goal far bigger than the loss."],
    ["lv-neerja-pan-am", "lv-shackleton-endurance", "Both are stories of someone keeping others alive by staying calm and acting step by step."],
    ["lv-nightingale-diagram", "lv-wright-wind-tunnel", "Both trusted their own careful measurements over what the experts of the day believed."],
    ["lv-edison-invention-factory", "lv-kariko-mrna", "Edison organised failure into a process; Karikó lived through decades of it before the breakthrough."],
    ["lv-anandibai-doctor", "lv-sudha-murty-postcard", "Two women from the Mumbai region who broke a rule about what women could do, 88 years apart."],
  );
})();
