/* Arts, culture and sport: stories behind famous things. Same shape as data-india.js. */
(function () {
  const P = list => list.map(a => Object.assign({ story: null, jargon: [], mis: [] }, a));

  MV.ASSETS.push(...P([

  /* ---------- World: art ---------- */

  { id: "ar-mona-lisa-theft", type: "historical story", domain: "history", title: "The Mona Lisa became famous by being stolen", value: 4, cue: "famous paintings, museums, or why some things become famous", story: "monalisa",
    emoji: "🖼️", wiki: "Mona Lisa",
    fact: "On 21 August 1911 a worker named Vincenzo Peruggia walked out of the Louvre in Paris with the Mona Lisa under his coat. Before the theft it was a respected painting known mainly to art lovers. The two years it was missing made it the most famous painting in the world.",
    why: "Fame often comes from a story, not only from quality. The empty wall drew bigger crowds than the painting had.",
    mech: "Newspapers across the world printed the picture every day while they hunted for it. People queued at the Louvre just to see the empty hooks. Even Pablo Picasso was questioned by the police. In December 1913 Peruggia tried to sell it to a dealer in Florence and was caught. When it came back, millions already knew its face.",
    models: ["availability-bias", "feedback-loops"],
    q: "How did the 1911 theft change the Mona Lisa's place in the world?",
    a: "Peruggia stole it from the Louvre in 1911. Newspapers everywhere printed its picture for two years while it was missing, so millions learned its face. It was found in Florence in 1913 and came back as the most famous painting in the world.",
    chain: [["Stolen from the Louvre in 1911", ["1911", "stolen", "stole", "theft", "peruggia"]], ["Newspapers printed it for two years", ["newspaper", "printed", "press", "two years", "missing"]], ["Found in Florence in 1913", ["florence", "1913", "found", "dealer", "caught"]], ["Came back world famous", ["famous", "fame", "millions", "crowd"]]],
    mcq: { q: "What made the Mona Lisa world famous in the 1910s?", o: ["It was stolen from the Louvre and missing for two years", "Napoleon hung it in his bedroom", "It was sold for a record price", "A film was made about Leonardo"] },
    bring: "When someone asks why the Mona Lisa is such a big deal: “A lot of it is a theft. In 1911 a worker walked out with it, and the hunt made it famous.”",
    follow: "What else do we think is great mainly because everyone keeps talking about it?",
    deeper: "Peruggia kept the painting in a trunk in his Paris room for two years. He said he wanted to return it to Italy. He served only about seven months in prison." },

  { id: "ar-van-gogh-sales", type: "fact", domain: "history", title: "Van Gogh sold almost nothing while alive", value: 4, cue: "artists, late success, or work that nobody values yet",
    emoji: "🌻", wiki: "Vincent van Gogh",
    fact: "Vincent van Gogh painted about 900 pictures in ten years, most of them in his last two. Only one sale of a painting in his lifetime is clearly recorded: The Red Vineyard, sold in 1890 for 400 francs. He died that same year, aged 37.",
    why: "The value of work and the price it gets at the time can be two completely different things.",
    mech: "His brother Theo, an art dealer, sent him money every month, so Vincent could keep painting without buyers. His thick, bright style looked wrong to buyers of the 1880s. After both brothers died, Theo's widow Johanna kept the paintings and letters together and pushed to show them. Within twenty years, prices rose sharply. Today his paintings sell for crores of rupees in a single bid.",
    models: ["survivorship-bias", "compounding"],
    q: "Why did Van Gogh sell almost nothing, and how did he become famous later?",
    a: "His bright thick style looked wrong to buyers of the 1880s, and only one sale, The Red Vineyard in 1890, is clearly recorded. His brother Theo paid for his life. After their deaths, Theo's widow Johanna kept the works together and showed them, and prices rose.",
    chain: [["About 900 paintings, one clear sale", ["900", "one sale", "red vineyard", "400 francs", "one painting"]], ["Theo sent money every month", ["theo", "brother", "money", "dealer"]], ["His style looked wrong to buyers then", ["style", "looked wrong", "thick", "bright", "buyers"]], ["Johanna kept the works and showed them", ["johanna", "widow", "kept", "showed", "letters"]]],
    mcq: { q: "Who kept Van Gogh's paintings together after his death and made them known?", o: ["Theo's widow Johanna", "The French government", "Pablo Picasso", "A Dutch bank"] },
    bring: "When someone feels their work is not valued: “Van Gogh sold one painting in his life. Now one sells for hundreds of crores.”",
    follow: "Do you think he would have painted the same way if buyers had liked him?",
    deeper: "Vincent wrote over 600 letters to Theo. They are the reason we know so much about how he thought. The Van Gogh Museum in Amsterdam holds most of the works Johanna saved." },

  { id: "ar-david-block", type: "fact", domain: "design", title: "Michelangelo's David came from a rejected block", value: 4, cue: "sculpture, Florence, or making something from what others gave up on",
    emoji: "🗿", wiki: "David (Michelangelo)",
    fact: "The marble block for David was cut in 1464. Two sculptors started on it and gave up. It lay in a cathedral yard in Florence for about 35 years, tall, thin and partly spoiled. In 1501 Michelangelo, aged 26, took it and finished the statue in 1504. It stands over 5 metres tall.",
    why: "The best work sometimes comes from a problem others walked away from. The limits of the block shaped the pose.",
    mech: "The block was narrow, so a figure with wide, open arms was impossible. Earlier sculptors had also cut holes into it. Michelangelo planned a standing figure with the weight on one leg and the sling over the shoulder, so everything fit inside the thin stone. He worked on it for about three years. The city placed it outside the town hall as a sign that small Florence could face big enemies.",
    models: ["first-principles", "inversion"],
    q: "Why was the David block special, and how did Michelangelo deal with it?",
    a: "The block had been cut in 1464, and two sculptors gave up on it, so it lay in a yard for about 35 years. It was thin and spoiled. Michelangelo designed a narrow standing pose that fit inside the stone, and finished in 1504.",
    chain: [["A block others had given up on", ["gave up", "rejected", "abandon", "1464", "35 years", "two sculptors"]], ["It was thin and partly spoiled", ["thin", "narrow", "spoiled", "holes"]], ["He designed a pose that fit the stone", ["pose", "fit", "one leg", "standing", "sling"]], ["Finished in 1504, over 5 metres tall", ["1504", "5 metres", "five metres", "finished"]]],
    mcq: { q: "What was unusual about the marble used for Michelangelo's David?", o: ["Two sculptors had already given up on it and it lay unused for decades", "It was the largest block ever cut", "It came from India", "It was pure black marble"] },
    bring: "When a project looks ruined: “Michelangelo's David was carved from a block two other sculptors had given up on.”",
    follow: "What have you seen someone make out of a thing everyone else had rejected?",
    deeper: "The original stood outside in the Piazza della Signoria for over 350 years. In 1873 it was moved indoors to the Accademia gallery, and a copy stands in the square today." },

  { id: "ar-leonardo-notebooks", type: "fact", domain: "history", title: "Leonardo's mirror writing", value: 3, cue: "Leonardo da Vinci, notebooks, or left-handed people",
    emoji: "📓", wiki: "Leonardo da Vinci",
    fact: "Leonardo da Vinci filled thousands of pages with notes and drawings. About 7,000 pages survive. He wrote almost all of them backwards, from right to left, so they read normally in a mirror.",
    why: "People often say it was a secret code. The simpler answer is that he was left-handed and this kept the ink from smudging.",
    mech: "A left-handed person writing left to right drags the hand over the wet ink. Writing right to left avoids this. Leonardo wrote this way even in private notes that nobody needed to hide. His pages mix anatomy, water, flying machines and shopping lists. He never finished the books he planned, so the notes were scattered after his death in 1519.",
    models: ["first-principles", "map-vs-territory"],
    q: "Why did Leonardo write backwards, and what happened to his notebooks?",
    a: "He was left-handed, and writing from right to left kept his hand out of the wet ink. About 7,000 pages survive, mixing anatomy, machines and daily notes. He never finished his planned books, so the pages were scattered after 1519.",
    chain: [["He wrote from right to left", ["backwards", "right to left", "mirror"]], ["Because he was left-handed and avoided smudging", ["left-handed", "left hand", "smudg", "ink"]], ["About 7,000 pages survive", ["7,000", "7000", "thousand", "pages"]], ["Scattered after his death", ["scattered", "never finished", "1519", "death"]]],
    mcq: { q: "Why is Leonardo's mirror writing most likely explained?", o: ["He was left-handed and it kept ink from smudging", "The Church banned normal writing", "He wanted to hide inventions from the king", "He could not read normal script"] },
    bring: "When Leonardo's secret code comes up: “It was probably just a left-handed man avoiding smudges. His notes were shopping lists too.”",
    follow: "Do you keep a notebook of ideas? What would someone learn from it in 500 years?",
    deeper: "One notebook, the Codex Leicester, was bought by Bill Gates in 1994 for about 30.8 million dollars. It is the most expensive book ever sold." },

  { id: "ar-guernica", type: "event", domain: "history", title: "Picasso's Guernica", value: 4, cue: "war, protest art, or a famous painting",
    emoji: "🕊️", wiki: "Guernica (Picasso)",
    fact: "On 26 April 1937 German and Italian planes bombed the Basque town of Guernica in Spain for Franco's side in the Spanish Civil War. Within weeks Pablo Picasso painted a huge black, white and grey picture, 3.5 metres tall and nearly 8 metres wide. It was shown at the Paris World Fair that summer.",
    why: "It became the best known anti-war picture of the 20th century. It shows no planes or soldiers, only people and animals in pain.",
    mech: "Picasso had been asked to paint something for Spain's pavilion at the Paris fair. News of the bombing of a market town full of civilians gave him his subject. He used no colour, like a newspaper photo, so the horror felt like news. After the fair the painting travelled to raise money for refugees. Picasso refused to let it go to Spain while Franco ruled. It returned to Spain only in 1981, after both men had died.",
    models: ["second-order-thinking"],
    q: "What was Guernica about, and why did it stay out of Spain for so long?",
    a: "It answered the bombing of the town of Guernica on 26 April 1937 by German and Italian planes. Picasso painted it in black, white and grey for the Paris World Fair. He refused to let it enter Spain under Franco, so it went to Spain only in 1981.",
    chain: [["The bombing of Guernica, April 1937", ["1937", "bomb", "guernica", "german", "italian"]], ["Painted for the Paris World Fair", ["paris", "world fair", "pavilion", "exhibition"]], ["No colour, like a news photo", ["black", "grey", "gray", "no colour", "photo"]], ["Kept out of Spain until 1981", ["1981", "franco", "refused", "return"]]],
    mcq: { q: "Why did Guernica only come to Spain in 1981?", o: ["Picasso refused to let it go to Spain while Franco ruled", "It was lost in a war", "Spain could not afford to buy it", "The painting was too large to move before then"] },
    bring: "When protest art comes up: “Guernica has no soldier in it. Picasso painted only the people and animals, and it is still the most famous war painting.”",
    follow: "Can a painting change what people think about a war?",
    deeper: "A copy of Guernica hangs at the United Nations in New York. In 2003, it was covered with a curtain while officials gave press briefings about the Iraq war." },

  /* ---------- World: words and music ---------- */

  { id: "ar-shakespeare-words", type: "fact", domain: "language", title: "Shakespeare's words we still use", value: 4, cue: "English words, phrases, or where sayings come from",
    emoji: "🎭", wiki: "William Shakespeare",
    fact: "William Shakespeare's plays give us the first known printed use of hundreds of English words. Older books often said about 1,700; scholars now think the true number is lower, because many words were spoken before he wrote them. Still, words like lonely, bedroom, eyeball and swagger first appear in print in his work.",
    why: "When you say something is a “wild goose chase” or that you must “break the ice”, you are quoting a 400-year-old play.",
    mech: "In the 1590s English had no dictionary and few rules. Writers freely turned nouns into verbs and joined old words into new ones. Shakespeare wrote about 37 plays for a theatre that needed new material every few weeks. His plays were printed, read in schools and performed for centuries. So his versions of words and phrases stayed in use, while others were forgotten.",
    models: ["lindy-effect", "survivorship-bias"],
    q: "Why does so much of everyday English trace back to Shakespeare?",
    a: "English in the 1590s had no dictionary and few rules, so writers coined freely. Shakespeare wrote about 37 plays, and words like lonely and eyeball first appear in print in them. His plays kept being printed and performed, so his phrases stayed alive.",
    chain: [["English had no dictionary and few rules", ["no dictionary", "rules", "1590", "freely"]], ["He wrote about 37 plays and coined freely", ["37", "plays", "coin", "first appear", "lonely", "eyeball"]], ["His plays were printed and performed for centuries", ["printed", "performed", "school", "centuries"]], ["So his words and phrases survived", ["survive", "stayed", "still use", "phrases"]]],
    mcq: { q: "Which phrase comes from a Shakespeare play?", o: ["A wild goose chase", "Once in a blue moon", "Spill the beans", "Hit the road"] },
    bring: "When someone uses the phrase “break the ice”: “That line is from Shakespeare. So is wild goose chase.”",
    follow: "Which Hindi or Marathi sayings do you think come from one famous poet?",
    deeper: "The claim of 1,700 new words comes partly from the Oxford English Dictionary, which once used Shakespeare as its first source very often. As older texts are digitised, many of his “firsts” turn out to be earlier." },

  { id: "ar-beethoven-ninth", type: "event", domain: "history", title: "Beethoven could not hear his own Ninth", value: 5, cue: "music, deafness, or working through a handicap",
    emoji: "🎼", wiki: "Symphony No. 9 (Beethoven)",
    fact: "Ludwig van Beethoven's hearing began to fail in his late twenties. By the time he wrote his Ninth Symphony he was almost completely deaf. At its first performance in Vienna on 7 May 1824, he stood on stage but could not hear the orchestra or the cheering.",
    why: "One of the best loved pieces of music in the world was written by a man who heard it only in his head.",
    mech: "Beethoven had trained for decades, so he could read a score and hear it in his mind. He kept composing by imagining sound, and later cut the legs off his piano so he could feel its vibration through the floor, as the story goes. At the premiere a conductor stood beside him and the players were told to follow the conductor. When the music ended Beethoven was still facing the orchestra. The singer Caroline Unger turned him around so he could see the audience clapping and waving hats.",
    models: ["circle-of-competence"],
    q: "How could Beethoven compose and present the Ninth Symphony when he was deaf?",
    a: "Years of training let him hear music in his mind from the written score. At the Vienna premiere on 7 May 1824 a conductor led the players while he stood on stage. When it ended, Caroline Unger turned him to see the audience clapping, because he could not hear it.",
    chain: [["He was almost completely deaf by then", ["deaf", "hearing", "could not hear"]], ["He heard music in his mind from the score", ["mind", "head", "imagin", "score"]], ["Premiere in Vienna, 7 May 1824", ["1824", "vienna", "premiere", "first performance"]], ["Unger turned him to see the applause", ["unger", "turned", "clapping", "applause", "cheer"]]],
    mcq: { q: "What happened at the end of the first performance of Beethoven's Ninth?", o: ["A singer turned him around to see the audience clapping, because he could not hear it", "The audience walked out", "Beethoven conducted an encore", "The king stopped the concert"] },
    bring: "When someone says a problem makes their work impossible: “Beethoven wrote the Ninth Symphony when he could not hear a note of it.”",
    follow: "Which skill do you know so well that you could do it without seeing or hearing?",
    deeper: "The last movement sets a poem, Ode to Joy, with a choir and singers, which no symphony had done before. Today it is the anthem of the European Union." },

  { id: "ar-mozart-requiem", type: "fact", domain: "history", title: "Mozart's Requiem: myth and fact", value: 3, cue: "Mozart, famous legends, or how stories get improved",
    emoji: "🎻", wiki: "Requiem (Mozart)",
    fact: "In 1791 a stranger ordered a Requiem, a mass for the dead, from Wolfgang Amadeus Mozart and paid in advance. Mozart fell ill and died on 5 December 1791, aged 35, with the work unfinished. His pupil Franz Xaver Süssmayr completed it from his sketches.",
    why: "The film Amadeus made many people believe the rival composer Salieri poisoned him. There is no evidence for that. The true story is strange enough.",
    mech: "The stranger worked for Count Franz von Walsegg, a nobleman who liked to pass off music by others as his own. He wanted a Requiem for his dead wife. Mozart, sick and in debt, worked on it in his last weeks. His widow Constanze needed the final payment, so she had the piece finished quietly and delivered as Mozart's. Later writers turned the anonymous order into a dark prophecy of his own death.",
    models: ["availability-bias", "incentives"],
    q: "What is true and what is legend about Mozart's Requiem?",
    a: "True: a stranger ordered it in 1791 for Count Walsegg, who wanted to pass it off as his own, and Mozart died on 5 December 1791 before finishing it. His pupil Süssmayr completed it so his widow could get paid. Legend: that Salieri poisoned him.",
    chain: [["A stranger ordered it in 1791", ["stranger", "anonymous", "1791", "ordered", "commission"]], ["It was for Count Walsegg, who passed off others' music as his own", ["walsegg", "count", "his own", "pass off"]], ["Mozart died before finishing it; Süssmayr completed it", ["died", "5 december", "unfinished", "süssmayr", "sussmayr", "pupil", "completed"]], ["The poisoning story is a legend", ["salieri", "poison", "legend", "no evidence"]]],
    mcq: { q: "Who finished Mozart's Requiem after his death?", o: ["His pupil Franz Xaver Süssmayr", "Antonio Salieri", "Ludwig van Beethoven", "Joseph Haydn"] },
    bring: "When the film Amadeus comes up: “Salieri did not poison Mozart. The real twist is that a count ordered the Requiem to pass it off as his own.”",
    follow: "Why do you think we prefer the murder story to the true one?",
    deeper: "Walsegg did have the Requiem performed in 1793 under his own name. Constanze had already arranged a public performance in Vienna, so the trick did not last." },

  { id: "ar-jazz-new-orleans", type: "concept", domain: "anthropology", title: "Why jazz was born in New Orleans", value: 3, cue: "music styles, mixing of cultures, or improvisation",
    emoji: "🎷", wiki: "Jazz",
    fact: "Jazz took shape in New Orleans, in the southern United States, in the years around 1900. It mixed African rhythms, church songs, marching brass bands and European harmony. The first jazz record was made in 1917.",
    why: "It is a case study in how new things come from mixing, not from purity. Jazz later shaped almost all popular music, including film music in India.",
    mech: "New Orleans was a port with French, Spanish, African, Caribbean and American people living close together. Enslaved people and their descendants had kept African drumming and singing alive, including at the Sunday gatherings in Congo Square. Brass band instruments became cheap after the American Civil War. Musicians played for parades, funerals and dance halls, where they began to change the tune as they played. That habit of making the music up on the spot, called improvisation, became the heart of jazz.",
    models: ["lollapalooza", "network-effects"],
    q: "Why did jazz begin in New Orleans and not somewhere else?",
    a: "It was a port where French, Spanish, African and Caribbean cultures lived close together. African rhythms survived there, and cheap brass instruments after the Civil War let musicians play for parades and dances. Improvisation grew from that. The first jazz record came in 1917.",
    chain: [["A port where many cultures lived close together", ["port", "french", "spanish", "african", "caribbean", "mix"]], ["African rhythms and song survived there", ["rhythm", "congo square", "drum", "african", "survived"]], ["Cheap brass instruments after the Civil War", ["brass", "cheap", "civil war", "instrument"]], ["Improvisation became the heart of it", ["improvis", "on the spot", "make up", "change the tune"]]],
    mcq: { q: "What is improvisation in jazz?", o: ["Making up or changing the music while playing it", "Playing only from written notes", "Playing without any instruments", "Singing in French"] },
    bring: "When someone says mixing cultures spoils tradition: “Jazz came from a port city where five cultures met. Purity would have given us nothing new.”",
    follow: "Which Indian music or food do you think came from a similar mixing?",
    deeper: "Louis Armstrong, born in New Orleans in 1901, grew up poor and learned the cornet in a home for boys. He became the first world famous jazz soloist." },

  { id: "ar-beatles-rishikesh", type: "event", domain: "anthropology", title: "The Beatles in Rishikesh, 1968", value: 4, cue: "the Beatles, yoga, or India's influence on the West",
    emoji: "🎸", wiki: "The Beatles in India",
    fact: "In February 1968 the Beatles came to Rishikesh to learn meditation at the ashram of Maharishi Mahesh Yogi. They stayed for several weeks and wrote dozens of songs there. Many appeared on the White Album later that year.",
    why: "It was the moment Indian music, yoga and meditation went mainstream in the West. Much of today's global yoga business grew from that attention.",
    mech: "George Harrison had already learned the sitar from Ravi Shankar and used it in the song Norwegian Wood in 1965. The band were tired and looking for meaning after huge fame. In the quiet of the ashram, with no stage and no press, they wrote more songs in a few weeks than in most years. The world's press followed them anyway, and photos of the Beatles in kurtas with flowers went everywhere. Interest in India among young Westerners jumped.",
    models: ["social-proof", "lollapalooza"],
    q: "Why did the Beatles come to Rishikesh, and what did their visit change?",
    a: "They came in February 1968 to learn meditation from Maharishi Mahesh Yogi, after George Harrison had taken up the sitar. In the quiet ashram they wrote dozens of songs, many for the White Album. The press coverage made Indian music, yoga and meditation popular in the West.",
    chain: [["George Harrison had taken up the sitar", ["harrison", "sitar", "ravi shankar", "norwegian wood"]], ["They came to Rishikesh in February 1968 for meditation", ["rishikesh", "1968", "meditat", "maharishi", "ashram"]], ["They wrote dozens of songs there", ["dozens", "songs", "white album", "wrote"]], ["It made yoga and Indian music popular in the West", ["west", "popular", "yoga", "mainstream", "interest"]]],
    mcq: { q: "Why did the Beatles go to Rishikesh in 1968?", o: ["To learn meditation at Maharishi Mahesh Yogi's ashram", "To record an album in Bombay", "To perform for the Indian government", "To climb in the Himalayas"] },
    bring: "When yoga's popularity abroad comes up: “The big push was 1968. The Beatles sat in Rishikesh for weeks and the whole Western press watched.”",
    follow: "What Indian idea do you think the West still misunderstands?",
    deeper: "The ashram was abandoned for decades and is now a tourist spot inside Rajaji Tiger Reserve, often called the Beatles Ashram. Ringo Starr left early, missing his favourite food." },

  /* ---------- World: sport ---------- */

  { id: "ar-olympic-truce", type: "concept", domain: "history", title: "The Olympic truce and the 1896 revival", value: 4, cue: "the Olympics, sport and politics, or ancient Greece",
    emoji: "🏛️", wiki: "Olympic Games",
    fact: "The ancient Olympic Games were held at Olympia in Greece from 776 BCE, by tradition, every four years for over a thousand years. Before each games, a truce was announced so that athletes and visitors could travel safely between warring cities. A Roman emperor ended the games in the 390s CE. A Frenchman, Pierre de Coubertin, revived them in Athens in 1896.",
    why: "The idea that sport can pause a quarrel is older than most countries. The modern Games borrowed that promise, and often fail to keep it.",
    mech: "The Greek cities fought each other often but shared gods and festivals. The truce, called ekecheiria, protected the religious festival, not the sport alone. When Christianity became Rome's religion, pagan festivals were shut down. In the 1890s Coubertin believed sport built character and could bring nations together. He gathered delegates in Paris in 1894 and the first modern Games had about 240 athletes from 14 nations, all men.",
    models: ["game-theory", "lindy-effect"],
    q: "What was the ancient Olympic truce, and how did the Games return?",
    a: "From 776 BCE the Greek cities held Games at Olympia every four years, with a truce so people could travel safely to the religious festival. Rome ended them in the 390s CE. Pierre de Coubertin revived them in Athens in 1896 with about 240 male athletes from 14 nations.",
    chain: [["Games at Olympia from 776 BCE, every four years", ["776", "olympia", "four years", "ancient"]], ["A truce protected travel to the festival", ["truce", "ekecheiria", "safe", "travel", "festival"]], ["Ended by Rome in the 390s CE", ["390", "rome", "roman", "emperor", "ended", "christian"]], ["Revived by Coubertin in Athens, 1896", ["coubertin", "1896", "athens", "revived", "modern"]]],
    mcq: { q: "Where and when were the first modern Olympic Games held?", o: ["Athens, 1896", "Paris, 1900", "London, 1908", "Rome, 1960"] },
    bring: "When the Olympics come up: “The ancient Greeks declared a truce before each Games so fans could travel through enemy land. That is 2,800 years old.”",
    follow: "Do you think sport really brings countries closer, or just gives them a new place to compete?",
    deeper: "Women first competed in 1900. The five rings were designed by Coubertin in 1913. India first sent a team in 1920 and won its first hockey gold in 1928." },

  { id: "ar-marathon-distance", type: "fact", domain: "history", title: "Why a marathon is 42.195 km", value: 3, cue: "running, the Mumbai Marathon, or odd numbers with a history",
    emoji: "🏃", wiki: "Marathon",
    fact: "A marathon is exactly 42.195 km. The odd number comes from the 1908 London Olympics. The course was set to start at Windsor Castle and finish in front of the royal box in the stadium. That came to 26 miles 385 yards, and in 1921 it became the official distance.",
    why: "A rule used by millions of runners was fixed by where a royal family wanted to sit.",
    mech: "The race is named after a Greek legend. A messenger is said to have run from the battle of Marathon to Athens in 490 BCE, about 40 km, to report a victory. The first modern marathons, from 1896, were roughly 40 km and varied from race to race. In 1908 the London organisers adjusted the course for the royal family. Later races copied London, and the athletics body made that distance the standard.",
    models: ["lindy-effect"],
    q: "Why is the marathon 42.195 km and not a round number?",
    a: "Early marathons were about 40 km, after the legend of a runner from Marathon to Athens in 490 BCE. In 1908 London set the course from Windsor Castle to the royal box in the stadium, which made 26 miles 385 yards. In 1921 that became the official distance.",
    chain: [["Named after a Greek legend, about 40 km", ["legend", "490", "athens", "40 km", "messenger"]], ["1908 London: from Windsor Castle to the royal box", ["1908", "london", "windsor", "royal", "box"]], ["That made 26 miles 385 yards", ["26 miles", "385", "42.195"]], ["Made official in 1921", ["1921", "official", "standard"]]],
    mcq: { q: "What fixed the marathon's odd distance?", o: ["The 1908 London course from Windsor Castle to the royal box", "The exact distance from Marathon to Athens", "A metric rule from France", "The size of the Rome stadium in 1960"] },
    bring: "At the Mumbai Marathon: “42.195 km is not Greek maths. It is the distance from Windsor Castle to the King's seat in 1908.”",
    follow: "What other rules do we follow that were really just one person's convenience?",
    deeper: "In that 1908 race the Italian runner Dorando Pietri collapsed near the finish, was helped across the line and then disqualified. The crowd's sympathy made him famous anyway." },

  { id: "ar-football-1863", type: "concept", domain: "history", title: "Football's rules and the offside change of 1925", value: 3, cue: "football, rules of a game, or how small rule changes change behaviour",
    emoji: "⚽", wiki: "Laws of the Game (association football)",
    fact: "Modern football began on 26 October 1863, when clubs met in a London tavern and formed the Football Association. They wrote 13 laws. Clubs that wanted to carry the ball and kick opponents' shins left, and became rugby. In 1925 the offside rule was eased, and goals in the English league jumped by about a third in one season.",
    why: "A shared rulebook is what made a village game into a world sport. And one line in that rulebook can change how everyone plays.",
    mech: "Before 1863 every school and town played by its own rules, so teams could not play each other. A written code let strangers play. Under the old offside law an attacker needed three defenders between him and the goal. Defenders learned to step forward and trap attackers, so games had few goals. In 1925 the number was cut to two. Attackers had more room, and league goals rose from about 4,700 to 6,373 in a season. Coaches then invented new defensive formations in reply.",
    models: ["incentives", "second-order-thinking", "goodharts-law"],
    q: "Why did written rules matter for football, and what did the 1925 offside change do?",
    a: "Before the Football Association wrote 13 laws in 1863, every town played its own way, so a shared code let strangers play. In 1925 the offside rule was cut from three defenders to two. Goals in the English league rose by about a third, and coaches invented new formations.",
    chain: [["Every town had its own rules before 1863", ["own rules", "school", "town", "could not play"]], ["The FA wrote 13 laws in 1863; rugby split off", ["1863", "13 laws", "football association", "rugby", "tavern"]], ["1925: offside cut from three defenders to two", ["1925", "three defenders", "two", "offside"]], ["Goals rose by a third; new formations followed", ["third", "6,373", "goals rose", "jumped", "formation"]]],
    mcq: { q: "What happened after the offside rule was eased in 1925?", o: ["Goals in the English league rose by about a third in a season", "Matches became shorter", "Goalkeepers were banned from using their hands", "Teams were cut to nine players"] },
    bring: "When someone says a small rule change will not matter: “Football changed one word in the offside law in 1925 and goals went up by a third.”",
    follow: "Which small rule at your workplace changes how everyone behaves?",
    deeper: "The English Premier League's 1992 breakaway, and its television deals, is a later example of a rule change reshaping the game. The FIFA World Cup began in 1930 in Uruguay." },

  /* ---------- World: prizes and books ---------- */

  { id: "ar-nobel-obituary", type: "fact", domain: "history", title: "The Nobel prizes and the dynamite fortune", value: 4, cue: "the Nobel prize, legacy, or how people want to be remembered",
    emoji: "🏅", wiki: "Alfred Nobel",
    fact: "Alfred Nobel, a Swedish chemist, invented dynamite in 1867 and grew very rich selling explosives. In his will of 1895 he left most of his fortune to fund yearly prizes for physics, chemistry, medicine, literature and peace. The first prizes were given in 1901.",
    why: "A man whose name meant explosives made it mean peace and science instead. It is the most famous example of someone designing his own legacy.",
    mech: "A story often told says a French newspaper printed his obituary by mistake in 1888, when his brother Ludvig died, and called him “the merchant of death”. Historians have not found that newspaper, so treat it as a legend. What is certain is that Nobel was uneasy about his trade and had no children. His will shocked his family and Sweden, and it took five years of legal fights to set up the prizes. Economics was added in 1968 by Sweden's central bank.",
    models: ["inversion", "incentives"],
    q: "How did the Nobel prizes come about?",
    a: "Alfred Nobel made a fortune from dynamite, which he invented in 1867. In his 1895 will he left most of it to fund prizes in physics, chemistry, medicine, literature and peace, first given in 1901. The story of a mistaken obituary calling him a merchant of death is often told but not proven.",
    chain: [["He grew rich from dynamite, invented in 1867", ["dynamite", "1867", "explosive", "fortune"]], ["The 1895 will left most of it for prizes", ["will", "1895", "left", "fortune", "prizes"]], ["Five fields, first given in 1901", ["1901", "physics", "chemistry", "medicine", "literature", "peace", "five"]], ["The obituary story is unproven", ["obituary", "merchant of death", "legend", "not proven", "unproven"]]],
    mcq: { q: "How did Alfred Nobel make the fortune that funds the Nobel prizes?", o: ["By inventing and selling dynamite and other explosives", "From Swedish iron mines", "By founding a bank", "From oil in Russia alone"] },
    bring: "When the Nobel prize is announced: “The man who funds it invented dynamite. He used his will to change what his name would mean.”",
    follow: "If you could set up one prize, what would it reward?",
    deeper: "Nobel's family fought the will in court, and Norway's parliament awards the Peace Prize because the will said so, though nobody knows why he chose Norway. Rabindranath Tagore won the literature prize in 1913, the first Asian winner." },

  { id: "ar-dostoevsky-execution", type: "historical story", domain: "history", title: "Dostoevsky's mock execution", value: 4, cue: "Russian novels, second chances, or facing death", story: "dostoevsky",
    emoji: "📚", wiki: "Fyodor Dostoevsky",
    fact: "On 22 December 1849 the young writer Fyodor Dostoevsky stood in a square in St Petersburg, sentenced to death for belonging to a group that read banned books. The first men were tied to the posts. Then a messenger arrived with a pardon from the Tsar. The whole scene had been staged to frighten them.",
    why: "He went on to write Crime and Punishment and The Brothers Karamazov. He said those minutes changed how he saw every day of life.",
    mech: "Tsar Nicholas I had decided in advance to change the death sentences to prison, but ordered the full execution ceremony to be played out first. Dostoevsky then spent four years in a prison camp in Siberia, in chains, and more years as a soldier. He lived among murderers and thieves and read only the Bible. These years gave him the deep knowledge of guilt, faith and suffering that fills his novels.",
    models: ["inversion"],
    q: "What happened to Dostoevsky in 1849 and how did it shape his writing?",
    a: "He was sentenced to death for being in a group that read banned books and stood before a firing squad on 22 December 1849. At the last minute a pardon arrived; the Tsar had planned the mock execution. He then spent four years in a Siberian prison camp, and that knowledge of suffering shaped his novels.",
    chain: [["Sentenced to death for reading banned books", ["banned books", "sentenced", "death", "group", "circle"]], ["A staged execution on 22 December 1849", ["1849", "mock", "staged", "firing squad", "square", "posts"]], ["A last-minute pardon planned by the Tsar", ["pardon", "tsar", "last minute", "messenger"]], ["Four years in a Siberian prison shaped his novels", ["siberia", "four years", "prison", "camp", "novels"]]],
    mcq: { q: "Why was Dostoevsky sentenced to death in 1849?", o: ["For belonging to a group that read and discussed banned writings", "For killing a man in a duel", "For stealing from the Tsar", "For deserting the army"] },
    bring: "When someone talks about a near miss: “Dostoevsky stood in front of a firing squad before the pardon came. He said he never wasted a minute after that.”",
    follow: "If you were told you had five minutes left, what would you think about?",
    deeper: "In his novel The Idiot, a character describes exactly those last minutes before a planned execution. Dostoevsky later became a devout Christian and a critic of the radicals he had once joined." },

  { id: "ar-marquez-solitude", type: "fact", domain: "history", title: "García Márquez could not afford the postage", value: 3, cue: "writers, taking a risk, or famous books",
    emoji: "✉️", wiki: "One Hundred Years of Solitude",
    fact: "Gabriel García Márquez wrote One Hundred Years of Solitude in Mexico City over about 18 months in 1965 and 1966. He stopped working and his family lived on credit. When the 490-page manuscript was ready, he and his wife could pay postage for only half of it to the publisher in Buenos Aires.",
    why: "The book has sold about 50 million copies and won him the Nobel Prize in 1982. The gap between that and the post office counter is the point.",
    mech: "He had the whole story in his head, he said, after years of trying to start it. So he shut himself in his study every day and let his wife Mercedes handle the bills. The family pawned the car and household goods. At the post office the clerk asked for 82 pesos; they had about 50. They sent the first half, pawned the heater and mixer, and sent the rest. The first printing of 8,000 copies in 1967 sold out in weeks.",
    models: ["margin-of-safety", "opportunity-cost"],
    q: "What did it cost García Márquez to write One Hundred Years of Solitude?",
    a: "He stopped working for about 18 months in Mexico City and his family lived on credit and pawned goods. At the post office he could afford to send only half the 490-page manuscript to Buenos Aires. The book sold about 50 million copies and he won the Nobel in 1982.",
    chain: [["He stopped working for 18 months to write", ["18 months", "stopped working", "study", "mexico"]], ["The family lived on credit and pawned things", ["credit", "pawn", "debt", "bills"]], ["They could post only half the manuscript", ["half", "postage", "post office", "pesos", "490"]], ["It sold tens of millions and won the Nobel in 1982", ["50 million", "nobel", "1982", "million copies"]]],
    mcq: { q: "What problem did García Márquez face when the manuscript was finished?", o: ["He could not afford the postage to send all of it to the publisher", "The publisher lost the only copy", "The government banned it", "He could not find a typewriter"] },
    bring: "When someone talks about betting on themselves: “García Márquez pawned the heater to post the second half of his novel. It sold 50 million copies.”",
    follow: "What would you need in place before you took a risk like that?",
    deeper: "The novel is set in the invented town of Macondo and is the best known example of “magical realism”, where strange events are told as plain fact. Salman Rushdie's Midnight's Children is often compared with it." },

  /* ---------- World: Japanese ideas ---------- */

  { id: "ar-kaizen", type: "business concept", domain: "business", title: "Kaizen: small steps every day", value: 4, cue: "improving at work, factories, or Japanese management",
    emoji: "🔧", wiki: "Kaizen",
    fact: "Kaizen is a Japanese word meaning “change for the better”. In business it means making many small improvements every day, by everyone, instead of waiting for big changes from the top. Toyota made it famous, and the 1986 book Kaizen by Masaaki Imai spread the word worldwide.",
    why: "It is why a Toyota worker can stop the whole line to fix a small fault. Small fixes, added up for decades, built the world's most copied factory system.",
    mech: "After the Second World War Japan had little money and few materials, so waste was costly. Toyota asked every worker, not only engineers, to suggest improvements to their own task. Ideas were tested fast and kept if they worked. Each fix was small, but thousands of fixes a year compounded. Problems were seen as information, not as blame. Over time this became the Toyota Production System, studied by factories and hospitals everywhere.",
    models: ["compounding", "feedback-loops", "bottlenecks"],
    q: "What is kaizen and why did it work so well at Toyota?",
    a: "Kaizen means change for the better: many small improvements every day, suggested by every worker. Post-war Japan could not afford waste, so Toyota tested small fixes fast and kept the good ones. Thousands of small fixes a year compounded into the Toyota Production System.",
    chain: [["Means change for the better, in small daily steps", ["change for the better", "small", "daily", "every day", "improvement"]], ["Every worker suggests fixes, not just managers", ["every worker", "everyone", "suggest", "own task"]], ["Post-war Japan could not afford waste", ["waste", "post-war", "after the second world war", "little money"]], ["Small fixes compound into a system", ["compound", "thousands", "added up", "production system"]]],
    mcq: { q: "What does kaizen ask of a company?", o: ["Many small improvements every day from every worker", "One big redesign every ten years", "Hiring only top engineers", "Copying the market leader"] },
    bring: "When someone wants a big dramatic change: “Toyota did it the other way. Kaizen: a thousand small fixes a year, from the workers themselves.”",
    follow: "What small fix in your daily routine would add up most over a year?",
    deeper: "The related idea of the andon cord lets any worker stop the line when they see a defect. Managers thank them, because a fault caught early is cheaper than one found by the customer." },

  { id: "ar-japanese-ideas", type: "concept", domain: "anthropology", title: "Ikigai, wabi-sabi and shinrin-yoku", value: 3, cue: "Japanese lifestyle words, self-help books, or finding meaning",
    emoji: "🎋", wiki: "Wabi-sabi",
    fact: "Three Japanese ideas have travelled the world. Ikigai means your reason for getting up in the morning. Wabi-sabi is finding beauty in things that are plain, worn or imperfect. Shinrin-yoku, or forest bathing, means slowly walking in a forest with all your senses open; the Japanese Forestry Agency coined the term in 1982.",
    why: "They are useful ideas. But the Western versions often say more than the Japanese ones do.",
    mech: "In Japan ikigai is an everyday word for small daily joys, like a hobby or grandchildren. The four-circle diagram of passion, mission, vocation and profession was drawn in the West around 2014 and is not Japanese. Wabi-sabi grew from Zen and the tea ceremony, where a cracked, simple bowl was valued over a perfect one. Kintsugi, mending pottery with gold, shows the same idea. Shinrin-yoku was a public health campaign, and studies since then suggest time among trees lowers stress.",
    models: ["map-vs-territory"],
    q: "What do ikigai, wabi-sabi and shinrin-yoku mean, and what do Western versions get wrong?",
    a: "Ikigai is a reason to get up in the morning, often small daily joys; the four-circle diagram is a Western drawing from about 2014. Wabi-sabi is beauty in plain, worn, imperfect things, from Zen and the tea ceremony. Shinrin-yoku, forest bathing, was coined in 1982 as a public health idea.",
    chain: [["Ikigai: a reason to get up, often small joys", ["ikigai", "reason", "get up", "morning", "daily joys"]], ["The four-circle diagram is Western, not Japanese", ["four-circle", "four circle", "diagram", "western", "2014"]], ["Wabi-sabi: beauty in the imperfect, from Zen and tea", ["wabi", "imperfect", "worn", "plain", "tea ceremony", "zen"]], ["Shinrin-yoku: forest bathing, coined in 1982", ["shinrin", "forest", "1982", "forestry"]]],
    mcq: { q: "Where does the popular four-circle ikigai diagram come from?", o: ["It was drawn in the West around 2014 and is not a Japanese tradition", "An ancient Zen temple", "A Japanese school textbook", "The Japanese Forestry Agency"] },
    bring: "When someone shows the ikigai circles: “In Japan ikigai just means the small things you live for. Those four circles were drawn in the West.”",
    follow: "What is one plain, worn thing you own that you love more than anything new?",
    deeper: "Okinawa, often called a land of long life, is where many ikigai books begin. Kintsugi, repairing pottery with gold so the cracks show, is the clearest picture of wabi-sabi." },

  /* ---------- India: music and dance ---------- */

  { id: "ar-ravi-shankar-sitar", type: "person", domain: "anthropology", region: "india", title: "Ravi Shankar takes the sitar to the world", value: 4, cue: "Indian classical music, the sitar, or Indians abroad",
    emoji: "🪕", wiki: "Ravi Shankar",
    fact: "Pandit Ravi Shankar played the sitar at the Monterey Pop Festival in 1967 and at Woodstock in 1969, in front of huge rock audiences. In 1971 he and George Harrison organised the Concert for Bangladesh in New York, the first big charity concert.",
    why: "He made a 300-year-old Indian instrument part of world music, and showed that Indian classical music could fill a stadium.",
    mech: "He had toured Europe as a dancer as a boy, so he understood Western audiences. In the 1950s he toured as a soloist and made records abroad. George Harrison learned from him in 1966, and the Beatles' use of the sitar made young people curious. Shankar then played at the big festivals, but insisted on playing full ragas, not pop versions. At the Concert for Bangladesh the crowd applauded after the musicians finished tuning. He replied that if they liked the tuning so much, he hoped they would enjoy the playing more.",
    models: ["network-effects", "circle-of-competence"],
    q: "How did Ravi Shankar bring the sitar to a world audience?",
    a: "He toured the West from the 1950s and taught George Harrison in 1966, which made young people curious. He played full ragas at Monterey in 1967 and Woodstock in 1969, and with Harrison organised the Concert for Bangladesh in 1971.",
    chain: [["He toured the West as a soloist from the 1950s", ["1950", "toured", "tour", "soloist", "abroad"]], ["He taught George Harrison in 1966", ["harrison", "1966", "beatles", "taught", "learned"]], ["Monterey 1967 and Woodstock 1969", ["monterey", "1967", "woodstock", "1969", "festival"]], ["The Concert for Bangladesh, 1971", ["bangladesh", "1971", "charity", "concert"]]],
    mcq: { q: "Which 1971 event did Ravi Shankar and George Harrison organise?", o: ["The Concert for Bangladesh in New York", "The first Woodstock festival", "The opening of the Sydney Opera House", "A sitar school in London"] },
    bring: "When Indian music abroad comes up: “Ravi Shankar played Woodstock. At one concert the crowd clapped for his tuning, and he said he hoped they would like the playing more.”",
    follow: "Which Indian art do you think could reach the world next?",
    deeper: "His daughters are the sitar player Anoushka Shankar and the singer Norah Jones. He received the Bharat Ratna in 1999." },

  { id: "ar-raga-time", type: "concept", domain: "anthropology", region: "india", title: "Ragas have a time of day", value: 4, cue: "Hindustani music, morning or evening moods, or a concert",
    emoji: "🌅", wiki: "Raga",
    fact: "In Hindustani classical music, each raga is traditionally linked to a time of day or a season. Bhairav is a dawn raga. Yaman belongs to the early evening. Malkauns is sung late at night. A raga is a set of notes with rules for moving between them, which gives a fixed mood.",
    why: "It is a 1,000-year-old idea that music should match the hour, long before playlists for morning and night.",
    mech: "The day is divided into eight parts of three hours each, called prahars. Theory links the notes used in a raga to a prahar. Ragas with flattened notes near the base of the scale, for example, are given to the hours around dawn and dusk. Musicians say the mood of these notes matches the quiet of those hours. Many singers still follow the rule, so an all-night concert moves through ragas as the night passes. Carnatic music in the south has the same idea but follows it less strictly today.",
    models: ["map-vs-territory"],
    q: "What does it mean that a raga has a time, and how does the system work?",
    a: "A raga is a set of notes with rules of movement that gives a mood. Each is linked to one of eight three-hour parts of the day, called prahars. Bhairav is for dawn, Yaman for early evening and Malkauns for late night, and concerts still often follow this.",
    chain: [["A raga is notes plus rules, giving a mood", ["set of notes", "rules", "mood", "notes"]], ["The day is split into eight prahars", ["prahar", "eight", "three hours", "three-hour"]], ["Examples: Bhairav dawn, Yaman evening, Malkauns night", ["bhairav", "yaman", "malkauns", "dawn", "evening", "night"]], ["Concerts still follow it", ["concert", "still", "follow", "singers"]]],
    mcq: { q: "Which raga is traditionally sung at dawn?", o: ["Bhairav", "Yaman", "Malkauns", "Darbari"] },
    bring: "When someone plays a Yaman-based film song in the morning: “Yaman is an evening raga. Our music has had time slots for a thousand years.”",
    follow: "Does any music feel wrong to you at the wrong time of day?",
    deeper: "Many film songs are built on ragas. Compositions in Yaman include many classic Hindi songs, which is one reason it sounds so familiar even to people who never studied music." },

  { id: "ar-bharatanatyam-revival", type: "event", domain: "anthropology", region: "india", title: "Bharatanatyam's revival in the 1930s", value: 4, cue: "classical dance, arangetrams, or how traditions get saved",
    emoji: "💃", wiki: "Bharatanatyam",
    fact: "Bharatanatyam, the classical dance of Tamil Nadu, grew from sadir, a temple and court dance performed by devadasi women. In the early 1900s reformers attacked the devadasi system, and the dance nearly died with it. In the 1930s a new movement put it on the public stage, and in 1947 Madras banned temple dedication of girls.",
    why: "The most popular Indian classical dance today was close to vanishing a hundred years ago. It survived by changing who danced it and where.",
    mech: "Devadasis were women dedicated to temples who kept music and dance alive for centuries, but by the 1800s many were pushed into poverty and exploitation. Reformers wanted the system ended, and the dance was shamed along with it. From 1932 the lawyer E. Krishna Iyer argued the dance itself was a treasure. In 1935 Rukmini Devi Arundale, from a Brahmin family, learned it and danced in public, and in 1936 she founded the Kalakshetra school in Madras. Hereditary dancers like T. Balasaraswati kept the older style alive. Middle-class families then began sending their daughters to learn.",
    models: ["second-order-thinking", "social-proof"],
    q: "How did Bharatanatyam nearly disappear and then revive?",
    a: "It came from sadir, danced by devadasi women in temples and courts. Reformers attacked the devadasi system, which was linked to exploitation, and the dance was shamed with it. From the 1930s E. Krishna Iyer and Rukmini Devi Arundale, who founded Kalakshetra in 1936, put it on the public stage, and Madras banned temple dedication in 1947.",
    chain: [["It grew from sadir, danced by devadasis", ["sadir", "devadasi", "temple", "court"]], ["Reformers attacked the system and the dance was shamed", ["reform", "shame", "exploit", "poverty", "banned", "1947"]], ["Krishna Iyer and Rukmini Devi put it on stage; Kalakshetra 1936", ["krishna iyer", "rukmini", "kalakshetra", "1936", "stage", "public"]], ["Middle-class families took it up", ["middle-class", "middle class", "families", "daughters", "learn"]]],
    mcq: { q: "Who founded the Kalakshetra dance school in 1936?", o: ["Rukmini Devi Arundale", "T. Balasaraswati", "Rabindranath Tagore", "M. S. Subbulakshmi"] },
    bring: "At an arangetram: “A hundred years ago this dance was almost gone. Rukmini Devi and others brought it from the temple to the stage in the 1930s.”",
    follow: "Which tradition around us today is at risk the way this dance was?",
    deeper: "The name Bharatanatyam itself came into common use in the 1930s. The older hereditary dancers lost their place in the revival, which is a painful part of the story that scholars still debate." },

  { id: "ar-kathakali-green", type: "concept", domain: "anthropology", region: "india", title: "Why Kathakali heroes have green faces", value: 3, cue: "Kerala, dance drama, or masks and make-up",
    emoji: "🎨", wiki: "Kathakali",
    fact: "Kathakali is a dance drama from Kerala that took shape around the 17th century. Its actors wear thick painted make-up that takes several hours to apply. The colour tells you the character's nature at once: green, called pacha, is for noble heroes and gods. A red mark or beard shows evil or anger.",
    why: "The audience knows who is good before anyone speaks. The face is a code, like a traffic light.",
    mech: "Kathakali has no spoken dialogue; singers tell the story while actors act it with hand signs and faces. So the make-up must do the work of a costume and a name tag. Pacha, green, means a calm, virtuous character like Rama or Arjuna. Kathi, green with a red moustache shape, marks a proud villain like Ravana. Thaadi types, with beards, are demons or wild men, and black is for hunters and forest people. A white paper frame, the chutti, is glued along the jaw to make the face larger for the audience. Plays often run all night by lamplight.",
    models: ["map-vs-territory"],
    q: "How does Kathakali make-up tell the story?",
    a: "There is no spoken dialogue, so colour codes the character. Green, pacha, is for noble heroes and gods. Kathi adds a red moustache shape for proud villains. Bearded thaadi types are demons, and a white chutti frame makes the face larger.",
    chain: [["No spoken dialogue, so the face must tell", ["no spoken", "dialogue", "singers", "hand signs"]], ["Green, pacha, for noble heroes", ["green", "pacha", "hero", "noble"]], ["Red marks for villains, beards for demons", ["red", "kathi", "villain", "thaadi", "beard", "demon"]], ["Hours of make-up and a white chutti frame", ["chutti", "hours", "paper", "frame"]]],
    mcq: { q: "In Kathakali, what does a green face mean?", o: ["A noble hero or god", "A demon", "A comic servant", "A dead character"] },
    bring: "When Kerala tourism posters come up: “That green face is a code. Green means the good guy. Add a red moustache and he is the villain.”",
    follow: "What colour codes do we use in daily life without thinking?",
    deeper: "The stories come mostly from the Mahabharata, Ramayana and Puranas. Training takes years and includes eye exercises so an actor can show emotion with eye movement alone." },

  /* ---------- India: film, painting, literature ---------- */

  { id: "ar-pather-panchali", type: "historical story", domain: "history", region: "india", title: "Pather Panchali was made on a shoestring", value: 5, cue: "Indian cinema, Satyajit Ray, or doing a lot with little money", story: "pather",
    emoji: "🎬", wiki: "Pather Panchali",
    fact: "Satyajit Ray, a Calcutta advertising artist, began shooting Pather Panchali in 1952 with no film experience, an amateur cast and a borrowed camera. Money ran out again and again, and shooting stretched over about three years. His wife Bijoya's jewellery was pawned. The West Bengal government finally loaned the money to finish it. Released in 1955, it won a prize at Cannes in 1956.",
    why: "India's most praised film was made by people who had never made one. It changed how the world saw Indian cinema.",
    mech: "Ray had seen Italian films that used real streets and ordinary people instead of stars and sets, and wanted to do the same for a Bengali village story. No producer would pay for a film with no songs or stars. He sold his records and books and shot on weekends when he had money. During the long gaps the boy actor could have grown up and a dog in the film died, but luck held. A story often told says the state loan was listed under roads improvement, since the title means Song of the Little Road. Jawaharlal Nehru supported the film being sent to Cannes.",
    models: ["margin-of-safety", "first-principles"],
    q: "How was Pather Panchali made, and why did it matter?",
    a: "Ray started in 1952 with an amateur cast and no experience, wanting real villages instead of stars and sets. No producer would fund a film without songs, so he pawned his wife's jewellery and shot when he had money over three years. The West Bengal government loaned the rest. Released in 1955, it won at Cannes in 1956.",
    chain: [["Ray began in 1952 with no experience and amateurs", ["1952", "no film experience", "amateur", "advertising", "borrowed camera"]], ["No producer would fund it; jewellery pawned", ["producer", "pawn", "jewellery", "jewelry", "sold his", "money ran out"]], ["The state government loaned money to finish", ["government", "loan", "west bengal", "roads"]], ["Released 1955, Cannes prize 1956", ["1955", "cannes", "1956", "prize"]]],
    mcq: { q: "Who finally paid for Pather Panchali to be finished?", o: ["The West Bengal government, with a loan", "A Bombay film studio", "Jawaharlal Nehru personally", "A British film company"] },
    bring: "When someone says they need a big budget first: “Satyajit Ray made Pather Panchali over three years with a borrowed camera and pawned jewellery.”",
    follow: "What would you make if you did not wait for someone else's money?",
    deeper: "Ray went on to make the Apu Trilogy and received an honorary Oscar in 1992, shortly before his death. The film's music was by Ravi Shankar." },

  { id: "ar-mughal-miniature", type: "concept", domain: "design", region: "india", title: "The Mughal painting workshop", value: 3, cue: "miniature paintings, museums, or how art gets made in a team",
    emoji: "🖌️", wiki: "Mughal painting",
    fact: "Mughal miniature paintings were made in a royal workshop, called a karkhana, where many artists worked on one picture. Under Akbar, over a hundred painters worked on the Hamzanama, a set of about 1,400 large paintings. Emperor Jahangir claimed he could name which artist had painted any face or hand.",
    why: "A famous miniature is usually a team product, not one genius with a brush. The workshop model is why so much was made so fast.",
    mech: "Humayun brought two Persian masters back from exile in the 1550s. Akbar expanded the workshop and hired Indian painters, many of them Hindu, so Persian and Indian styles mixed. Work was split: one artist drew the outline, another painted the colours, a specialist did faces, and a gilder added gold. Names were sometimes written in the margin so the emperor could judge each person. Under Jahangir the fashion moved to detailed studies of birds, animals and single portraits, painted from life.",
    models: ["network-effects"],
    q: "How were Mughal miniature paintings produced?",
    a: "In a royal workshop, the karkhana, where work was divided: one artist drew outlines, another coloured, a specialist painted faces. Akbar hired Indian painters alongside Persian masters, so styles mixed; over a hundred artists made the 1,400 Hamzanama paintings. Jahangir claimed he could identify each painter's hand.",
    chain: [["A royal workshop, the karkhana", ["karkhana", "workshop", "royal", "atelier"]], ["Work was divided among specialists", ["divided", "split", "outline", "colour", "faces", "specialist"]], ["Persian and Indian styles mixed under Akbar", ["persian", "indian painters", "mixed", "akbar", "hundred"]], ["Jahangir could identify each painter's hand", ["jahangir", "identify", "name which", "hand"]]],
    mcq: { q: "What was a Mughal karkhana?", o: ["A royal workshop where teams of artists and craftsmen worked", "A tax on paintings", "A type of paper from Kashmir", "A Persian word for a portrait"] },
    bring: "In a museum: “Most of these miniatures were team work. One man did outlines, one did colour, one did only faces.”",
    follow: "Does knowing it was a team change how you see the painting?",
    deeper: "Painters used brushes with a single squirrel hair for fine lines and ground lapis lazuli for blue. Rajput courts developed their own schools from the same roots, which is why so many styles exist." },

  { id: "ar-mahabharata-length", type: "fact", domain: "language", region: "india", title: "The Mahabharata is the longest poem ever", value: 4, cue: "epics, long books, or Indian stories",
    emoji: "📜", wiki: "Mahabharata",
    fact: "The Mahabharata has about one lakh shlokas, or verse couplets, in Sanskrit, around 1.8 million words. That is roughly ten times the Iliad and the Odyssey put together, and about four times the Ramayana. It is the longest epic poem known.",
    why: "It contains the Bhagavad Gita, hundreds of side stories, and a line that says what is not here is nowhere. Much of Indian storytelling still draws from it.",
    mech: "The epic grew over centuries, roughly from 400 BCE to 400 CE. It began as a shorter poem about a war between cousins, the Pandavas and the Kauravas. Storytellers added myths, laws, philosophy and advice as they recited it in different regions. Because it was passed on by memory and by many hands, it kept growing. A critical edition made in Pune between 1919 and 1966 compared over a thousand manuscripts to find the common core.",
    models: ["compounding", "lindy-effect"],
    q: "How long is the Mahabharata, and why is it so long?",
    a: "About one lakh shlokas, around 1.8 million words, roughly ten times the Iliad and Odyssey together. It began as a shorter war poem and grew from about 400 BCE to 400 CE as reciters added stories, laws and philosophy. Pune scholars compared over a thousand manuscripts for a critical edition.",
    chain: [["About one lakh shlokas, 1.8 million words", ["lakh", "1.8 million", "100,000", "shloka", "longest"]], ["Ten times the Iliad and Odyssey together", ["ten times", "iliad", "odyssey", "four times", "ramayana"]], ["Grew over centuries as reciters added material", ["grew", "centuries", "added", "400 bce", "recit"]], ["Pune critical edition compared a thousand manuscripts", ["pune", "critical edition", "manuscripts", "thousand"]]],
    mcq: { q: "Roughly how does the Mahabharata compare with the Iliad and Odyssey combined?", o: ["About ten times as long", "About the same length", "About half as long", "About twice as long"] },
    bring: "When someone says a book is too long: “The Mahabharata is ten times the Iliad and Odyssey together, and people still tell it at festivals.”",
    follow: "Which story from it did you hear first as a child?",
    deeper: "The Bhandarkar Oriental Research Institute in Pune made the critical edition. The Mahabharata was shown as a 94-episode TV series in 1988 and 1989, and streets emptied on Sunday mornings when it aired." },

  { id: "ar-panchatantra-travels", type: "fact", domain: "language", region: "india", title: "The Panchatantra travelled to Europe", value: 4, cue: "fables, children's stories, or Indian ideas abroad",
    emoji: "🦊", wiki: "Panchatantra",
    fact: "The Panchatantra is a Sanskrit book of animal fables, traditionally said to be by Vishnu Sharma, from around 300 BCE or earlier. In the 500s CE a Persian doctor translated it into Pahlavi. From there it went into Arabic as Kalila wa Dimna, then into Hebrew, Latin and most European languages. Many fables Europeans know as their own began here.",
    why: "It may be the most translated non-religious book from ancient times. Stories are India's oldest export.",
    mech: "The stories were written to teach princes how to think about friends, enemies and power. Animal characters made the lessons safe and easy to remember. The Persian king Khosrow I sent his doctor Borzuya to India to fetch it. Arabic scholars translated it around 750 CE, and Muslim Spain carried it into Europe. The French poet La Fontaine said openly in 1678 that many of his fables came from the Indian sage Pilpay, a European name for the book's author.",
    models: ["network-effects", "lindy-effect"],
    q: "How did the Panchatantra reach Europe?",
    a: "A Sanskrit book of animal fables for teaching princes, from around 300 BCE. A Persian doctor, Borzuya, translated it in the 500s; it went into Arabic as Kalila wa Dimna around 750 and then through Spain into Hebrew, Latin and European languages. La Fontaine credited the Indian sage Pilpay in 1678.",
    chain: [["Sanskrit animal fables to teach princes", ["sanskrit", "fables", "princes", "vishnu sharma", "300 bce"]], ["Translated into Persian in the 500s", ["persian", "pahlavi", "borzuya", "500s", "khosrow"]], ["Into Arabic as Kalila wa Dimna, then Europe", ["arabic", "kalila", "750", "spain", "latin", "hebrew"]], ["La Fontaine credited Pilpay", ["la fontaine", "pilpay", "1678", "credited"]]],
    mcq: { q: "What is Kalila wa Dimna?", o: ["The Arabic version of the Panchatantra", "A Persian cookbook", "An Arabic history of India", "A Mughal painting"] },
    bring: "When someone tells a fable about a clever jackal: “Half of Europe's animal fables came from the Panchatantra, through Persian and Arabic.”",
    follow: "Which Panchatantra story do you still use to explain something?",
    deeper: "The two jackals Karataka and Damanaka became Kalila and Dimna in Arabic. Aesop's fables are older in Greece, and scholars still argue about which stories travelled in which direction." },

  { id: "ar-indian-words-english", type: "fact", domain: "language", region: "india", title: "English words that came from India", value: 4, cue: "English words, pyjamas, bungalows, or language mixing",
    emoji: "🔤", wiki: "Hobson-Jobson",
    fact: "Many everyday English words came from Indian languages during the colonial period. Bungalow is from Bengali bangla, a house in the Bengal style. Shampoo is from Hindi champo, to press or massage. Jungle is from jangal and loot from Hindi lut. Pyjamas comes from Persian and Urdu pae-jama, a leg garment. Verandah, thug, juggernaut, avatar and guru are others.",
    why: "When you wear pyjamas in a bungalow and shampoo your hair, you are speaking three Indian words. The flow of words went both ways.",
    mech: "Company officers and soldiers lived in India for years and needed words for things England did not have. A low house with a verandah, a head massage, a dense forest, loose trousers for sleeping: each needed a name. They carried the words home. In 1886 two Englishmen published Hobson-Jobson, a dictionary of such words with over 2,000 entries. The Oxford English Dictionary later took many of its entries from it. Juggernaut comes from Jagannath of Puri, whose giant festival chariot amazed visitors.",
    models: ["network-effects"],
    q: "How did Indian words enter English, and which ones do we use every day?",
    a: "Company officers and soldiers in India needed words for Indian things, like bungalow from bangla, shampoo from champo, jungle from jangal and pyjamas from pae-jama. They carried them home. Hobson-Jobson in 1886 collected over 2,000 such words and the Oxford dictionary used it.",
    chain: [["Colonial officers needed words for Indian things", ["officer", "soldier", "company", "needed words", "colonial"]], ["Bungalow, shampoo, jungle, pyjamas, loot", ["bungalow", "shampoo", "jungle", "pyjama", "loot", "bangla", "champo"]], ["Hobson-Jobson, 1886, listed over 2,000 of them", ["hobson", "1886", "2,000", "dictionary"]], ["They passed into the Oxford dictionary", ["oxford", "carried", "passed", "entered"]]],
    mcq: { q: "Which English word comes from the Hindi word for a head massage?", o: ["Shampoo", "Bungalow", "Jungle", "Verandah"] },
    bring: "When someone says Indians mix too much English into Hindi: “English did the same. Shampoo, bungalow, pyjamas and loot are all Indian words.”",
    follow: "Which Marathi or Hindi word do you think English should borrow next?",
    deeper: "Catamaran is from Tamil kattumaram, tied logs. Cot is from Hindi khat. Hobson-Jobson's odd name is how British soldiers heard the cries of Ya Hasan, Ya Husain at Muharram." },

  /* ---------- India: food and sport ---------- */

  { id: "ar-chai-history", type: "historical story", domain: "business", region: "india", title: "India did not drink chai until the British sold it", value: 5, cue: "chai, tea stalls, marketing, or habits we think are ancient",
    emoji: "🫖", wiki: "Masala chai",
    fact: "Tea was planted in Assam from the 1830s, but almost all of it was shipped to Britain. Ordinary Indians hardly drank tea before 1900. A tea cess from 1903 paid for campaigns to sell it inside India, with tea stalls at railway stations, free samples and posters. By the 1930s chai was an Indian habit.",
    why: "The most Indian drink in the world is barely a century old as a mass habit. It was created by advertising.",
    mech: "In the 1900s tea planters had too much tea and falling prices, so they looked for a new market of 300 million people at home. The Tea Cess Committee gave kettles and tea packets to vendors at railway junctions and factory gates. Demonstration teams went to melas to show how to brew it. Indians changed the drink, adding lots of milk, sugar and spices, which planters disliked because it used less tea. Nationalist leaders were suspicious of tea as a British product. But cheap, hot and sweet chai spread everywhere. Today India drinks most of the tea it grows.",
    models: ["incentives", "social-proof", "feedback-loops"],
    q: "How did chai become India's drink?",
    a: "Tea grown in Assam from the 1830s was exported, and Indians hardly drank it before 1900. Facing a glut, planters used a 1903 tea cess to pay for stalls at railway stations, free samples and posters. Indians added milk, sugar and spices, and by the 1930s chai was a habit.",
    chain: [["Tea grown from the 1830s was all exported", ["1830", "assam", "export", "shipped", "britain"]], ["Planters had a glut and wanted a home market", ["glut", "too much tea", "falling prices", "home market", "300 million"]], ["A 1903 cess paid for stalls, samples and posters", ["cess", "1903", "stall", "railway", "sample", "poster", "campaign"]], ["Indians added milk, sugar and spices; a habit by the 1930s", ["milk", "sugar", "spice", "1930", "habit"]]],
    mcq: { q: "Why did Indians start drinking tea in large numbers in the early 1900s?", o: ["Tea planters ran advertising campaigns and set up stalls to sell their surplus at home", "Ayurveda had recommended it for centuries", "Mughal emperors made it the court drink", "Chinese traders introduced it to Indian markets"] },
    bring: "At a tea stall: “A hundred years ago this stall would not exist. Indians did not drink tea until the planters advertised it.”",
    follow: "What habit of ours today do you think was made by a company?",
    deeper: "Posters in the 1920s and 1930s showed exactly how much tea, water and milk to use, because planters feared people would use too little tea. The Tea Board of India was formed in 1953." },

  { id: "ar-hindustani-carnatic", type: "concept", domain: "anthropology", region: "india", title: "Hindustani and Carnatic: one root, two systems", value: 4, cue: "classical music, north and south India, or a concert",
    emoji: "🎶", wiki: "Carnatic music",
    fact: "India has two classical music systems. Hindustani music belongs to the north and Carnatic music to the south. Both grew from the same ancient roots and share the ideas of raga, a melodic frame, and tala, a rhythm cycle. They drifted apart from about the 13th century, when Persian and Central Asian music entered the northern courts.",
    why: "A listener from Chennai and one from Lucknow hear the same raga names but very different music. The split is a map of India's history.",
    mech: "In the north, Muslim courts brought Persian instruments and tastes, and forms like khayal grew, with long free improvisation and teaching families called gharanas. The south, farther from those courts, kept closer to temple music and fixed compositions. The three great Carnatic composers, Tyagaraja, Muthuswami Dikshitar and Syama Sastri, were all born in Tiruvarur in Tamil Nadu in the 1700s. Their kritis, songs with set words and tunes, are the heart of a Carnatic concert, with improvisation built around them. Carnatic theory sorts ragas into 72 parent scales; Hindustani theory uses 10.",
    models: ["lindy-effect"],
    q: "What do Hindustani and Carnatic music share, and how did they come to differ?",
    a: "Both use raga and tala and come from the same ancient roots. From about the 13th century Persian music entered the northern courts, so Hindustani music grew long improvised forms like khayal and gharanas. Carnatic music in the south stayed closer to temples and to fixed kritis by composers like Tyagaraja.",
    chain: [["Both share raga and tala from the same roots", ["raga", "tala", "same", "roots", "share"]], ["They split from the 13th century under Persian influence in the north", ["13th", "persian", "courts", "split", "drifted"]], ["Hindustani: khayal, long improvisation, gharanas", ["khayal", "improvis", "gharana"]], ["Carnatic: fixed kritis by the Trinity of Tiruvarur", ["kriti", "tyagaraja", "dikshitar", "syama", "tiruvarur", "composition"]]],
    mcq: { q: "Which three composers are called the Trinity of Carnatic music?", o: ["Tyagaraja, Muthuswami Dikshitar and Syama Sastri", "Tansen, Amir Khusrau and Baiju Bawra", "Purandara Dasa, Kabir and Meera", "M. S. Subbulakshmi, Balamuralikrishna and Semmangudi"] },
    bring: "When north and south differences come up: “Our two classical musics use the same raga idea. The north took in Persian taste; the south kept to temple songs.”",
    follow: "Which do you find easier to listen to, and why?",
    deeper: "Hindustani concerts feature instruments like the sitar, sarod and tabla. Carnatic concerts use the veena, violin and mridangam. The violin came with Europeans and was adopted by Carnatic musicians in the 1800s." },

  { id: "ar-anand-chess", type: "person", domain: "history", region: "india", title: "Viswanathan Anand and India's chess boom", value: 4, cue: "chess, child prodigies, or how one success creates many",
    emoji: "♟️", wiki: "Viswanathan Anand",
    fact: "Viswanathan Anand from Chennai became India's first chess grandmaster in 1988. He was world champion five times. In 1988 India had one grandmaster; by 2024 it had over 80, and in December 2024 D. Gukesh, aged 18, became the youngest world champion ever.",
    why: "One person showing it can be done changes what thousands of parents and children think is possible. The game itself began in India as chaturanga.",
    mech: "Anand learned chess from his mother and played fast, which earned him the name Lightning Kid. His success made chess respectable for middle-class families, especially in Tamil Nadu. Chennai built clubs and coaches, and the state gave jobs and support to players. The internet then let Indian children play strong opponents and study with computers from home. Younger players like Praggnanandhaa and Gukesh trained in Anand's academy. In 2024 India won both the open and women's gold at the Chess Olympiad.",
    models: ["social-proof", "network-effects", "compounding"],
    q: "How did Anand's success lead to an Indian chess boom?",
    a: "Anand became India's first grandmaster in 1988 and a five-time world champion, which made chess respectable for middle-class families. Chennai built clubs and coaches, the internet let children train from home, and his academy coached players like Gukesh. India went from one grandmaster to over 80, and Gukesh became world champion in 2024.",
    chain: [["First Indian grandmaster in 1988, five-time champion", ["1988", "first", "grandmaster", "five", "world champion"]], ["Made chess respectable for families", ["respectable", "families", "parents", "middle-class", "middle class"]], ["Clubs, coaches and the internet", ["club", "coach", "internet", "computer", "academy"]], ["Over 80 grandmasters; Gukesh champion in 2024", ["80", "gukesh", "2024", "youngest", "olympiad"]]],
    mcq: { q: "Who became the youngest world chess champion ever, in December 2024?", o: ["D. Gukesh", "Viswanathan Anand", "Praggnanandhaa", "Magnus Carlsen"] },
    bring: "When chess comes up: “India had one grandmaster in 1988, Anand. Now there are over 80, and the world champion is an 18-year-old from Chennai.”",
    follow: "In which field do you think India needs its first Anand?",
    deeper: "Anand's early years were helped by a Soviet cultural centre in Madras that ran chess sessions. Chess computers and online play ended the advantage that Soviet-trained players once held from their books and coaches." }

  ]));

  MV.STORIES.push(
  { id: "monalisa", assetId: "ar-mona-lisa-theft", title: "The Empty Hooks on the Wall",
    hook: "The Mona Lisa became the most famous painting on earth because one morning in 1911 it was not there.",
    setting: "Paris, Monday 21 August 1911. The Louvre is closed to visitors for cleaning, and a few workers in white coats move through the halls.",
    character: "Vincenzo Peruggia, an Italian house painter who had once worked at the museum, and the police of Paris, who have no idea what to do.",
    conflict: "Peruggia lifted the small painting off its hooks, took it out of its frame in a stairway and walked out under his coat. For a whole day nobody noticed it was missing.",
    surprise: "When the museum reopened a week later, thousands of Parisians queued to look at the empty hooks on the wall. Newspapers printed the picture every day for two years.",
    turning: "In December 1913 Peruggia wrote to an art dealer in Florence, offering to return the painting to Italy. The dealer called the museum director, and the police were waiting.",
    payoff: "The painting toured Italy and returned to the Louvre on 4 January 1914. Crowds that had never heard of it now knew its face.",
    meaning: "Fame grows from a story people repeat. The two years of empty wall did more for the Mona Lisa than four centuries of quiet admiration.",
    extra: ["The police questioned the poet Guillaume Apollinaire and his friend Pablo Picasso, because they had once handled small statues stolen from the Louvre.", "Peruggia hid the painting in a trunk with a false bottom in his room in Paris, a short walk from the museum.", "He was given about a year in prison and served only around seven months; many Italians saw him as a patriot."],
    facts: [["1911"], ["louvre", "paris"], ["peruggia", "worker", "house painter"], ["empty", "hooks"], ["newspaper"], ["florence", "dealer", "1913"], ["famous", "fame"]],
    vocab: ["heist", "icon", "patriot"] },

  { id: "dostoevsky", assetId: "ar-dostoevsky-execution", title: "Five Minutes Before the Firing Squad",
    hook: "A young writer stood in the snow waiting to be shot. The pardon that saved him had been written before he was even led out.",
    setting: "St Petersburg, Russia, 22 December 1849. A frozen parade ground at dawn, with soldiers in rows and a crowd watching.",
    character: "Fyodor Dostoevsky, 28, a writer with one successful novel, and Tsar Nicholas I, who wanted to frighten young thinkers into silence.",
    conflict: "Dostoevsky had joined a circle that met to read banned books and discuss freeing the serfs. The police arrested the whole group. After eight months in a fortress they were sentenced to death.",
    surprise: "The men were dressed in white shrouds, the sentence was read aloud, and the first three were tied to posts. Then a drum rolled and an officer rode up with a letter. The Tsar had changed the sentences to prison. He had planned the whole show.",
    turning: "One of the condemned men lost his mind that morning. Dostoevsky wrote to his brother the same night that life was a gift and he would not waste a single minute.",
    payoff: "He spent four years in chains in a prison camp in Siberia, then years as a soldier. He came back and wrote Crime and Punishment, The Idiot and The Brothers Karamazov.",
    meaning: "Knowing how close the end can be changes what a person does with ordinary days. Dostoevsky turned the cruelest trick of his life into the depth of his books.",
    extra: ["The group was called the Petrashevsky Circle after the man who hosted the meetings.", "In Siberia he could read only the New Testament, given to him by the wives of earlier political prisoners.", "In The Idiot, a character describes the thoughts of a man in his last minutes before execution, drawn from Dostoevsky's own memory."],
    facts: [["1849"], ["banned books", "circle", "serfs"], ["death", "firing squad", "shot"], ["pardon", "letter", "changed the sentences"], ["tsar"], ["siberia", "prison camp", "chains"], ["crime and punishment", "karamazov", "idiot"]],
    vocab: ["pardon", "condemned", "serf"] },

  { id: "pather", assetId: "ar-pather-panchali", title: "The Song of the Little Road",
    hook: "An advertising artist with no film training, a borrowed camera and a cast of amateurs made the film that put Indian cinema on the world map.",
    setting: "A village near Calcutta, 1952. Satyajit Ray shoots on weekends because he still works at an advertising agency during the week.",
    character: "Satyajit Ray, tall, quiet and stubborn, and his wife Bijoya, who watches the family savings disappear into film stock.",
    conflict: "No producer wants a Bengali film with no songs, no stars and child actors. Money runs out after a few days of shooting, and the half-finished film sits in cans for months at a time.",
    surprise: "Ray sells his records and art books and pawns his life insurance. When even that is gone, Bijoya's jewellery goes to the pawnshop so shooting can continue a few more days.",
    turning: "After about three years, the West Bengal government agrees to loan the money to finish the film. A story often told says the loan was recorded under roads improvement, because the title means Song of the Little Road.",
    payoff: "Pather Panchali was released in 1955 and ran for weeks in Calcutta. In 1956 it won a prize at the Cannes film festival and was shown around the world.",
    meaning: "You do not need permission, or a big budget, to start. Ray learned filmmaking by making the film, and the lack of money forced him to show real life instead of sets.",
    extra: ["Ray got the courage to try after seeing the Italian film Bicycle Thieves in London in 1950, made with real streets and non-actors.", "During the long gaps, the boy playing Apu could have grown too big for his part, and the family's dog died and had to be replaced.", "Ravi Shankar composed the music in a single long overnight session, and Ray went on to make two more films about Apu."],
    facts: [["1952", "1955", "1956"], ["ray"], ["no producer", "no songs", "no stars", "money runs out", "money ran out"], ["jewellery", "pawn"], ["government", "loan"], ["cannes"], ["amateur", "borrowed camera", "no film training"]],
    vocab: ["shoestring", "amateur", "pawn"] }
  );

  MV.LINKS.push(
    /* world art and words */
    ["ar-mona-lisa-theft", "ar-van-gogh-sales", "In both cases the value the world placed on a painting came years later, from a story and from who kept telling it."],
    ["ar-mona-lisa-theft", "py-mere-exposure", "Seeing the Mona Lisa's picture in the newspaper every day for two years made millions feel they knew and liked it."],
    ["ar-mona-lisa-theft", "mp-kala-ghoda", "A missing painting and a missing horse statue both made a place more famous than the object itself."],
    ["ar-van-gogh-sales", "wald-bombers", "We see the few artists who became famous after death, not the many whose work was simply lost. Johanna's care was the difference."],
    ["ar-van-gogh-sales", "ar-marquez-solitude", "Both men created their best work while someone else paid the bills: Theo for Vincent, Mercedes and the pawnshop for Gabo."],
    ["ar-david-block", "shivaji-forts", "Both turned a limit others saw as a weakness, a thin block or steep hills, into the shape of their success."],
    ["ar-david-block", "kailasa-temple", "Both were carved out of a single piece of stone, one by removing a hillside, one by removing everything that was not David."],
    ["ar-leonardo-notebooks", "th-darwin-golden-rule", "Both men wrote down everything, and the notebooks outlived the books they planned to write."],
    ["ar-leonardo-notebooks", "mp-asiatic-dante", "Mumbai's Asiatic Society and Bill Gates's Codex Leicester show how a single old manuscript can become priceless."],
    ["ar-guernica", "wm-hitler-election", "Guernica was bombed by German planes sent to help Franco, a rehearsal for the war Hitler's rise would bring."],
    ["ar-guernica", "wm-hiroshima", "Both are images of civilians under bombing that shaped how the century saw war."],
    ["ar-shakespeare-words", "ar-indian-words-english", "English grew by borrowing and inventing: Shakespeare coined words at home while soldiers brought bungalow and shampoo from India."],
    ["ar-shakespeare-words", "wh-gutenberg", "Printing is why Shakespeare's words survived. Cheap books kept his plays in schools for 400 years."],
    ["ar-shakespeare-words", "is-panini-grammar", "Panini fixed Sanskrit with rules; Shakespeare's English had no rules yet, which is why he could invent so freely."],
    /* music */
    ["ar-beethoven-ninth", "py-deliberate-practice", "Decades of practice let Beethoven hear a full orchestra in his head from the written notes alone."],
    ["ar-beethoven-ninth", "th-frankl-meaning", "Both found a reason to keep working inside a loss that looked like the end of their life's purpose."],
    ["ar-mozart-requiem", "py-bystander", "Both are famous stories where the dramatic version replaced the true one and is still repeated."],
    ["ar-mozart-requiem", "ar-nobel-obituary", "Both carry a popular legend, the poisoning and the mistaken obituary, that is more told than proven."],
    ["ar-jazz-new-orleans", "wh-columbian-exchange", "Jazz is a late result of the Columbian exchange: African, European and American traditions meeting in a port city."],
    ["ar-jazz-new-orleans", "mhc-lavani", "Both are popular music forms shaped by the places they were performed, dance halls in New Orleans and tamasha tents in Maharashtra."],
    ["ar-beatles-rishikesh", "ar-ravi-shankar-sitar", "George Harrison's lessons with Ravi Shankar led the Beatles to India, and their fame sent crowds to Shankar's concerts."],
    ["ar-beatles-rishikesh", "th-vivekananda-chicago", "Vivekananda in 1893 and the Beatles in 1968 are the two moments when Indian thought reached a mass Western audience."],
    ["ar-ravi-shankar-sitar", "mhc-bhimsen-sawai", "Shankar took Hindustani music to Woodstock while Bhimsen Joshi built a festival for it at home in Pune."],
    ["ar-ravi-shankar-sitar", "ar-pather-panchali", "Ravi Shankar composed the music for Pather Panchali in one overnight session."],
    ["ar-raga-time", "mhc-bhimsen-sawai", "The Sawai Gandharva festival runs through the night so singers can present the ragas of each hour."],
    ["ar-raga-time", "sp-doppler", "Both are about how sound carries meaning: a raga's notes signal a time of day, a siren's pitch signals motion."],
    ["ar-raga-time", "ar-jazz-new-orleans", "Both traditions build on improvisation within rules: a raga's grammar in India, chord changes in jazz."],
    /* dance and theatre */
    ["ar-bharatanatyam-revival", "mhc-bal-gandharva", "In the same decades, Bal Gandharva played women on the Marathi stage because respectable women did not perform in public."],
    ["ar-bharatanatyam-revival", "im-sati-abolition", "Both are reform movements that ended a practice tied to women, with gains and losses still debated today."],
    ["ar-kathakali-green", "mh-warli", "Both use a small fixed code, three shapes in Warli and a few face colours in Kathakali, to tell a whole story."],
    ["ar-kathakali-green", "ar-mahabharata-length", "Most Kathakali plays take their stories from the Mahabharata and the Ramayana."],
    /* sport */
    ["ar-olympic-truce", "thermopylae", "The Greek cities that fought side by side at Thermopylae, and often against each other, still paused their wars for the Games at Olympia."],
    ["ar-olympic-truce", "wh-athens-lottery", "Both are ancient Greek institutions that modern states copied in form while changing the meaning."],
    ["ar-marathon-distance", "mw-marathon", "Every runner in the Mumbai Marathon covers the distance fixed by a royal box in London in 1908."],
    ["ar-marathon-distance", "wm-metric-system", "One distance came from a revolution's wish for logic; the other from where a king wanted to sit."],
    ["ar-football-1863", "in-ipl", "Written rules made football a world sport in 1863; a new format and TV deal made cricket a business in 2008."],
    ["ar-football-1863", "red-queen", "After the 1925 offside change, attackers scored more until coaches invented new defences, and the race began again."],
    ["ar-football-1863", "bm-incentives", "Change one rule and the whole game changes: goals rose by a third when the offside law was eased."],
    ["ar-hindustani-carnatic", "ar-raga-time", "The time-of-day rule for ragas is followed strictly in Hindustani music and loosely in Carnatic music."],
    ["ar-hindustani-carnatic", "ih-sultanate-founding", "The Delhi Sultanate brought the Persian court culture that pulled northern music away from the south."],
    ["ar-hindustani-carnatic", "ih-shore-temple", "Carnatic music stayed close to the temple traditions of the Tamil country, where Mahabalipuram also stands."],
    ["ar-anand-chess", "in-chaturanga", "Chess began in India as chaturanga, and Anand brought the world title back 1,400 years later."],
    ["ar-anand-chess", "mhc-tendulkar-debut", "Anand and Tendulkar both arrived as teenagers in the late 1980s and made a whole generation believe."],
    ["ar-anand-chess", "bm-misjudgment", "Once one Indian grandmaster existed, thousands of families decided chess was a serious path."],
    /* prizes, books, ideas */
    ["ar-nobel-obituary", "in-raman-effect", "C. V. Raman in 1930 was the first Asian to win a Nobel in science, from the prize Nobel's will created."],
    ["ar-nobel-obituary", "bm-reputation", "Nobel used his will to rebuild in one stroke the reputation that dynamite had built for him."],
    ["ar-dostoevsky-execution", "stoic-control", "Facing death, Dostoevsky found that only his attention and his use of time were truly his."],
    ["ar-dostoevsky-execution", "th-seneca-premeditatio", "Seneca advised imagining the worst; Dostoevsky lived it, and said it made every day after a gift."],
    ["ar-marquez-solitude", "in-ramanujan-hardy", "A manuscript posted with great difficulty from a poor man changed a whole field, in literature and in mathematics."],
    ["ar-marquez-solitude", "mhc-sairat", "Both show that a story made for a local audience, in Spanish or in Marathi, can earn far beyond its budget."],
    ["ar-kaizen", "dabbawalas", "Both systems work through small steps owned by the people doing the work, not through top-down design."],
    ["ar-kaizen", "wm-meiji", "Japan's habit of learning fast from others and improving in steps goes back to the Meiji years."],
    ["ar-kaizen", "th-aristotle-habit", "Aristotle said we become what we repeatedly do; kaizen applies the same idea to a factory."],
    ["ar-japanese-ideas", "ph-zen-beginners-mind", "Wabi-sabi grew from the same Zen tradition that values an empty cup and a beginner's mind."],
    ["ar-japanese-ideas", "map-territory", "The ikigai diagram is a Western map of a Japanese word; the two do not match."],
    /* Indian literature and language */
    ["ar-mahabharata-length", "ih-rigveda-oral", "Both huge Sanskrit texts were carried by memory for centuries, which is also why the Mahabharata kept growing."],
    ["ar-mahabharata-length", "th-gita-nishkama-karma", "The Bhagavad Gita is one small part of the Mahabharata, set just before the great battle."],
    ["ar-panchatantra-travels", "wh-house-of-wisdom", "Indian numbers and Indian fables took the same road west, through Persia and Arabic scholars."],
    ["ar-panchatantra-travels", "th-chanakya-four-ways", "Both are Indian handbooks on power written for princes, one in rules and one in animal stories."],
    ["ar-indian-words-english", "east-india-company", "The Company's officers carried these words home along with the fortunes they made in India."],
    ["ar-indian-words-english", "is-shampoo-sachet", "The word shampoo came from India to England; the sachet took the product back to Indian villages."],
    ["ar-indian-words-english", "im-macaulay-minute", "Macaulay pushed English on India, but India had already been pushing its words into English."],
    /* chai */
    ["ar-chai-history", "mh-irani-cafes", "The Irani cafés of Bombay were part of the same wave that made tea a daily habit in the city."],
    ["ar-chai-history", "ih-calico-craze", "Twice the tea and cotton trades flowed from Indian producers to British buyers before the home market mattered."],
    ["ar-chai-history", "monsoon-economy", "Tea is a monsoon crop. Assam's rains, not Chinese seeds, made India the world's second largest grower."],
    ["ar-chai-history", "salt-march", "Nationalists distrusted tea as a British product, yet by the 1930s it had become the drink of Indian meetings and strikes."],
    ["ar-mughal-miniature", "ih-jahangir-chain", "Jahangir judged painters' hands with the same close attention he claimed for justice."],
    ["ar-mughal-miniature", "ajanta", "Ajanta's painters and the Mughal karkhana are the two great traditions of Indian painting, a thousand years apart."],
    ["ar-mughal-miniature", "th-smith-pin-factory", "Splitting one painting among outline, colour and face specialists is Adam Smith's division of labour in art."],
    ["ar-pather-panchali", "raja-harishchandra", "Phalke in 1913 and Ray in 1955 both made their first films with no training and borrowed money."],
    ["ar-pather-panchali", "mhc-sairat", "Both were low-budget regional films that out-earned expectations and changed what producers would fund."]
  );
})();
