/* More India. Same shape as data-india.js. */
(function () {
  const P = list => list.map(a => Object.assign({ region: "india", story: null, jargon: [], mis: [] }, a));

  MV.ASSETS.push(...P([
  { id: "in-constitution-handwritten", type: "fact", domain: "history", region: "india", title: "The handwritten Constitution", value: 4, cue: "Republic Day, the Constitution, or beautiful old documents",
    emoji: "📜", wiki: "Constitution of India",
    fact: "The original Constitution of India was not printed. Prem Behari Narain Raizada wrote every page by hand. Artists from Santiniketan, led by Nandalal Bose, decorated the pages. It is the longest written constitution of any country.",
    why: "India's highest law is also a work of art. The care taken over the pages shows how seriously its makers took the task.",
    mech: "The Constituent Assembly worked for 2 years, 11 months and 18 days. It adopted the Constitution on 26 November 1949. Members signed the handwritten copies on 24 January 1950. The Constitution came into force two days later, on 26 January 1950, which is now Republic Day. Raizada asked for no fee. He asked only to write his name on every page.",
    models: [],
    q: "How was the original Constitution of India made, and when did it come into force?",
    a: "Prem Behari Narain Raizada wrote it by hand and artists led by Nandalal Bose decorated it. The Assembly adopted it on 26 November 1949 after almost three years of work, and it came into force on 26 January 1950.",
    chain: [["Written by hand by Raizada", ["hand", "raizada", "calligraph"]], ["Decorated by Nandalal Bose and other artists", ["nandalal", "santiniketan", "artist", "decorat"]], ["Adopted on 26 November 1949 after almost three years", ["1949", "three years", "2 years", "adopted"]], ["In force on 26 January 1950", ["1950", "26 january", "force", "republic day"]]],
    mcq: { q: "What is special about the original copy of India's Constitution?", o: ["It was written out by hand and decorated by artists", "It was printed in London on gold paper", "It was carved on stone pillars", "It was typed in one night"] },
    bring: "On Republic Day: “The original Constitution was written by hand. The writer took no fee. He only asked to sign every page.”",
    follow: "Have you ever seen pictures of the original pages?",
    deeper: "The original copies are kept in sealed, gas-filled cases in the Parliament library. The makers borrowed good ideas freely: parliamentary government from Britain, fundamental rights from the United States, and directive principles from Ireland." },

  { id: "in-basic-structure", type: "concept", domain: "philosophy", region: "india", title: "The basic structure rule", value: 5, cue: "changing the Constitution, the Supreme Court, or limits on power",
    emoji: "⚖️", wiki: "Kesavananda Bharati v. State of Kerala",
    fact: "On 24 April 1973 the Supreme Court decided the Kesavananda Bharati case. It said Parliament can amend the Constitution, but it cannot change its ‘basic structure’. Thirteen judges heard the case, and the vote was 7 to 6.",
    why: "This one ruling means that no government, however large its majority, can remove the core of the Constitution.",
    mech: "Kesavananda Bharati was the head of the Edneer Matha, a religious institution in Kerala. He challenged state land laws that affected its property. The case grew into a larger question: is there any limit on Parliament's power to amend? The court heard arguments for 68 days. It said some features, such as democracy, secularism and the separation of powers, must always remain.",
    models: ["margin-of-safety", "second-order-thinking"],
    q: "What did the Kesavananda Bharati ruling of 1973 decide?",
    a: "The Supreme Court, by 7 judges to 6, said Parliament can amend the Constitution but cannot change its basic structure. Features such as democracy and the separation of powers must remain, so there is a limit on any majority.",
    chain: [["The Kesavananda Bharati case, 1973", ["kesavananda", "1973"]], ["Parliament can amend the Constitution", ["amend", "parliament"]], ["But not its basic structure", ["basic structure", "core", "limit"]], ["Thirteen judges, decided 7 to 6", ["7 to 6", "7 judges", "thirteen", "13"]]],
    mcq: { q: "What does the ‘basic structure’ rule say?", o: ["Parliament can amend the Constitution but cannot change its core features", "Parliament cannot amend the Constitution at all", "Only the President can amend the Constitution", "The Constitution must be rewritten every 50 years"] },
    bring: "When someone says a big majority can do anything: “Not quite. Since 1973 the Supreme Court says the basic structure of the Constitution cannot be changed.”",
    follow: "Which features of the Constitution do you think should never be changed?",
    deeper: "It is the largest bench in the Supreme Court's history. The lawyer Nani Palkhivala led the arguments for Kesavananda Bharati. The court never gave one fixed list of basic features, so later cases have added to it." },

  { id: "in-chola-navy", type: "event", domain: "strategy", region: "india", title: "The Chola fleet crosses the sea", value: 4, cue: "the navy, Southeast Asia, or old Indian trade",
    emoji: "⛵", wiki: "Rajendra I",
    fact: "In 1025 the Chola king Rajendra I sent a fleet across the Bay of Bengal. It raided the ports of the Srivijaya kingdom in today's Indonesia and Malaysia, including Kadaram, now Kedah. Chola records say its king was captured.",
    why: "Most Indian kingdoms fought only on land. The Cholas of Tamil Nadu carried an army across more than a thousand kilometres of open sea.",
    mech: "Srivijaya controlled the Strait of Malacca, the narrow sea lane between India and China. Ships on this trade route had to pass its ports. The Cholas were rich from sea trade, and Tamil merchant groups worked across these waters. Historians are not sure of the exact reason for the raid. Many think it was a fight over who controlled this trade.",
    models: ["bottlenecks", "incentives"],
    q: "What did Rajendra Chola's navy do in 1025, and what was the likely reason?",
    a: "The Chola fleet crossed the Bay of Bengal and raided the ports of Srivijaya, including Kadaram. Srivijaya controlled the Strait of Malacca, so the likely reason was control of the trade route between India and China.",
    chain: [["Rajendra Chola sent a fleet in 1025", ["chola", "rajendra", "1025", "fleet"]], ["It raided Srivijaya's ports across the Bay of Bengal", ["srivijaya", "kadaram", "kedah", "bay of bengal", "raid"]], ["Srivijaya controlled the Strait of Malacca", ["malacca", "strait", "narrow"]], ["The likely reason was control of trade", ["trade", "china", "merchant"]]],
    mcq: { q: "Which kingdom did Rajendra Chola's fleet raid in 1025?", o: ["Srivijaya, in today's Indonesia and Malaysia", "The Roman Empire", "The Mughal Empire", "The kingdom of Nepal"] },
    bring: "When the navy or Southeast Asia comes up: “A thousand years ago the Cholas sent a fleet from Tamil Nadu all the way to Malaysia and Sumatra.”",
    follow: "Why do you think so few Indian rulers built strong navies?",
    deeper: "Rajendra's father, Rajaraja I, built the great Brihadisvara temple at Thanjavur, finished in 1010. It is a UNESCO World Heritage Site. Tamil merchant inscriptions have been found in Sumatra and even in China." },

  { id: "in-todar-mal", type: "concept", domain: "economics", region: "india", title: "Todar Mal's land tax", value: 4, cue: "taxes, land records, or how Akbar ran his empire",
    emoji: "📏", wiki: "Todar Mal",
    fact: "Raja Todar Mal was Emperor Akbar's finance minister. Around 1580 he set up a land tax system called dahsala, which means ‘ten years’. Fields were measured, and the tax was fixed from ten years of harvests and prices.",
    why: "It replaced guesswork with data. Later Mughal rulers and the British both built their land records on this model.",
    mech: "Earlier, officials estimated each farmer's crop every year. That led to cheating and quarrels. Todar Mal's staff measured the fields with standard units. They recorded yields and prices for ten years, from 1570 to 1580. The state then took about one third of the average crop, paid in cash. Farmers knew in advance what they owed, and the treasury knew what it would receive.",
    models: ["incentives", "first-principles"],
    q: "How did Todar Mal's land tax system work?",
    a: "Fields were measured with standard units. The tax was set from the average harvests and prices of ten years, at about one third of the crop, paid in cash. So farmers knew in advance what they owed.",
    chain: [["Fields were measured with standard units", ["measur", "standard", "survey"]], ["Ten years of harvests and prices were averaged", ["ten years", "10 years", "average", "dahsala"]], ["About one third, paid in cash", ["one third", "third", "cash"]], ["Farmers and the state knew the amount in advance", ["advance", "knew", "fixed", "certain"]]],
    mcq: { q: "What was Todar Mal's tax based on?", o: ["Measured land and ten years of average harvests and prices", "The number of people in each family", "A fresh guess by the local officer every year", "The number of cattle a farmer owned"] },
    bring: "When taxes come up: “Akbar's minister Todar Mal fixed the land tax from ten years of real data. That was in 1580.”",
    follow: "Would you prefer a tax that is fixed in advance or one that changes each year with your income?",
    deeper: "The old measuring ropes stretched when wet and shrank when dry. Akbar's officials replaced them with bamboo rods joined by iron rings. Todar Mal was one of the ‘nine gems’ of Akbar's court." },

  { id: "in-tipu-rockets", type: "fact", domain: "science", region: "india", title: "Tipu Sultan's iron rockets", value: 4, cue: "rockets, missiles, or Indian inventions",
    emoji: "🚀", wiki: "Mysorean rockets",
    fact: "In the late 1700s the armies of Hyder Ali and Tipu Sultan of Mysore fired rockets with iron tubes. They could fly close to 1 km. After Tipu's defeat in 1799, the British copied the design.",
    why: "They were the first successful iron-cased war rockets. A weapon made in Mysore changed European armies.",
    mech: "Older rockets used paper or bamboo tubes, which burst if packed with too much powder. An iron tube could hold much more pressure, so the rocket flew farther. A long bamboo pole tied to it kept it steady. The British found hundreds of rockets at Srirangapatna in 1799. William Congreve studied the idea in England and showed his own rocket in 1805.",
    models: ["first-principles", "second-order-thinking"],
    q: "What was new about the Mysore rockets, and what happened to the idea?",
    a: "They used iron tubes, which held more pressure than paper or bamboo, so they flew close to 1 km. After 1799 the British studied them and William Congreve made his own rocket.",
    chain: [["Hyder Ali and Tipu Sultan of Mysore used war rockets", ["tipu", "mysore", "hyder"]], ["Iron tubes held more pressure", ["iron", "pressure", "tube"]], ["So they flew farther, close to 1 km", ["farther", "1 km", "range", "far"]], ["The British copied them: the Congreve rocket", ["congreve", "british", "copied", "1799"]]],
    mcq: { q: "Why did Mysore's rockets fly farther than older rockets?", o: ["Their iron tubes could hold more pressure", "They were lighter because they were made of paper", "They were fired from cannons", "They used petrol as fuel"] },
    bring: "When rockets or missiles come up: “Tipu Sultan's army used iron rockets in the 1780s. The British copied them after 1799.”",
    follow: "Which other Indian invention do you think was copied abroad?",
    deeper: "British Congreve rockets were fired at Baltimore in 1814. That is the ‘rockets' red glare’ in the national anthem of the United States." },

  { id: "in-princely-states", type: "historical story", domain: "history", region: "india", title: "Joining 560 kingdoms into one India", value: 5, cue: "Sardar Patel, the map of India, or hard negotiations", story: "in-princely",
    emoji: "🗺️", wiki: "Political integration of India",
    fact: "In 1947 British India was only part of the map. More than 560 princely states, covering about two fifths of the land, had their own rulers. Within about two years Sardar Vallabhbhai Patel and V. P. Menon brought almost all of them into India.",
    why: "Without this work, India could have become hundreds of small countries. It was done mostly by talks, in a very short time.",
    mech: "When the British left, their treaties with the princes ended. Each ruler could join India or Pakistan, or try to stay alone. Patel and Menon made a small first request. A ruler signed the Instrument of Accession and gave up only defence, foreign affairs and communications. He kept his title and got a yearly payment called a privy purse. Most rulers signed before 15 August 1947, and fuller mergers followed step by step.",
    models: ["game-theory", "incentives", "commitment-consistency"],
    q: "How did Sardar Patel and V. P. Menon bring the princely states into India?",
    a: "More than 560 princely states could have stayed apart when the British left. Patel and Menon asked each ruler to sign the Instrument of Accession and give up only defence, foreign affairs and communications, while keeping his title and a privy purse. Fuller mergers came later.",
    chain: [["More than 560 princely states had their own rulers", ["560", "princely", "ruler"]], ["Patel and Menon led the work", ["patel", "menon"]], ["A small first request: defence, foreign affairs, communications", ["defence", "foreign affairs", "communications", "accession", "small"]], ["Rulers kept titles and a privy purse; mergers came later", ["privy purse", "title", "merger", "later", "step by step"]]],
    mcq: { q: "What did the Instrument of Accession first ask a ruler to give up?", o: ["Only defence, foreign affairs and communications", "His palace and all his land", "His religion and his title", "All his money and jewels"] },
    bring: "When a hard negotiation comes up: “Patel and Menon did not ask the princes for everything. They first asked for only three subjects.”",
    follow: "In a negotiation, what is the smallest first step you could ask the other side to accept?",
    deeper: "Three cases were hard: Junagadh, Hyderabad, and Jammu and Kashmir. Each was settled in a different way. Hyderabad joined after an Indian military action in September 1948. The privy purses were ended in 1971." },

  { id: "in-raman-effect", type: "scientific principle", domain: "science", region: "india", title: "The Raman effect", value: 5, cue: "Nobel Prizes, National Science Day, or why the sea is blue",
    emoji: "🔬", wiki: "C. V. Raman",
    fact: "In 1928, in Calcutta, C. V. Raman and K. S. Krishnan found that a tiny part of light changes colour when it passes through a clear material. This is the Raman effect. Raman won the Nobel Prize in Physics in 1930.",
    why: "He was the first Asian to win a Nobel Prize in science. Today the effect lets a machine identify a substance without touching or damaging it.",
    mech: "Light comes in small packets of energy. Most packets bounce off a molecule unchanged. About one in a million gives a little energy to the molecule, or takes a little from it. That changes the colour of the light very slightly. Each kind of molecule changes it in its own way, like a fingerprint.",
    models: ["first-principles"],
    q: "What is the Raman effect and why is it useful?",
    a: "When light passes through a material, a tiny part of it exchanges energy with the molecules and changes colour. Each molecule gives its own pattern, like a fingerprint, so the effect can identify substances. Raman won the Nobel Prize for it in 1930.",
    chain: [["Raman found it in 1928 and won the Nobel in 1930", ["raman", "1928", "nobel", "1930"]], ["A tiny part of the light changes colour", ["tiny", "changes colour", "one in a million", "colour"]], ["Light exchanges energy with molecules", ["energy", "molecule"]], ["Each substance gives its own fingerprint", ["fingerprint", "identify", "pattern"]]],
    mcq: { q: "What happens in the Raman effect?", o: ["A tiny part of light changes colour after meeting molecules", "Light stops completely inside glass", "Light turns into sound", "All light becomes blue in water"] },
    bring: "On National Science Day, 28 February: “The day marks the Raman effect. A tiny part of light changes colour, and that tells you what a material is made of.”",
    follow: "Did you know the question started with Raman wondering why the sea looks blue?",
    deeper: "In 1921 Raman sailed to Europe and wondered why the Mediterranean was so blue. That question started his work on light. India marks National Science Day on 28 February in memory of the discovery." },

  { id: "in-ramanujan-hardy", type: "historical story", domain: "science", region: "india", title: "Ramanujan's letter to Hardy", value: 5, cue: "genius, mathematics, or talent that nobody notices", story: "in-ramanujan",
    emoji: "✉️", wiki: "Srinivasa Ramanujan",
    fact: "In January 1913 Srinivasa Ramanujan, a 25-year-old clerk in Madras, posted nine pages of formulas to the Cambridge mathematician G. H. Hardy. He had no degree. Hardy saw that he was a genius and brought him to England in 1914.",
    why: "One of the greatest mathematicians in history was earning 30 rupees a month as a clerk. He was found only because one person read his letter with care.",
    mech: "Ramanujan had taught himself, mostly from one book of formulas. He worked alone, so he wrote down results without the proofs that mathematicians expect. Two other professors sent his papers back. Hardy took the time to check the pages with his colleague Littlewood. He decided nobody could have invented such formulas unless they were true. At Cambridge, Hardy gave the training in proof and Ramanujan gave the ideas.",
    models: ["authority-bias", "bayesian-thinking"],
    q: "How was Ramanujan discovered?",
    a: "He was a self-taught clerk in Madras with no degree. In 1913 he sent a letter full of formulas to Hardy, who checked them, saw his genius and brought him to Cambridge in 1914.",
    chain: [["A self-taught clerk in Madras with no degree", ["clerk", "madras", "no degree", "self-taught", "taught himself"]], ["He sent a letter of formulas to Hardy in 1913", ["letter", "1913", "formula", "hardy", "nine pages"]], ["Hardy checked them and saw his genius", ["check", "genius", "littlewood", "true"]], ["He went to Cambridge in 1914", ["cambridge", "england", "1914"]]],
    mcq: { q: "What was Ramanujan's job when he wrote to Hardy?", o: ["A clerk at the Madras Port Trust", "A professor at Madras University", "A school headmaster in Kumbakonam", "An engineer with the railways"] },
    bring: "When talent comes up: “Ramanujan was a clerk on 30 rupees a month. Two professors ignored his letter. The third one changed mathematics.”",
    follow: "How many Ramanujans do you think we miss because nobody reads their letter?",
    deeper: "He left about 3,900 results and died in 1920, aged only 32. The number 1729 is called the Hardy-Ramanujan number. It equals 1 cubed plus 12 cubed, and also 9 cubed plus 10 cubed." },

  { id: "in-iron-pillar", type: "fact", domain: "science", region: "india", title: "The iron pillar that does not rust", value: 4, cue: "Delhi, the Qutub Minar, or old Indian technology",
    emoji: "🗼", wiki: "Iron pillar of Delhi",
    fact: "An iron pillar has stood in the open air in Delhi for about 1,600 years, and it has hardly rusted. It is 7.21 metres tall and weighs more than six tonnes. It dates from the time of the Gupta king Chandragupta II.",
    why: "Ordinary iron left in the rain rusts away in a few decades. Scientists worked out the reason for this pillar only about twenty years ago.",
    mech: "The old ironworkers did not add lime when they made the iron, so much more phosphorus stayed in the metal. When the pillar first rusted a little, the phosphorus helped form a thin, tight layer on the surface. This layer keeps air and water away from the iron below. Delhi's cycle of wet and dry weather helped the layer grow. So the first rust became a shield against more rust.",
    models: ["lindy-effect", "second-order-thinking"],
    q: "Why has the iron pillar of Delhi not rusted away in 1,600 years?",
    a: "The iron has a lot of phosphorus. It helped form a thin, tight layer on the surface that keeps air and water away from the metal, so the pillar has stood about 1,600 years since Gupta times.",
    chain: [["It has stood about 1,600 years, since Gupta times", ["1,600", "1600", "gupta", "chandragupta"]], ["The iron has a lot of phosphorus", ["phosphorus"]], ["A thin protective layer formed on the surface", ["layer", "shield", "film", "surface"]], ["The layer keeps air and water away", ["air", "water", "keeps"]]],
    mcq: { q: "What protects the iron pillar of Delhi from rust?", o: ["A thin layer formed with the help of phosphorus in the iron", "A coat of paint added every year", "It is really made of stainless steel", "It stands inside a glass case"] },
    bring: "At the Qutub Minar: “That iron pillar is 1,600 years old. The phosphorus in the iron made a thin layer that stops the rust.”",
    follow: "What other old skills do you think we have lost and found again?",
    deeper: "The pillar was forge-welded from many pieces of hot iron. R. Balasubramaniam of IIT Kanpur explained the protective layer in the early 2000s. The pillar was probably first set up elsewhere and moved to Delhi centuries later." },

  { id: "in-kerala-school", type: "fact", domain: "science", region: "india", title: "Madhava and the Kerala school", value: 4, cue: "pi, calculus, or who discovered what first",
    emoji: "♾️", wiki: "Madhava of Sangamagrama",
    fact: "Around 1400, Madhava of Sangamagrama in Kerala found how to write pi and the sine as endless sums of smaller and smaller fractions. European mathematicians found the same sums more than 200 years later.",
    why: "These endless sums are a key step towards calculus. They were worked out in Kerala long before Newton and Leibniz.",
    mech: "Astronomers needed exact values to work out the positions of the sun, moon and planets. Madhava found sums that never end but come closer and closer to the true value. One says that a quarter of pi equals 1 minus 1/3 plus 1/5 minus 1/7, and so on. He added a correction so that fewer steps were needed. With this he got pi correct to 11 decimal places.",
    models: ["first-principles"],
    q: "What did Madhava of Kerala discover, and when?",
    a: "Around 1400 he found endless sums of fractions for pi and the sine, which come closer and closer to the true value. He got pi correct to 11 decimal places, more than 200 years before Europe found the same sums.",
    chain: [["Madhava of Kerala, around 1400", ["madhava", "kerala", "1400"]], ["Endless sums of fractions for pi and the sine", ["endless", "sum", "series", "infinite", "fraction"]], ["Pi correct to 11 decimal places", ["11 decimal", "decimal", "pi correct"]], ["More than 200 years before Europe", ["200 years", "europe", "newton", "leibniz"]]],
    mcq: { q: "What did Madhava of Sangamagrama find around 1400?", o: ["Endless sums of fractions that give pi and the sine", "The first rules for using zero", "That the Earth goes round the Sun", "A way to print books"] },
    bring: "When calculus or pi comes up: “A mathematician in Kerala, Madhava, wrote pi as an endless sum around 1400. Europe got there 200 years later.”",
    follow: "Why do you think his name is not in most school books?",
    deeper: "Madhava's own books are lost. His students passed the work on, and the Yuktibhasa, written in Malayalam around 1530, gives the proofs. There is no evidence that this work reached Europe. Most historians think Europe found it separately." },

  { id: "in-tata-steel", type: "event", domain: "business", region: "india", title: "Jamsetji Tata's steel dream", value: 5, cue: "the Tatas, Jamshedpur, or building something nobody believes in",
    emoji: "🏭", wiki: "Tata Steel",
    fact: "Jamsetji Tata planned India's first big steel plant, but he died in 1904 before it was built. His son Dorabji Tata founded the Tata Iron and Steel Company in 1907. The first steel ingot was made at Sakchi on 16 February 1912.",
    why: "Many experts believed Indians could not make good steel. The plant was built with Indian money, and a city grew around it.",
    mech: "Investors in London were not keen on the plan. So the Tatas offered the shares in India. About 8,000 Indian investors bought the whole issue within weeks. The site at Sakchi was chosen because iron ore, coal and river water were all nearby. In 1919 Sakchi was renamed Jamshedpur in honour of Jamsetji.",
    models: ["first-principles", "compounding"],
    q: "How did the Tata steel plant come to be built?",
    a: "Jamsetji Tata planned it but died in 1904. His son Dorabji founded the company in 1907 with shares bought by about 8,000 Indian investors. Sakchi was chosen for its ore, coal and water, and the first steel came in 1912.",
    chain: [["Jamsetji Tata planned it but died in 1904", ["jamsetji", "1904", "planned"]], ["Dorabji founded the company in 1907", ["dorabji", "1907", "son"]], ["About 8,000 Indian investors bought the shares", ["8,000", "indian investors", "shares", "indian money"]], ["Sakchi had ore, coal and water; first steel in 1912", ["sakchi", "ore", "coal", "1912"]]],
    mcq: { q: "Who paid for the first Tata steel plant?", o: ["About 8,000 Indian investors who bought its shares", "The British government", "A single bank in London", "The Maharaja of Mysore alone"] },
    bring: "When Indian industry comes up: “London would not fund Tata Steel in 1907. So 8,000 Indian investors bought the whole share issue.”",
    follow: "Would you have put your savings into a steel plant that experts said would fail?",
    deeper: "A senior railway official, Sir Frederick Upcott, is said to have promised to eat every pound of steel rail the Tatas managed to make. The plant later supplied rails in large amounts during the First World War." },

  { id: "in-infosys-y2k", type: "business concept", domain: "business", region: "india", title: "Infosys and the Y2K chance", value: 4, cue: "IT jobs, Bengaluru, or how Indian software became big",
    emoji: "💻", wiki: "Infosys",
    fact: "Infosys began in Pune in 1981. Seven engineers started it with 10,000 rupees that N. R. Narayana Murthy borrowed from his wife, Sudha Murty. In the late 1990s the Y2K problem gave Indian IT firms their big chance.",
    why: "A dull repair job for the world's computers helped build an industry that now employs millions of Indians.",
    mech: "Old computer programs stored the year as two digits, so the year 2000 would look like 1900. Companies everywhere had to check huge amounts of old code before the date changed. Rich countries did not have enough programmers for this work. India had many English-speaking engineers at much lower pay. Firms that did the job well won trust, and bigger projects followed.",
    models: ["compounding", "second-order-thinking"],
    q: "How did the Y2K problem help Indian IT companies such as Infosys?",
    a: "Old programs stored years as two digits, so all that code had to be checked before 2000. India had many engineers at lower pay, did the work well, won trust and then got bigger projects. Infosys itself had begun in 1981 with 10,000 rupees.",
    chain: [["Infosys began in 1981 with 10,000 rupees", ["1981", "10,000", "infosys"]], ["Old programs stored years as two digits", ["two digits", "y2k", "2000", "1900"]], ["India had many engineers at lower pay", ["engineer", "lower pay", "cheap", "english"]], ["Good work won trust and bigger projects", ["trust", "bigger projects", "followed"]]],
    mcq: { q: "What was the Y2K problem?", o: ["Old programs stored the year as two digits, so 2000 could be read as 1900", "A computer virus that spread in the year 2000", "A shortage of computers in India", "A tax on software exports"] },
    bring: "When IT jobs come up: “Indian IT took off with Y2K. The world needed people to fix old code, and India had the engineers.”",
    follow: "What dull but urgent problem today could become the next big industry?",
    deeper: "Infosys moved to Bengaluru in 1983. In March 1999 it became the first Indian company to list its shares on the Nasdaq exchange in the United States." },

  { id: "in-lijjat", type: "business concept", domain: "business", region: "india", title: "Lijjat Papad: seven women and 80 rupees", value: 4, cue: "women's work, cooperatives, or small beginnings",
    emoji: "🫓", wiki: "Shri Mahila Griha Udyog Lijjat Papad",
    fact: "On 15 March 1959 seven women in Girgaum, Mumbai, began rolling papads on a building terrace. They started with a loan of 80 rupees. Lijjat now has about 45,000 women members and yearly sales of around 1,600 crore rupees.",
    why: "It grew huge without rich owners or outside investors. The women who roll the papads own the business.",
    mech: "Each member collects ready dough from her branch in the morning. She rolls the papads at home and brings them back the next day. She is paid for what she rolls, so she can earn without leaving her home for long. Every member is a co-owner, and each branch shares its profit or loss equally. Quality is checked when the papads come back.",
    models: ["incentives", "compounding"],
    q: "How does Lijjat Papad work, and how did it begin?",
    a: "Seven women in Girgaum began it in 1959 with a loan of 80 rupees. Members collect dough, roll papads at home and are paid for what they roll. Every member is a co-owner and shares the profit of her branch.",
    chain: [["Seven women began in 1959 with 80 rupees", ["seven", "1959", "80 rupees"]], ["Members roll papads at home", ["home", "roll", "dough"]], ["Paid for what they roll", ["paid", "earn"]], ["Every member is a co-owner and shares profit", ["co-owner", "owner", "share", "profit"]]],
    mcq: { q: "Who owns Lijjat Papad?", o: ["The women members who roll the papads", "A large food company from Delhi", "The Government of Maharashtra", "A family of Mumbai traders"] },
    bring: "When start-ups come up: “Lijjat started in Girgaum with seven women and 80 rupees. No investors, and now about 45,000 co-owners.”",
    follow: "Why do you think so few businesses share ownership with their workers?",
    deeper: "The loan came from Chhaganlal Karamsi Parekh, a social worker. On the first day the women made just four packets of papad. Members call each other ‘ben’, which means sister in Gujarati." },

  { id: "in-thumba", type: "fact", domain: "science", region: "india", title: "ISRO began in a church", value: 5, cue: "ISRO, rockets, or doing a lot with very little",
    emoji: "⛪", wiki: "Thumba Equatorial Rocket Launching Station",
    fact: "India's space programme began in a fishing village. On 21 November 1963 a small American-made Nike-Apache rocket rose from Thumba in Kerala. A church served as the first office, and rocket parts were carried on a bicycle.",
    why: "The agency that reached the Moon and Mars started with a borrowed rocket, a church and a bicycle.",
    mech: "The Earth's magnetic equator passes close to Thumba. Scientists wanted to study the upper air above this line. Dr Vikram Sarabhai asked the local bishop for the church of St Mary Magdalene and the land around it. The bishop and the fishing families agreed, and the families moved to a new village nearby. The team had little money, so it used whatever was at hand.",
    models: ["first-principles", "compounding"],
    q: "Where and how did India's space programme begin?",
    a: "It began at Thumba in Kerala in 1963, chosen because the magnetic equator passes close by. Vikram Sarabhai got a church and its land from the bishop and the fishing families. The first rocket's parts were carried on a bicycle.",
    chain: [["First rocket from Thumba on 21 November 1963", ["thumba", "1963", "nike"]], ["Chosen because of the magnetic equator", ["magnetic equator", "equator"]], ["A church became the first office", ["church", "bishop"]], ["Little money: parts on a bicycle", ["bicycle", "little money", "cycle"]]],
    mcq: { q: "Why was Thumba chosen for India's first rocket launches?", o: ["The Earth's magnetic equator passes close to it", "It is the highest place in Kerala", "It had India's largest airport", "It was far from any village"] },
    bring: "When ISRO launches something: “It all started at Thumba in 1963. The office was a church and the rocket parts came on a bicycle.”",
    follow: "What big thing could you start with what you already have?",
    deeper: "The church is now a space museum. A young A. P. J. Abdul Kalam was part of the early team. In 1981 ISRO tested its APPLE satellite on a bullock cart, to keep metal away from the antenna during the test." },

  { id: "in-first-election", type: "event", domain: "history", region: "india", title: "The first election and the symbols", value: 5, cue: "elections, party symbols, or voting",
    emoji: "🗳️", wiki: "1951–52 Indian general election",
    fact: "India's first general election ran from 25 October 1951 to 21 February 1952. About 17.3 crore people had the right to vote, and most of them could not read. So every party was given a picture symbol.",
    why: "No country had tried to give so many poor and unschooled people the vote at one time. Many outsiders expected it to fail.",
    mech: "India gave the vote to every adult from the start. Only about 18 out of 100 Indians could read then. Sukumar Sen, the first Chief Election Commissioner, had to make voting possible without reading. Each candidate had a separate ballot box with his symbol on it. The voter simply dropped the ballot paper into the box of his choice. Nearly two lakh polling booths were set up across the country.",
    models: ["first-principles", "inversion"],
    q: "How did India hold its first election when most voters could not read?",
    a: "Every adult had the vote, about 17.3 crore people, but most could not read. Sukumar Sen gave each party a picture symbol and each candidate a separate ballot box with that symbol, so a voter only had to drop the paper in the right box.",
    chain: [["First election, 1951 to 1952, about 17.3 crore voters", ["1951", "1952", "17.3 crore", "17 crore"]], ["Every adult had the vote but most could not read", ["could not read", "every adult", "illiterate"]], ["Each party got a picture symbol", ["symbol", "picture"]], ["A separate ballot box for each candidate", ["ballot box", "separate", "box"]]],
    mcq: { q: "Why were party symbols used in India's first election?", o: ["Most voters could not read the names", "Parties wanted to save paper", "The British had ordered it", "Voting was done by raising hands"] },
    bring: "At election time: “The party symbols were invented in 1951 because most voters could not read. Each candidate even had his own ballot box.”",
    follow: "Do you think symbols still decide votes today, when most people can read?",
    deeper: "The first votes were cast in Chini in Himachal Pradesh, months early, before snow closed the passes. Shyam Saran Negi, a schoolteacher there, is remembered as independent India's first voter." },

  { id: "in-radcliffe-line", type: "event", domain: "history", region: "india", title: "The Radcliffe Line", value: 5, cue: "Partition, borders, or big decisions made in a hurry",
    emoji: "✂️", wiki: "Radcliffe Line",
    fact: "The border between India and Pakistan was drawn by a British lawyer, Sir Cyril Radcliffe. He reached India on 8 July 1947 and had never been there before. He had about five weeks to finish.",
    why: "A line drawn quickly on maps changed millions of lives. It shows the cost of giving a huge decision too little time.",
    mech: "Britain had fixed 15 August 1947 as the day it would leave, so the deadline could not move. Radcliffe chaired two commissions, one for Punjab and one for Bengal. Each had four judges, two named by the Congress and two by the Muslim League. They rarely agreed, so he made the final choices himself. He worked mainly from maps and census figures. The line was published on 17 August, two days after independence.",
    models: ["map-vs-territory", "margin-of-safety", "second-order-thinking"],
    q: "How was the border between India and Pakistan drawn in 1947?",
    a: "Sir Cyril Radcliffe, a British lawyer who had never been to India, had about five weeks. The commission judges rarely agreed, so he decided himself, working from maps and census figures. The line was published on 17 August 1947, two days after independence.",
    chain: [["Sir Cyril Radcliffe, who had never been to India", ["radcliffe", "never been", "lawyer"]], ["He had about five weeks", ["five weeks", "weeks", "deadline"]], ["He worked from maps and census figures", ["map", "census"]], ["Published on 17 August, two days after independence", ["17 august", "two days after", "published"]]],
    mcq: { q: "How long did Radcliffe have to draw the border?", o: ["About five weeks", "About five years", "About five months", "One full year"] },
    bring: "When rushed decisions come up: “The India-Pakistan border was drawn in about five weeks, by a man who had never seen India before.”",
    follow: "What big decision have you seen go wrong because of a fixed deadline?",
    deeper: "Radcliffe left India at once, destroyed his papers and refused his fee. Estimates vary widely. Historians think 1 to 2 crore people crossed the new borders, and that between a few lakh and 20 lakh people died in the violence." },

  { id: "in-jallianwala", type: "event", domain: "history", region: "india", title: "Jallianwala Bagh, 1919", value: 5, cue: "Amritsar, the freedom movement, or the abuse of power",
    emoji: "🕯️", wiki: "Jallianwala Bagh massacre",
    fact: "On 13 April 1919, the day of Baisakhi, British-led troops fired on an unarmed crowd in Jallianwala Bagh in Amritsar. They fired about 1,650 rounds in about ten minutes. The official count was 379 dead, and Indian estimates were about 1,000 or more.",
    why: "It ended the belief of many Indians that British rule was fair. The freedom movement became a movement of the masses after this.",
    mech: "The Rowlatt Act of 1919 let the government jail people without trial, and Punjab was protesting. Meetings had been banned in Amritsar, but many in the crowd had come for the festival and did not know. Brigadier-General Reginald Dyer brought fifty soldiers and gave no warning. The garden had high walls and only a few narrow exits. People had no way to escape.",
    models: ["second-order-thinking"],
    q: "What happened at Jallianwala Bagh in 1919, and what did it change?",
    a: "On Baisakhi, 13 April 1919, General Dyer's troops fired without warning on an unarmed crowd in a walled garden in Amritsar with few exits. Hundreds died. It followed protests against the Rowlatt Act, and it turned many Indians against British rule.",
    chain: [["13 April 1919, Baisakhi, in Amritsar", ["1919", "baisakhi", "amritsar"]], ["Protests against the Rowlatt Act", ["rowlatt", "protest", "without trial"]], ["Dyer's troops fired on an unarmed crowd without warning", ["dyer", "fired", "unarmed", "no warning", "without warning"]], ["High walls and few exits: no escape", ["wall", "exit", "escape"]]],
    mcq: { q: "Why could people not escape at Jallianwala Bagh?", o: ["The garden had high walls and only a few narrow exits", "A river surrounded the garden", "The gates were made of iron and too heavy", "It was night and nobody could see"] },
    bring: "When Amritsar comes up: “At Jallianwala Bagh you can still see the bullet marks on the walls. The firing lasted about ten minutes.”",
    follow: "Have you visited the memorial in Amritsar?",
    deeper: "Rabindranath Tagore gave up his British knighthood in protest. A British inquiry, the Hunter Commission, criticised Dyer and he was removed from his command. He was never put on trial." },

  { id: "in-1983-world-cup", type: "event", domain: "history", region: "india", title: "The 1983 World Cup win", value: 4, cue: "cricket, Kapil Dev, or underdogs who win",
    emoji: "🏏", wiki: "1983 Cricket World Cup final",
    fact: "On 25 June 1983 India beat the West Indies by 43 runs at Lord's to win the cricket World Cup. India had scored only 183. The West Indies had won both earlier World Cups.",
    why: "One match turned India into a cricket country. The money and power of world cricket slowly moved to India after it.",
    mech: "Before 1983 India had won only one match in two World Cups. Nobody expected much from Kapil Dev's team. The win made millions of Indians follow one-day cricket. Advertisers and television went where the viewers were. In 1987 India and Pakistan hosted the World Cup, the first one held outside England.",
    models: ["social-proof", "feedback-loops"],
    q: "What happened in the 1983 World Cup final, and how did it change Indian cricket?",
    a: "Kapil Dev's India scored only 183 but beat the West Indies, the winners of both earlier World Cups, by 43 runs at Lord's. Millions began to follow one-day cricket, advertisers and television followed the viewers, and in 1987 the World Cup came to India.",
    chain: [["India beat the West Indies at Lord's on 25 June 1983", ["1983", "west indies", "lord's"]], ["India scored only 183 and won by 43 runs", ["183", "43 runs"]], ["Millions began to follow one-day cricket", ["million", "follow", "viewers"]], ["Advertisers, television and the 1987 World Cup followed", ["advertis", "television", "1987", "money"]]],
    mcq: { q: "Whom did India beat in the 1983 World Cup final?", o: ["The West Indies", "Australia", "England", "Pakistan"] },
    bring: "When cricket comes up: “India defended just 183 in the 1983 final. The West Indies had never lost a World Cup before that tournament.”",
    follow: "Which Indian win do you think mattered more, 1983 or 2011?",
    deeper: "Earlier in the tournament India was 17 for 5 against Zimbabwe. Kapil Dev then scored 175 not out. No film of that innings exists, because BBC staff were on strike that day." },

  { id: "in-ipl", type: "business concept", domain: "business", region: "india", title: "The IPL as a business", value: 4, cue: "the IPL, sports money, or TV rights",
    emoji: "💰", wiki: "Indian Premier League",
    fact: "The Indian Premier League began in 2008. Until then, top cricket was played between countries or states. The IPL sold city teams to private owners, and the first eight teams sold for about 724 million US dollars in total.",
    why: "It turned cricket into a product made for evening television. It is now one of the richest sports leagues in the world per match.",
    mech: "Three ideas work together. A Twenty20 match lasts about three hours, which suits evening television. Owners bid for players at an open auction, so good players are spread across teams. The league sells the right to show the matches and shares that money with the teams. More viewers bring higher TV fees, which pay for better players, who bring more viewers.",
    models: ["feedback-loops", "incentives", "network-effects"],
    q: "Why does the IPL work so well as a business?",
    a: "City teams are owned by private owners. Short Twenty20 matches suit evening television, and the player auction spreads good players across teams. TV money is shared with teams, so more viewers bring more money, better players and still more viewers.",
    chain: [["City teams sold to private owners in 2008", ["private owners", "2008", "city teams", "owner"]], ["Short Twenty20 matches suit evening TV", ["twenty20", "three hours", "evening", "short"]], ["An auction spreads good players", ["auction", "bid"]], ["TV money and viewers feed each other", ["viewers", "tv", "television", "shared"]]],
    mcq: { q: "Where does most of the IPL's money come from?", o: ["Selling the right to show the matches", "Selling tickets at the stadium gate", "Government grants for sport", "Fees paid by the players"] },
    bring: "During the IPL: “The real game is the TV rights. The 2023 to 2027 rights sold for about 48,000 crore rupees.”",
    follow: "Could kabaddi or football in India ever copy this model fully?",
    deeper: "The media rights for 2023 to 2027 sold for about 48,390 crore rupees. In 2021 the new Lucknow team alone sold for about 7,000 crore rupees." },

  { id: "in-chaturanga", type: "fact", domain: "anthropology", region: "india", title: "Chess began as chaturanga", value: 4, cue: "chess, board games, or Indian ideas that travelled",
    emoji: "♟️", wiki: "Chaturanga",
    fact: "Chess grew from chaturanga, a board game played in India by about the 6th century CE. The name means ‘four parts’. These were the four parts of an old Indian army: foot soldiers, horses, elephants and chariots.",
    why: "The game played all over the world today still carries the shape of an ancient Indian army.",
    mech: "The four army parts became the pawn, the knight, the bishop and the rook. The game travelled to Persia, where it was called shatranj. Arab traders and rulers carried it on to Europe. On the way the pieces changed: the elephant became the bishop, and the king's minister became the queen. The Persian words ‘shah mat’, ‘the king is helpless’, became ‘checkmate’.",
    models: ["lindy-effect"],
    q: "Where does chess come from, and how did it reach Europe?",
    a: "It grew from chaturanga, an Indian game of about the 6th century, named after the four parts of an army: foot soldiers, horses, elephants and chariots. It went to Persia as shatranj and then with the Arabs to Europe, where the pieces changed.",
    chain: [["Chaturanga, India, about the 6th century", ["chaturanga", "6th century", "india"]], ["Four parts of an army", ["four parts", "elephant", "chariot", "foot soldiers", "army"]], ["To Persia as shatranj, then with Arabs to Europe", ["persia", "shatranj", "arab", "europe"]], ["Pieces and words changed: minister to queen, shah mat to checkmate", ["queen", "checkmate", "shah mat", "pieces changed", "bishop"]]],
    mcq: { q: "What does the name ‘chaturanga’ refer to?", o: ["The four parts of an old Indian army", "The four corners of the board", "The four players in the game", "The four colours of the pieces"] },
    bring: "Over a game of chess: “This started in India as chaturanga. Checkmate comes from the Persian ‘shah mat’, the king is helpless.”",
    follow: "Do you know what the chess pieces are called in Hindi or Marathi?",
    deeper: "In Hindi the queen is still called ‘wazir’, the minister, and the knight is ‘ghoda’, the horse. In 2024 D. Gukesh of Chennai became the youngest world chess champion, at 18." },

  { id: "in-vasco-spices", type: "event", domain: "economics", region: "india", title: "Why Vasco da Gama sailed for pepper", value: 5, cue: "spices, Kerala, or why Europeans came to India",
    emoji: "🌶️", wiki: "Vasco da Gama",
    fact: "In May 1498 Vasco da Gama's ships reached the coast near Calicut, now Kozhikode, in Kerala. He had sailed from Portugal around Africa. He came mainly for one thing: pepper and other spices.",
    why: "The hunt for cheaper pepper opened the sea route from Europe to India. That route later brought the Dutch, the French and the British.",
    mech: "Spices reached Europe through many hands: Indian and Arab traders, Egypt, and then Venice. Each added a profit, so pepper was very costly in Europe. Portugal wanted to buy at the source and cut out these middlemen. The voyage took over ten months, and fewer than half the men returned. But the cargo is said to have been worth many times the cost of the trip.",
    models: ["incentives", "second-order-thinking"],
    q: "Why did Vasco da Gama sail to India, and what followed?",
    a: "Pepper passed through many middlemen, including Arab traders and Venice, and was very costly in Europe. Portugal wanted to buy at the source, so da Gama sailed around Africa and reached Calicut in 1498. The profit drew other Europeans to India by sea.",
    chain: [["Vasco da Gama reached Calicut in 1498", ["1498", "calicut", "kozhikode", "vasco", "da gama"]], ["He came for pepper and spices", ["pepper", "spice"]], ["Middlemen made spices costly in Europe", ["middlem", "venice", "arab", "costly", "many hands"]], ["Buying at the source by sea gave huge profit", ["source", "profit", "around africa", "sea route"]]],
    mcq: { q: "Why did Portugal look for a sea route to India?", o: ["To buy spices directly and avoid the middlemen", "To find gold mines in Kerala", "To escape a war in Europe", "To sell Portuguese cloth in Delhi"] },
    bring: "When food or spices come up: “Europeans first sailed to India for pepper. Vasco da Gama landed near Kozhikode in 1498 looking for it.”",
    follow: "Which thing today is expensive mostly because of the middlemen?",
    deeper: "A pilot taken on at Malindi in East Africa guided the ships across the Arabian Sea. The Zamorin, the ruler of Calicut, was not impressed by the cheap gifts da Gama brought." },

  { id: "in-project-tiger", type: "concept", domain: "science", region: "india", title: "Project Tiger", value: 4, cue: "tigers, national parks, or saving wildlife",
    emoji: "🐅", wiki: "Project Tiger",
    fact: "India began Project Tiger on 1 April 1973 with nine reserves. A count in 1972 had found only about 1,800 tigers. The 2022 count estimated 3,682, about three quarters of all the wild tigers in the world.",
    why: "It is one of the few cases where a large wild animal has come back in a crowded country.",
    mech: "A tiger needs a large forest, plenty of deer and wild pigs, and safety from hunters. Each reserve has a core area where people do not live or cut wood. Around it is a buffer area where some human use is allowed. Protecting the tiger in this way protects the whole forest. Counting also improved: since 2006, camera traps identify each tiger by its stripes.",
    models: ["second-order-thinking", "feedback-loops"],
    q: "How has Project Tiger helped tiger numbers grow?",
    a: "It began in 1973 with nine reserves when only about 1,800 tigers were left. Each reserve has a protected core area and a buffer around it, which keeps the forest and the prey safe. The 2022 count estimated 3,682 tigers.",
    chain: [["Began in 1973 with nine reserves", ["1973", "nine reserves", "nine"]], ["Only about 1,800 tigers were left", ["1,800", "1800", "1972"]], ["A protected core area with a buffer around it", ["core", "buffer"]], ["3,682 tigers in 2022, three quarters of the world's", ["3,682", "2022", "three quarters"]]],
    mcq: { q: "About how much of the world's wild tiger population lives in India?", o: ["About three quarters", "About one tenth", "About one quarter", "Almost none"] },
    bring: "When a safari trip comes up: “India has about three quarters of the world's wild tigers. In 1972 there were only about 1,800 left here.”",
    follow: "Have you ever seen a tiger in the wild, at Tadoba or anywhere else?",
    deeper: "The 2006 count gave only about 1,411 tigers, and Sariska reserve was found to have lost all its tigers. Stronger protection followed. India now has more than 55 tiger reserves." },

  { id: "in-root-bridges", type: "concept", domain: "design", region: "india", title: "The living root bridges of Meghalaya", value: 4, cue: "Meghalaya, bridges, or building with nature",
    emoji: "🌳", wiki: "Living root bridge",
    fact: "In the hills of Meghalaya, the Khasi and Jaintia people grow their bridges. They guide the roots of the rubber fig tree across a stream. After many years the roots join into a bridge strong enough to walk on.",
    why: "Most bridges get weaker with age. These get stronger every year, because they are alive.",
    mech: "This is one of the wettest places on Earth, and a wooden bridge rots quickly here. The rubber fig sends out roots from its branches into the air. Villagers lead these roots across the stream through hollow betel nut trunks or along bamboo. When the roots reach the far bank, they take hold in the soil. It can take 15 years or more, but the bridge keeps growing thicker.",
    models: ["compounding", "lindy-effect"],
    q: "How are the living root bridges of Meghalaya made, and why?",
    a: "Wooden bridges rot in the heavy rain, so Khasi and Jaintia villagers guide the roots of the rubber fig across a stream through hollow trunks or bamboo. After 15 years or more the roots take hold and form a bridge that grows stronger with age.",
    chain: [["Heavy rain rots wooden bridges", ["rot", "wettest", "heavy rain", "rain"]], ["Roots of the rubber fig are guided across the stream", ["root", "rubber fig", "guide", "lead"]], ["Through hollow trunks or along bamboo", ["hollow", "bamboo", "betel", "trunk"]], ["It takes 15 years or more and grows stronger", ["15 years", "stronger", "thicker"]]],
    mcq: { q: "What are Meghalaya's living bridges made from?", o: ["The living roots of rubber fig trees", "Cut bamboo tied with rope", "Stone blocks without cement", "Old railway tracks"] },
    bring: "When travel in the north-east comes up: “In Meghalaya people grow bridges from tree roots. It takes 15 years, and then the bridge lasts for generations.”",
    follow: "What would you start today if you knew it would be ready only in 15 years?",
    deeper: "The double-decker root bridge at Nongriat is thought to be about 200 years old. Nearby Mawsynram gets nearly 12,000 mm of rain a year, among the highest in the world." },

  { id: "in-east-rivers", type: "concept", domain: "geography", region: "india", title: "Why the big southern rivers flow east", value: 4, cue: "rivers, the Godavari, or the map of India",
    emoji: "🏞️", wiki: "Godavari River",
    fact: "The Godavari begins at Trimbak near Nashik, only about 80 km from the Arabian Sea. Yet it flows about 1,465 km the other way, to the Bay of Bengal. The Krishna, the Kaveri and the Mahanadi also flow east.",
    why: "One simple fact about the land explains the path of most rivers in south and central India, and where the rich farm deltas are.",
    mech: "The Deccan plateau is like a table tilted gently towards the east. Its high edge is the Western Ghats, close to the west coast. Rain that falls just east of the top has to run down the long slope to the east. These long, slow rivers carry soil and build wide deltas on the east coast. Rivers on the west side are short and fast, so they build no large deltas.",
    models: ["first-principles"],
    q: "Why do the Godavari, Krishna and Kaveri flow east to the Bay of Bengal?",
    a: "The Deccan plateau is tilted towards the east, and its high edge, the Western Ghats, is close to the west coast. So rivers that begin near the Arabian Sea run down the long slope to the Bay of Bengal and build wide deltas there.",
    chain: [["The rivers begin close to the Arabian Sea", ["arabian sea", "trimbak", "80 km", "begin"]], ["The Deccan plateau is tilted to the east", ["tilt", "slope", "plateau"]], ["The Western Ghats are the high edge", ["western ghats", "ghats", "high edge"]], ["Long rivers build deltas on the east coast", ["delta", "bay of bengal", "east coast"]]],
    mcq: { q: "Why does the Godavari flow east even though it begins near the west coast?", o: ["The Deccan plateau slopes down towards the east", "The wind pushes the water east", "A dam near Nashik turns it around", "The Arabian Sea is higher than the land"] },
    bring: "At Trimbakeshwar or Nashik: “The Godavari starts here, about 80 km from the Arabian Sea, and still flows all the way to the Bay of Bengal.”",
    follow: "Can you name the two big rivers that flow west instead?",
    deeper: "The Narmada and the Tapi are the main exceptions. They flow west because they run along rift valleys, long cracks in the Earth's crust. The Krishna begins near Mahabaleshwar, also very close to the west coast." }
  ]));

  MV.STORIES.push(
  { id: "in-princely", assetId: "in-princely-states", title: "Five Hundred Signatures",
    hook: "In the summer of 1947 India was about to become free. It was also in danger of breaking into hundreds of pieces.",
    setting: "Delhi, July 1947. More than 560 princely states are not part of British India. Their treaties with Britain will end on 15 August.",
    character: "Sardar Vallabhbhai Patel, the firm minister in charge of the new States Department, and V. P. Menon, his secretary, who had begun his career as a clerk.",
    conflict: "Each ruler could join India or Pakistan, or try to stay independent. Some dreamed of their own countries. Only a few weeks were left.",
    surprise: "Patel and Menon did not ask for the kingdoms. They asked for only three subjects: defence, foreign affairs and communications. The rulers could keep their palaces, their titles and a yearly payment.",
    turning: "On 25 July the Viceroy, Lord Mountbatten, told the princes that they could not stand alone. One by one they signed the Instrument of Accession. Menon travelled from court to court with the papers.",
    payoff: "By 15 August almost all the states had joined. Junagadh, Hyderabad, and Jammu and Kashmir were settled later, each in a different way. Within about two years the map of India was one piece.",
    meaning: "Ask first for a small step that is easy to accept. Once people are inside, the larger change becomes possible.",
    extra: ["Menon wrote that the young Maharaja of Jodhpur once pointed a small pistol at him during the talks, and then signed.", "Hyderabad joined after an Indian military action in September 1948.", "The rulers' yearly payments, called privy purses, were ended in 1971."],
    facts: [["1947"], ["560", "princely"], ["patel"], ["menon"], ["defence", "three subjects"], ["accession", "signed"], ["hyderabad", "junagadh", "kashmir"]],
    vocab: ["accession", "treaty", "negotiate"] },
  { id: "in-ramanujan", assetId: "in-ramanujan-hardy", title: "Nine Pages from Madras",
    hook: "In January 1913 a famous Cambridge mathematician opened a letter from an unknown clerk in India. It was full of formulas he had never seen.",
    setting: "Madras, 1913. Srinivasa Ramanujan, aged 25, works as a clerk at the Madras Port Trust for 30 rupees a month.",
    character: "Ramanujan had no degree. He had taught himself and filled notebooks with his own results. G. H. Hardy was one of England's leading mathematicians.",
    conflict: "Ramanujan had already written to two other Cambridge professors. Both sent his papers back without comment. His letter to Hardy had nine pages of formulas and almost no proofs.",
    surprise: "Hardy first wondered if it was a trick. Then he and his colleague Littlewood studied the pages. Some results were already known, but others were completely new.",
    turning: "Hardy decided the formulas must be true, because nobody would have the imagination to invent them. He wrote back and invited Ramanujan to Cambridge.",
    payoff: "Ramanujan sailed in 1914 and worked with Hardy for five years. In 1918 he became a Fellow of the Royal Society. He fell ill, returned to India, and died in 1920 at the age of 32.",
    meaning: "Talent can appear anywhere. It still needs one person who is willing to read the letter with care.",
    extra: ["Hardy once said his taxi had a dull number, 1729. Ramanujan replied that it is the smallest number that is the sum of two cubes in two different ways.", "Mathematicians are still studying the results in his notebooks today.", "His birthday, 22 December, is National Mathematics Day in India."],
    facts: [["1913"], ["hardy"], ["clerk", "port trust"], ["letter"], ["formula"], ["cambridge"], ["1920", "32"]],
    vocab: ["proof", "formula", "genius"] });

  MV.LINKS.push(
    ["in-constitution-handwritten", "in-basic-structure", "The text adopted in 1949 can be amended. The 1973 ruling says which core parts of it can never be removed."],
    ["in-constitution-handwritten", "mahad-satyagraha", "Dr B. R. Ambedkar, who led the march at Mahad, later chaired the committee that drafted the Constitution."],
    ["in-constitution-handwritten", "in-first-election", "The Constitution gave every adult the vote in 1950. The first election, two years later, put that promise into practice."],
    ["in-basic-structure", "veil-ignorance", "Both ask for rules that stay fair whoever holds power. The basic structure rule binds every future majority."],
    ["in-basic-structure", "margin-of-safety", "The rule is a safety margin for the Constitution. Even a very large majority cannot remove its core."],
    ["in-first-election", "india-election", "The picture symbols invented for voters in 1951 are still on every voting machine today."],
    ["in-princely-states", "in-radcliffe-line", "In the same weeks of 1947, one team drew the border while another persuaded hundreds of rulers to join."],
    ["in-princely-states", "bm-incentives", "Rulers kept their titles and got a privy purse. The offer made signing the easier choice for them."],
    ["in-radcliffe-line", "map-territory", "Radcliffe worked from maps and census tables. The real land had villages, canals and families that the line cut through."],
    ["in-radcliffe-line", "in-jallianwala", "Amritsar, the city of Jallianwala Bagh, ended up only about 30 km from the new border in 1947."],
    ["in-jallianwala", "salt-march", "Jallianwala Bagh turned many Indians against British rule. Eleven years later the Salt March showed how to resist it without weapons."],
    ["in-chola-navy", "shivaji-navy", "Both were Indian rulers who saw that power over sea trade needs ships, not only armies."],
    ["in-chola-navy", "hormuz", "The Strait of Malacca, like the Strait of Hormuz, is a narrow sea lane that trade cannot avoid."],
    ["in-chola-navy", "in-vasco-spices", "The same Indian Ocean trade that the Cholas fought over drew the Portuguese to India about 470 years later."],
    ["in-vasco-spices", "vada-pav", "The Portuguese came to buy pepper. They also brought the chilli, the potato and the bread that later made the vada pav."],
    ["in-vasco-spices", "east-india-company", "Portugal's profits from the sea route pushed English traders to form their own Company in 1600."],
    ["in-todar-mal", "bm-incentives", "A tax fixed in advance gave farmers a reason to grow more, and gave officials less room to cheat."],
    ["in-todar-mal", "indus-valley", "Both show the power of standard measures: standard weights in the Indus cities, standard land units under Akbar."],
    ["in-tipu-rockets", "in-thumba", "India's rocket story has two starts: iron war rockets in Mysore, and a small research rocket at Thumba in 1963."],
    ["in-tipu-rockets", "east-india-company", "The Company's army first suffered from the Mysore rockets and then took the idea home to copy."],
    ["in-thumba", "isro-frugal", "The habit of doing more with less began at Thumba with a bicycle. It later took Chandrayaan-3 to the Moon at low cost."],
    ["in-thumba", "in-raman-effect", "Vikram Sarabhai, who started the work at Thumba, had done his early research under C. V. Raman in Bengaluru."],
    ["in-raman-effect", "in-ramanujan-hardy", "Both did world-class work in British-ruled India with very few resources, within about fifteen years of each other."],
    ["in-ramanujan-hardy", "in-kerala-school", "Madhava and Ramanujan, five centuries apart in south India, both found new endless sums for pi."],
    ["in-kerala-school", "zero-brahmagupta", "Madhava's long calculations of pi were possible only because of zero and the place-value way of writing numbers."],
    ["in-iron-pillar", "pantheon-dome", "Both have lasted well over 1,500 years because of the chemistry of their material, which their makers found by practice."],
    ["in-iron-pillar", "in-tata-steel", "Indian ironworkers made the Delhi pillar 1,600 years ago. Modern Indian steel began at Sakchi in 1912."],
    ["in-tata-steel", "gateway-of-india", "Jamsetji Tata opened the Taj Mahal hotel beside the future Gateway in 1903, in the same years that he planned the steel plant."],
    ["in-tata-steel", "bse-banyan", "Bombay's share market let thousands of ordinary Indian savers fund the country's first big steel plant."],
    ["in-infosys-y2k", "comparative-advantage", "India had many trained engineers at lower pay. Selling software work to the world was its comparative advantage."],
    ["in-infosys-y2k", "reforms-1991", "After 1991 it became much easier to import computers and to serve foreign clients, so IT firms could grow fast."],
    ["in-lijjat", "amul-white-revolution", "Both are cooperatives owned by the people who do the work: milk farmers at Amul, papad rollers at Lijjat."],
    ["in-lijjat", "dabbawalas", "Both are Mumbai systems built on simple rules, equal shares and trust, with almost no technology."],
    ["in-1983-world-cup", "in-ipl", "The 1983 win created a huge cricket audience in India. Twenty-five years later the IPL turned that audience into a business."],
    ["in-ipl", "amazon-flywheel", "Both run on a loop: more viewers or buyers bring more money, which improves the product, which brings more viewers or buyers."],
    ["in-chaturanga", "zero-brahmagupta", "Chess and the Indian numbers took the same road: from India to Persia and the Arab world, and then to Europe."],
    ["in-chaturanga", "sun-tzu", "Both treat war as a contest of thinking, where position and planning matter more than force."],
    ["in-project-tiger", "in-east-rivers", "Many tiger reserves protect the hill forests where rivers begin. Saving the tiger also guards the water."],
    ["in-project-tiger", "in-root-bridges", "Both show people living with a forest for the long term instead of only cutting it."],
    ["in-root-bridges", "kailasa-temple", "Two unusual ways to build: Kailasa was made by cutting rock away, and a root bridge is made by letting a tree grow."],
    ["in-root-bridges", "buffett-compounding", "A root bridge is compounding in wood. It starts slowly and adds strength every year for generations."],
    ["in-east-rivers", "western-ghats-rain", "The Ghats catch the monsoon rain, and the eastward tilt of the land sends that water across the whole peninsula."],
    ["in-east-rivers", "deccan-traps", "The Godavari and the Krishna flow east across the lava plateau that the Deccan eruptions built."]
  );
})();
